import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: "Vue d'ensemble des World",
  introTitle: 'World',
  sheetTitle: "État de l'assemblage",
  reloadPrefixBtn: '↻ Recharger le préfixe système',
  prefixReloaded: 'Préfixe rechargé',
  prefixReloadFailed: (msg: string) => `Échec du rechargement du préfixe : ${msg}`,
  updated: 'Mis à jour',
  toggleFailed: (msg: string) => `Échec du basculement : ${msg}`,
  reloadNowTitle: 'Recharger le préfixe système maintenant ?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `« ${name} » est de nouveau visible pour l'agent.` : `« ${name} » est désormais masqué pour l'agent.`)
    + "\n\nLa livraison des événements suit déjà le nouvel état. Le rechargement met à jour le prompt d'environnement et les déclarations d'outils, et conserve les messages de conversation existants. "
    + "En cas d'annulation, ils sont mis à jour à la prochaine passation de contexte ou au prochain redémarrage.",
  deactivateTitle: (name: string) => `Désactiver « ${name} » ?`,
  deactivateBody: (id: string) =>
    "Le World s'arrête immédiatement (ses processus externes et connexions gérés sont clôturés), et "
    + `worlds.${id}.enabled=false est réécrit dans config.json. Le prompt d'environnement et les outils de l'agent sont retirés aussitôt ; une nouvelle activation le reconstruit à partir de la configuration actuelle.`,
  activated: 'Activé',
  deactivated: 'Désactivé',
  activateFailed: (msg: string) => `Échec de l'activation : ${msg}`,
  deactivateFailed: (msg: string) => `Échec de la désactivation : ${msg}`,
  restartTitle: (name: string) => `Redémarrer « ${name} » ?`,
  restartBody: "Arrête et reconstruit le World pour appliquer les réglages marqués pour un redémarrage du World. Les processus et connexions gérés s'arrêtent puis redémarrent.",
  restarted: 'Redémarré',
  restartFailed: (msg: string) => `Échec du redémarrage : ${msg}`,
  lampAssembly: 'assemblage',
  notInstalled: 'Indisponible',
  notActive: 'Inactif',
  declaredByPersona: 'Déclaré par la Persona',
  optionalAddon: 'Module optionnel',
  open: 'Ouvrir',
  details: '→ Détails',
  toolsCount: (id: string, n: number) => `${id} · ${n} outil${n > 1 ? 's' : ''}`,
  missingReasonDefault: 'Impossible de charger ce World.',
  activateWorld: 'Activer le World',
  inactiveNoteActivatable: "L'activation enregistre dans config.json et démarre le World immédiatement.",
  inactiveNoteManual: (id: string) => `Implémenté localement mais non assemblé. Pour l'activer, mettez worlds.${id}.enabled à true dans config.json et redémarrez.`,
  hideFromAgent: "Masquer pour l'agent",
  showToAgent: "Afficher pour l'agent",
  restartWorld: 'Redémarrer le World',
  deactivateWorld: 'Désactiver le World',
  visibleToAgent: "Visible pour l'agent",
  hidden: 'Masqué',
  prefixPending: 'Rechargement du préfixe en attente',
  kvTools: 'Outils',
  kvNone: '(aucun)',
  kvWorkspace: 'Espace de travail',
  listSep: ', ',
  driftNote: "La livraison des événements suit déjà le nouvel état ; le prompt d'environnement et les déclarations d'outils sont mis à jour après un rechargement du préfixe.",
  sumVisible: (n: number) => `Visibles ${n}`,
  sumHidden: (n: number) => `Masqués ${n}`,
  sumInactive: (n: number) => `Inactifs ${n}`,
  sumMissing: (n: number) => `Indisponibles ${n}`,
  noWorlds: 'Aucun World',
  listLoadFailed: (msg: string) => `Échec du chargement de la liste des World : ${msg}`,
  loading: 'Chargement…',
};
