import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'World 總覽',
  introTitle: 'World',
  sheetTitle: '裝配狀態',
  reloadPrefixBtn: '↻ 重新載入系統前綴',
  prefixReloaded: '前綴已重新載入',
  prefixReloadFailed: (msg: string) => `前綴重新載入失敗: ${msg}`,
  updated: '已更新',
  toggleFailed: (msg: string) => `切換失敗: ${msg}`,
  reloadNowTitle: '現在重新載入 system 前綴?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `「${name}」已對 agent 重新可見。` : `「${name}」已對 agent 隱藏。`)
    + '\n\n事件投遞已依新狀態生效。重新載入會更新環境提示詞與工具宣告，保留既有對話。'
    + '取消後將在下次上下文交接或重開時更新。',
  deactivateTitle: (name: string) => `停用「${name}」?`,
  deactivateBody: (id: string) =>
    'World 會立即停止(它託管的外部處理程序與連線一併收尾),並寫回 config.json 的 '
    + `worlds.${id}.enabled=false。agent 的環境提示詞與工具隨即撤下;再次啟用依目前設定重建。`,
  activated: '已啟用',
  deactivated: '已停用',
  activateFailed: (msg: string) => `啟用失敗: ${msg}`,
  deactivateFailed: (msg: string) => `停用失敗: ${msg}`,
  restartTitle: (name: string) => `重新啟動「${name}」?`,
  restartBody: '停止並重建 World，套用標有「重新啟動 World 生效」的設定。託管處理程序與連線會停止後重新啟動。',
  restarted: '已重新啟動',
  restartFailed: (msg: string) => `重新啟動失敗: ${msg}`,
  lampAssembly: '裝配',
  notInstalled: '無法使用',
  notActive: '未啟用',
  declaredByPersona: 'Persona定義',
  optionalAddon: '選配外掛',
  open: '開啟',
  details: '→ 詳情',
  toolsCount: (id: string, n: number) => `${id} · ${n} 個工具`,
  missingReasonDefault: '無法載入這個 World。',
  activateWorld: '啟用 World',
  inactiveNoteActivatable: '啟用後寫入 config.json 並立即啟動。',
  inactiveNoteManual: (id: string) => `本機有實作但沒裝配。要啟用,把 config.json 裡 worlds.${id}.enabled 改為 true 後重新啟動。`,
  hideFromAgent: '對 agent 隱藏',
  showToAgent: '對 agent 顯示',
  restartWorld: '重新啟動 World',
  deactivateWorld: '停用 World',
  visibleToAgent: '對 agent 可見',
  hidden: '已隱藏',
  prefixPending: '前綴待重新載入',
  kvTools: '工具',
  kvNone: '（無）',
  kvWorkspace: '工作區',
  listSep: '、',
  driftNote: '事件投遞已依新狀態生效；環境提示詞與工具宣告將在前綴重新載入後更新。',
  sumVisible: (n: number) => `可見 ${n}`,
  sumHidden: (n: number) => `已隱藏 ${n}`,
  sumInactive: (n: number) => `未啟用 ${n}`,
  sumMissing: (n: number) => `無法使用 ${n}`,
  noWorlds: '沒有任何 World',
  listLoadFailed: (msg: string) => `World 清單載入失敗: ${msg}`,
  loading: '載入中…',
};
