import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'World 一覧',
  introTitle: 'World',
  sheetTitle: '構成状態',
  reloadPrefixBtn: '↻ システムプレフィックスを再読み込み',
  prefixReloaded: 'プレフィックスを再読み込みしました',
  prefixReloadFailed: (msg: string) => `プレフィックスの再読み込みに失敗しました：${msg}`,
  updated: '更新しました',
  toggleFailed: (msg: string) => `切り替えに失敗しました：${msg}`,
  reloadNowTitle: '今すぐシステムプレフィックスを再読み込みしますか？',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `「${name}」はエージェントから再び見えるようになりました。` : `「${name}」をエージェントから隠しました。`)
    + '\n\nイベント配信は既に新しい状態に従っています。再読み込みすると環境プロンプトとツール宣言が更新され、既存の会話は保持されます。'
    + 'キャンセルした場合は、次のコンテキスト引き継ぎか再起動のときに更新されます。',
  deactivateTitle: (name: string) => `「${name}」を無効化しますか？`,
  deactivateBody: (id: string) =>
    'World は直ちに停止し（管理している外部プロセスと接続も終了処理されます）、config.json に '
    + `worlds.${id}.enabled=false を書き戻します。エージェントの環境プロンプトとツールはすぐに取り下げられ、再び有効化すると現在の設定から再構築されます。`,
  activated: '有効化しました',
  deactivated: '無効化しました',
  activateFailed: (msg: string) => `有効化に失敗しました：${msg}`,
  deactivateFailed: (msg: string) => `無効化に失敗しました：${msg}`,
  restartTitle: (name: string) => `「${name}」を再起動しますか？`,
  restartBody: 'World を停止して再構築し、「World の再起動後に反映」と表示された設定を適用します。管理しているプロセスと接続は停止した後に再起動します。',
  restarted: '再起動しました',
  restartFailed: (msg: string) => `再起動に失敗しました：${msg}`,
  lampAssembly: '構成',
  notInstalled: '利用不可',
  notActive: '無効',
  declaredByPersona: 'Persona で定義',
  optionalAddon: 'オプションのアドオン',
  open: '開く',
  details: '→ 詳細',
  toolsCount: (id: string, n: number) => `${id} · ツール ${n} 個`,
  missingReasonDefault: 'この World を読み込めません。',
  activateWorld: 'World を有効化',
  inactiveNoteActivatable: '有効化すると config.json に書き込まれ、すぐに起動します。',
  inactiveNoteManual: (id: string) => `ローカルに実装はありますが、構成に含まれていません。有効にするには config.json の worlds.${id}.enabled を true にして再起動してください。`,
  hideFromAgent: 'エージェントから隠す',
  showToAgent: 'エージェントに表示',
  restartWorld: 'World を再起動',
  deactivateWorld: 'World を無効化',
  visibleToAgent: 'エージェントに表示中',
  hidden: '非表示',
  prefixPending: 'プレフィックスの再読み込み待ち',
  kvTools: 'ツール',
  kvNone: '（なし）',
  kvWorkspace: 'ワークスペース',
  listSep: '、',
  driftNote: 'イベント配信は既に新しい状態に従っています。環境プロンプトとツール宣言はプレフィックスの再読み込み後に更新されます。',
  sumVisible: (n: number) => `表示 ${n}`,
  sumHidden: (n: number) => `非表示 ${n}`,
  sumInactive: (n: number) => `無効 ${n}`,
  sumMissing: (n: number) => `利用不可 ${n}`,
  noWorlds: 'World がありません',
  listLoadFailed: (msg: string) => `World 一覧を読み込めませんでした：${msg}`,
  loading: '読み込み中…',
};
