import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Resumen de Worlds',
  introTitle: 'Worlds',
  sheetTitle: 'Estado del ensamblado',
  reloadPrefixBtn: '↻ Recargar prefijo del sistema',
  prefixReloaded: 'Prefijo recargado',
  prefixReloadFailed: (msg: string) => `Falló la recarga del prefijo: ${msg}`,
  updated: 'Actualizado',
  toggleFailed: (msg: string) => `No se pudo cambiar: ${msg}`,
  reloadNowTitle: '¿Recargar ahora el prefijo del sistema?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `“${name}” vuelve a ser visible para el agente.` : `“${name}” ahora está oculto para el agente.`)
    + '\n\nLa entrega de eventos ya sigue el nuevo estado. Al recargar se actualizan el prompt del entorno y las declaraciones de herramientas, y se conservan los mensajes existentes de la conversación. '
    + 'Si cancelas, se actualizan en el próximo traspaso de contexto o reinicio.',
  deactivateTitle: (name: string) => `¿Desactivar “${name}”?`,
  deactivateBody: (id: string) =>
    'El World se detiene de inmediato (sus procesos externos y conexiones gestionados se cierran) y '
    + `se escribe worlds.${id}.enabled=false en config.json. El prompt del entorno y las herramientas del agente se retiran en el acto; al activarlo de nuevo se reconstruye con la configuración actual.`,
  activated: 'Activado',
  deactivated: 'Desactivado',
  activateFailed: (msg: string) => `Falló la activación: ${msg}`,
  deactivateFailed: (msg: string) => `Falló la desactivación: ${msg}`,
  restartTitle: (name: string) => `¿Reiniciar “${name}”?`,
  restartBody: 'Detiene y reconstruye el World para aplicar los ajustes marcados para reinicio del World. Los procesos y conexiones gestionados se detienen y vuelven a iniciarse.',
  restarted: 'Reiniciado',
  restartFailed: (msg: string) => `Falló el reinicio: ${msg}`,
  lampAssembly: 'ensamblado',
  notInstalled: 'No disponible',
  notActive: 'Inactivo',
  declaredByPersona: 'Declarado por la Persona',
  optionalAddon: 'Complemento opcional',
  open: 'Abrir',
  details: '→ Detalles',
  toolsCount: (id: string, n: number) => `${id} · ${n} ${n === 1 ? 'herramienta' : 'herramientas'}`,
  missingReasonDefault: 'No se pudo cargar este World.',
  activateWorld: 'Activar World',
  inactiveNoteActivatable: 'Al activarlo se guarda en config.json y el World se inicia de inmediato.',
  inactiveNoteManual: (id: string) => `Implementado localmente pero no ensamblado. Para activarlo, cambia worlds.${id}.enabled a true en config.json y reinicia.`,
  hideFromAgent: 'Ocultar al agente',
  showToAgent: 'Mostrar al agente',
  restartWorld: 'Reiniciar World',
  deactivateWorld: 'Desactivar World',
  visibleToAgent: 'Visible para el agente',
  hidden: 'Oculto',
  prefixPending: 'Recarga de prefijo pendiente',
  kvTools: 'Herramientas',
  kvNone: '(ninguna)',
  kvWorkspace: 'Espacio de trabajo',
  listSep: ', ',
  driftNote: 'La entrega de eventos ya sigue el nuevo estado; el prompt del entorno y las declaraciones de herramientas se actualizan tras recargar el prefijo.',
  sumVisible: (n: number) => `Visibles: ${n}`,
  sumHidden: (n: number) => `Ocultos: ${n}`,
  sumInactive: (n: number) => `Inactivos: ${n}`,
  sumMissing: (n: number) => `No disponibles: ${n}`,
  noWorlds: 'No hay Worlds',
  listLoadFailed: (msg: string) => `No se pudo cargar la lista de Worlds: ${msg}`,
  loading: 'Cargando…',
};
