import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Panoramica dei World',
  introTitle: 'World',
  sheetTitle: "Stato dell'assemblaggio",
  reloadPrefixBtn: '↻ Ricarica prefisso di sistema',
  prefixReloaded: 'Prefisso ricaricato',
  prefixReloadFailed: (msg: string) => `Ricaricamento del prefisso non riuscito: ${msg}`,
  updated: 'Aggiornato',
  toggleFailed: (msg: string) => `Cambio non riuscito: ${msg}`,
  reloadNowTitle: 'Ricaricare ora il prefisso di sistema?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `«${name}» è di nuovo visibile all'agente.` : `«${name}» è ora nascosto all'agente.`)
    + "\n\nLa consegna degli eventi segue già il nuovo stato. Il ricaricamento aggiorna il prompt dell'ambiente e le dichiarazioni degli strumenti e conserva i messaggi della conversazione esistenti. "
    + 'Se annulli, si aggiornano al prossimo passaggio di contesto o al prossimo riavvio.',
  deactivateTitle: (name: string) => `Disattivare «${name}»?`,
  deactivateBody: (id: string) =>
    'Il World si arresta subito (i processi esterni e le connessioni che gestisce vengono chiusi) e '
    + `worlds.${id}.enabled=false viene riscritto in config.json. Il prompt dell'ambiente e gli strumenti dell'agente vengono ritirati subito; una nuova attivazione lo ricostruisce dalla configurazione attuale.`,
  activated: 'Attivato',
  deactivated: 'Disattivato',
  activateFailed: (msg: string) => `Attivazione non riuscita: ${msg}`,
  deactivateFailed: (msg: string) => `Disattivazione non riuscita: ${msg}`,
  restartTitle: (name: string) => `Riavviare «${name}»?`,
  restartBody: 'Arresta e ricostruisce il World per applicare le impostazioni che richiedono il riavvio del World. I processi e le connessioni gestiti si arrestano e ripartono.',
  restarted: 'Riavviato',
  restartFailed: (msg: string) => `Riavvio non riuscito: ${msg}`,
  lampAssembly: 'assemblaggio',
  notInstalled: 'Non disponibile',
  notActive: 'Inattivo',
  declaredByPersona: 'Dichiarato dalla Persona',
  optionalAddon: 'Componente aggiuntivo opzionale',
  open: 'Apri',
  details: '→ Dettagli',
  toolsCount: (id: string, n: number) => `${id} · ${n} ${n === 1 ? 'strumento' : 'strumenti'}`,
  missingReasonDefault: 'Impossibile caricare questo World.',
  activateWorld: 'Attiva World',
  inactiveNoteActivatable: "L'attivazione salva in config.json e avvia subito il World.",
  inactiveNoteManual: (id: string) => `Implementato in locale ma non assemblato. Per attivarlo, imposta worlds.${id}.enabled a true in config.json e riavvia.`,
  hideFromAgent: "Nascondi all'agente",
  showToAgent: "Mostra all'agente",
  restartWorld: 'Riavvia World',
  deactivateWorld: 'Disattiva World',
  visibleToAgent: "Visibile all'agente",
  hidden: 'Nascosto',
  prefixPending: 'Ricaricamento prefisso in attesa',
  kvTools: 'Strumenti',
  kvNone: '(nessuno)',
  kvWorkspace: 'Area di lavoro',
  listSep: ', ',
  driftNote: "La consegna degli eventi segue già il nuovo stato; il prompt dell'ambiente e le dichiarazioni degli strumenti si aggiornano dopo un ricaricamento del prefisso.",
  sumVisible: (n: number) => `Visibili ${n}`,
  sumHidden: (n: number) => `Nascosti ${n}`,
  sumInactive: (n: number) => `Inattivi ${n}`,
  sumMissing: (n: number) => `Non disponibili ${n}`,
  noWorlds: 'Nessun World',
  listLoadFailed: (msg: string) => `Caricamento dell'elenco dei World non riuscito: ${msg}`,
  loading: 'Caricamento…',
};
