import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Visão geral dos Worlds',
  introTitle: 'Worlds',
  sheetTitle: 'Status da montagem',
  reloadPrefixBtn: '↻ Recarregar prefixo de sistema',
  prefixReloaded: 'Prefixo recarregado',
  prefixReloadFailed: (msg: string) => `Falha ao recarregar o prefixo: ${msg}`,
  updated: 'Atualizado',
  toggleFailed: (msg: string) => `Falha ao alternar: ${msg}`,
  reloadNowTitle: 'Recarregar o prefixo de sistema agora?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `“${name}” está visível para o agente novamente.` : `“${name}” agora está oculto para o agente.`)
    + '\n\nA entrega de eventos já segue o novo estado. Recarregar atualiza o prompt do ambiente e as declarações de ferramentas e mantém as mensagens existentes da conversa. '
    + 'Se cancelar, eles são atualizados na próxima transferência de contexto ou reinício.',
  deactivateTitle: (name: string) => `Desativar “${name}”?`,
  deactivateBody: (id: string) =>
    'O World para imediatamente (seus processos externos e conexões gerenciados são encerrados), e '
    + `worlds.${id}.enabled=false é gravado em config.json. O prompt do ambiente e as ferramentas do agente são retirados na hora; ativar de novo o reconstrói com a configuração atual.`,
  activated: 'Ativado',
  deactivated: 'Desativado',
  activateFailed: (msg: string) => `Falha na ativação: ${msg}`,
  deactivateFailed: (msg: string) => `Falha na desativação: ${msg}`,
  restartTitle: (name: string) => `Reiniciar “${name}”?`,
  restartBody: 'Para e reconstrói o World para aplicar as configurações marcadas para reinício do World. Processos e conexões gerenciados param e reiniciam.',
  restarted: 'Reiniciado',
  restartFailed: (msg: string) => `Falha ao reiniciar: ${msg}`,
  lampAssembly: 'montagem',
  notInstalled: 'Indisponível',
  notActive: 'Inativo',
  declaredByPersona: 'Declarado pela Persona',
  optionalAddon: 'Complemento opcional',
  open: 'Abrir',
  details: '→ Detalhes',
  toolsCount: (id: string, n: number) => `${id} · ${n} ${n === 1 ? 'ferramenta' : 'ferramentas'}`,
  missingReasonDefault: 'Não foi possível carregar este World.',
  activateWorld: 'Ativar World',
  inactiveNoteActivatable: 'Ativar salva em config.json e inicia o World na hora.',
  inactiveNoteManual: (id: string) => `Implementado localmente, mas não montado. Para ativá-lo, defina worlds.${id}.enabled como true em config.json e reinicie.`,
  hideFromAgent: 'Ocultar do agente',
  showToAgent: 'Mostrar ao agente',
  restartWorld: 'Reiniciar World',
  deactivateWorld: 'Desativar World',
  visibleToAgent: 'Visível para o agente',
  hidden: 'Oculto',
  prefixPending: 'Recarga do prefixo pendente',
  kvTools: 'Ferramentas',
  kvNone: '(nenhuma)',
  kvWorkspace: 'Espaço de trabalho',
  listSep: ', ',
  driftNote: 'A entrega de eventos já segue o novo estado; o prompt do ambiente e as declarações de ferramentas são atualizados após recarregar o prefixo.',
  sumVisible: (n: number) => `Visíveis: ${n}`,
  sumHidden: (n: number) => `Ocultos: ${n}`,
  sumInactive: (n: number) => `Inativos: ${n}`,
  sumMissing: (n: number) => `Indisponíveis: ${n}`,
  noWorlds: 'Nenhum World',
  listLoadFailed: (msg: string) => `Falha ao carregar a lista de Worlds: ${msg}`,
  loading: 'Carregando…',
};
