import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'World-Übersicht',
  introTitle: 'Worlds',
  sheetTitle: 'Assemblierungsstatus',
  reloadPrefixBtn: '↻ Systempräfix neu laden',
  prefixReloaded: 'Präfix neu geladen',
  prefixReloadFailed: (msg: string) => `Neuladen des Präfixes fehlgeschlagen: ${msg}`,
  updated: 'Aktualisiert',
  toggleFailed: (msg: string) => `Umschalten fehlgeschlagen: ${msg}`,
  reloadNowTitle: 'Systempräfix jetzt neu laden?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `„${name}“ ist für den Agenten wieder sichtbar.` : `„${name}“ ist jetzt vor dem Agenten verborgen.`)
    + '\n\nDie Ereigniszustellung folgt bereits dem neuen Zustand. Neuladen aktualisiert den Umgebungs-Prompt und die Tool-Deklarationen und behält bestehende Gesprächsnachrichten. '
    + 'Bei Abbruch werden sie bei der nächsten Kontextübergabe oder beim nächsten Neustart aktualisiert.',
  deactivateTitle: (name: string) => `„${name}“ deaktivieren?`,
  deactivateBody: (id: string) =>
    'Die World stoppt sofort (ihre verwalteten externen Prozesse und Verbindungen werden beendet), und '
    + `worlds.${id}.enabled=false wird in config.json zurückgeschrieben. Umgebungs-Prompt und Tools des Agenten werden sofort entfernt; eine erneute Aktivierung baut sie aus der aktuellen Konfiguration neu auf.`,
  activated: 'Aktiviert',
  deactivated: 'Deaktiviert',
  activateFailed: (msg: string) => `Aktivierung fehlgeschlagen: ${msg}`,
  deactivateFailed: (msg: string) => `Deaktivierung fehlgeschlagen: ${msg}`,
  restartTitle: (name: string) => `„${name}“ neu starten?`,
  restartBody: 'Stoppt die World und baut sie neu auf, um Einstellungen anzuwenden, die einen World-Neustart erfordern. Verwaltete Prozesse und Verbindungen werden gestoppt und neu gestartet.',
  restarted: 'Neu gestartet',
  restartFailed: (msg: string) => `Neustart fehlgeschlagen: ${msg}`,
  lampAssembly: 'Assemblierung',
  notInstalled: 'Nicht verfügbar',
  notActive: 'Inaktiv',
  declaredByPersona: 'Von der Persona deklariert',
  optionalAddon: 'Optionales Add-on',
  open: 'Öffnen',
  details: '→ Details',
  toolsCount: (id: string, n: number) => `${id} · ${n} ${n === 1 ? 'Tool' : 'Tools'}`,
  missingReasonDefault: 'Diese World konnte nicht geladen werden.',
  activateWorld: 'World aktivieren',
  inactiveNoteActivatable: 'Die Aktivierung speichert in config.json und startet die World sofort.',
  inactiveNoteManual: (id: string) => `Lokal implementiert, aber nicht assembliert. Zum Aktivieren setze worlds.${id}.enabled in config.json auf true und starte neu.`,
  hideFromAgent: 'Vor dem Agenten verbergen',
  showToAgent: 'Dem Agenten zeigen',
  restartWorld: 'World neu starten',
  deactivateWorld: 'World deaktivieren',
  visibleToAgent: 'Für den Agenten sichtbar',
  hidden: 'Verborgen',
  prefixPending: 'Präfix-Neuladen ausstehend',
  kvTools: 'Tools',
  kvNone: '(keine)',
  kvWorkspace: 'Arbeitsbereich',
  listSep: ', ',
  driftNote: 'Die Ereigniszustellung folgt bereits dem neuen Zustand; Umgebungs-Prompt und Tool-Deklarationen werden nach einem Neuladen des Präfixes aktualisiert.',
  sumVisible: (n: number) => `Sichtbar ${n}`,
  sumHidden: (n: number) => `Verborgen ${n}`,
  sumInactive: (n: number) => `Inaktiv ${n}`,
  sumMissing: (n: number) => `Nicht verfügbar ${n}`,
  noWorlds: 'Keine Worlds',
  listLoadFailed: (msg: string) => `World-Liste konnte nicht geladen werden: ${msg}`,
  loading: 'Lädt…',
};
