import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'World 개요',
  introTitle: 'World 목록',
  sheetTitle: '구성 상태',
  reloadPrefixBtn: '↻ 시스템 프리픽스 다시 불러오기',
  prefixReloaded: '프리픽스를 다시 불러왔습니다',
  prefixReloadFailed: (msg: string) => `프리픽스를 다시 불러오지 못했습니다: ${msg}`,
  updated: '업데이트했습니다',
  toggleFailed: (msg: string) => `전환하지 못했습니다: ${msg}`,
  reloadNowTitle: '지금 시스템 프리픽스를 다시 불러오시겠습니까?',
  reloadNowBody: (name: string, wantVisible: boolean) =>
    (wantVisible ? `"${name}"이(가) 에이전트에게 다시 보입니다.` : `"${name}"을(를) 에이전트에게서 숨겼습니다.`)
    + '\n\n이벤트 전달은 이미 새 상태를 따릅니다. 다시 불러오면 환경 프롬프트와 도구 선언이 업데이트되고 기존 대화는 유지됩니다. '
    + '취소하면 다음 컨텍스트 인계나 재시작 때 업데이트됩니다.',
  deactivateTitle: (name: string) => `"${name}"을(를) 비활성화하시겠습니까?`,
  deactivateBody: (id: string) =>
    'World가 즉시 중지되고(관리하는 외부 프로세스와 연결도 함께 정리됨), config.json에 '
    + `worlds.${id}.enabled=false가 기록됩니다. 에이전트의 환경 프롬프트와 도구는 바로 제거되며, 다시 활성화하면 현재 설정으로 다시 만듭니다.`,
  activated: '활성화했습니다',
  deactivated: '비활성화했습니다',
  activateFailed: (msg: string) => `활성화하지 못했습니다: ${msg}`,
  deactivateFailed: (msg: string) => `비활성화하지 못했습니다: ${msg}`,
  restartTitle: (name: string) => `"${name}"을(를) 재시작하시겠습니까?`,
  restartBody: 'World를 중지하고 다시 만들어 "World 재시작 후 적용"으로 표시된 설정을 적용합니다. 관리하는 프로세스와 연결은 중지된 뒤 다시 시작됩니다.',
  restarted: '재시작했습니다',
  restartFailed: (msg: string) => `재시작하지 못했습니다: ${msg}`,
  lampAssembly: '구성',
  notInstalled: '사용 불가',
  notActive: '비활성',
  declaredByPersona: 'Persona에서 정의',
  optionalAddon: '선택형 애드온',
  open: '열기',
  details: '→ 세부 정보',
  toolsCount: (id: string, n: number) => `${id} · 도구 ${n}개`,
  missingReasonDefault: '이 World를 불러올 수 없습니다.',
  activateWorld: 'World 활성화',
  inactiveNoteActivatable: '활성화하면 config.json에 기록되고 즉시 시작됩니다.',
  inactiveNoteManual: (id: string) => `로컬에 구현은 있지만 구성되지 않았습니다. 사용하려면 config.json에서 worlds.${id}.enabled를 true로 바꾸고 재시작하세요.`,
  hideFromAgent: '에이전트에게서 숨기기',
  showToAgent: '에이전트에게 표시',
  restartWorld: 'World 재시작',
  deactivateWorld: 'World 비활성화',
  visibleToAgent: '에이전트에게 보임',
  hidden: '숨김',
  prefixPending: '프리픽스 다시 불러오기 대기',
  kvTools: '도구',
  kvNone: '(없음)',
  kvWorkspace: '작업 공간',
  listSep: ', ',
  driftNote: '이벤트 전달은 이미 새 상태를 따릅니다. 환경 프롬프트와 도구 선언은 프리픽스를 다시 불러온 뒤 업데이트됩니다.',
  sumVisible: (n: number) => `표시 ${n}`,
  sumHidden: (n: number) => `숨김 ${n}`,
  sumInactive: (n: number) => `비활성 ${n}`,
  sumMissing: (n: number) => `사용 불가 ${n}`,
  noWorlds: 'World가 없습니다',
  listLoadFailed: (msg: string) => `World 목록을 불러오지 못했습니다: ${msg}`,
  loading: '불러오는 중…',
};
