import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: 'Copiar',
  copyNothing: 'Nada para copiar',
  copied: 'Copiado',
  copyFailed: 'Falha ao copiar; o texto foi expandido para seleção manual',
  imageReadFailed: 'Falha ao ler a imagem',
  canvasUnsupported: 'Este navegador não suporta canvas; não é possível redimensionar a imagem',
  imageEncodeFailed: 'Falha ao recodificar a imagem',
  fileFallback: 'Arquivo',
  imageFallback: 'Imagem',
  notImage: (name: string) => `${name} não está em um formato de imagem suportado (JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `Não foi possível decodificar ${name}`,
  stillTooLarge: (name: string, mb: number) => `${name} ainda excede ${mb}MB após o redimensionamento`,
  lamp: {
    online: 'normal',
    loading: 'iniciando',
    error: 'erro',
    offline: 'desativado',
  },
  cancel: 'Cancelar',
  proceedAnyway: 'Continuar mesmo assim',
  confirm: 'Confirmar',
  close: '✕ Fechar (Esc)',
  tooManyImages: (max: number) => `No máximo ${max} ${max === 1 ? 'imagem' : 'imagens'} por mensagem`,
  messageInput: 'Entrada de mensagem',
  typeMessage: 'Digite uma mensagem…',
  processingImages: (count: number) => `Processando ${count} ${count === 1 ? 'imagem' : 'imagens'}…`,
  sendMessage: 'Enviar mensagem',
  addImage: 'Adicionar imagem',
  addImageHint: 'Adicionar imagem (também dá para colar ou arrastar)',
  removeImage: (name: string) => `Remover ${name}`,
};
