import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: 'Copia',
  copyNothing: 'Niente da copiare',
  copied: 'Copiato',
  copyFailed: 'Copia non riuscita; testo espanso per la selezione manuale',
  imageReadFailed: "Lettura dell'immagine non riuscita",
  canvasUnsupported: "Questo browser non supporta canvas; impossibile ridimensionare l'immagine",
  imageEncodeFailed: "Ricodifica dell'immagine non riuscita",
  fileFallback: 'File',
  imageFallback: 'Immagine',
  notImage: (name: string) => `${name} non è un formato immagine supportato (JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name} non può essere decodificato`,
  stillTooLarge: (name: string, mb: number) => `${name} supera ancora ${mb} MB dopo il ridimensionamento`,
  lamp: {
    online: 'attivo',
    loading: 'in avvio',
    error: 'errore',
    offline: 'disattivato',
  },
  cancel: 'Annulla',
  proceedAnyway: 'Procedi comunque',
  confirm: 'Conferma',
  close: '✕ Chiudi (Esc)',
  tooManyImages: (max: number) => `Al massimo ${max} immagini per messaggio`,
  messageInput: 'Inserimento messaggio',
  typeMessage: 'Scrivi un messaggio…',
  processingImages: (count: number) => `Elaborazione di ${count} ${count === 1 ? 'immagine' : 'immagini'}…`,
  sendMessage: 'Invia messaggio',
  addImage: 'Aggiungi immagine',
  addImageHint: 'Aggiungi immagine (puoi anche incollarla o trascinarla)',
  removeImage: (name: string) => `Rimuovi ${name}`,
};
