import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: '複製',
  copyNothing: '取不到要複製的內容',
  copied: '已複製',
  copyFailed: '複製失敗，已展開文字供手動選取',
  imageReadFailed: '讀取圖片失敗',
  canvasUnsupported: '瀏覽器不支援 canvas,無法縮放圖片',
  imageEncodeFailed: '圖片重新編碼失敗',
  fileFallback: '檔案',
  imageFallback: '圖片',
  notImage: (name: string) => `${name} 不是支援的圖片格式(JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name} 無法解碼`,
  stillTooLarge: (name: string, mb: number) => `${name} 縮放後仍超過 ${mb}MB`,
  lamp: {
    online: '正常',
    loading: '啟動中',
    error: '故障',
    offline: '未啟用',
  },
  cancel: '取消',
  proceedAnyway: '仍要繼續',
  confirm: '確認',
  close: '✕ 關閉 (Esc)',
  tooManyImages: (max: number) => `一則訊息最多 ${max} 張圖`,
  messageInput: '訊息輸入',
  typeMessage: '輸入訊息…',
  processingImages: (count: number) => `處理 ${count} 張圖片…`,
  sendMessage: '傳送訊息',
  addImage: '新增圖片',
  addImageHint: '新增圖片（也可貼上或拖入）',
  removeImage: (name: string) => `移除 ${name}`,
};
