import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: '복사',
  copyNothing: '복사할 내용이 없습니다',
  copied: '복사했습니다',
  copyFailed: '복사하지 못했습니다. 텍스트를 펼쳤으니 직접 선택하세요',
  imageReadFailed: '이미지를 읽지 못했습니다',
  canvasUnsupported: '이 브라우저는 canvas를 지원하지 않아 이미지 크기를 줄일 수 없습니다',
  imageEncodeFailed: '이미지를 다시 인코딩하지 못했습니다',
  fileFallback: '파일',
  imageFallback: '이미지',
  notImage: (name: string) => `${name}은(는) 지원하지 않는 이미지 형식입니다(JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name}을(를) 디코딩할 수 없습니다`,
  stillTooLarge: (name: string, mb: number) => `${name}은(는) 크기를 줄인 뒤에도 ${mb}MB를 넘습니다`,
  lamp: {
    online: '정상',
    loading: '시작 중',
    error: '오류',
    offline: '사용 안 함',
  },
  cancel: '취소',
  proceedAnyway: '그래도 계속',
  confirm: '확인',
  close: '✕ 닫기 (Esc)',
  tooManyImages: (max: number) => `메시지 하나에 이미지는 최대 ${max}장입니다`,
  messageInput: '메시지 입력',
  typeMessage: '메시지 입력…',
  processingImages: (count: number) => `이미지 ${count}장 처리 중…`,
  sendMessage: '메시지 보내기',
  addImage: '이미지 추가',
  addImageHint: '이미지 추가(붙여넣기나 끌어다 놓기도 가능)',
  removeImage: (name: string) => `${name} 제거`,
};
