import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: 'Copier',
  copyNothing: 'Rien à copier',
  copied: 'Copié',
  copyFailed: 'Échec de la copie ; texte déplié pour sélection manuelle',
  imageReadFailed: "Échec de la lecture de l'image",
  canvasUnsupported: "Ce navigateur ne prend pas en charge canvas ; impossible de redimensionner l'image",
  imageEncodeFailed: "Échec du réencodage de l'image",
  fileFallback: 'Fichier',
  imageFallback: 'Image',
  notImage: (name: string) => `${name} n'est pas un format d'image pris en charge (JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `${name} n'a pas pu être décodé`,
  stillTooLarge: (name: string, mb: number) => `${name} dépasse encore ${mb} Mo après redimensionnement`,
  lamp: {
    online: 'actif',
    loading: 'démarrage',
    error: 'erreur',
    offline: 'désactivé',
  },
  cancel: 'Annuler',
  proceedAnyway: 'Continuer quand même',
  confirm: 'Confirmer',
  close: '✕ Fermer (Échap)',
  tooManyImages: (max: number) => `${max} images au maximum par message`,
  messageInput: 'Saisie du message',
  typeMessage: 'Saisissez un message…',
  processingImages: (count: number) => `Traitement de ${count} image${count > 1 ? 's' : ''}…`,
  sendMessage: 'Envoyer le message',
  addImage: 'Ajouter une image',
  addImageHint: 'Ajouter une image (coller ou glisser-déposer fonctionne aussi)',
  removeImage: (name: string) => `Retirer ${name}`,
};
