import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  copy: 'Copiar',
  copyNothing: 'No hay nada que copiar',
  copied: 'Copiado',
  copyFailed: 'No se pudo copiar; el texto se expandió para seleccionarlo manualmente',
  imageReadFailed: 'No se pudo leer la imagen',
  canvasUnsupported: 'Este navegador no admite canvas; no se puede redimensionar la imagen',
  imageEncodeFailed: 'Falló la recodificación de la imagen',
  fileFallback: 'Archivo',
  imageFallback: 'Imagen',
  notImage: (name: string) => `${name} no tiene un formato de imagen compatible (JPEG / PNG / WebP / GIF)`,
  undecodable: (name: string) => `No se pudo decodificar ${name}`,
  stillTooLarge: (name: string, mb: number) => `${name} sigue superando ${mb}MB tras redimensionar`,
  lamp: {
    online: 'en línea',
    loading: 'iniciando',
    error: 'falla',
    offline: 'desactivado',
  },
  cancel: 'Cancelar',
  proceedAnyway: 'Continuar de todos modos',
  confirm: 'Confirmar',
  close: '✕ Cerrar (Esc)',
  tooManyImages: (max: number) => `Máximo ${max} ${max === 1 ? 'imagen' : 'imágenes'} por mensaje`,
  messageInput: 'Entrada de mensaje',
  typeMessage: 'Escribe un mensaje…',
  processingImages: (count: number) => `Procesando ${count} ${count === 1 ? 'imagen' : 'imágenes'}…`,
  sendMessage: 'Enviar mensaje',
  addImage: 'Agregar imagen',
  addImageHint: 'Agregar imagen (también puedes pegarla o arrastrarla)',
  removeImage: (name: string) => `Quitar ${name}`,
};
