import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Diagnóstico',
  navGroup: 'Core',
  pageTitle: 'Diagnóstico',
  subRun: 'Ejecución',
  subSessions: 'Sesiones',
  subEvents: 'Eventos',
  subRunlog: 'Registro de ejecución',
  subData: 'Datos',
  subConfig: 'Configuración',
  groupObserve: 'Observar',
  groupMaintain: 'Mantener',
  dataTitle: 'Datos de Core',
  dataDesc: 'Almacenamiento que Core acumula por su cuenta: el almacén de eventos, la sesión, los registros de ejecución y el libro de uso.',
  configTitle: 'Configuración de Core',
  configDesc: 'Los cambios se guardan automáticamente en config.json. Los ajustes marcados para reinicio se aplican al reiniciar; el resto se aplica de inmediato.',
  configEmpty: 'Core no tiene ajustes configurables.',
  netOffline: 'No se puede acceder a la API',

  // events.ts
  eventsDesc: 'Registros de eventos que el agente puede consultar.',
  allSources: 'Todas las fuentes',
  sourceTitle: 'Filtra por fuente. Las sugerencias vienen de los eventos cargados; puedes escribir cualquier fuente.',
  showArchive: 'Mostrar archivo sin procesar',
  showArchiveTitle: 'Incluir los eventos archivados que no se entregan directamente al contexto',
  loadEarlier: '← Cargar anteriores',
  evHeadTime: 'Hora',
  evHeadSource: 'Fuente',
  evHeadType: 'Tipo',
  evHeadText: 'Texto',
  noEvents: 'Aún no hay eventos',

  // run.ts
  runTitle: 'Estado del ciclo',
  noStatus: 'Aún no hay estado',
  statBehind: 'Pendientes de entrega',
  statDelivered: 'Entregado hasta',
  statTruncating: 'Traspaso de contexto',
  truncatingOn: 'en curso',
  truncatingOff: 'ninguno',
  statProvider: 'Proveedor de modelo actual',
  statContext: 'Contexto',
  statMessages: 'mensajes de la sesión',
  statCache: 'Aciertos de caché',
  statRounds: 'Rondas de este lote',
  statBatches: 'Lotes totales',
  statEvents: 'Cursor del último evento',
  statOnline: 'En línea en la terminal',
  statRun: 'Ejecución',
  unitMsgs: 'mensajes',
  unitPeople: 'usuarios',
  runPaused: 'en pausa',
  runBlocked: 'entrega retenida',
  runRunning: 'en ejecución',

  // runlog.ts
  currentRun: 'Ejecución actual',
  allLevels: 'Todos los niveles',
  areaPlaceholder: 'Prefijo de área, p. ej. worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Regex; coincide con el mensaje y los datos',
  roundPlaceholder: 'Ronda',
  roundField: 'Ronda',
  refresh: 'Actualizar',
  runlogDesc: 'Registros de ejecución, invisibles para el agente.',
  logHeadTime: 'Hora',
  logHeadLevel: 'Nivel',
  logHeadArea: 'Área',
  logHeadMsg: 'Mensaje',
  noLog: 'No hay entradas de registro',
  logDetail: 'Expandir',
  copyEntry: 'Copiar entrada',

  // sessions.ts
  sessionsTitle: 'Estadísticas de sesiones',
  sessionsDesc: 'Uso de tokens y aciertos de caché de cada sesión en este proceso. Los conteos vuelven a cero al reiniciar y solo se conservan las 8 sesiones temporales terminadas más recientes. Para el historial entre reinicios, consulta “Uso y costo”.',
  sesHeadStatus: 'Estado',
  sesHeadCalls: 'Llamadas',
  sesHeadInput: 'tok de entrada',
  sesHeadCache: 'Aciertos de caché',
  sesHeadOutput: 'tok de salida',
  sesHeadMsgs: 'Mensajes',
  noSessions: 'Aún no hay sesiones',
  running: 'sin terminar',
  ended: 'terminada',
};
