import { pick } from '../../core/language.ts';

const zh = {
  // index.ts
  navLabel: '运行诊断',
  navGroup: '系统',
  pageTitle: '运行诊断',
  subRun: '运行',
  subSessions: '会话统计',
  subEvents: '事件流',
  subRunlog: '运行日志',
  subTools: '工具表',
  subData: '数据',
  subParams: '参数',
  dataTitle: 'Core 的数据',
  dataDesc: '事件库、session、运行日志、用量流水这些 Core 自己攒下的存储。',
  paramsTitle: 'Core 参数',
  paramsDesc: '修改自动保存到 config.json。标有重启要求的参数在重启后生效,其余立即生效。',
  paramsEmpty: 'Core 没有可调参数。',
  netOffline: '接口不可达',
  toolsNote: (msg: string) => `完整工具表接口不可用：${msg}；上方是当前主循环那一份。`,

  // tools.ts
  ioGroup: (name: string | undefined) => `IO 工具 · ${name}`,
  groupCore: '原生动作 · core',
  groupPersona: '记忆 / 文件工具 · Persona',
  noDescription: '（未填写工具说明）',
  paramCount: (n: number) => `${n} 个参数`,
  paramHeadPath: '参数路径',
  paramHeadType: '类型',
  paramHeadConstraint: '约束',
  paramHeadDesc: '说明',
  required: '必填',
  optional: '可选',
  noParams: '这个工具没有声明参数',
  copySchema: '复制 schema',
  fullSchema: '完整 JSON Schema',
  toolsTitle: '工具库',
  toolsDesc: '当前提供给模型的工具定义，只读。',
  toolCount: (n: number) => `${n} 个`,
  toolsFilter: '筛选工具名或说明…',
  toolsEmpty: '工具表为空——主循环启动后会在这里出现',

  // events.ts
  eventsDesc: '事件记录，agent 可查询。',
  allSources: '全部来源',
  showArchive: '显示原始归档',
  showArchiveTitle: '包括仅归档、未直接投递到上下文的事件',
  loadEarlier: '← 加载更早',
  evHeadTime: '时间',
  evHeadSource: '来源',
  evHeadType: '类型',
  evHeadText: '正文',
  noEvents: '暂无事件',

  // run.ts
  runTitle: '运行态',
  noStatus: '暂无状态',
  statContext: '上下文',
  statMessages: 'session 消息',
  statCache: '缓存命中',
  statRounds: '本批轮数',
  statBatches: '累计批次',
  statEvents: '事件库',
  statOnline: '终端在线',
  statRun: '运行',
  unitMsgs: '条',
  unitEvents: '条',
  unitPeople: '人',
  runPaused: '暂停',
  runBlocked: '闹钟阻断',
  runRunning: '进行',

  // runlog.ts
  currentRun: '当前 run',
  allLevels: '全部级别',
  areaPlaceholder: '区域前缀,如 worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '正则,匹配内容与 data',
  roundPlaceholder: '轮次',
  roundField: '轮次',
  refresh: '刷新',
  runlogDesc: '运行日志，agent 不可见。',
  logHeadTime: '时间',
  logHeadLevel: '级别',
  logHeadArea: '区域',
  logHeadMsg: '内容',
  noLog: '暂无日志',

  // sessions.ts
  sessionsTitle: '会话统计',
  sessionsDesc: '本次运行中各 session 的 token 用量与缓存命中。跨重启统计见「用量 · 成本」。',
  sesHeadStatus: '状态',
  sesHeadCalls: '调用',
  sesHeadInput: '输入 tok',
  sesHeadCache: '缓存命中',
  sesHeadOutput: '输出 tok',
  sesHeadMsgs: '消息',
  noSessions: '暂无 session',
  running: '进行中',
  ended: '已结束',
};

const en: typeof zh = {
  // index.ts
  navLabel: 'Diagnostics',
  navGroup: 'System',
  pageTitle: 'Diagnostics',
  subRun: 'Run',
  subSessions: 'Sessions',
  subEvents: 'Events',
  subRunlog: 'Run log',
  subTools: 'Tools',
  subData: 'Data',
  subParams: 'Parameters',
  dataTitle: 'Core data',
  dataDesc: 'Storage Core accumulates on its own: the event store, the session, run logs and the usage ledger.',
  paramsTitle: 'Core parameters',
  paramsDesc: 'Changes save to config.json automatically. Parameters marked for restart apply after restarting; the rest apply immediately.',
  paramsEmpty: 'Core has no tunable parameters.',
  netOffline: 'API unreachable',
  toolsNote: (msg: string) => `Full tool table endpoint unavailable: ${msg}; shown above is the main loop's current copy.`,

  // tools.ts
  ioGroup: (name: string | undefined) => `IO tools · ${name}`,
  groupCore: 'Native actions · core',
  groupPersona: 'Memory / file tools · Persona',
  noDescription: '(no tool description)',
  paramCount: (n: number) => `${n} params`,
  paramHeadPath: 'Path',
  paramHeadType: 'Type',
  paramHeadConstraint: 'Constraint',
  paramHeadDesc: 'Description',
  required: 'required',
  optional: 'optional',
  noParams: 'This tool declares no parameters',
  copySchema: 'Copy schema',
  fullSchema: 'Full JSON Schema',
  toolsTitle: 'Tool library',
  toolsDesc: 'Current tool definitions provided to the model. Read-only.',
  toolCount: (n: number) => `${n} tools`,
  toolsFilter: 'Filter by tool name or description…',
  toolsEmpty: 'Tool table is empty — it appears here once the main loop starts',

  // events.ts
  eventsDesc: 'Event records, queryable by the agent.',
  allSources: 'All sources',
  showArchive: 'Show raw archive',
  showArchiveTitle: 'Include archived events that are not delivered directly to the context',
  loadEarlier: '← Load earlier',
  evHeadTime: 'Time',
  evHeadSource: 'Source',
  evHeadType: 'Type',
  evHeadText: 'Text',
  noEvents: 'No events yet',

  // run.ts
  runTitle: 'Loop status',
  noStatus: 'No status yet',
  statContext: 'Context',
  statMessages: 'session messages',
  statCache: 'Cache hit',
  statRounds: 'Rounds this batch',
  statBatches: 'Total batches',
  statEvents: 'Event store',
  statOnline: 'Terminal online',
  statRun: 'Run',
  unitMsgs: 'msgs',
  unitEvents: 'events',
  unitPeople: 'users',
  runPaused: 'paused',
  runBlocked: 'schedule blocked',
  runRunning: 'running',

  // runlog.ts
  currentRun: 'Current run',
  allLevels: 'All levels',
  areaPlaceholder: 'Area prefix, e.g. worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Regex, matches message and data',
  roundPlaceholder: 'Round',
  roundField: 'Round',
  refresh: 'Refresh',
  runlogDesc: 'Run logs, invisible to the agent.',
  logHeadTime: 'Time',
  logHeadLevel: 'Level',
  logHeadArea: 'Area',
  logHeadMsg: 'Message',
  noLog: 'No log entries',

  // sessions.ts
  sessionsTitle: 'Session stats',
  sessionsDesc: 'Token usage and cache hits for each session in this run. For history across restarts, see "Usage · Cost".',
  sesHeadStatus: 'Status',
  sesHeadCalls: 'Calls',
  sesHeadInput: 'Input tok',
  sesHeadCache: 'Cache hit',
  sesHeadOutput: 'Output tok',
  sesHeadMsgs: 'Messages',
  noSessions: 'No sessions yet',
  running: 'running',
  ended: 'ended',
};

export const S = pick({ zh, en });
