import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '実行診断',
  navGroup: 'Core',
  pageTitle: '実行診断',
  subRun: '実行',
  subSessions: 'セッション統計',
  subEvents: 'イベント',
  subRunlog: '実行ログ',
  subData: 'データ',
  subConfig: '設定',
  groupObserve: '観察',
  groupMaintain: 'メンテナンス',
  dataTitle: 'Core のデータ',
  dataDesc: 'Core 自身が蓄積するストレージ：イベントストア、セッション、実行ログ、使用量の記録。',
  configTitle: 'Core の設定',
  configDesc: '変更は config.json に自動保存されます。再起動が必要と表示された設定は再起動後に、それ以外はすぐに反映されます。',
  configEmpty: 'Core に調整できる設定はありません。',
  netOffline: 'API に接続できません',

  // events.ts
  eventsDesc: 'イベントの記録です。エージェントが検索できます。',
  allSources: 'すべてのソース',
  sourceTitle: 'ソースで絞り込みます。候補は読み込み済みのイベントから取得しますが、直接入力もできます。',
  showArchive: '生のアーカイブを表示',
  showArchiveTitle: 'アーカイブのみで、コンテキストに直接配信されていないイベントも含める',
  loadEarlier: '← さらに前を読み込む',
  evHeadTime: '時刻',
  evHeadSource: 'ソース',
  evHeadType: '種類',
  evHeadText: '本文',
  noEvents: 'イベントはまだありません',

  // run.ts
  runTitle: 'ループの状態',
  noStatus: '状態はまだありません',
  statBehind: '配信待ちのイベント',
  statDelivered: '配信済みの位置',
  statTruncating: 'コンテキストの引き継ぎ',
  truncatingOn: '進行中',
  truncatingOff: 'なし',
  statProvider: '現在のモデルプロバイダー',
  statContext: 'コンテキスト',
  statMessages: 'セッションのメッセージ',
  statCache: 'キャッシュヒット',
  statRounds: 'このバッチのラウンド数',
  statBatches: '累計バッチ数',
  statEvents: '最新のイベントカーソル',
  statOnline: 'ターミナル接続中',
  statRun: '実行',
  unitMsgs: '件',
  unitPeople: '人',
  runPaused: '一時停止',
  runBlocked: '配信保留',
  runRunning: '実行中',

  // runlog.ts
  currentRun: '現在の実行',
  allLevels: 'すべてのレベル',
  areaPlaceholder: '領域のプレフィックス（例：worlds.minecraft）', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '正規表現。メッセージと data に一致',
  roundPlaceholder: 'ラウンド',
  roundField: 'ラウンド',
  refresh: '更新',
  runlogDesc: '実行ログです。エージェントからは見えません。',
  logHeadTime: '時刻',
  logHeadLevel: 'レベル',
  logHeadArea: '領域',
  logHeadMsg: 'メッセージ',
  noLog: 'ログはまだありません',
  logDetail: '展開',
  copyEntry: 'この項目をコピー',

  // sessions.ts
  sessionsTitle: 'セッション統計',
  sessionsDesc: 'このプロセス内の各セッションの token 使用量とキャッシュヒットです。再起動するとゼロから数え直し、終了した一時セッションは直近 8 個だけ残ります。再起動をまたいだ統計は「使用量とコスト」を参照してください。',
  sesHeadStatus: '状態',
  sesHeadCalls: '呼び出し',
  sesHeadInput: '入力 tok',
  sesHeadCache: 'キャッシュヒット',
  sesHeadOutput: '出力 tok',
  sesHeadMsgs: 'メッセージ',
  noSessions: 'セッションはまだありません',
  running: '未終了',
  ended: '終了',
};
