import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Диагностика',
  navGroup: 'Core',
  pageTitle: 'Диагностика',
  subRun: 'Запуск',
  subSessions: 'Сессии',
  subEvents: 'События',
  subRunlog: 'Журнал запуска',
  subData: 'Данные',
  subConfig: 'Конфигурация',
  groupObserve: 'Наблюдение',
  groupMaintain: 'Обслуживание',
  dataTitle: 'Данные Core',
  dataDesc: 'Хранилища, которые Core накапливает сам: хранилище событий, сессия, журналы запуска и журнал расхода.',
  configTitle: 'Конфигурация Core',
  configDesc: 'Изменения автоматически сохраняются в config.json. Параметры с пометкой о перезапуске применяются после перезапуска, остальные сразу.',
  configEmpty: 'У Core нет настраиваемых параметров.',
  netOffline: 'API недоступен',

  // events.ts
  eventsDesc: 'Записи событий, доступные агенту для запросов.',
  allSources: 'Все источники',
  sourceTitle: 'Фильтр по источнику. Подсказки берутся из загруженных событий; можно ввести любой источник.',
  showArchive: 'Показать сырой архив',
  showArchiveTitle: 'Включить архивные события, которые не доставляются в контекст напрямую',
  loadEarlier: '← Загрузить более ранние',
  evHeadTime: 'Время',
  evHeadSource: 'Источник',
  evHeadType: 'Тип',
  evHeadText: 'Текст',
  noEvents: 'Событий пока нет',

  // run.ts
  runTitle: 'Состояние цикла',
  noStatus: 'Состояния пока нет',
  statBehind: 'Ожидают доставки',
  statDelivered: 'Доставлено до',
  statTruncating: 'Передача контекста',
  truncatingOn: 'идёт',
  truncatingOff: 'нет',
  statProvider: 'Текущий провайдер модели',
  statContext: 'Контекст',
  statMessages: 'сообщения сессии',
  statCache: 'Попадания в кэш',
  statRounds: 'Раунды в этом пакете',
  statBatches: 'Всего пакетов',
  statEvents: 'Курсор последнего события',
  statOnline: 'В сети в терминале',
  statRun: 'Запуск',
  unitMsgs: 'сообщ.',
  unitPeople: 'польз.',
  runPaused: 'приостановлен',
  runBlocked: 'расписание заблокировано',
  runRunning: 'работает',

  // runlog.ts
  currentRun: 'Текущий запуск',
  allLevels: 'Все уровни',
  areaPlaceholder: 'Префикс области, например worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Регулярное выражение по сообщению и данным',
  roundPlaceholder: 'Раунд',
  roundField: 'Раунд',
  refresh: 'Обновить',
  runlogDesc: 'Журнал запуска, агенту не виден.',
  logHeadTime: 'Время',
  logHeadLevel: 'Уровень',
  logHeadArea: 'Область',
  logHeadMsg: 'Сообщение',
  noLog: 'Записей журнала нет',
  logDetail: 'Развернуть',
  copyEntry: 'Копировать запись',

  // sessions.ts
  sessionsTitle: 'Статистика сессий',
  sessionsDesc: 'Расход token и попадания в кэш по каждой сессии этого процесса. После перезапуска счёт начинается с нуля; из завершённых временных сессий хранятся только 8 последних. Историю между перезапусками см. в разделе «Расход и затраты».',
  sesHeadStatus: 'Состояние',
  sesHeadCalls: 'Вызовы',
  sesHeadInput: 'Вход, tok',
  sesHeadCache: 'Попадания в кэш',
  sesHeadOutput: 'Выход, tok',
  sesHeadMsgs: 'Сообщения',
  noSessions: 'Сессий пока нет',
  running: 'не завершена',
  ended: 'завершена',
};
