import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Diagnose',
  navGroup: 'Core',
  pageTitle: 'Diagnose',
  subRun: 'Lauf',
  subSessions: 'Sessions',
  subEvents: 'Ereignisse',
  subRunlog: 'Laufprotokoll',
  subData: 'Daten',
  subConfig: 'Konfiguration',
  groupObserve: 'Beobachten',
  groupMaintain: 'Warten',
  dataTitle: 'Core-Daten',
  dataDesc: 'Speicher, den der Core selbst anlegt: Ereignisspeicher, Session, Laufprotokolle und Verbrauchsjournal.',
  configTitle: 'Core-Konfiguration',
  configDesc: 'Änderungen werden automatisch in config.json gespeichert. Für einen Neustart markierte Einstellungen gelten nach dem Neustart, alle anderen sofort.',
  configEmpty: 'Der Core hat keine einstellbaren Werte.',
  netOffline: 'API nicht erreichbar',

  // events.ts
  eventsDesc: 'Ereignisdatensätze, vom Agenten abfragbar.',
  allSources: 'Alle Quellen',
  sourceTitle: 'Nach Quelle filtern. Vorschläge stammen aus geladenen Ereignissen; jede Quelle kann eingegeben werden.',
  showArchive: 'Rohes Archiv anzeigen',
  showArchiveTitle: 'Archivierte Ereignisse einbeziehen, die nicht direkt in den Kontext zugestellt werden',
  loadEarlier: '← Ältere laden',
  evHeadTime: 'Zeit',
  evHeadSource: 'Quelle',
  evHeadType: 'Typ',
  evHeadText: 'Text',
  noEvents: 'Noch keine Ereignisse',

  // run.ts
  runTitle: 'Schleifenstatus',
  noStatus: 'Noch kein Status',
  statBehind: 'Ausstehende Zustellung',
  statDelivered: 'Zugestellt bis',
  statTruncating: 'Kontextübergabe',
  truncatingOn: 'läuft',
  truncatingOff: 'keine',
  statProvider: 'Aktueller Modellanbieter',
  statContext: 'Kontext',
  statMessages: 'Session-Nachrichten',
  statCache: 'Cache-Treffer',
  statRounds: 'Runden in diesem Batch',
  statBatches: 'Batches gesamt',
  statEvents: 'Neuester Ereignis-Cursor',
  statOnline: 'Terminal online',
  statRun: 'Lauf',
  unitMsgs: 'Nachr.',
  unitPeople: 'Nutzer',
  runPaused: 'pausiert',
  runBlocked: 'Zustellung zurückgehalten',
  runRunning: 'läuft',

  // runlog.ts
  currentRun: 'Aktueller Lauf',
  allLevels: 'Alle Stufen',
  areaPlaceholder: 'Bereichspräfix, z. B. worlds.minecraft', // arch-allow: Beispielpräfix im Bereichsfilter des Laufprotokolls, nur Platzhaltertext
  grepPlaceholder: 'Regex, prüft Meldung und data',
  roundPlaceholder: 'Runde',
  roundField: 'Runde',
  refresh: 'Aktualisieren',
  runlogDesc: 'Laufprotokolle, für den Agenten unsichtbar.',
  logHeadTime: 'Zeit',
  logHeadLevel: 'Stufe',
  logHeadArea: 'Bereich',
  logHeadMsg: 'Meldung',
  noLog: 'Keine Protokolleinträge',
  logDetail: 'Aufklappen',
  copyEntry: 'Eintrag kopieren',

  // sessions.ts
  sessionsTitle: 'Session-Statistik',
  sessionsDesc: 'Token-Verbrauch und Cache-Treffer je Session in diesem Prozess. Die Zähler beginnen beim Neustart bei null, und nur die 8 zuletzt beendeten temporären Sessions bleiben erhalten. Für den Verlauf über Neustarts hinweg siehe „Verbrauch & Kosten“.',
  sesHeadStatus: 'Status',
  sesHeadCalls: 'Aufrufe',
  sesHeadInput: 'Eingabe-tok',
  sesHeadCache: 'Cache-Treffer',
  sesHeadOutput: 'Ausgabe-tok',
  sesHeadMsgs: 'Nachrichten',
  noSessions: 'Noch keine Sessions',
  running: 'nicht beendet',
  ended: 'beendet',
};
