import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '실행 진단',
  navGroup: 'Core',
  pageTitle: '실행 진단',
  subRun: '실행',
  subSessions: '세션 통계',
  subEvents: '이벤트',
  subRunlog: '실행 로그',
  subData: '데이터',
  subConfig: '설정',
  groupObserve: '관찰',
  groupMaintain: '유지 관리',
  dataTitle: 'Core 데이터',
  dataDesc: 'Core가 스스로 쌓는 저장소: 이벤트 저장소, 세션, 실행 로그, 사용량 기록.',
  configTitle: 'Core 설정',
  configDesc: '변경 사항은 config.json에 자동 저장됩니다. 재시작이 필요하다고 표시된 설정은 재시작 후에, 나머지는 즉시 적용됩니다.',
  configEmpty: 'Core에는 조정할 수 있는 설정이 없습니다.',
  netOffline: 'API에 연결할 수 없음',

  // events.ts
  eventsDesc: '이벤트 기록이며 에이전트가 조회할 수 있습니다.',
  allSources: '모든 소스',
  sourceTitle: '소스로 필터링합니다. 후보는 불러온 이벤트에서 가져오며 직접 입력할 수도 있습니다.',
  showArchive: '원본 보관 기록 표시',
  showArchiveTitle: '보관만 되고 컨텍스트에 직접 전달되지 않은 이벤트도 포함',
  loadEarlier: '← 이전 항목 불러오기',
  evHeadTime: '시간',
  evHeadSource: '소스',
  evHeadType: '유형',
  evHeadText: '본문',
  noEvents: '아직 이벤트가 없습니다',

  // run.ts
  runTitle: '루프 상태',
  noStatus: '아직 상태가 없습니다',
  statBehind: '전달 대기 이벤트',
  statDelivered: '전달 위치',
  statTruncating: '컨텍스트 인계',
  truncatingOn: '진행 중',
  truncatingOff: '없음',
  statProvider: '현재 모델 공급자',
  statContext: '컨텍스트',
  statMessages: '세션 메시지',
  statCache: '캐시 적중',
  statRounds: '이번 배치 라운드',
  statBatches: '누적 배치',
  statEvents: '최신 이벤트 커서',
  statOnline: '터미널 접속',
  statRun: '실행',
  unitMsgs: '개',
  unitPeople: '명',
  runPaused: '일시 중지',
  runBlocked: '알람 대기',
  runRunning: '실행 중',

  // runlog.ts
  currentRun: '현재 실행',
  allLevels: '모든 수준',
  areaPlaceholder: '영역 접두사, 예: worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '정규식, 메시지와 data에 일치',
  roundPlaceholder: '라운드',
  roundField: '라운드',
  refresh: '새로 고침',
  runlogDesc: '실행 로그이며 에이전트에게 보이지 않습니다.',
  logHeadTime: '시간',
  logHeadLevel: '수준',
  logHeadArea: '영역',
  logHeadMsg: '메시지',
  noLog: '로그 항목이 없습니다',
  logDetail: '펼치기',
  copyEntry: '이 항목 복사',

  // sessions.ts
  sessionsTitle: '세션 통계',
  sessionsDesc: '이 프로세스 안 각 세션의 token 사용량과 캐시 적중입니다. 재시작하면 0부터 다시 세며, 끝난 임시 세션은 최근 8개만 남깁니다. 재시작을 넘는 통계는 "사용량 및 비용"을 확인하세요.',
  sesHeadStatus: '상태',
  sesHeadCalls: '호출',
  sesHeadInput: '입력 tok',
  sesHeadCache: '캐시 적중',
  sesHeadOutput: '출력 tok',
  sesHeadMsgs: '메시지',
  noSessions: '아직 세션이 없습니다',
  running: '진행 중',
  ended: '종료됨',
};
