import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '執行診斷',
  navGroup: 'Core',
  pageTitle: '執行診斷',
  subRun: '執行',
  subSessions: '工作階段統計',
  subEvents: '事件流',
  subRunlog: '執行日誌',
  subData: '資料',
  subConfig: '設定',
  groupObserve: '觀察',
  groupMaintain: '維護',
  dataTitle: 'Core 的資料',
  dataDesc: '事件庫、session、執行日誌、用量流水這些 Core 自己累積的儲存。',
  configTitle: 'Core 設定',
  configDesc: '修改自動儲存到 config.json。標有重新啟動要求的設定在重新啟動後生效,其餘立即生效。',
  configEmpty: 'Core 沒有可調設定。',
  netOffline: '介面無法連線',

  // events.ts
  eventsDesc: '事件記錄，agent 可查詢。',
  allSources: '全部來源',
  sourceTitle: '依來源篩選。候選項目取自已載入的事件，也可以直接輸入。',
  showArchive: '顯示原始封存',
  showArchiveTitle: '包括僅封存、未直接投遞到上下文的事件',
  loadEarlier: '← 載入更早',
  evHeadTime: '時間',
  evHeadSource: '來源',
  evHeadType: '類型',
  evHeadText: '正文',
  noEvents: '暫無事件',

  // run.ts
  runTitle: '執行狀態',
  noStatus: '暫無狀態',
  statBehind: '待投遞事件',
  statDelivered: '投遞水位',
  statTruncating: '上下文交接',
  truncatingOn: '進行中',
  truncatingOff: '無',
  statProvider: '目前模型供應商',
  statContext: '上下文',
  statMessages: 'session 訊息',
  statCache: '快取命中',
  statRounds: '本批輪數',
  statBatches: '累計批次',
  statEvents: '最新事件游標',
  statOnline: '終端在線',
  statRun: '執行',
  unitMsgs: '則',
  unitPeople: '人',
  runPaused: '暫停',
  runBlocked: '投遞扣留',
  runRunning: '進行',

  // runlog.ts
  currentRun: '目前 run',
  allLevels: '全部層級',
  areaPlaceholder: '區域前綴,如 worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '正規表示式,比對內容與 data',
  roundPlaceholder: '輪次',
  roundField: '輪次',
  refresh: '重新整理',
  runlogDesc: '執行日誌，agent 不可見。',
  logHeadTime: '時間',
  logHeadLevel: '層級',
  logHeadArea: '區域',
  logHeadMsg: '內容',
  noLog: '暫無日誌',
  logDetail: '展開',
  copyEntry: '複製這一條',

  // sessions.ts
  sessionsTitle: '工作階段統計',
  sessionsDesc: '本次處理程序內各 session 的 token 用量與快取命中，重新啟動後從零計數；已結束的臨時 session 只保留最近 8 個。跨重新啟動的統計見「用量與成本」。',
  sesHeadStatus: '狀態',
  sesHeadCalls: '呼叫',
  sesHeadInput: '輸入 tok',
  sesHeadCache: '快取命中',
  sesHeadOutput: '輸出 tok',
  sesHeadMsgs: '訊息',
  noSessions: '暫無 session',
  running: '未結束',
  ended: '已結束',
};
