import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Diagnostica',
  navGroup: 'Core',
  pageTitle: 'Diagnostica',
  subRun: 'Esecuzione',
  subSessions: 'Sessioni',
  subEvents: 'Eventi',
  subRunlog: 'Log di esecuzione',
  subData: 'Dati',
  subConfig: 'Configurazione',
  groupObserve: 'Osserva',
  groupMaintain: 'Manutenzione',
  dataTitle: 'Dati del Core',
  dataDesc: "Archiviazione che il Core accumula da sé: l'archivio eventi, la sessione, i log di esecuzione e il registro d'uso.",
  configTitle: 'Configurazione del Core',
  configDesc: 'Le modifiche vengono salvate automaticamente in config.json. Le impostazioni contrassegnate per il riavvio si applicano dopo il riavvio; le altre subito.',
  configEmpty: 'Il Core non ha impostazioni regolabili.',
  netOffline: 'API non raggiungibile',

  // events.ts
  eventsDesc: "Record degli eventi, consultabili dall'agente.",
  allSources: 'Tutte le fonti',
  sourceTitle: 'Filtra per fonte. I suggerimenti provengono dagli eventi caricati; si può digitare qualsiasi fonte.',
  showArchive: "Mostra l'archivio grezzo",
  showArchiveTitle: 'Includi gli eventi archiviati non consegnati direttamente al contesto',
  loadEarlier: '← Carica precedenti',
  evHeadTime: 'Ora',
  evHeadSource: 'Fonte',
  evHeadType: 'Tipo',
  evHeadText: 'Testo',
  noEvents: 'Ancora nessun evento',

  // run.ts
  runTitle: 'Stato del ciclo',
  noStatus: 'Ancora nessuno stato',
  statBehind: 'In attesa di consegna',
  statDelivered: 'Consegnato fino a',
  statTruncating: 'Passaggio di contesto',
  truncatingOn: 'in corso',
  truncatingOff: 'nessuno',
  statProvider: 'Provider del modello attuale',
  statContext: 'Contesto',
  statMessages: 'messaggi della sessione',
  statCache: 'Hit della cache',
  statRounds: 'Turni in questo batch',
  statBatches: 'Batch totali',
  statEvents: "Cursore dell'ultimo evento",
  statOnline: 'Terminale in linea',
  statRun: 'Esecuzione',
  unitMsgs: 'msg',
  unitPeople: 'utenti',
  runPaused: 'in pausa',
  runBlocked: 'consegna trattenuta',
  runRunning: 'in esecuzione',

  // runlog.ts
  currentRun: 'Esecuzione attuale',
  allLevels: 'Tutti i livelli',
  areaPlaceholder: 'Prefisso di area, ad es. worlds.minecraft', // arch-allow: prefisso di esempio nel filtro per area del log, solo testo indicativo
  grepPlaceholder: 'Regex, confronta messaggio e data',
  roundPlaceholder: 'Turno',
  roundField: 'Turno',
  refresh: 'Aggiorna',
  runlogDesc: "Log di esecuzione, invisibili all'agente.",
  logHeadTime: 'Ora',
  logHeadLevel: 'Livello',
  logHeadArea: 'Area',
  logHeadMsg: 'Messaggio',
  noLog: 'Nessuna voce di log',
  logDetail: 'Espandi',
  copyEntry: 'Copia voce',

  // sessions.ts
  sessionsTitle: 'Statistiche sessioni',
  sessionsDesc: 'Uso dei token e hit della cache per ogni sessione in questo processo. I conteggi ripartono da zero al riavvio e vengono conservate solo le 8 sessioni temporanee terminate più recenti. Per la cronologia tra i riavvii, vedi «Uso e costi».',
  sesHeadStatus: 'Stato',
  sesHeadCalls: 'Chiamate',
  sesHeadInput: 'tok in ingresso',
  sesHeadCache: 'Hit della cache',
  sesHeadOutput: 'tok in uscita',
  sesHeadMsgs: 'Messaggi',
  noSessions: 'Ancora nessuna sessione',
  running: 'non terminata',
  ended: 'terminata',
};
