import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Diagnostic',
  navGroup: 'Core',
  pageTitle: 'Diagnostic',
  subRun: 'Exécution',
  subSessions: 'Sessions',
  subEvents: 'Événements',
  subRunlog: "Journal d'exécution",
  subData: 'Données',
  subConfig: 'Configuration',
  groupObserve: 'Observer',
  groupMaintain: 'Maintenance',
  dataTitle: 'Données du Core',
  dataDesc: "Stockage accumulé par le Core lui-même : la base d'événements, la session, les journaux d'exécution et le registre d'utilisation.",
  configTitle: 'Configuration du Core',
  configDesc: "Les modifications sont enregistrées automatiquement dans config.json. Les réglages marqués pour redémarrage s'appliquent après redémarrage ; les autres immédiatement.",
  configEmpty: "Le Core n'a aucun réglage ajustable.",
  netOffline: 'API injoignable',

  // events.ts
  eventsDesc: "Enregistrements d'événements, consultables par l'agent.",
  allSources: 'Toutes les sources',
  sourceTitle: 'Filtrer par source. Les suggestions proviennent des événements chargés ; toute source peut être saisie.',
  showArchive: "Afficher l'archive brute",
  showArchiveTitle: 'Inclure les événements archivés qui ne sont pas livrés directement au contexte',
  loadEarlier: '← Charger plus ancien',
  evHeadTime: 'Heure',
  evHeadSource: 'Source',
  evHeadType: 'Type',
  evHeadText: 'Texte',
  noEvents: "Aucun événement pour l'instant",

  // run.ts
  runTitle: 'État de la boucle',
  noStatus: "Aucun état pour l'instant",
  statBehind: 'En attente de livraison',
  statDelivered: "Livré jusqu'à",
  statTruncating: 'Passation de contexte',
  truncatingOn: 'en cours',
  truncatingOff: 'aucune',
  statProvider: 'Fournisseur de modèle actuel',
  statContext: 'Contexte',
  statMessages: 'messages de session',
  statCache: 'Succès de cache',
  statRounds: 'Tours de ce lot',
  statBatches: 'Lots au total',
  statEvents: "Dernier curseur d'événement",
  statOnline: 'Terminal en ligne',
  statRun: 'Exécution',
  unitMsgs: 'msg',
  unitPeople: 'utilisateurs',
  runPaused: 'en pause',
  runBlocked: 'bloqué par planification',
  runRunning: 'en cours',

  // runlog.ts
  currentRun: 'Exécution actuelle',
  allLevels: 'Tous les niveaux',
  areaPlaceholder: 'Préfixe de zone, par ex. worlds.minecraft', // arch-allow: exemple de préfixe du filtre de zone du journal, texte indicatif seulement
  grepPlaceholder: 'Regex, appliquée au message et à data',
  roundPlaceholder: 'Tour',
  roundField: 'Tour',
  refresh: 'Actualiser',
  runlogDesc: "Journaux d'exécution, invisibles pour l'agent.",
  logHeadTime: 'Heure',
  logHeadLevel: 'Niveau',
  logHeadArea: 'Zone',
  logHeadMsg: 'Message',
  noLog: 'Aucune entrée de journal',
  logDetail: 'Déplier',
  copyEntry: "Copier l'entrée",

  // sessions.ts
  sessionsTitle: 'Statistiques des sessions',
  sessionsDesc: "Utilisation des tokens et succès de cache de chaque session dans ce processus. Les compteurs repartent de zéro au redémarrage, et seules les 8 dernières sessions temporaires terminées sont conservées. Pour l'historique entre redémarrages, voir « Utilisation et coûts ».",
  sesHeadStatus: 'État',
  sesHeadCalls: 'Appels',
  sesHeadInput: 'tok entrée',
  sesHeadCache: 'Succès de cache',
  sesHeadOutput: 'tok sortie',
  sesHeadMsgs: 'Messages',
  noSessions: "Aucune session pour l'instant",
  running: 'non terminée',
  ended: 'terminée',
};
