import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Diagnóstico',
  navGroup: 'Core',
  pageTitle: 'Diagnóstico',
  subRun: 'Execução',
  subSessions: 'Sessões',
  subEvents: 'Eventos',
  subRunlog: 'Log de execução',
  subData: 'Dados',
  subConfig: 'Configuração',
  groupObserve: 'Observar',
  groupMaintain: 'Manter',
  dataTitle: 'Dados do Core',
  dataDesc: 'Armazenamento que o Core acumula por conta própria: o armazenamento de eventos, a sessão, os logs de execução e o registro de uso.',
  configTitle: 'Configuração do Core',
  configDesc: 'As alterações são salvas automaticamente em config.json. As configurações marcadas para reinício valem após reiniciar; as demais valem na hora.',
  configEmpty: 'O Core não tem configurações ajustáveis.',
  netOffline: 'API inacessível',

  // events.ts
  eventsDesc: 'Registros de eventos que o agente pode consultar.',
  allSources: 'Todas as fontes',
  sourceTitle: 'Filtre por fonte. As sugestões vêm dos eventos carregados; qualquer fonte pode ser digitada.',
  showArchive: 'Mostrar arquivo bruto',
  showArchiveTitle: 'Incluir eventos arquivados que não são entregues diretamente ao contexto',
  loadEarlier: '← Carregar anteriores',
  evHeadTime: 'Hora',
  evHeadSource: 'Fonte',
  evHeadType: 'Tipo',
  evHeadText: 'Texto',
  noEvents: 'Ainda não há eventos',

  // run.ts
  runTitle: 'Status do loop',
  noStatus: 'Ainda não há status',
  statBehind: 'Aguardando entrega',
  statDelivered: 'Entregue até',
  statTruncating: 'Transferência de contexto',
  truncatingOn: 'em andamento',
  truncatingOff: 'nenhuma',
  statProvider: 'Provedor de modelo atual',
  statContext: 'Contexto',
  statMessages: 'mensagens da sessão',
  statCache: 'Acertos de cache',
  statRounds: 'Rodadas neste lote',
  statBatches: 'Total de lotes',
  statEvents: 'Cursor do último evento',
  statOnline: 'On-line no terminal',
  statRun: 'Execução',
  unitMsgs: 'mensagens',
  unitPeople: 'usuários',
  runPaused: 'pausado',
  runBlocked: 'agendamento bloqueado',
  runRunning: 'em execução',

  // runlog.ts
  currentRun: 'Execução atual',
  allLevels: 'Todos os níveis',
  areaPlaceholder: 'Prefixo de área, ex.: worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Regex; corresponde à mensagem e aos dados',
  roundPlaceholder: 'Rodada',
  roundField: 'Rodada',
  refresh: 'Atualizar',
  runlogDesc: 'Logs de execução, invisíveis para o agente.',
  logHeadTime: 'Hora',
  logHeadLevel: 'Nível',
  logHeadArea: 'Área',
  logHeadMsg: 'Mensagem',
  noLog: 'Nenhuma entrada de log',
  logDetail: 'Expandir',
  copyEntry: 'Copiar entrada',

  // sessions.ts
  sessionsTitle: 'Estatísticas de sessões',
  sessionsDesc: 'Uso de tokens e acertos de cache de cada sessão neste processo. As contagens recomeçam do zero ao reiniciar, e só as 8 sessões temporárias encerradas mais recentes são mantidas. Para o histórico entre reinícios, veja “Uso e custo”.',
  sesHeadStatus: 'Status',
  sesHeadCalls: 'Chamadas',
  sesHeadInput: 'tok de entrada',
  sesHeadCache: 'Acertos de cache',
  sesHeadOutput: 'tok de saída',
  sesHeadMsgs: 'Mensagens',
  noSessions: 'Ainda não há sessões',
  running: 'não encerrada',
  ended: 'encerrada',
};
