import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'ターミナル',
  currentProvider: '現在のモデルプロバイダー',
  noProvider: 'モデルプロバイダーが選択されていません',
  ctxOpenAria: 'token の内訳を表示',
  ctxPanelAria: 'token の内訳',
  netConnecting: 'コンソールに接続中…',
  netOnline: 'コンソールに接続済み',
  netOffline: 'コンソールの接続が切れました',
  composerLabel: 'ターミナルのメッセージ入力',
  composerPlaceholder: 'メッセージを入力…',
  exportDiagnostics: '診断をエクスポート',
  exportFailed: '診断パッケージを取得できませんでした',
  exportConfirmTitle: '診断パッケージをエクスポート',
  exportConfirmBody: '診断パッケージには会話、プロンプト、イベント、ツール呼び出し、使用量、実行ログが含まれます。設定内の秘密情報はマスクされ、それ以外はそのまま書き出されます。共有する前に個人情報が含まれていないか確認してください。',
  composerFork: 'バックグラウンドセッションを表示中です。ここで送信したメッセージはメインセッションに届きます',
  composerNoProvider: '現在のモデルプロバイダーを利用できません。「モデル接続」ページで設定してください',
  composerQueued: 'ターミナルのチャネルが再接続中のため、メッセージをキューに入れました',
  emptyConnecting: 'デバッグチャネルに接続中…',
  ctxTitle: (total: string, max: string | null) =>
    `コンテキスト ${total}${max !== null ? ` / ${max}` : ''} tok · クリックで内訳を表示`,
  ctxWaiting: 'コンテキストのデータを待っています',
  sessionResetNote: 'SESSION を切り詰めて再構築しました',
  debugUnavailable: 'デバッグチャネルを利用できません',
  debugNotMounted: 'デバッグチャネルを利用できないため、タイムラインを表示できません。',

  // status.ts
  docTitle: (name: string) => `コンソール · ${name}`,
  chipDisconnected: '未接続',
  chipMsgs: ' 件',
  chipCache: 'キャッシュ ',
  chipBatchesPre: '累計 ',
  chipBatchesPost: ' バッチ',
  chipPaused: '⏸ 一時停止中',
  chipBehind: (n: number) => `配信待ち ${n}`,
  chipScheduleBlocked: '◷ アラーム待ち',
  chipTruncating: '切り詰め中',
  chipOnline: '接続中 ',
  phaseDelivering: 'イベントをコンテキストに書き込み中',
  phaseModel: 'モデルの出力を待っています',
  phaseTools: 'ツールを実行中',
  phaseBackoff: (clock: string) => `モデル呼び出しに失敗しました。${clock} に再試行します`,
  phaseHandoff: 'コンテキストの引き継ぎ中',
  phaseRound: (n: number) => `第 ${n} ラウンド`,
  phaseRunning: (names: string) => `実行中：${names}`,

  // fork.ts
  mainLabel: 'メインセッション',
  forkViewing: '◉ バックグラウンドセッションを表示中 ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} 件 · ~${tok} tok · ` + (ended ? '終了（固定）' : `未終了（${sec} 秒ごとに更新）`),
  forkReadOnly: 'この表示は読み取り専用です。入力欄から送信したメッセージはメインセッションに届きます。',
  forkBack: '⏎ メインセッションに戻る',
  forkEmpty: '（このセッションにはまだメッセージがありません）',
  forkFetchFailed: (msg: string) => `（取得に失敗しました：${msg}）`,

  // sessions.ts
  sessionBandTitle: '今回の実行におけるセッションごとの累計使用量',
  sessionCache: (pct: string) => `キャッシュ ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? '未終了' : `終了 ${endedAt}`}\n` +
    `入力 ${prompt} / 出力 ${completion} / キャッシュヒット ${hit}`,

  // timeline.ts
  jumpBottom: '↓ 一番下へ',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} 文字`,
  ordinalTitle: (index: number) => `セッションの ${index} 番目の Item`,
  userGlyphTitle: 'user メッセージ',
  empty: '（空）',
  visibleReasoning: (n: number) => `表示される思考 ${n} 文字`,
  encryptedReasoning: (n: number) => `暗号化された思考 ${n} 文字`,
  summary: '要約',
  monologTitle: (phase: string) => `assistant 本文${phase ? ` · ${phase}` : ''}`,
  refusal: '拒否',
  synthetic: '合成',
  encryptedPayload: (n: number) => `暗号化されたペイロード ${n} 文字`,
  rawItems: '元の Item',
  headStart: '合成された冒頭 · 保存されない',
  headEnd: '合成された冒頭 · ここまで',
  sessionEmpty: 'セッションは空です',

  // context.ts
  groupPrefix: 'システムプレフィックス',
  groupTools: 'ツール',
  groupDialogue: '会話',
  catOrient: 'ORIENTATION',
  catConstitution: '憲法 CONSTITUTION',
  catEnv: '環境の説明 · World',
  catToolsUsage: 'ツールの使い方の説明',
  catMemory: '記憶 MEMORY',
  catPrefixMisc: '前置き / 区切り / 構造',
  catToolsSchema: 'ツールの schema',
  catHead: '合成された冒頭',
  catReasoning: '思考',
  catDialogue: '会話のやり取り · イベント',
  catToolIO: 'ツールの呼び出しと結果',
  ctxNone: 'コンテキストのデータはまだありません。',
  ctxUsage: 'コンテキストの推定内訳',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? '予算不明' : `予算の ${budgetPct}`}　·　過去の思考を保持：${keepOn ? 'オン' : 'オフ'}`,
  toolCount: (n: number) => `　${n} 個`,
  footCountedPre: '合計は上流のカウントに従います（直前の呼び出しで ',
  footCountedPost: ' と集計、それ以降の追加分はローカル推定）。分類はローカル推定から按分した値なので、比率としてのみ見てください。',
  footEstimated: '上流のカウントがまだないため、全体を文字数で推定しています（CJK ≈ 0.6、その他 ≈ 0.3 token/文字、項目ごとに構造分 +8）。次の呼び出しの後は上流のカウントに従います。',
  footSchemaB: 'ツールの schema',
  footSchemaPost: ' は tools パラメーターとして毎回の呼び出しで送信され、メッセージとは別に数えます。',
  footStrippedPre: '過去の思考のうち約 ',
  footStrippedPost: ' tok は破棄済みで、送信されません。',
  footHardPre: '入力が ',
  footHardPost: ' （モデルの入力上限：コンテキストウィンドウから出力の予約分を引いた値）を超えると、Core が強制的に引き継ぎを行います。',
  footSoftPre: 'Persona のソフトしきい値：',
  footSoftPost: (max: string) => `。段階予算 ${max}。`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Cortico へようこそ！最初の Cortico ボットをデプロイしましょう。',
  obProvider: 'まず、モデルプロバイダーを設定してください：',
  obProviderNone: '利用できるモデルプロバイダーがまだ設定されていません',
  obProviderReady: 'モデルプロバイダーを設定しました',
  obWorlds: '次に、ボットが接続する外部環境モジュール（Cortico World）を有効にして設定してください。最初はターミナルでの会話だけを有効にしてもかまいません。',
  obWorldsState: (labels: readonly string[]) => `現在 ${labels.length} 個の外部環境が有効です：${labels.join('、')}`,
  obPrompts: '最後に、ここでシステムプロンプトを編集して、人格の説明、振る舞いのルール、話し方などをカスタマイズできます！',
  obReady: '準備完了！',
  obGoConfigure: '設定する',
  obGoEdit: '編集を始める',
  obStart: 'あいさつしてみますか？',
};
