import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Terminal',
  currentProvider: 'Fournisseur de modèle actuel',
  noProvider: 'Aucun fournisseur sélectionné',
  ctxOpenAria: 'Voir la répartition des tokens',
  ctxPanelAria: 'Répartition des tokens',
  netConnecting: 'Connexion de la console…',
  netOnline: 'Console connectée',
  netOffline: 'Console déconnectée',
  composerLabel: 'Saisie de message du terminal',
  composerPlaceholder: 'Saisissez un message…',
  exportDiagnostics: 'Exporter le diagnostic',
  exportFailed: 'Impossible de récupérer le paquet de diagnostic',
  exportConfirmTitle: 'Exporter le diagnostic',
  exportConfirmBody: "Le paquet contient les conversations, prompts, événements, appels d'outils, l'utilisation et les journaux d'exécution. Les secrets de la configuration sont masqués ; tout le reste est écrit tel quel. Vérifiez qu'il ne contient pas d'informations privées avant de le partager.",
  composerFork: "Affichage d'une session d'arrière-plan ; les messages envoyés ici vont toujours à la session principale",
  composerNoProvider: 'Aucun fournisseur utilisable. Configurez-en un sur la page « Connexions de modèles ».',
  composerQueued: 'Le canal du terminal se reconnecte ; message mis en file',
  emptyConnecting: 'Connexion au canal de débogage…',
  ctxTitle: (total: string, max: string | null) =>
    `Contexte ${total}${max !== null ? ` / ${max}` : ''} tok · cliquez pour la répartition`,
  ctxWaiting: 'En attente des données de contexte',
  sessionResetNote: 'SESSION tronquée et reconstruite',
  debugUnavailable: 'Canal de débogage indisponible',
  debugNotMounted: 'Canal de débogage indisponible ; la chronologie ne peut pas être affichée.',

  // status.ts
  docTitle: (name: string) => `Console · ${name}`,
  chipDisconnected: 'Déconnecté',
  chipMsgs: ' msg',
  chipCache: 'cache ',
  chipBatchesPre: 'cumul ',
  chipBatchesPost: ' lots',
  chipPaused: '⏸ En pause',
  chipBehind: (n: number) => `${n} en attente de livraison`,
  chipScheduleBlocked: '◷ Bloqué par planification',
  chipTruncating: 'Troncature',
  chipOnline: 'en ligne ',
  phaseDelivering: 'Écriture des événements dans le contexte',
  phaseModel: 'En attente de la sortie du modèle',
  phaseTools: 'Exécution des outils',
  phaseBackoff: (clock: string) => `Échec de l'appel au modèle ; nouvelle tentative à ${clock}`,
  phaseHandoff: 'Passation de contexte en cours',
  phaseRound: (n: number) => `tour ${n}`,
  phaseRunning: (names: string) => `en cours : ${names}`,

  // fork.ts
  mainLabel: 'Session principale',
  forkViewing: "◉ Affichage de la session d'arrière-plan ",
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} msg · ~${tok} tok · ` + (ended ? 'terminée (figée)' : `non terminée (actualisée toutes les ${sec} s)`),
  forkReadOnly: 'Cette vue est en lecture seule ; la zone de saisie envoie toujours à la session principale.',
  forkBack: '⏎ Retour à la session principale',
  forkEmpty: "(Cette session n'a pas encore de messages)",
  forkFetchFailed: (msg: string) => `(échec de la récupération : ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Utilisation des sessions pour cette exécution',
  sessionCache: (pct: string) => `cache ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'non terminée' : `terminée ${endedAt}`}\n` +
    `entrée ${prompt} / sortie ${completion} / succès de cache ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Retour en bas',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} caractère${n > 1 ? 's' : ''}`,
  ordinalTitle: (index: number) => `Item n° ${index} de la session`,
  userGlyphTitle: 'message user',
  empty: '(vide)',
  visibleReasoning: (n: number) => `Raisonnement visible ${n} caractère${n > 1 ? 's' : ''}`,
  encryptedReasoning: (n: number) => `Raisonnement chiffré ${n} caractère${n > 1 ? 's' : ''}`,
  summary: 'Résumé',
  monologTitle: (phase: string) => `texte assistant${phase ? ` · ${phase}` : ''}`,
  refusal: 'Refus',
  synthetic: 'synthétique',
  encryptedPayload: (n: number) => `Charge utile chiffrée ${n} caractère${n > 1 ? 's' : ''}`,
  rawItems: 'Items bruts',
  headStart: 'Début de session · non persisté',
  headEnd: 'Début de session · fin',
  sessionEmpty: 'la session est vide',

  // context.ts
  groupPrefix: 'Préfixe système',
  groupTools: 'Outils',
  groupDialogue: 'Dialogue',
  catOrient: 'ORIENTATION',
  catConstitution: 'CONSTITUTION',
  catEnv: 'Environnement · World',
  catToolsUsage: "Notes d'utilisation des outils",
  catMemory: 'MEMORY',
  catPrefixMisc: 'Préambule / séparateurs / structure',
  catToolsSchema: 'Schémas des outils',
  catHead: 'Début de session (synthétique)',
  catReasoning: 'Raisonnement',
  catDialogue: 'Échanges · événements',
  catToolIO: "Appels d'outils et résultats",
  ctxNone: "Aucune donnée de contexte pour l'instant.",
  ctxUsage: 'Répartition estimée du contexte',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Budget inconnu' : `${budgetPct} du budget`} · Conserver le raisonnement passé : ${keepOn ? 'activé' : 'désactivé'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: 'Le total suit le décompte amont (le dernier appel en a compté ',
  footCountedPost: ' ; les ajouts ultérieurs sont des estimations locales) ; les catégories sont réparties au prorata des estimations locales, à lire uniquement comme des proportions.',
  footEstimated: "Pas encore de décompte amont ; tout le contexte est estimé par caractères (CJK ≈ 0,6, autres ≈ 0,3 token/caractère, +8 de surcoût structurel par élément) ; le décompte amont prend le relais après le prochain appel.",
  footSchemaB: 'Les schémas des outils',
  footSchemaPost: ' sont envoyés comme paramètre tools à chaque appel et comptés séparément des messages.',
  footStrippedPre: 'Environ ',
  footStrippedPost: ' tok de raisonnement passé sont exclus des requêtes.',
  footHardPre: 'Au-delà de ',
  footHardPost: " (la limite d'entrée du modèle : fenêtre de contexte moins la sortie réservée), le Core force une passation.",
  footSoftPre: 'Seuil souple de la Persona : ',
  footSoftPost: (max: string) => ` ; budget de l'étape ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Bienvenue dans Cortico ! Configurons votre premier bot Cortico.',
  obProvider: 'Commencez par configurer un fournisseur de modèle :',
  obProviderNone: 'Aucun fournisseur de modèle utilisable pour le moment',
  obProviderReady: 'Fournisseur de modèle configuré',
  obWorlds: 'Ensuite, activez et configurez les environnements externes auxquels votre bot accède (World Cortico). Commencer avec la seule discussion du terminal convient aussi.',
  obWorldsState: (labels: readonly string[]) =>
    `${labels.length} environnement${labels.length > 1 ? 's' : ''} externe${labels.length > 1 ? 's' : ''} actuellement activé${labels.length > 1 ? 's' : ''} : ${labels.join(', ')}`,
  obPrompts: 'Enfin, le prompt système se modifie ici : qui il est, comment il se comporte, comment il parle.',
  obReady: 'Tout est prêt !',
  obGoConfigure: 'Configurer',
  obGoEdit: 'Modifier',
  obStart: 'Dire bonjour ?',
};
