import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Terminal',
  currentProvider: 'Aktueller Modellanbieter',
  noProvider: 'Kein Anbieter ausgewählt',
  ctxOpenAria: 'Token-Aufschlüsselung anzeigen',
  ctxPanelAria: 'Token-Aufschlüsselung',
  netConnecting: 'Konsole verbindet…',
  netOnline: 'Konsole verbunden',
  netOffline: 'Konsole getrennt',
  composerLabel: 'Terminal-Nachrichteneingabe',
  composerPlaceholder: 'Nachricht eingeben…',
  exportDiagnostics: 'Diagnose exportieren',
  exportFailed: 'Das Diagnosepaket konnte nicht abgerufen werden',
  exportConfirmTitle: 'Diagnose exportieren',
  exportConfirmBody: 'Das Paket enthält Gespräche, Prompts, Ereignisse, Tool-Aufrufe, Verbrauch und Laufprotokolle. Secrets in der Konfiguration werden geschwärzt; alles andere wird unverändert geschrieben. Prüfe es vor dem Teilen auf private Informationen.',
  composerFork: 'Du siehst eine Hintergrund-Session; hier gesendete Nachrichten gehen weiterhin an die Haupt-Session',
  composerNoProvider: 'Kein nutzbarer Anbieter. Richte einen auf der Seite „Modellverbindungen“ ein.',
  composerQueued: 'Terminal-Kanal verbindet sich neu; Nachricht eingereiht',
  emptyConnecting: 'Verbinde mit dem Debug-Kanal…',
  ctxTitle: (total: string, max: string | null) =>
    `Kontext ${total}${max !== null ? ` / ${max}` : ''} tok · für Aufschlüsselung klicken`,
  ctxWaiting: 'Warte auf Kontextdaten',
  sessionResetNote: 'SESSION gekürzt und neu aufgebaut',
  debugUnavailable: 'Debug-Kanal nicht verfügbar',
  debugNotMounted: 'Debug-Kanal nicht verfügbar; die Zeitleiste kann nicht angezeigt werden.',

  // status.ts
  docTitle: (name: string) => `Konsole · ${name}`,
  chipDisconnected: 'Getrennt',
  chipMsgs: ' Nachr.',
  chipCache: 'Cache ',
  chipBatchesPre: 'gesamt ',
  chipBatchesPost: ' Batches',
  chipPaused: '⏸ Pausiert',
  chipBehind: (n: number) => `${n} ausstehend`,
  chipScheduleBlocked: '◷ Zustellung zurückgehalten',
  chipTruncating: 'Kürzung läuft',
  chipOnline: 'online ',
  phaseDelivering: 'Ereignisse werden in den Kontext geschrieben',
  phaseModel: 'Warte auf Modellausgabe',
  phaseTools: 'Tools werden ausgeführt',
  phaseBackoff: (clock: string) => `Modellaufruf fehlgeschlagen; neuer Versuch um ${clock}`,
  phaseHandoff: 'Kontextübergabe läuft',
  phaseRound: (n: number) => `Runde ${n}`,
  phaseRunning: (names: string) => `läuft: ${names}`,

  // fork.ts
  mainLabel: 'Haupt-Session',
  forkViewing: '◉ Hintergrund-Session wird angezeigt ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} Nachr. · ~${tok} tok · ` + (ended ? 'beendet (eingefroren)' : `nicht beendet (Aktualisierung alle ${sec} s)`),
  forkReadOnly: 'Diese Ansicht ist schreibgeschützt; das Eingabefeld sendet weiterhin an die Haupt-Session.',
  forkBack: '⏎ Zurück zur Haupt-Session',
  forkEmpty: '(Diese Session hat noch keine Nachrichten)',
  forkFetchFailed: (msg: string) => `(Abruf fehlgeschlagen: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Session-Verbrauch in diesem Lauf',
  sessionCache: (pct: string) => `Cache ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'nicht beendet' : `beendet ${endedAt}`}\n` +
    `Eingabe ${prompt} / Ausgabe ${completion} / Cache-Treffer ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Nach unten',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} Zeichen`,
  ordinalTitle: (index: number) => `Item #${index} in der Session`,
  userGlyphTitle: 'user-Nachricht',
  empty: '(leer)',
  visibleReasoning: (n: number) => `Sichtbarer Denkprozess ${n} Zeichen`,
  encryptedReasoning: (n: number) => `Verschlüsselter Denkprozess ${n} Zeichen`,
  summary: 'Zusammenfassung',
  monologTitle: (phase: string) => `assistant-Text${phase ? ` · ${phase}` : ''}`,
  refusal: 'Ablehnung',
  synthetic: 'synthetisch',
  encryptedPayload: (n: number) => `Verschlüsselte Nutzlast ${n} Zeichen`,
  rawItems: 'Rohe Items',
  headStart: 'Session-Anfang · nicht gespeichert',
  headEnd: 'Session-Anfang · Ende',
  sessionEmpty: 'Session ist leer',

  // context.ts
  groupPrefix: 'Systempräfix',
  groupTools: 'Tools',
  groupDialogue: 'Gespräch',
  catOrient: 'ORIENTATION',
  catConstitution: 'Verfassung CONSTITUTION',
  catEnv: 'Umgebung · World',
  catToolsUsage: 'Hinweise zur Tool-Nutzung',
  catMemory: 'MEMORY',
  catPrefixMisc: 'Präambel / Trenner / Struktur',
  catToolsSchema: 'Tool-Schemas',
  catHead: 'Session-Anfang (synthetisch)',
  catReasoning: 'Denkprozess',
  catDialogue: 'Dialog · Ereignisse',
  catToolIO: 'Tool-Aufrufe und Ergebnisse',
  ctxNone: 'Noch keine Kontextdaten.',
  ctxUsage: 'Geschätzte Kontextaufteilung',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Budget unbekannt' : `${budgetPct} des Budgets`} · Früheren Denkprozess behalten: ${keepOn ? 'an' : 'aus'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: 'Die Summe folgt der Upstream-Zählung (der letzte Aufruf zählte ',
  footCountedPost: '; spätere Zugänge sind lokale Schätzungen); die Kategorien werden anteilig aus lokalen Schätzungen verteilt, lies sie nur als Verhältnisse.',
  footEstimated: 'Noch keine Upstream-Zählung; der ganze Kontext wird nach Zeichen geschätzt (CJK ≈ 0,6, andere ≈ 0,3 Token/Zeichen, +8 Strukturaufwand pro Eintrag); nach dem nächsten Aufruf gilt die Upstream-Zählung.',
  footSchemaB: 'Tool-Schemas',
  footSchemaPost: ' werden bei jedem Aufruf als tools-Parameter gesendet und getrennt von Nachrichten gezählt.',
  footStrippedPre: 'Etwa ',
  footStrippedPost: ' tok früherer Denkprozess sind von Anfragen ausgenommen.',
  footHardPre: 'Jenseits von ',
  footHardPost: ' (Eingabelimit des Modells: Kontextfenster minus reservierte Ausgabe) erzwingt der Core eine Übergabe.',
  footSoftPre: 'Weiche Schwelle der Persona: ',
  footSoftPost: (max: string) => `; Phasenbudget ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Willkommen bei Cortico! Richten wir deinen ersten Cortico-Bot ein.',
  obProvider: 'Konfiguriere zuerst einen Modellanbieter:',
  obProviderNone: 'Noch kein nutzbarer Modellanbieter',
  obProviderReady: 'Modellanbieter konfiguriert',
  obWorlds: 'Aktiviere und konfiguriere als Nächstes die externen Umgebungen, die dein Bot erreicht (Cortico-Worlds). Nur mit dem Terminal-Chat zu beginnen, ist auch in Ordnung.',
  obWorldsState: (labels: readonly string[]) =>
    `Derzeit ${labels.length === 1 ? 'ist 1 externe Umgebung' : `sind ${labels.length} externe Umgebungen`} aktiviert: ${labels.join(', ')}`,
  obPrompts: 'Zum Schluss bearbeitest du hier den System-Prompt: wer der Bot ist, wie er sich verhält, wie er spricht.',
  obReady: 'Alles bereit!',
  obGoConfigure: 'Konfigurieren',
  obGoEdit: 'Bearbeiten',
  obStart: 'Hallo sagen?',
};
