import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '터미널',
  currentProvider: '현재 모델 공급자',
  noProvider: '선택된 모델 공급자 없음',
  ctxOpenAria: 'token 구성 보기',
  ctxPanelAria: 'token 구성',
  netConnecting: '콘솔 연결 중…',
  netOnline: '콘솔 연결됨',
  netOffline: '콘솔 연결 끊김',
  composerLabel: '터미널 메시지 입력',
  composerPlaceholder: '메시지 입력…',
  exportDiagnostics: '진단 내보내기',
  exportFailed: '진단 패키지를 가져오지 못했습니다',
  exportConfirmTitle: '진단 패키지 내보내기',
  exportConfirmBody: '진단 패키지에는 대화, 프롬프트, 이벤트, 도구 호출, 사용량, 실행 로그가 들어 있습니다. 설정의 비밀 값은 가려지며 나머지는 그대로 기록됩니다. 공유하기 전에 개인 정보가 있는지 확인하세요.',
  composerFork: '백그라운드 세션을 보는 중입니다. 여기서 보낸 메시지는 기본 세션으로 갑니다',
  composerNoProvider: '현재 모델 공급자를 사용할 수 없습니다. "모델 연결" 페이지에서 설정하세요',
  composerQueued: '터미널 채널이 다시 연결하는 중이라 메시지를 대기열에 넣었습니다',
  emptyConnecting: '디버그 채널에 연결하는 중…',
  ctxTitle: (total: string, max: string | null) =>
    `컨텍스트 ${total}${max !== null ? ` / ${max}` : ''} tok · 클릭하여 구성 보기`,
  ctxWaiting: '컨텍스트 데이터를 기다리는 중',
  sessionResetNote: 'SESSION을 잘라 내고 다시 만들었습니다',
  debugUnavailable: '디버그 채널을 사용할 수 없음',
  debugNotMounted: '디버그 채널을 사용할 수 없어 타임라인을 표시할 수 없습니다.',

  // status.ts
  docTitle: (name: string) => `콘솔 · ${name}`,
  chipDisconnected: '연결 안 됨',
  chipMsgs: '개',
  chipCache: '캐시 ',
  chipBatchesPre: '누적 ',
  chipBatchesPost: '배치',
  chipPaused: '⏸ 일시 중지됨',
  chipBehind: (n: number) => `전달 대기 ${n}`,
  chipScheduleBlocked: '◷ 알람 대기',
  chipTruncating: '자르는 중',
  chipOnline: '접속 ',
  phaseDelivering: '이벤트를 컨텍스트에 쓰는 중',
  phaseModel: '모델 출력을 기다리는 중',
  phaseTools: '도구 실행 중',
  phaseBackoff: (clock: string) => `모델 호출에 실패했습니다. ${clock}에 다시 시도합니다`,
  phaseHandoff: '컨텍스트 인계 중',
  phaseRound: (n: number) => `${n}번째 라운드`,
  phaseRunning: (names: string) => `실행 중: ${names}`,

  // fork.ts
  mainLabel: '기본 세션',
  forkViewing: '◉ 백그라운드 세션 보는 중 ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count}개 · ~${tok} tok · ` + (ended ? '종료됨(고정)' : `진행 중(${sec}초마다 새로 고침)`),
  forkReadOnly: '이 보기는 읽기 전용이며, 입력란에서 보낸 메시지는 기본 세션으로 갑니다.',
  forkBack: '⏎ 기본 세션으로 돌아가기',
  forkEmpty: '(이 세션에는 아직 메시지가 없습니다)',
  forkFetchFailed: (msg: string) => `(가져오지 못함: ${msg})`,

  // sessions.ts
  sessionBandTitle: '이번 실행의 세션별 누적 사용량',
  sessionCache: (pct: string) => `캐시 ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? '진행 중' : `종료 ${endedAt}`}\n` +
    `입력 ${prompt} / 출력 ${completion} / 캐시 적중 ${hit}`,

  // timeline.ts
  jumpBottom: '↓ 맨 아래로',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n}자`,
  ordinalTitle: (index: number) => `세션의 ${index}번째 Item`,
  userGlyphTitle: 'user 메시지',
  empty: '(비어 있음)',
  visibleReasoning: (n: number) => `보이는 추론 ${n}자`,
  encryptedReasoning: (n: number) => `암호화된 추론 ${n}자`,
  summary: '요약',
  monologTitle: (phase: string) => `assistant 본문${phase ? ` · ${phase}` : ''}`,
  refusal: '거부',
  synthetic: '합성',
  encryptedPayload: (n: number) => `암호화된 페이로드 ${n}자`,
  rawItems: '원본 Item',
  headStart: '합성된 시작부 · 저장 안 됨',
  headEnd: '합성된 시작부 · 끝',
  sessionEmpty: '세션이 비어 있습니다',

  // context.ts
  groupPrefix: '시스템 프리픽스',
  groupTools: '도구',
  groupDialogue: '대화',
  catOrient: 'ORIENTATION',
  catConstitution: '헌법 CONSTITUTION',
  catEnv: '환경 설명 · World',
  catToolsUsage: '도구 사용법 설명',
  catMemory: '기억 MEMORY',
  catPrefixMisc: '머리말 / 구분자 / 구조',
  catToolsSchema: '도구 schema',
  catHead: '합성된 시작부',
  catReasoning: '추론',
  catDialogue: '대화 주고받기 · 이벤트',
  catToolIO: '도구 호출과 결과',
  ctxNone: '아직 컨텍스트 데이터가 없습니다.',
  ctxUsage: '컨텍스트 추정 구성',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? '예산 알 수 없음' : `예산의 ${budgetPct}`} · 이전 추론 유지: ${keepOn ? '켬' : '끔'}`,
  toolCount: (n: number) => ` (${n}개)`,
  footCountedPre: '합계는 업스트림 집계를 따릅니다(직전 호출 집계 ',
  footCountedPost: ', 이후 추가분은 로컬 추정). 분류는 로컬 추정치로 비례 배분한 값이므로 비율로만 보세요.',
  footEstimated: '아직 업스트림 집계가 없어 전체를 글자 수로 추정합니다(CJK ≈ 0.6, 그 외 ≈ 0.3 token/글자, 항목마다 구조 오버헤드 +8). 다음 호출 이후에는 업스트림 집계를 따릅니다.',
  footSchemaB: '도구 schema',
  footSchemaPost: '는 tools 매개변수로 매 호출마다 전송되며 메시지와 따로 집계됩니다.',
  footStrippedPre: '이전 추론 약 ',
  footStrippedPost: ' tok은 버려져 요청에 포함되지 않습니다.',
  footHardPre: '입력이 ',
  footHardPost: '(모델 입력 한도: 컨텍스트 창에서 출력 예약분을 뺀 값)을 넘으면 Core가 인계를 강제합니다.',
  footSoftPre: 'Persona 소프트 임계값: ',
  footSoftPost: (max: string) => `; 단계 예산 ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Cortico에 오신 것을 환영합니다! 이제 첫 번째 Cortico 봇을 배포해 봅시다.',
  obProvider: '먼저 모델 공급자를 설정하세요:',
  obProviderNone: '아직 사용할 수 있는 모델 공급자가 없습니다',
  obProviderReady: '모델 공급자 설정 완료',
  obWorlds: '다음으로, 봇이 연결할 외부 환경 모듈(Cortico World)을 활성화하고 설정하세요. 처음에는 터미널 대화만 활성화해도 됩니다.',
  obWorldsState: (labels: readonly string[]) => `현재 외부 환경 ${labels.length}개가 활성화되어 있습니다: ${labels.join(', ')}`,
  obPrompts: '마지막으로, 여기서 시스템 프롬프트를 편집해 인격 설명, 행동 규칙, 말투 등을 원하는 대로 정할 수 있습니다!',
  obReady: '준비 완료!',
  obGoConfigure: '설정하기',
  obGoEdit: '편집 시작',
  obStart: '인사해 볼까요?',
};
