import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '終端',
  currentProvider: '目前模型供應商',
  noProvider: '未選擇模型供應商',
  ctxOpenAria: '查看 token 分類',
  ctxPanelAria: 'Token 分類',
  netConnecting: '控制台連線中…',
  netOnline: '控制台已連線',
  netOffline: '控制台已中斷連線',
  composerLabel: '終端訊息輸入',
  composerPlaceholder: '輸入訊息…',
  exportDiagnostics: '匯出診斷',
  exportFailed: '診斷包取不回來',
  exportConfirmTitle: '匯出診斷包',
  exportConfirmBody: '診斷包包含對話、提示詞、事件、工具呼叫、用量和執行日誌。設定裡的金鑰已遮蔽，其餘內容原樣寫出。分享前請檢查其中的私人資訊。',
  composerFork: '正在查看背景工作階段；這裡發出的訊息仍送到主工作階段',
  composerNoProvider: '目前模型供應商無法使用，請前往「模型供應商」頁設定',
  composerQueued: '終端通道正在重新連線，訊息已排入佇列',
  emptyConnecting: '連線除錯通道中…',
  ctxTitle: (total: string, max: string | null) =>
    `上下文 ${total}${max !== null ? ` / ${max}` : ''} tok · 點擊查看分類`,
  ctxWaiting: '等待上下文資料',
  sessionResetNote: 'SESSION 已截斷重建',
  debugUnavailable: '除錯通道無法使用',
  debugNotMounted: '除錯通道無法使用，無法顯示時間軸。',

  // status.ts
  docTitle: (name: string) => `控制台 · ${name}`,
  chipDisconnected: '未連線',
  chipMsgs: ' 則',
  chipCache: '快取 ',
  chipBatchesPre: '累計 ',
  chipBatchesPost: ' 批',
  chipPaused: '⏸ 已暫停',
  chipBehind: (n: number) => `待投遞 ${n}`,
  chipScheduleBlocked: '◷ 投遞扣留中',
  chipTruncating: '截斷中',
  chipOnline: '在線 ',
  phaseDelivering: '正在把事件寫入上下文',
  phaseModel: '等待模型輸出',
  phaseTools: '執行工具',
  phaseBackoff: (clock: string) => `模型呼叫失敗，${clock} 重試`,
  phaseHandoff: '上下文交接中',
  phaseRound: (n: number) => `第 ${n} 輪`,
  phaseRunning: (names: string) => `執行中：${names}`,

  // fork.ts
  mainLabel: '主 session',
  forkViewing: '◉ 正在查看背景工作階段 ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} 則 · ~${tok} tok · ` + (ended ? '已結束（定格）' : `未結束（每 ${sec} 秒重新整理）`),
  forkReadOnly: '此檢視唯讀，輸入框發出的訊息仍送到主工作階段。',
  forkBack: '⏎ 返回主 session',
  forkEmpty: '（這個 session 還沒有訊息）',
  forkFetchFailed: (msg: string) => `(擷取失敗: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Session 本次執行累計用量',
  sessionCache: (pct: string) => `快取${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? '未結束' : `已結束 ${endedAt}`}\n` +
    `輸入 ${prompt} / 輸出 ${completion} / 命中 ${hit}`,

  // timeline.ts
  jumpBottom: '↓ 回到底部',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} 字`,
  ordinalTitle: (index: number) => `session 第 ${index} 條 Item`,
  userGlyphTitle: 'user 訊息',
  empty: '（空）',
  visibleReasoning: (n: number) => `可見思考 ${n} 字`,
  encryptedReasoning: (n: number) => `加密思考 ${n} 字元`,
  summary: '摘要',
  monologTitle: (phase: string) => `assistant 正文${phase ? ` · ${phase}` : ''}`,
  refusal: '拒絕',
  synthetic: '合成',
  encryptedPayload: (n: number) => `加密酬載 ${n} 字元`,
  rawItems: '原始 Item',
  headStart: '合成開頭 · 不寫入磁碟',
  headEnd: '合成開頭 · 結束',
  sessionEmpty: 'session 為空',

  // context.ts
  groupPrefix: '系統前綴',
  groupTools: '工具',
  groupDialogue: '對話',
  catOrient: 'ORIENTATION',
  catConstitution: '憲法 CONSTITUTION',
  catEnv: '環境描述 · World',
  catToolsUsage: '工具用法說明',
  catMemory: '記憶 MEMORY',
  catPrefixMisc: '前言 / 分隔 / 結構',
  catToolsSchema: '工具表 schema',
  catHead: '合成開頭',
  catReasoning: '思維鏈',
  catDialogue: '對話往來 · 事件',
  catToolIO: '工具呼叫與結果',
  ctxNone: '暫無上下文資料。',
  ctxUsage: '上下文估計構成',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? '預算未知' : `占預算 ${budgetPct}`}　·　保留歷史思維鏈：${keepOn ? '開' : '關'}`,
  toolCount: (n: number) => `　${n} 個`,
  footCountedPre: '總數以上游計數為準（上一次呼叫已計 ',
  footCountedPost: '，之後新增的為本機估算）；分類依本機估算等比分攤，只看比例。',
  footEstimated: '還沒有上游計數，整份依字數估算（中文≈0.6、其餘≈0.3 token/字，每條 +8 結構開銷）；下一次呼叫後以上游計數為準。',
  footSchemaB: '工具表 schema',
  footSchemaPost: ' 作為 tools 參數隨每次呼叫傳送，與訊息分開計算。',
  footStrippedPre: '歷史思維鏈已捨棄約 ',
  footStrippedPost: ' tok，不傳送。',
  footHardPre: '越過 ',
  footHardPost: '（模型輸入上限：上下文視窗減去輸出預留）由 core 強制交接。',
  footSoftPre: 'Persona 軟閾值：',
  footSoftPost: (max: string) => `；階段預算 ${max}。`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: '歡迎使用 Cortico！現在，讓我們開始部署你的第一個 Cortico Bot。',
  obProvider: '首先，請設定模型供應商：',
  obProviderNone: '尚未設定可用的模型供應商',
  obProviderReady: '模型供應商已設定',
  obWorlds: '接下來，請啟用並設定你的 Bot 接入的外部環境模組（Cortico World）。也可以先僅啟用終端對話。',
  obWorldsState: (labels: readonly string[]) => `目前已經啟用了 ${labels.length} 個外部環境：${labels.join('、')}`,
  obPrompts: '最後，你可以在這裡方便地編輯系統提示詞，來提供人格描述、行為規範、語言風格等客製化內容！',
  obReady: '準備就緒！',
  obGoConfigure: '前往設定',
  obGoEdit: '開始編輯',
  obStart: '打個招呼？',
};
