import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Terminal',
  currentProvider: 'Proveedor de modelo actual',
  noProvider: 'Ningún proveedor seleccionado',
  ctxOpenAria: 'Ver el desglose de tokens',
  ctxPanelAria: 'Desglose de tokens',
  netConnecting: 'Conectando la consola…',
  netOnline: 'Consola conectada',
  netOffline: 'Consola desconectada',
  composerLabel: 'Entrada de mensajes de la terminal',
  composerPlaceholder: 'Escribe un mensaje…',
  exportDiagnostics: 'Exportar diagnóstico',
  exportFailed: 'No se pudo obtener el paquete de diagnóstico',
  exportConfirmTitle: 'Exportar diagnóstico',
  exportConfirmBody: 'El paquete contiene conversaciones, prompts, eventos, llamadas a herramientas, uso y registros de ejecución. Los secretos de la configuración se ocultan; todo lo demás se escribe tal cual. Revisa que no tenga información privada antes de compartirlo.',
  composerFork: 'Estás viendo una sesión en segundo plano; los mensajes que envíes aquí siguen yendo a la sesión principal',
  composerNoProvider: 'No hay un proveedor utilizable. Configura uno en la página Conexiones de modelo.',
  composerQueued: 'El canal de la terminal se está reconectando; mensaje en cola',
  emptyConnecting: 'Conectando al canal de depuración…',
  ctxTitle: (total: string, max: string | null) =>
    `Contexto ${total}${max !== null ? ` / ${max}` : ''} tok · haz clic para ver el desglose`,
  ctxWaiting: 'Esperando datos del contexto',
  sessionResetNote: 'SESSION truncada y reconstruida',
  debugUnavailable: 'Canal de depuración no disponible',
  debugNotMounted: 'El canal de depuración no está disponible; no se puede mostrar la línea de tiempo.',

  // status.ts
  docTitle: (name: string) => `Consola · ${name}`,
  chipDisconnected: 'Desconectado',
  chipMsgs: ' msj.',
  chipCache: 'caché ',
  chipBatchesPre: 'lotes: ',
  chipBatchesPost: '',
  chipPaused: '⏸ En pausa',
  chipBehind: (n: number) => `${n} ${n === 1 ? 'pendiente' : 'pendientes'} de entrega`,
  chipScheduleBlocked: '◷ Entrega retenida',
  chipTruncating: 'Truncando',
  chipOnline: 'en línea: ',
  phaseDelivering: 'Escribiendo eventos en el contexto',
  phaseModel: 'Esperando la salida del modelo',
  phaseTools: 'Ejecutando herramientas',
  phaseBackoff: (clock: string) => `Falló la llamada al modelo; se reintentará a las ${clock}`,
  phaseHandoff: 'Traspaso de contexto en curso',
  phaseRound: (n: number) => `ronda ${n}`,
  phaseRunning: (names: string) => `en ejecución: ${names}`,

  // fork.ts
  mainLabel: 'Sesión principal',
  forkViewing: '◉ Viendo la sesión en segundo plano ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} ${count === 1 ? 'mensaje' : 'mensajes'} · ~${tok} tok · ` + (ended ? 'terminada (congelada)' : `sin terminar (se actualiza cada ${sec} s)`),
  forkReadOnly: 'Esta vista es de solo lectura; el cuadro de entrada sigue enviando a la sesión principal.',
  forkBack: '⏎ Volver a la sesión principal',
  forkEmpty: '(Esta sesión aún no tiene mensajes)',
  forkFetchFailed: (msg: string) => `(falló la obtención: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Uso de sesiones en esta ejecución',
  sessionCache: (pct: string) => `caché ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'sin terminar' : `terminada ${endedAt}`}\n` +
    `entrada ${prompt} / salida ${completion} / aciertos de caché ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Volver al final',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} ${n === 1 ? 'carácter' : 'caracteres'}`,
  ordinalTitle: (index: number) => `Elemento n.º ${index} de la sesión`,
  userGlyphTitle: 'mensaje del usuario',
  empty: '(vacío)',
  visibleReasoning: (n: number) => `Razonamiento visible: ${n} ${n === 1 ? 'carácter' : 'caracteres'}`,
  encryptedReasoning: (n: number) => `Razonamiento cifrado: ${n} ${n === 1 ? 'carácter' : 'caracteres'}`,
  summary: 'Resumen',
  monologTitle: (phase: string) => `texto del asistente${phase ? ` · ${phase}` : ''}`,
  refusal: 'Rechazo',
  synthetic: 'sintético',
  encryptedPayload: (n: number) => `Carga cifrada: ${n} ${n === 1 ? 'carácter' : 'caracteres'}`,
  rawItems: 'Elementos sin procesar',
  headStart: 'Inicio de la sesión · no se guarda',
  headEnd: 'Inicio de la sesión · fin',
  sessionEmpty: 'la sesión está vacía',

  // context.ts
  groupPrefix: 'Prefijo del sistema',
  groupTools: 'Herramientas',
  groupDialogue: 'Conversación',
  catOrient: 'ORIENTATION',
  catConstitution: 'Constitución (CONSTITUTION)',
  catEnv: 'Entorno · World',
  catToolsUsage: 'Notas de uso de herramientas',
  catMemory: 'Memoria (MEMORY)',
  catPrefixMisc: 'Preámbulo / separadores / estructura',
  catToolsSchema: 'Esquemas de herramientas',
  catHead: 'Inicio de la sesión (sintético)',
  catReasoning: 'Razonamiento',
  catDialogue: 'Diálogo · eventos',
  catToolIO: 'Llamadas a herramientas y resultados',
  ctxNone: 'Aún no hay datos de contexto.',
  ctxUsage: 'Desglose estimado del contexto',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Presupuesto desconocido' : `${budgetPct} del presupuesto`} · Conservar razonamiento previo: ${keepOn ? 'activado' : 'desactivado'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: 'El total sigue el conteo del upstream (la última llamada contó ',
  footCountedPost: '; lo agregado después es estimación local); las categorías se prorratean según estimaciones locales, así que léelas solo como proporciones.',
  footEstimated: 'Aún no hay conteo del upstream; todo el contexto se estima por caracteres (CJK ≈ 0.6, otros ≈ 0.3 token/carácter, +8 de sobrecarga estructural por elemento); tras la próxima llamada se usa el conteo del upstream.',
  footSchemaB: 'Los esquemas de herramientas',
  footSchemaPost: ' se envían como parámetro tools en cada llamada y se cuentan aparte de los mensajes.',
  footStrippedPre: 'Unos ',
  footStrippedPost: ' tok de razonamiento previo se excluyen de las solicitudes.',
  footHardPre: 'Por encima de ',
  footHardPost: ' (el límite de entrada del modelo: ventana de contexto menos la salida reservada), el core fuerza un traspaso.',
  footSoftPre: 'Umbral blando de la Persona: ',
  footSoftPost: (max: string) => `; presupuesto de la etapa ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: '¡Te damos la bienvenida a Cortico! Configuremos tu primer Cortico Bot.',
  obProvider: 'Primero, configura un proveedor de modelos:',
  obProviderNone: 'Aún no hay un proveedor de modelos utilizable',
  obProviderReady: 'Proveedor de modelos configurado',
  obWorlds: 'Después, activa y configura los entornos externos a los que llega tu bot (Cortico Worlds). Para empezar, basta con el chat de terminal.',
  obWorldsState: (labels: readonly string[]) =>
    `Actualmente hay ${labels.length} ${labels.length === 1 ? 'entorno externo activado' : 'entornos externos activados'}: ${labels.join(', ')}`,
  obPrompts: 'Por último, aquí se edita el prompt del sistema: quién es, cómo se comporta y cómo habla.',
  obReady: '¡Todo listo!',
  obGoConfigure: 'Configurar',
  obGoEdit: 'Editar',
  obStart: '¿Saludamos?',
};
