import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Терминал',
  currentProvider: 'Текущий провайдер модели',
  noProvider: 'Провайдер не выбран',
  ctxOpenAria: 'Показать разбивку token',
  ctxPanelAria: 'Разбивка token',
  netConnecting: 'Подключение консоли…',
  netOnline: 'Консоль подключена',
  netOffline: 'Консоль отключена',
  composerLabel: 'Ввод сообщения терминала',
  composerPlaceholder: 'Введите сообщение…',
  exportDiagnostics: 'Экспорт диагностики',
  exportFailed: 'Не удалось получить пакет диагностики',
  exportConfirmTitle: 'Экспорт диагностики',
  exportConfirmBody: 'Пакет содержит разговоры, промпты, события, вызовы инструментов, расход и журналы запуска. Секреты в конфигурации скрываются; всё остальное записывается как есть. Перед тем как делиться пакетом, проверьте его на личные данные.',
  composerFork: 'Вы просматриваете фоновую сессию; отправленные здесь сообщения всё равно уходят в основную сессию',
  composerNoProvider: 'Нет доступного провайдера. Настройте его на странице «Подключения к моделям».',
  composerQueued: 'Канал терминала переподключается; сообщение поставлено в очередь',
  emptyConnecting: 'Подключение к отладочному каналу…',
  ctxTitle: (total: string, max: string | null) =>
    `Контекст ${total}${max !== null ? ` / ${max}` : ''} tok · нажмите для разбивки`,
  ctxWaiting: 'Ожидание данных контекста',
  sessionResetNote: 'SESSION усечена и пересобрана',
  debugUnavailable: 'Отладочный канал недоступен',
  debugNotMounted: 'Отладочный канал недоступен; ленту нельзя показать.',

  // status.ts
  docTitle: (name: string) => `Консоль · ${name}`,
  chipDisconnected: 'Отключено',
  chipMsgs: ' сообщ.',
  chipCache: 'кэш ',
  chipBatchesPre: 'пакетов: ',
  chipBatchesPost: '',
  chipPaused: '⏸ Приостановлено',
  chipBehind: (n: number) => `Ожидают доставки: ${n}`,
  chipScheduleBlocked: '◷ Расписание заблокировано',
  chipTruncating: 'Усечение',
  chipOnline: 'в сети: ',
  phaseDelivering: 'Запись событий в контекст',
  phaseModel: 'Ожидание вывода модели',
  phaseTools: 'Выполнение инструментов',
  phaseBackoff: (clock: string) => `Вызов модели не удался; повтор в ${clock}`,
  phaseHandoff: 'Идёт передача контекста',
  phaseRound: (n: number) => `раунд ${n}`,
  phaseRunning: (names: string) => `выполняется: ${names}`,

  // fork.ts
  mainLabel: 'Основная сессия',
  forkViewing: '◉ Просмотр фоновой сессии ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} сообщ. · ~${tok} tok · ` + (ended ? 'завершена (зафиксирована)' : `не завершена (обновляется каждые ${sec} с)`),
  forkReadOnly: 'Это представление только для чтения; поле ввода по-прежнему отправляет в основную сессию.',
  forkBack: '⏎ Вернуться к основной сессии',
  forkEmpty: '(В этой сессии пока нет сообщений)',
  forkFetchFailed: (msg: string) => `(не удалось получить: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Расход сессий за этот запуск',
  sessionCache: (pct: string) => `кэш ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'не завершена' : `завершена ${endedAt}`}\n` +
    `вход ${prompt} / выход ${completion} / попадания в кэш ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Вниз',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} симв.`,
  ordinalTitle: (index: number) => `Элемент № ${index} в сессии`,
  userGlyphTitle: 'сообщение пользователя',
  empty: '(пусто)',
  visibleReasoning: (n: number) => `Видимое рассуждение: ${n} симв.`,
  encryptedReasoning: (n: number) => `Зашифрованное рассуждение: ${n} симв.`,
  summary: 'Сводка',
  monologTitle: (phase: string) => `текст ассистента${phase ? ` · ${phase}` : ''}`,
  refusal: 'Отказ',
  synthetic: 'синтетический',
  encryptedPayload: (n: number) => `Зашифрованные данные: ${n} симв.`,
  rawItems: 'Исходные элементы',
  headStart: 'Начало сессии · не сохраняется',
  headEnd: 'Начало сессии · конец',
  sessionEmpty: 'сессия пуста',

  // context.ts
  groupPrefix: 'Системный префикс',
  groupTools: 'Инструменты',
  groupDialogue: 'Разговор',
  catOrient: 'ORIENTATION',
  catConstitution: 'Конституция (CONSTITUTION)',
  catEnv: 'Окружение · World',
  catToolsUsage: 'Пояснения к инструментам',
  catMemory: 'Память (MEMORY)',
  catPrefixMisc: 'Преамбула / разделители / структура',
  catToolsSchema: 'Схемы инструментов',
  catHead: 'Начало сессии (синтетическое)',
  catReasoning: 'Рассуждение',
  catDialogue: 'Диалог · события',
  catToolIO: 'Вызовы инструментов и результаты',
  ctxNone: 'Данных о контексте пока нет.',
  ctxUsage: 'Оценочная структура контекста',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Бюджет неизвестен' : `${budgetPct} бюджета`} · Сохранять прошлые рассуждения: ${keepOn ? 'вкл.' : 'выкл.'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: 'Итог следует счёту upstream (последний вызов насчитал ',
  footCountedPost: '; добавленное позже оценено локально); категории распределены пропорционально локальной оценке, поэтому смотрите только на соотношения.',
  footEstimated: 'Счёта upstream пока нет; весь контекст оценивается по символам (CJK ≈ 0.6, остальные ≈ 0.3 token/символ, +8 на структуру каждого элемента); после следующего вызова используется счёт upstream.',
  footSchemaB: 'Схемы инструментов',
  footSchemaPost: ' отправляются как параметр tools при каждом вызове и считаются отдельно от сообщений.',
  footStrippedPre: 'Около ',
  footStrippedPost: ' tok прошлых рассуждений исключено из запросов.',
  footHardPre: 'При превышении ',
  footHardPost: ' (предел входа модели: окно контекста минус резерв на вывод) core принудительно выполняет передачу контекста.',
  footSoftPre: 'Мягкий порог Persona: ',
  footSoftPost: (max: string) => `; бюджет этапа ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Добро пожаловать в Cortico! Давайте настроим ваш первый Cortico Bot.',
  obProvider: 'Сначала настройте провайдера модели:',
  obProviderNone: 'Доступного провайдера модели пока нет',
  obProviderReady: 'Провайдер модели настроен',
  obWorlds: 'Затем включите и настройте внешние окружения, с которыми работает ваш бот (Cortico Worlds). Для начала достаточно и чата в терминале.',
  obWorldsState: (labels: readonly string[]) =>
    `Сейчас включено внешних окружений: ${labels.length} (${labels.join(', ')})`,
  obPrompts: 'И наконец, здесь редактируется системный промпт: кто бот, как он себя ведёт и как говорит.',
  obReady: 'Всё готово!',
  obGoConfigure: 'Настроить',
  obGoEdit: 'Редактировать',
  obStart: 'Поздороваться?',
};
