import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Terminal',
  currentProvider: 'Provedor de modelo atual',
  noProvider: 'Nenhum provedor selecionado',
  ctxOpenAria: 'Ver detalhamento de tokens',
  ctxPanelAria: 'Detalhamento de tokens',
  netConnecting: 'Conectando o console…',
  netOnline: 'Console conectado',
  netOffline: 'Console desconectado',
  composerLabel: 'Entrada de mensagens do terminal',
  composerPlaceholder: 'Digite uma mensagem…',
  exportDiagnostics: 'Exportar diagnóstico',
  exportFailed: 'Não foi possível obter o pacote de diagnóstico',
  exportConfirmTitle: 'Exportar diagnóstico',
  exportConfirmBody: 'O pacote contém conversas, prompts, eventos, chamadas de ferramentas, uso e logs de execução. Os segredos da configuração são ocultados; todo o resto é gravado como está. Verifique se há informações privadas antes de compartilhar.',
  composerFork: 'Você está vendo uma sessão em segundo plano; as mensagens enviadas aqui ainda vão para a sessão principal',
  composerNoProvider: 'Nenhum provedor utilizável. Configure um na página Conexões de modelo.',
  composerQueued: 'O canal do terminal está reconectando; mensagem na fila',
  emptyConnecting: 'Conectando ao canal de depuração…',
  ctxTitle: (total: string, max: string | null) =>
    `Contexto ${total}${max !== null ? ` / ${max}` : ''} tok · clique para ver o detalhamento`,
  ctxWaiting: 'Aguardando dados de contexto',
  sessionResetNote: 'SESSION truncada e reconstruída',
  debugUnavailable: 'Canal de depuração indisponível',
  debugNotMounted: 'Canal de depuração indisponível; a linha do tempo não pode ser exibida.',

  // status.ts
  docTitle: (name: string) => `Console · ${name}`,
  chipDisconnected: 'Desconectado',
  chipMsgs: ' mens.',
  chipCache: 'cache: ',
  chipBatchesPre: 'lotes: ',
  chipBatchesPost: '',
  chipPaused: '⏸ Pausado',
  chipBehind: (n: number) => `${n} aguardando entrega`,
  chipScheduleBlocked: '◷ Entrega retida',
  chipTruncating: 'Truncando',
  chipOnline: 'on-line: ',
  phaseDelivering: 'Gravando eventos no contexto',
  phaseModel: 'Aguardando a saída do modelo',
  phaseTools: 'Executando ferramentas',
  phaseBackoff: (clock: string) => `A chamada ao modelo falhou; nova tentativa às ${clock}`,
  phaseHandoff: 'Transferência de contexto em andamento',
  phaseRound: (n: number) => `rodada ${n}`,
  phaseRunning: (names: string) => `em execução: ${names}`,

  // fork.ts
  mainLabel: 'Sessão principal',
  forkViewing: '◉ Vendo a sessão em segundo plano ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} ${count === 1 ? 'mensagem' : 'mensagens'} · ~${tok} tok · ` + (ended ? 'encerrada (congelada)' : `não encerrada (atualiza a cada ${sec} s)`),
  forkReadOnly: 'Esta visualização é somente leitura; a caixa de entrada continua enviando para a sessão principal.',
  forkBack: '⏎ Voltar à sessão principal',
  forkEmpty: '(Esta sessão ainda não tem mensagens)',
  forkFetchFailed: (msg: string) => `(falha ao buscar: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Uso das sessões nesta execução',
  sessionCache: (pct: string) => `cache: ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'não encerrada' : `encerrada ${endedAt}`}\n` +
    `entrada ${prompt} / saída ${completion} / acertos de cache ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Voltar ao fim',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} ${n === 1 ? 'caractere' : 'caracteres'}`,
  ordinalTitle: (index: number) => `Item nº ${index} da sessão`,
  userGlyphTitle: 'mensagem do usuário',
  empty: '(vazio)',
  visibleReasoning: (n: number) => `Raciocínio visível: ${n} ${n === 1 ? 'caractere' : 'caracteres'}`,
  encryptedReasoning: (n: number) => `Raciocínio criptografado: ${n} ${n === 1 ? 'caractere' : 'caracteres'}`,
  summary: 'Resumo',
  monologTitle: (phase: string) => `texto do assistente${phase ? ` · ${phase}` : ''}`,
  refusal: 'Recusa',
  synthetic: 'sintético',
  encryptedPayload: (n: number) => `Carga criptografada: ${n} ${n === 1 ? 'caractere' : 'caracteres'}`,
  rawItems: 'Itens brutos',
  headStart: 'Início da sessão · não salvo',
  headEnd: 'Início da sessão · fim',
  sessionEmpty: 'a sessão está vazia',

  // context.ts
  groupPrefix: 'Prefixo de sistema',
  groupTools: 'Ferramentas',
  groupDialogue: 'Conversa',
  catOrient: 'ORIENTATION',
  catConstitution: 'Constituição (CONSTITUTION)',
  catEnv: 'Ambiente · World',
  catToolsUsage: 'Notas de uso das ferramentas',
  catMemory: 'Memória (MEMORY)',
  catPrefixMisc: 'Preâmbulo / separadores / estrutura',
  catToolsSchema: 'Esquemas de ferramentas',
  catHead: 'Início da sessão (sintético)',
  catReasoning: 'Raciocínio',
  catDialogue: 'Diálogo · eventos',
  catToolIO: 'Chamadas de ferramentas e resultados',
  ctxNone: 'Ainda não há dados de contexto.',
  ctxUsage: 'Composição estimada do contexto',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Orçamento desconhecido' : `${budgetPct} do orçamento`} · Manter raciocínio anterior: ${keepOn ? 'ativado' : 'desativado'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: 'O total segue a contagem do upstream (a última chamada contou ',
  footCountedPost: '; o que veio depois é estimativa local); as categorias são rateadas pelas estimativas locais, então leia-as só como proporções.',
  footEstimated: 'Ainda não há contagem do upstream; todo o contexto é estimado por caracteres (CJK ≈ 0.6, outros ≈ 0.3 token/caractere, +8 de sobrecarga estrutural por item); após a próxima chamada vale a contagem do upstream.',
  footSchemaB: 'Os esquemas de ferramentas',
  footSchemaPost: ' são enviados como o parâmetro tools em cada chamada e contados separadamente das mensagens.',
  footStrippedPre: 'Cerca de ',
  footStrippedPost: ' tok de raciocínio anterior ficam fora das requisições.',
  footHardPre: 'Acima de ',
  footHardPost: ' (o limite de entrada do modelo: janela de contexto menos a saída reservada), o core força uma transferência.',
  footSoftPre: 'Limite flexível da Persona: ',
  footSoftPost: (max: string) => `; orçamento da etapa ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Boas-vindas ao Cortico! Vamos configurar seu primeiro Cortico Bot.',
  obProvider: 'Primeiro, configure um provedor de modelos:',
  obProviderNone: 'Ainda não há um provedor de modelos utilizável',
  obProviderReady: 'Provedor de modelos configurado',
  obWorlds: 'Em seguida, ative e configure os ambientes externos que seu bot alcança (Cortico Worlds). Começar só com o chat do terminal já basta.',
  obWorldsState: (labels: readonly string[]) =>
    `No momento, ${labels.length} ${labels.length === 1 ? 'ambiente externo ativado' : 'ambientes externos ativados'}: ${labels.join(', ')}`,
  obPrompts: 'Por fim, o prompt de sistema é editado aqui: quem ele é, como se comporta e como fala.',
  obReady: 'Tudo pronto!',
  obGoConfigure: 'Configurar',
  obGoEdit: 'Editar',
  obStart: 'Dizer olá?',
};
