import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Terminale',
  currentProvider: 'Provider del modello attuale',
  noProvider: 'Nessun provider selezionato',
  ctxOpenAria: 'Mostra la ripartizione dei token',
  ctxPanelAria: 'Ripartizione dei token',
  netConnecting: 'Connessione della console…',
  netOnline: 'Console connessa',
  netOffline: 'Console disconnessa',
  composerLabel: 'Inserimento messaggi del terminale',
  composerPlaceholder: 'Scrivi un messaggio…',
  exportDiagnostics: 'Esporta diagnostica',
  exportFailed: 'Impossibile recuperare il pacchetto di diagnostica',
  exportConfirmTitle: 'Esporta diagnostica',
  exportConfirmBody: "Il pacchetto contiene conversazioni, prompt, eventi, chiamate agli strumenti, uso e log di esecuzione. I secret nella configurazione sono oscurati; tutto il resto è scritto così com'è. Controlla che non contenga informazioni private prima di condividerlo.",
  composerFork: 'Stai visualizzando una sessione in background; i messaggi inviati qui vanno comunque alla sessione principale',
  composerNoProvider: 'Nessun provider utilizzabile. Configurane uno nella pagina «Connessioni ai modelli».',
  composerQueued: 'Il canale del terminale si sta riconnettendo; messaggio in coda',
  emptyConnecting: 'Connessione al canale di debug…',
  ctxTitle: (total: string, max: string | null) =>
    `Contesto ${total}${max !== null ? ` / ${max}` : ''} tok · clicca per la ripartizione`,
  ctxWaiting: 'In attesa dei dati di contesto',
  sessionResetNote: 'SESSIONE troncata e ricostruita',
  debugUnavailable: 'Canale di debug non disponibile',
  debugNotMounted: 'Canale di debug non disponibile; impossibile mostrare la cronologia.',

  // status.ts
  docTitle: (name: string) => `Console · ${name}`,
  chipDisconnected: 'Disconnesso',
  chipMsgs: ' msg',
  chipCache: 'cache ',
  chipBatchesPre: 'totale ',
  chipBatchesPost: ' batch',
  chipPaused: '⏸ In pausa',
  chipBehind: (n: number) => `${n} in attesa di consegna`,
  chipScheduleBlocked: '◷ Consegna trattenuta',
  chipTruncating: 'Troncamento',
  chipOnline: 'in linea ',
  phaseDelivering: 'Scrittura degli eventi nel contesto',
  phaseModel: "In attesa dell'uscita del modello",
  phaseTools: 'Esecuzione degli strumenti',
  phaseBackoff: (clock: string) => `Chiamata al modello non riuscita; nuovo tentativo alle ${clock}`,
  phaseHandoff: 'Passaggio di contesto in corso',
  phaseRound: (n: number) => `turno ${n}`,
  phaseRunning: (names: string) => `in esecuzione: ${names}`,

  // fork.ts
  mainLabel: 'Sessione principale',
  forkViewing: '◉ Visualizzazione della sessione in background ',
  forkInfo: (count: number, tok: string, ended: boolean, sec: number) =>
    ` · ${count} msg · ~${tok} tok · ` + (ended ? 'terminata (congelata)' : `non terminata (aggiornata ogni ${sec} s)`),
  forkReadOnly: 'Questa vista è in sola lettura; la casella di inserimento invia comunque alla sessione principale.',
  forkBack: '⏎ Torna alla sessione principale',
  forkEmpty: '(Questa sessione non ha ancora messaggi)',
  forkFetchFailed: (msg: string) => `(recupero non riuscito: ${msg})`,

  // sessions.ts
  sessionBandTitle: 'Uso delle sessioni in questa esecuzione',
  sessionCache: (pct: string) => `cache ${pct}`,
  sessionCardTitle: (
    label: string,
    id: string,
    running: boolean,
    endedAt: string,
    prompt: number,
    completion: number,
    hit: number,
  ) =>
    `${label} (${id})\n` +
    `${running ? 'non terminata' : `terminata ${endedAt}`}\n` +
    `ingresso ${prompt} / uscita ${completion} / hit della cache ${hit}`,

  // timeline.ts
  jumpBottom: '↓ Torna in fondo',
  foldHead: (open: boolean, n: number) => `${open ? '▾' : '▸'} ${n} ${n === 1 ? 'carattere' : 'caratteri'}`,
  ordinalTitle: (index: number) => `Item n. ${index} della sessione`,
  userGlyphTitle: 'messaggio user',
  empty: '(vuoto)',
  visibleReasoning: (n: number) => `Ragionamento visibile ${n} ${n === 1 ? 'carattere' : 'caratteri'}`,
  encryptedReasoning: (n: number) => `Ragionamento crittografato ${n} ${n === 1 ? 'carattere' : 'caratteri'}`,
  summary: 'Riepilogo',
  monologTitle: (phase: string) => `testo assistant${phase ? ` · ${phase}` : ''}`,
  refusal: 'Rifiuto',
  synthetic: 'sintetico',
  encryptedPayload: (n: number) => `Payload crittografato ${n} ${n === 1 ? 'carattere' : 'caratteri'}`,
  rawItems: 'Item grezzi',
  headStart: 'Inizio della sessione · non salvato',
  headEnd: 'Inizio della sessione · fine',
  sessionEmpty: 'la sessione è vuota',

  // context.ts
  groupPrefix: 'Prefisso di sistema',
  groupTools: 'Strumenti',
  groupDialogue: 'Conversazione',
  catOrient: 'ORIENTATION',
  catConstitution: 'Costituzione CONSTITUTION',
  catEnv: 'Ambiente · World',
  catToolsUsage: "Note sull'uso degli strumenti",
  catMemory: 'MEMORY',
  catPrefixMisc: 'Preambolo / separatori / struttura',
  catToolsSchema: 'Schemi degli strumenti',
  catHead: 'Inizio della sessione (sintetico)',
  catReasoning: 'Ragionamento',
  catDialogue: 'Dialogo · eventi',
  catToolIO: 'Chiamate agli strumenti e risultati',
  ctxNone: 'Ancora nessun dato di contesto.',
  ctxUsage: 'Composizione stimata del contesto',
  ctxSub: (budgetPct: string | null, keepOn: boolean) =>
    `${budgetPct === null ? 'Budget sconosciuto' : `${budgetPct} del budget`} · Conserva ragionamento passato: ${keepOn ? 'attivo' : 'disattivo'}`,
  toolCount: (n: number) => ` (${n})`,
  footCountedPre: "Il totale segue il conteggio upstream (l'ultima chiamata ne ha contati ",
  footCountedPost: '; le aggiunte successive sono stime locali); le categorie sono ripartite in proporzione alle stime locali, da leggere solo come rapporti.',
  footEstimated: 'Ancora nessun conteggio upstream; tutto il contesto è stimato per caratteri (CJK ≈ 0,6, altri ≈ 0,3 token/carattere, +8 di overhead strutturale per elemento); dopo la prossima chiamata vale il conteggio upstream.',
  footSchemaB: 'Gli schemi degli strumenti',
  footSchemaPost: ' vengono inviati come parametro tools a ogni chiamata e contati separatamente dai messaggi.',
  footStrippedPre: 'Circa ',
  footStrippedPost: ' tok di ragionamento passato sono esclusi dalle richieste.',
  footHardPre: 'Oltre ',
  footHardPost: ' (il limite di ingresso del modello: finestra di contesto meno uscita riservata) il Core forza un passaggio di consegne.',
  footSoftPre: 'Soglia morbida della Persona: ',
  footSoftPost: (max: string) => `; budget della fase ${max}.`,

  // onboarding.ts
  obWho: 'Cortico',
  obWelcome: 'Benvenuto in Cortico! Configuriamo il tuo primo bot Cortico.',
  obProvider: 'Per prima cosa, configura un provider di modelli:',
  obProviderNone: 'Ancora nessun provider di modelli utilizzabile',
  obProviderReady: 'Provider di modelli configurato',
  obWorlds: 'Poi attiva e configura gli ambienti esterni a cui accede il tuo bot (World di Cortico). Va bene anche iniziare solo con la chat del terminale.',
  obWorldsState: (labels: readonly string[]) =>
    `Attualmente ${labels.length === 1 ? 'è attivo 1 ambiente esterno' : `sono attivi ${labels.length} ambienti esterni`}: ${labels.join(', ')}`,
  obPrompts: 'Infine, qui modifichi il prompt di sistema: chi è, come si comporta, come parla.',
  obReady: 'Tutto pronto!',
  obGoConfigure: 'Configura',
  obGoEdit: 'Modifica',
  obStart: 'Vuoi salutare?',
};
