import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  profileObject: 'La configurazione del modello deve essere un oggetto',
  modelRequired: 'Il nome del modello non può essere vuoto',
  thinkingBoolean: "L'interruttore del ragionamento deve essere un booleano",
  tierUnsupported: (title: string) => `${title} non supporta questo livello di ragionamento`,
  effortString: 'Lo sforzo di ragionamento deve essere una stringa non vuota',
  effortWithoutThinking: 'Lo sforzo di ragionamento non può essere impostato con il ragionamento disattivato',
  temperatureRange: 'temperature deve essere compresa tra 0 e 2',
  positiveInteger: (field: string) => `${field} deve essere un intero positivo`,
  contextWindowAboveOutput: (window: number, output: number) =>
    `contextWindow deve essere maggiore di maxTokens (attualmente ${window} ≤ ${output})`,
  optionsObject: 'Le opzioni native devono essere un oggetto',
  kindChange: "Un'istanza non può cambiare il tipo di modulo del provider",
  baseUrlFormat: "L'URL del provider deve essere un URL HTTP(S) senza credenziali",
  secretName: 'Il riferimento al secret deve essere il nome di una variabile di ambiente',
  multimodalBoolean: "L'interruttore multimodale deve essere un booleano",
  serviceTierString: 'Il livello di servizio deve essere una stringa',
  serviceTierUnsupported: (title: string, tier: string) =>
    `${title} non supporta il livello di servizio ${tier}`,
  pricingArray: 'I prezzi devono essere un array',
  rulesArray: 'Le regole di prezzo devono essere un array',
  ruleShape: 'Una regola di prezzo richiede una metrica e un prezzo unitario non negativo',
  unitRequired: "L'unità non può essere vuota",
  tokenUnit: "Le metriche token standard devono usare l'unità token",
  bandsArray: 'Le fasce di input devono essere un array',
  bandsIncreasing: 'Le soglie delle fasce di input devono essere strettamente crescenti e maggiori di 0',
  modelsRequired: 'Una tariffa richiede nomi di modello espliciti o *',
  currencyRequired: 'La valuta della tariffa non può essere vuota',
  basisValue: 'La base della tariffa deve essere marginal o equivalent',
  sourceRequired: 'Una tariffa richiede una fonte',
  tiersObject: 'I prezzi per livello di servizio devono essere un oggetto',
  tierNameRequired: 'Il nome del livello di servizio non può essere vuoto',
  tierRules: 'I prezzi per livello di servizio richiedono un oggetto di regole',
  timeWindowsUnsupported: "La tariffazione per fascia oraria è dichiarata da un'estensione del provider nella tariffa del suo modulo; i prezzi dell'endpoint non accettano timeWindows",
  noModel: 'Nessun modello selezionato',
  noSecret: (name: string) => `Secret ${name} mancante`,
};
