import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  profileObject: '模型設定必須是物件',
  modelRequired: '模型名稱不能為空',
  thinkingBoolean: '推理開關必須是布林值',
  tierUnsupported: (title: string) => `${title} 不支援該推理檔位`,
  effortString: '推理強度必須是非空字串',
  effortWithoutThinking: '思維鏈關閉時不能帶推理強度',
  temperatureRange: 'temperature 必須在 0–2 之間',
  positiveInteger: (field: string) => `${field} 必須為正整數`,
  contextWindowAboveOutput: (window: number, output: number) =>
    `contextWindow 必須大於 maxTokens(目前 ${window} ≤ ${output})`,
  optionsObject: '原生參數必須是物件',
  kindChange: '實例不能改變 Provider 模組類型',
  baseUrlFormat: '供應位址需要不含憑證的 HTTP(S) URL',
  secretName: '金鑰引用必須是環境變數名稱',
  multimodalBoolean: '多模態開關必須是布林值',
  serviceTierString: '服務檔必須是字串',
  serviceTierUnsupported: (title: string, tier: string) =>
    `${title} 不支援服務檔 ${tier}`,
  pricingArray: '報價必須是陣列',
  rulesArray: '報價規則必須是陣列',
  ruleShape: '報價規則需要計量維度和非負單價',
  unitRequired: '計量單位不能為空',
  tokenUnit: '標準 token 計量必須使用 token 單位',
  bandsArray: '輸入階梯必須是陣列',
  bandsIncreasing: '輸入階梯閾值必須嚴格遞增且大於 0',
  modelsRequired: '報價需要明確模型名稱或 *',
  currencyRequired: '報價幣別不能為空',
  basisValue: '報價口徑必須為 marginal 或 equivalent',
  sourceRequired: '報價需要來源',
  tiersObject: '服務檔報價必須是物件',
  tierNameRequired: '服務檔名稱不能為空',
  tierRules: '服務檔報價需要規則物件',
  timeWindowsUnsupported: '分時段價目由 provider 擴充功能在模組價目裡宣告,端點價目不接受 timeWindows',
  noModel: '未選模型',
  noSecret: (name: string) => `缺少金鑰 ${name}`,
};
