import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  profileObject: 'A configuração do modelo deve ser um objeto',
  modelRequired: 'O nome do modelo não pode ficar vazio',
  thinkingBoolean: 'A chave de raciocínio deve ser um booleano',
  tierUnsupported: (title: string) => `${title} não suporta este nível de raciocínio`,
  effortString: 'O esforço de raciocínio deve ser uma string não vazia',
  effortWithoutThinking: 'Não é possível definir o esforço de raciocínio com o raciocínio desativado',
  temperatureRange: 'temperature deve estar entre 0 e 2',
  positiveInteger: (field: string) => `${field} deve ser um inteiro positivo`,
  contextWindowAboveOutput: (window: number, output: number) =>
    `contextWindow deve ser maior que maxTokens (atualmente ${window} ≤ ${output})`,
  optionsObject: 'As opções nativas devem ser um objeto',
  kindChange: 'Uma instância não pode mudar o tipo de módulo do provedor',
  baseUrlFormat: 'A URL do provedor deve ser uma URL HTTP(S) sem credenciais',
  secretName: 'A referência ao segredo deve ser um nome de variável de ambiente',
  multimodalBoolean: 'A chave multimodal deve ser um booleano',
  serviceTierString: 'O nível de serviço deve ser uma string',
  serviceTierUnsupported: (title: string, tier: string) =>
    `${title} não suporta o nível de serviço ${tier}`,
  pricingArray: 'Os preços devem ser um array',
  rulesArray: 'As regras de preço devem ser um array',
  ruleShape: 'Uma regra de preço precisa de um medidor e de uma tarifa não negativa',
  unitRequired: 'A unidade não pode ficar vazia',
  tokenUnit: 'Medidores padrão de token devem usar a unidade token',
  bandsArray: 'As faixas de entrada devem ser um array',
  bandsIncreasing: 'Os limites das faixas de entrada devem ser estritamente crescentes e maiores que 0',
  modelsRequired: 'Uma cotação precisa de nomes de modelo explícitos ou *',
  currencyRequired: 'A moeda da cotação não pode ficar vazia',
  basisValue: 'A base da cotação deve ser marginal ou equivalent',
  sourceRequired: 'Uma cotação precisa de uma fonte',
  tiersObject: 'Os preços por nível de serviço devem ser um objeto',
  tierNameRequired: 'O nome do nível de serviço não pode ficar vazio',
  tierRules: 'Os preços por nível de serviço precisam de um objeto de regras',
  timeWindowsUnsupported: 'Preços por horário são declarados por uma extensão de provedor na cotação do módulo; os preços do endpoint não aceitam timeWindows',
  noModel: 'Nenhum modelo selecionado',
  noSecret: (name: string) => `Segredo ${name} ausente`,
};
