import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  profileObject: 'モデル設定はオブジェクトである必要があります',
  modelRequired: 'モデル名を空にすることはできません',
  thinkingBoolean: '推論のオン／オフはブール値である必要があります',
  tierUnsupported: (title: string) => `${title} はこの推論階層に対応していません`,
  effortString: '推論の強さは空でない文字列である必要があります',
  effortWithoutThinking: '推論がオフのときは推論の強さを指定できません',
  temperatureRange: 'temperature は 0〜2 の範囲である必要があります',
  positiveInteger: (field: string) => `${field} は正の整数である必要があります`,
  optionsObject: 'ネイティブオプションはオブジェクトである必要があります',
  kindChange: 'インスタンスのプロバイダーモジュールの種類は変更できません',
  baseUrlFormat: 'プロバイダー URL は認証情報を含まない HTTP(S) URL である必要があります',
  secretName: 'シークレットの参照は環境変数名である必要があります',
  multimodalBoolean: 'マルチモーダルのオン／オフはブール値である必要があります',
  serviceTierString: 'サービス階層は文字列である必要があります',
  serviceTierUnsupported: (title: string, tier: string) =>
    `${title} はサービス階層 ${tier} に対応していません`,
  pricingArray: '料金は配列である必要があります',
  rulesArray: '料金ルールは配列である必要があります',
  ruleShape: '料金ルールには計量項目と 0 以上の単価が必要です',
  unitRequired: '計量単位を空にすることはできません',
  tokenUnit: '標準の token 計量では token 単位を使う必要があります',
  bandsArray: '入力の段階料金は配列である必要があります',
  bandsIncreasing: '入力の段階料金のしきい値は 0 より大きく、厳密に増加する必要があります',
  modelsRequired: '料金には明示的なモデル名または * が必要です',
  currencyRequired: '料金の通貨を空にすることはできません',
  basisValue: '料金の基準は marginal または equivalent である必要があります',
  sourceRequired: '料金には出典が必要です',
  tiersObject: 'サービス階層の料金はオブジェクトである必要があります',
  tierNameRequired: 'サービス階層名を空にすることはできません',
  tierRules: 'サービス階層の料金にはルールのオブジェクトが必要です',
  timeWindowsUnsupported: '時間帯別の料金はプロバイダー拡張機能がモジュールの料金表で宣言するもので、エンドポイントの料金では timeWindows を受け付けません',
  noModel: 'モデルが選択されていません',
  noSecret: (name: string) => `シークレット ${name} がありません`,
};
