import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: '저장했습니다. 다음 요청부터 적용됩니다.',
  instancesTitle: '공급자 인스턴스',
  instancesDescription:
    '인스턴스마다 연결, 모델 사양, 가격을 따로 저장합니다. 처리 중인 요청과 이미 시작된 백그라운드 세션은 기존 연결을 유지합니다.',
  activeSuffix: ' · 현재',
  instanceField: '공급자 인스턴스',
  newInstanceName: '새 인스턴스 이름',
  newInstanceUrl: 'HTTP(S) 공급자 URL',
  addInstance: '인스턴스 추가',
  connectionTitle: '연결',
  connectionDescription:
    'URL과 키는 전역으로 공유됩니다. 같은 인스턴스를 선택한 다른 배포도 같은 값을 읽습니다.',
  baseUrl: '공급자 URL',
  secretName: '키 변수 이름',
  secretNamePlaceholder: '환경 변수 이름. 비워 두면 인증 없음',
  secretStatus: 'API Key',
  secretSource: { env: '프로세스 환경 변수', file: '엔드포인트 .env', none: '설정 안 됨' },
  secretValue: '키 값',
  secretValuePlaceholder: '엔드포인트 .env에만 기록하며 다시 표시하지 않음',
  saveSecret: '키 기록',
  secretSaved: '키를 엔드포인트 .env에 기록했습니다.',
  secretNameFirst: '키 값을 기록하기 전에 키 변수 이름을 저장하세요.',
  multimodal: '이미지 입력 허용',
  endpointPath: '요청 경로',
  extraHeaders: '추가 요청 헤더(JSON 객체)',
  extraBody: '추가 요청 본문(JSON 객체)',
  jsonObjectRequired: (label: string) => `${label}은(는) JSON 객체여야 합니다`,
  advancedProtocolTitle: '프로토콜 및 요청 확장',
  advancedProtocolDescription: 'OpenAI Responses 호환 엔드포인트를 위한 고급 설정(엔드포인트 경로와 추가 JSON 필드).',
  modelFieldLabel: '모델 식별자',
  effortFieldLabel: '추론 강도',
  temperatureFieldLabel: '샘플링 온도',
  specTitle: '모델',
  specDescription: '이 인스턴스가 호출할 모델과 추론 강도, 온도, token 한도 같은 생성 매개변수를 설정합니다.',
  modelName: '정확한 모델 이름',
  fetchModels: '모델 목록 가져오기',
  modelsFetched: (count: number) => `모델 ${count}개를 가져왔습니다.`,
  modelListFailed: (message: string) => `모델 목록을 가져오지 못했습니다: ${message}`,
  selectModel: '모델 선택',
  unsupportedTier: (current: string) => `지원하지 않는 현재 등급: ${current}`,
  thinkingOn: '켬',
  thinkingOff: '끔',
  effortPlaceholder: '추론 강도. 비우면 엔드포인트 기본값, none이면 끔',
  effortAria: '추론 강도',
  temperaturePlaceholder: '기본 온도',
  modelAria: '모델',
  tierAria: '추론 등급',
  temperatureAria: '온도',
  maxTokens: '최대 출력 token',
  contextWindow: '컨텍스트 창',
  serviceTier: '서비스 등급',
  serverDefault: '서버 기본값',
  activate: '현재 공급자 인스턴스로 설정',
  probe: '사용 가능 여부 테스트',
  probeTitle: '테스트 결과',
  probeStatus: '상태',
  probeOk: '성공',
  probeFailed: '실패',
  probeLatency: '소요 시간',
  probeModel: '응답한 모델',
  probeUsage: '사용량',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `입력 ${input} · 캐시 적중 ${cached} · 출력 ${output} · 추론 ${reasoning}`,
  probeEncrypted: '암호화된 추론',
  yes: '있음',
  no: '없음',
  probeCost: '이번 호출 비용',
  duplicate: '복제',
  duplicateName: '사본 이름',
  duplicateConfirm: '다음 이름으로 복제',
  duplicated: '복제했습니다.',
  delete: '삭제',
  deleteConfirmTitle: (name: string) => `인스턴스 ${name}을(를) 삭제하시겠습니까?`,
  deleteConfirmBody:
    '엔드포인트 설정과 .env를 함께 삭제합니다. 다른 배포가 이 인스턴스를 선택했는지는 여기서 알 수 없습니다.',
  deleted: '삭제했습니다.',
  pricingTitle: '가격',
  pricingDescription:
    '과거 기록은 요청 시점의 가격을 계속 사용합니다. 사용자 지정 가격은 모델과 비용 기준별로 모듈 기본값을 덮어씁니다.',
  pricingUnset: '사용자 지정 가격 없음: 모듈 가격표가 있으면 그것을 쓰고, 없으면 token만 기록하고 금액은 계산하지 않습니다.',
  meters: {
    input: '입력',
    cachedInput: '캐시 적중',
    uncachedInput: '캐시되지 않은 입력',
    output: '출력',
    reasoning: '추론',
    total: '합계',
  },
  marginal: '한계 비용',
  equivalent: 'API 환산 비용',
  perMillion: (label: string, rate: number) => `${label} ${rate}/100만`,
  free: '명시적 무료',
  bandsNote: '입력 구간 요금이나 서비스 등급이 포함되어 있습니다. 요청마다 실제 사용량과 서비스 등급으로 과금됩니다.',
  rateCached: '캐시 적중 / 100만 token',
  rateUncached: '캐시되지 않은 입력 / 100만 token',
  rateOutput: '출력 / 100만 token',
  currencyField: '통화',
  currencyRequired: '통화를 입력해야 이 가격을 저장합니다.',
  costFormNote:
    '기본 요금은 모든 모델에 적용됩니다. 구간 요금이나 서비스 등급은 아래 전체 규칙에서 설정하세요.',
  costFormOverridden:
    '저장된 가격은 세 칸 양식으로 표현할 수 없는 형태라 아래 전체 규칙이 적용됩니다. 양식을 편집하면 규칙이 대체됩니다.',
  editFull: '고급 가격 규칙(JSON)',
  fullNote:
    '빈 배열이면 모듈 기본 가격으로 돌아가고, rules가 빈 배열이면 명시적 무료입니다. 전체 규칙은 입력 구간 요금, 서비스 등급, 추가 계량 단위를 지원합니다.',
  viewSnapshot: '현재 적용 중인 가격 스냅숏 보기',
};
