import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: 'Salvato; vale dalla richiesta successiva.',
  instancesTitle: 'Istanze del provider',
  instancesDescription:
    'Ogni istanza conserva la propria connessione, specifica del modello e prezzi. Le richieste in corso e le sessioni in background attive mantengono il vincolo esistente.',
  activeSuffix: ' · attiva',
  instanceField: 'Istanza del provider',
  newInstanceName: 'Nome della nuova istanza',
  newInstanceUrl: 'URL HTTP(S) del provider',
  addInstance: 'Aggiungi istanza',
  connectionTitle: 'Connessione',
  connectionDescription:
    'URL e chiave sono globali: gli altri deployment che selezionano questa istanza leggono la stessa copia.',
  baseUrl: 'URL del provider',
  secretName: 'Nome della variabile della chiave',
  secretNamePlaceholder: 'Nome della variabile di ambiente; vuoto = nessuna autenticazione',
  secretStatus: 'API Key',
  secretSource: { env: 'ambiente del processo', file: ".env dell'endpoint", none: 'non impostata' },
  secretValue: 'Valore della chiave',
  secretValuePlaceholder: "Scritto solo nel .env dell'endpoint; mai mostrato",
  saveSecret: 'Salva chiave',
  secretSaved: "Chiave scritta nel .env dell'endpoint.",
  secretNameFirst: 'Salva il nome della variabile della chiave prima di scriverne il valore.',
  multimodal: 'Accetta immagini in ingresso',
  endpointPath: 'Percorso della richiesta',
  extraHeaders: 'Header aggiuntivi (oggetto JSON)',
  extraBody: 'Corpo aggiuntivo (oggetto JSON)',
  jsonObjectRequired: (label: string) => `${label} deve essere un oggetto JSON`,
  advancedProtocolTitle: 'Protocollo e override della richiesta',
  advancedProtocolDescription: 'Opzioni avanzate per endpoint compatibili con OpenAI Responses (percorso personalizzato e campi JSON aggiuntivi).',
  modelFieldLabel: 'Identificatore del modello',
  effortFieldLabel: 'Sforzo di ragionamento',
  temperatureFieldLabel: 'Temperatura di campionamento',
  specTitle: 'Modello',
  specDescription: 'Configura identificatore del modello, sforzo di ragionamento, temperatura e limiti di token per questa istanza.',
  modelName: 'Nome esatto del modello',
  fetchModels: 'Recupera modelli',
  modelsFetched: (count: number) => `${count} ${count === 1 ? 'modello recuperato' : 'modelli recuperati'}.`,
  modelListFailed: (message: string) => `Impossibile recuperare l'elenco dei modelli: ${message}`,
  selectModel: 'Scegli un modello',
  unsupportedTier: (current: string) => `Livello attuale non supportato: ${current}`,
  thinkingOn: 'attivo',
  thinkingOff: 'disattivo',
  effortPlaceholder: "Sforzo di ragionamento; vuoto = predefinito dell'endpoint, none = disattivato",
  effortAria: 'Sforzo di ragionamento',
  temperaturePlaceholder: 'Temperatura predefinita',
  modelAria: 'Modello',
  tierAria: 'Livello di ragionamento',
  temperatureAria: 'Temperatura',
  maxTokens: 'Token massimi in uscita',
  contextWindow: 'Finestra di contesto',
  serviceTier: 'Livello di servizio',
  serverDefault: 'Predefinito del server',
  activate: 'Imposta come istanza del provider attiva',
  probe: 'Testa endpoint',
  probeTitle: 'Risultato del test',
  probeStatus: 'Stato',
  probeOk: 'riuscito',
  probeFailed: 'non riuscito',
  probeLatency: 'Latenza',
  probeModel: 'Modello restituito',
  probeUsage: 'Uso',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `ingresso ${input} · in cache ${cached} · uscita ${output} · ragionamento ${reasoning}`,
  probeEncrypted: 'Ragionamento crittografato',
  yes: 'sì',
  no: 'no',
  probeCost: 'Costo di questa chiamata',
  duplicate: 'Duplica',
  duplicateName: 'Nome della copia',
  duplicateConfirm: 'Duplica come',
  duplicated: 'Duplicato.',
  delete: 'Elimina',
  deleteConfirmTitle: (name: string) => `Eliminare l'istanza ${name}?`,
  deleteConfirmBody:
    "Rimuove la configurazione dell'endpoint e il suo .env. Da qui non si può sapere se un altro deployment la seleziona.",
  deleted: 'Eliminato.',
  pricingTitle: 'Prezzi',
  pricingDescription:
    'I record storici mantengono la tariffa in vigore al momento della richiesta. Le tariffe personalizzate sostituiscono i valori predefiniti del modulo per modello e base di costo.',
  pricingUnset: 'Nessun prezzo personalizzato: si applicano i prezzi del modulo se disponibili; altrimenti si registrano solo i token.',
  meters: {
    input: 'Ingresso',
    cachedInput: 'Hit della cache',
    uncachedInput: 'Ingresso non in cache',
    output: 'Uscita',
    reasoning: 'Ragionamento',
    total: 'Totale',
  },
  marginal: 'Costo marginale',
  equivalent: 'Costo equivalente API',
  perMillion: (label: string, rate: number) => `${label} ${rate}/Mln`,
  free: 'Esplicitamente gratuito',
  bandsNote: "Include fasce di input o livelli di servizio; fatturato in base all'uso effettivo e al livello di servizio di ogni richiesta.",
  rateCached: 'Hit della cache / Mln token',
  rateUncached: 'Ingresso non in cache / Mln token',
  rateOutput: 'Uscita / Mln token',
  currencyField: 'Valuta',
  currencyRequired: 'Inserisci una valuta per salvare questa tariffa.',
  costFormNote:
    'Le tariffe base valgono per tutti i modelli; fasce di input e livelli di servizio vanno nelle regole complete qui sotto.',
  costFormOverridden:
    'I prezzi salvati hanno una forma che il form a tre tariffe non può esprimere; valgono le regole complete qui sotto. Modificare il form le sostituisce.',
  editFull: 'Regole di prezzo avanzate (JSON)',
  fullNote:
    'Un array vuoto ripristina la tariffa predefinita del modulo; un array rules vuoto significa esplicitamente gratuito. Le regole complete supportano fasce di input, livelli di servizio e metriche aggiuntive.',
  viewSnapshot: "Visualizza l'istantanea dei prezzi attiva",
};
