import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: '保存しました。次のリクエストから反映されます。',
  instancesTitle: 'プロバイダーインスタンス',
  instancesDescription:
    '各インスタンスは接続、モデル設定、料金を個別に保存します。処理中のリクエストと起動済みのバックグラウンドセッションは既存の割り当てを維持します。',
  activeSuffix: ' · 現在',
  instanceField: 'プロバイダーインスタンス',
  newInstanceName: '新しいインスタンス名',
  newInstanceUrl: 'HTTP(S) プロバイダー URL',
  addInstance: 'インスタンスを追加',
  connectionTitle: '接続',
  connectionDescription:
    'URL とキーは全体で共有されます。同じインスタンスを選んだ他のデプロイも同じものを読み込みます。',
  baseUrl: 'プロバイダー URL',
  secretName: 'キーの変数名',
  secretNamePlaceholder: '環境変数名。空欄 = 認証なし',
  secretStatus: 'API Key',
  secretSource: { env: 'プロセスの環境変数', file: 'エンドポイントの .env', none: '未設定' },
  secretValue: 'キーの値',
  secretValuePlaceholder: 'エンドポイントの .env にのみ書き込み、表示しません',
  saveSecret: 'キーを書き込む',
  secretSaved: 'キーをエンドポイントの .env に書き込みました。',
  secretNameFirst: 'キーの値を書き込む前に、キーの変数名を保存してください。',
  multimodal: '画像入力を受け付ける',
  endpointPath: 'リクエストパス',
  extraHeaders: '追加リクエストヘッダー（JSON オブジェクト）',
  extraBody: '追加リクエストボディ（JSON オブジェクト）',
  jsonObjectRequired: (label: string) => `${label} は JSON オブジェクトである必要があります`,
  advancedProtocolTitle: 'プロトコルとリクエストの拡張',
  advancedProtocolDescription: 'OpenAI Responses 互換エンドポイント向けの高度な設定（エンドポイントのパスと追加の JSON フィールド）。',
  modelFieldLabel: 'モデル ID',
  effortFieldLabel: '推論の強さ',
  temperatureFieldLabel: 'サンプリング温度',
  specTitle: 'モデル',
  specDescription: 'このインスタンスで呼び出すモデルと、推論の強さ、温度、token 上限などの生成パラメーターを設定します。',
  modelName: '正確なモデル名',
  fetchModels: 'モデル一覧を取得',
  modelsFetched: (count: number) => `${count} 個のモデルを取得しました。`,
  modelListFailed: (message: string) => `モデル一覧を取得できませんでした：${message}`,
  selectModel: 'モデルを選択',
  unsupportedTier: (current: string) => `現在の階層には対応していません：${current}`,
  thinkingOn: 'オン',
  thinkingOff: 'オフ',
  effortPlaceholder: '推論の強さ。空欄 = エンドポイントの既定値、none = オフ',
  effortAria: '推論の強さ',
  temperaturePlaceholder: '既定の温度',
  modelAria: 'モデル',
  tierAria: '推論の階層',
  temperatureAria: '温度',
  maxTokens: '最大出力 token 数',
  contextWindow: 'コンテキストウィンドウ',
  serviceTier: 'サービス階層',
  serverDefault: 'サーバーの既定値',
  activate: '現在のプロバイダーインスタンスに設定',
  probe: '動作をテスト',
  probeTitle: 'テスト結果',
  probeStatus: '状態',
  probeOk: '成功',
  probeFailed: '失敗',
  probeLatency: '所要時間',
  probeModel: '応答のモデル',
  probeUsage: '使用量',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `入力 ${input} · キャッシュヒット ${cached} · 出力 ${output} · 推論 ${reasoning}`,
  probeEncrypted: '暗号化された思考',
  yes: 'あり',
  no: 'なし',
  probeCost: '今回の費用',
  duplicate: '複製',
  duplicateName: '複製後の名前',
  duplicateConfirm: '複製',
  duplicated: '複製しました。',
  delete: '削除',
  deleteConfirmTitle: (name: string) => `インスタンス ${name} を削除しますか？`,
  deleteConfirmBody:
    'エンドポイントの設定と .env を削除します。他のデプロイがこれを選んでいるかどうかは、ここではわかりません。',
  deleted: '削除しました。',
  pricingTitle: '料金',
  pricingDescription:
    '過去の記録はリクエスト時点の料金を使い続けます。カスタム料金は、モデルと費用の基準ごとにモジュールの既定値を上書きします。',
  pricingUnset: 'カスタム料金は未設定です。モジュールの料金表があればそれを使い、なければ token のみを記録して金額は計算しません。',
  meters: {
    input: '入力',
    cachedInput: 'キャッシュヒット',
    uncachedInput: 'キャッシュ外の入力',
    output: '出力',
    reasoning: '推論',
    total: '合計',
  },
  marginal: '限界費用',
  equivalent: 'API 換算費用',
  perMillion: (label: string, rate: number) => `${label} ${rate}/100万`,
  free: '無料と明示',
  bandsNote: '入力の段階料金またはサービス階層を含みます。リクエストごとの実際の使用量とサービス階層で課金されます。',
  rateCached: 'キャッシュヒット / 100万 token',
  rateUncached: 'キャッシュ外の入力 / 100万 token',
  rateOutput: '出力 / 100万 token',
  currencyField: '通貨',
  currencyRequired: '通貨を入力するとこの料金を保存できます。',
  costFormNote:
    '基本料金はすべてのモデルに適用されます。段階料金やサービス階層は下の完全なルールで設定してください。',
  costFormOverridden:
    '保存済みの料金は 3 項目のフォームでは表現できない形のため、下の完全なルールが適用されています。フォームを編集するとルールが置き換わります。',
  editFull: '高度な料金ルール（JSON）',
  fullNote:
    '空の配列にするとモジュールの既定料金に戻ります。rules を空の配列にすると無料と明示したことになります。完全なルールでは入力の段階料金、サービス階層、追加の計量単位を扱えます。',
  viewSnapshot: '現在有効な料金のスナップショットを表示',
};
