import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: 'Сохранено; действует со следующего запроса.',
  instancesTitle: 'Экземпляры провайдера',
  instancesDescription:
    'У каждого экземпляра свои подключение, спецификация модели и цены. Выполняющиеся запросы и работающие фоновые сессии сохраняют текущую привязку.',
  activeSuffix: ' · активный',
  instanceField: 'Экземпляр провайдера',
  newInstanceName: 'Имя нового экземпляра',
  newInstanceUrl: 'HTTP(S) URL провайдера',
  addInstance: 'Добавить экземпляр',
  connectionTitle: 'Подключение',
  connectionDescription:
    'URL и ключ глобальные: другие развёртывания, выбравшие этот экземпляр, читают ту же копию.',
  baseUrl: 'URL провайдера',
  secretName: 'Имя переменной с ключом',
  secretNamePlaceholder: 'Имя переменной окружения; пусто = без аутентификации',
  secretStatus: 'API Key',
  secretSource: { env: 'окружение процесса', file: '.env эндпоинта', none: 'не задан' },
  secretValue: 'Значение ключа',
  secretValuePlaceholder: 'Записывается только в .env эндпоинта; никогда не показывается',
  saveSecret: 'Сохранить ключ',
  secretSaved: 'Ключ записан в .env эндпоинта.',
  secretNameFirst: 'Сохраните имя переменной с ключом, прежде чем записывать значение ключа.',
  multimodal: 'Принимает изображения',
  endpointPath: 'Путь запроса',
  extraHeaders: 'Дополнительные заголовки (объект JSON)',
  extraBody: 'Дополнительное тело (объект JSON)',
  jsonObjectRequired: (label: string) => `${label}: должно быть объектом JSON`,
  advancedProtocolTitle: 'Протокол и переопределения запроса',
  advancedProtocolDescription: 'Расширенные параметры для эндпоинтов, совместимых с OpenAI Responses (свой путь и дополнительные поля JSON).',
  modelFieldLabel: 'Идентификатор модели',
  effortFieldLabel: 'Глубина рассуждения',
  temperatureFieldLabel: 'Температура сэмплирования',
  specTitle: 'Модель',
  specDescription: 'Настройте идентификатор модели, глубину рассуждения, температуру и лимиты token для этого экземпляра.',
  modelName: 'Точное имя модели',
  fetchModels: 'Получить модели',
  modelsFetched: (count: number) => `Получено моделей: ${count}.`,
  modelListFailed: (message: string) => `Не удалось получить список моделей: ${message}`,
  selectModel: 'Выберите модель',
  unsupportedTier: (current: string) => `Текущий уровень не поддерживается: ${current}`,
  thinkingOn: 'вкл.',
  thinkingOff: 'выкл.',
  effortPlaceholder: 'Глубина рассуждения; пусто = по умолчанию эндпоинта, none = выкл.',
  effortAria: 'Глубина рассуждения',
  temperaturePlaceholder: 'Температура по умолчанию',
  modelAria: 'Модель',
  tierAria: 'Уровень рассуждения',
  temperatureAria: 'Температура',
  maxTokens: 'Максимум token на выходе',
  contextWindow: 'Окно контекста',
  serviceTier: 'Уровень обслуживания',
  serverDefault: 'По умолчанию сервера',
  activate: 'Сделать активным экземпляром провайдера',
  probe: 'Проверить эндпоинт',
  probeTitle: 'Результат проверки',
  probeStatus: 'Состояние',
  probeOk: 'успешно',
  probeFailed: 'ошибка',
  probeLatency: 'Задержка',
  probeModel: 'Модель в ответе',
  probeUsage: 'Расход',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `вход ${input} · из кэша ${cached} · выход ${output} · рассуждение ${reasoning}`,
  probeEncrypted: 'Зашифрованное рассуждение',
  yes: 'да',
  no: 'нет',
  probeCost: 'Стоимость этого вызова',
  duplicate: 'Дублировать',
  duplicateName: 'Имя копии',
  duplicateConfirm: 'Дублировать как',
  duplicated: 'Дублировано.',
  delete: 'Удалить',
  deleteConfirmTitle: (name: string) => `Удалить экземпляр ${name}?`,
  deleteConfirmBody:
    'Удаляет конфигурацию эндпоинта и его .env. Отсюда нельзя узнать, выбирает ли его другое развёртывание.',
  deleted: 'Удалено.',
  pricingTitle: 'Цены',
  pricingDescription:
    'Исторические записи хранят расценку, действовавшую на момент запроса. Пользовательские расценки переопределяют значения модуля по умолчанию для каждой модели и основы стоимости.',
  pricingUnset: 'Пользовательских цен нет: применяются цены модуля, если они есть; иначе записываются только token.',
  meters: {
    input: 'Вход',
    cachedInput: 'Попадание в кэш',
    uncachedInput: 'Вход без кэша',
    output: 'Выход',
    reasoning: 'Рассуждение',
    total: 'Итого',
  },
  marginal: 'Предельная стоимость',
  equivalent: 'Эквивалентная стоимость API',
  perMillion: (label: string, rate: number) => `${label} ${rate}/млн`,
  free: 'Явно бесплатно',
  bandsNote: 'Включает входные диапазоны или уровни обслуживания; оплата по фактическому расходу и уровню обслуживания каждого запроса.',
  rateCached: 'Попадание в кэш / млн token',
  rateUncached: 'Вход без кэша / млн token',
  rateOutput: 'Выход / млн token',
  currencyField: 'Валюта',
  currencyRequired: 'Укажите валюту, чтобы сохранить эту расценку.',
  costFormNote:
    'Базовые ставки применяются ко всем моделям; входные диапазоны и уровни обслуживания задаются в полных правилах ниже.',
  costFormOverridden:
    'Сохранённые цены имеют форму, которую нельзя выразить формой из трёх ставок; действуют полные правила ниже. Изменение формы заменит их.',
  editFull: 'Расширенные правила тарификации (JSON)',
  fullNote:
    'Пустой массив восстанавливает расценку модуля по умолчанию; пустой массив rules означает явно бесплатно. Полные правила поддерживают входные диапазоны, уровни обслуживания и дополнительные счётчики.',
  viewSnapshot: 'Показать снимок действующих цен',
};
