import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: '已儲存，下一次請求生效。',
  instancesTitle: '供應實例',
  instancesDescription:
    '每個實例獨立儲存連線、模型檔與報價。目前請求與已啟動的背景工作階段保持原有綁定。',
  activeSuffix: ' · 目前',
  instanceField: '供應實例',
  newInstanceName: '新實例名稱',
  newInstanceUrl: 'HTTP(S) 供應位址',
  addInstance: '新增實例',
  connectionTitle: '連線',
  connectionDescription: '位址與金鑰全域共用：別的部署選中同一實例時讀的是同一份。',
  baseUrl: '供應位址',
  secretName: '金鑰變數名稱',
  secretNamePlaceholder: '環境變數名稱；留空 = 無驗證',
  secretStatus: '金鑰',
  secretSource: { env: '處理程序環境', file: '端點 .env', none: '未設定' },
  secretValue: '金鑰值',
  secretValuePlaceholder: '只寫入端點 .env，不回顯',
  saveSecret: '寫入金鑰',
  secretSaved: '金鑰已寫入端點 .env。',
  secretNameFirst: '先儲存金鑰變數名稱，再寫入金鑰值。',
  multimodal: '接受圖片輸入',
  endpointPath: '請求路徑',
  extraHeaders: '附加請求標頭（JSON 物件）',
  extraBody: '附加請求內容（JSON 物件）',
  jsonObjectRequired: (label: string) => `${label} 必須是 JSON 物件`,
  advancedProtocolTitle: '協定與請求擴充',
  advancedProtocolDescription: '針對 OpenAI Responses 相容端點的進階設定（端點路徑與附加 JSON 欄位）。',
  modelFieldLabel: '模型識別碼',
  effortFieldLabel: '推理強度',
  temperatureFieldLabel: '取樣溫度',
  specTitle: '模型檔',
  specDescription: '設定此實例呼叫的模型及推理、溫度和 Token 限制等生成參數。',
  modelName: '明確模型名稱',
  fetchModels: '取得模型清單',
  modelsFetched: (count: number) => `取得 ${count} 個模型。`,
  modelListFailed: (message: string) => `取不到模型清單：${message}`,
  selectModel: '選擇模型',
  unsupportedTier: (current: string) => `目前檔位未支援：${current}`,
  thinkingOn: '開啟',
  thinkingOff: '關閉',
  effortPlaceholder: '推理強度；空 = 端點預設，none = 關閉',
  effortAria: '推理強度',
  temperaturePlaceholder: '溫度預設',
  modelAria: '模型',
  tierAria: '推理檔位',
  temperatureAria: '溫度',
  maxTokens: '最大輸出 token',
  contextWindow: '上下文視窗',
  serviceTier: '服務檔',
  serverDefault: '伺服器端預設',
  activate: '設為目前供應實例',
  probe: '測試可用性',
  probeTitle: '測試結果',
  probeStatus: '狀態',
  probeOk: '成功',
  probeFailed: '失敗',
  probeLatency: '耗時',
  probeModel: '回顯模型',
  probeUsage: '用量',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `輸入 ${input} · 快取命中 ${cached} · 輸出 ${output} · 推理 ${reasoning}`,
  probeEncrypted: '加密思維鏈',
  yes: '有',
  no: '無',
  probeCost: '本次費用',
  duplicate: '複製',
  duplicateName: '副本名稱',
  duplicateConfirm: '複製為',
  duplicated: '已複製。',
  delete: '刪除',
  deleteConfirmTitle: (name: string) => `刪除實例 ${name}？`,
  deleteConfirmBody: '端點設定與 .env 一併刪除。別的部署若選中了它，無法在此得知。',
  deleted: '已刪除。',
  pricingTitle: '報價',
  pricingDescription: '歷史流水固定使用請求時的報價。自訂報價依模型與費用口徑覆蓋模組預設值。',
  pricingUnset: '未設自訂報價：優先使用模組價目；若無適用價目，僅記錄 token，不計金額。',
  meters: {
    input: '輸入',
    cachedInput: '快取命中',
    uncachedInput: '未快取輸入',
    output: '輸出',
    reasoning: '推理',
    total: '總量',
  },
  marginal: '邊際費用',
  equivalent: 'API 等價費用',
  perMillion: (label: string, rate: number) => `${label} ${rate}/百萬`,
  free: '已明確免費',
  bandsNote: '含輸入階梯或服務檔；依本次實際用量與服務檔計費。',
  rateCached: '快取命中 / 百萬 token',
  rateUncached: '未快取輸入 / 百萬 token',
  rateOutput: '輸出 / 百萬 token',
  currencyField: '幣別',
  currencyRequired: '填寫幣別後才儲存這份報價。',
  costFormNote: '基礎費率統一適用於全部模型；階梯或多模型規則請在下方完整規則中設定。',
  costFormOverridden: '目前報價不是三格表能表達的形狀，以下方完整規則為準；改動三格表會覆蓋它。',
  editFull: '進階定價規則 (JSON)',
  fullNote:
    '空陣列恢復模組預設報價；rules 為空陣列表示明確免費。完整規則支援輸入階梯、服務檔及額外計量單位。',
  viewSnapshot: '查看目前生效報價快照',
};
