import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: 'Salvo; vale a partir da próxima requisição.',
  instancesTitle: 'Instâncias de provedor',
  instancesDescription:
    'Cada instância mantém sua própria conexão, especificação de modelo e preços. Requisições em andamento e sessões em segundo plano em execução mantêm o vínculo atual.',
  activeSuffix: ' · ativa',
  instanceField: 'Instância de provedor',
  newInstanceName: 'Nome da nova instância',
  newInstanceUrl: 'URL HTTP(S) do provedor',
  addInstance: 'Adicionar instância',
  connectionTitle: 'Conexão',
  connectionDescription:
    'A URL e a chave são globais: outras implantações que selecionam esta instância leem a mesma cópia.',
  baseUrl: 'URL do provedor',
  secretName: 'Nome da variável da chave',
  secretNamePlaceholder: 'Nome da variável de ambiente; vazio = sem autenticação',
  secretStatus: 'API Key',
  secretSource: { env: 'ambiente do processo', file: '.env do endpoint', none: 'não definida' },
  secretValue: 'Valor da chave',
  secretValuePlaceholder: 'Gravado só no .env do endpoint; nunca é exibido',
  saveSecret: 'Salvar chave',
  secretSaved: 'Chave gravada no .env do endpoint.',
  secretNameFirst: 'Salve o nome da variável da chave antes de gravar um valor de chave.',
  multimodal: 'Aceita entrada de imagens',
  endpointPath: 'Caminho da requisição',
  extraHeaders: 'Cabeçalhos extras (objeto JSON)',
  extraBody: 'Corpo extra (objeto JSON)',
  jsonObjectRequired: (label: string) => `${label} deve ser um objeto JSON`,
  advancedProtocolTitle: 'Protocolo e substituições da requisição',
  advancedProtocolDescription: 'Opções avançadas para endpoints compatíveis com OpenAI Responses (caminho personalizado e campos JSON extras).',
  modelFieldLabel: 'Identificador do modelo',
  effortFieldLabel: 'Esforço de raciocínio',
  temperatureFieldLabel: 'Temperatura de amostragem',
  specTitle: 'Modelo',
  specDescription: 'Configure o identificador do modelo, o esforço de raciocínio, a temperatura e os limites de tokens desta instância.',
  modelName: 'Nome exato do modelo',
  fetchModels: 'Buscar modelos',
  modelsFetched: (count: number) => (count === 1 ? '1 modelo obtido.' : `${count} modelos obtidos.`),
  modelListFailed: (message: string) => `Não foi possível obter a lista de modelos: ${message}`,
  selectModel: 'Escolha um modelo',
  unsupportedTier: (current: string) => `Nível atual não suportado: ${current}`,
  thinkingOn: 'ativado',
  thinkingOff: 'desativado',
  effortPlaceholder: 'Esforço de raciocínio; vazio = padrão do endpoint, none = desativado',
  effortAria: 'Esforço de raciocínio',
  temperaturePlaceholder: 'Temperatura padrão',
  modelAria: 'Modelo',
  tierAria: 'Nível de raciocínio',
  temperatureAria: 'Temperatura',
  maxTokens: 'Máximo de tokens de saída',
  contextWindow: 'Janela de contexto',
  serviceTier: 'Nível de serviço',
  serverDefault: 'Padrão do servidor',
  activate: 'Definir como instância de provedor ativa',
  probe: 'Testar endpoint',
  probeTitle: 'Resultado do teste',
  probeStatus: 'Status',
  probeOk: 'sucesso',
  probeFailed: 'falhou',
  probeLatency: 'Latência',
  probeModel: 'Modelo retornado',
  probeUsage: 'Uso',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `entrada ${input} · em cache ${cached} · saída ${output} · raciocínio ${reasoning}`,
  probeEncrypted: 'Raciocínio criptografado',
  yes: 'sim',
  no: 'não',
  probeCost: 'Custo desta chamada',
  duplicate: 'Duplicar',
  duplicateName: 'Nome da cópia',
  duplicateConfirm: 'Duplicar como',
  duplicated: 'Duplicado.',
  delete: 'Excluir',
  deleteConfirmTitle: (name: string) => `Excluir a instância ${name}?`,
  deleteConfirmBody:
    'Remove a configuração do endpoint e o .env dele. Daqui não é possível saber se outra implantação o seleciona.',
  deleted: 'Excluído.',
  pricingTitle: 'Preços',
  pricingDescription:
    'Os registros históricos mantêm a cotação vigente no momento da requisição. Cotações personalizadas substituem os padrões do módulo por modelo e base de custo.',
  pricingUnset: 'Sem preços personalizados: os preços do módulo valem quando existem; caso contrário, só os tokens são registrados.',
  meters: {
    input: 'Entrada',
    cachedInput: 'Acerto de cache',
    uncachedInput: 'Entrada sem cache',
    output: 'Saída',
    reasoning: 'Raciocínio',
    total: 'Total',
  },
  marginal: 'Custo marginal',
  equivalent: 'Custo equivalente de API',
  perMillion: (label: string, rate: number) => `${label} ${rate}/M`,
  free: 'Explicitamente gratuito',
  bandsNote: 'Inclui faixas de entrada ou níveis de serviço; cobrado pelo uso real e pelo nível de serviço de cada requisição.',
  rateCached: 'Acerto de cache / M tokens',
  rateUncached: 'Entrada sem cache / M tokens',
  rateOutput: 'Saída / M tokens',
  currencyField: 'Moeda',
  currencyRequired: 'Informe uma moeda para salvar esta cotação.',
  costFormNote:
    'As tarifas base valem para todos os modelos; faixas de entrada e níveis de serviço ficam nas regras completas abaixo.',
  costFormOverridden:
    'Os preços salvos têm um formato que o formulário de três tarifas não consegue expressar; valem as regras completas abaixo. Editar o formulário as substitui.',
  editFull: 'Regras de preço avançadas (JSON)',
  fullNote:
    'Um array vazio restaura a cotação padrão do módulo; um array rules vazio significa explicitamente gratuito. As regras completas aceitam faixas de entrada, níveis de serviço e medidores extras.',
  viewSnapshot: 'Ver o snapshot de preços ativo',
};
