import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: "Enregistré ; s'applique dès la requête suivante.",
  instancesTitle: 'Instances de fournisseur',
  instancesDescription:
    "Chaque instance conserve sa propre connexion, sa spécification de modèle et sa tarification. Les requêtes en cours et les sessions d'arrière-plan actives conservent leur liaison actuelle.",
  activeSuffix: ' · active',
  instanceField: 'Instance de fournisseur',
  newInstanceName: 'Nom de la nouvelle instance',
  newInstanceUrl: 'URL HTTP(S) du fournisseur',
  addInstance: 'Ajouter une instance',
  connectionTitle: 'Connexion',
  connectionDescription:
    "L'URL et la clé sont globales : les autres déploiements qui sélectionnent cette instance lisent la même copie.",
  baseUrl: 'URL du fournisseur',
  secretName: 'Nom de la variable de clé',
  secretNamePlaceholder: "Nom de variable d'environnement ; vide = sans authentification",
  secretStatus: 'API Key',
  secretSource: { env: 'env. du processus', file: ".env de l'endpoint", none: 'non définie' },
  secretValue: 'Valeur de la clé',
  secretValuePlaceholder: "Écrite uniquement dans le .env de l'endpoint ; jamais affichée",
  saveSecret: 'Enregistrer la clé',
  secretSaved: "Clé écrite dans le .env de l'endpoint.",
  secretNameFirst: "Enregistrez le nom de la variable de clé avant d'écrire une valeur de clé.",
  multimodal: "Accepte l'entrée d'images",
  endpointPath: 'Chemin de requête',
  extraHeaders: 'En-têtes supplémentaires (objet JSON)',
  extraBody: 'Corps supplémentaire (objet JSON)',
  jsonObjectRequired: (label: string) => `${label} doit être un objet JSON`,
  advancedProtocolTitle: 'Protocole et surcharges de requête',
  advancedProtocolDescription: 'Options avancées pour les endpoints compatibles OpenAI Responses (chemin personnalisé et champs JSON supplémentaires).',
  modelFieldLabel: 'Identifiant du modèle',
  effortFieldLabel: 'Effort de raisonnement',
  temperatureFieldLabel: "Température d'échantillonnage",
  specTitle: 'Modèle',
  specDescription: "Configurez l'identifiant du modèle, l'effort de raisonnement, la température et les limites de tokens de cette instance.",
  modelName: 'Nom exact du modèle',
  fetchModels: 'Récupérer les modèles',
  modelsFetched: (count: number) => `${count} modèle${count > 1 ? 's' : ''} récupéré${count > 1 ? 's' : ''}.`,
  modelListFailed: (message: string) => `Impossible de récupérer la liste des modèles : ${message}`,
  selectModel: 'Choisir un modèle',
  unsupportedTier: (current: string) => `Niveau actuel non pris en charge : ${current}`,
  thinkingOn: 'activé',
  thinkingOff: 'désactivé',
  effortPlaceholder: "Effort de raisonnement ; vide = défaut de l'endpoint, none = désactivé",
  effortAria: 'Effort de raisonnement',
  temperaturePlaceholder: 'Température par défaut',
  modelAria: 'Modèle',
  tierAria: 'Niveau de raisonnement',
  temperatureAria: 'Température',
  maxTokens: 'Tokens de sortie max',
  contextWindow: 'Fenêtre de contexte',
  serviceTier: 'Niveau de service',
  serverDefault: 'Défaut du serveur',
  activate: 'Définir comme instance de fournisseur active',
  probe: "Tester l'endpoint",
  probeTitle: 'Résultat du test',
  probeStatus: 'État',
  probeOk: 'réussi',
  probeFailed: 'échec',
  probeLatency: 'Latence',
  probeModel: 'Modèle renvoyé',
  probeUsage: 'Utilisation',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `entrée ${input} · en cache ${cached} · sortie ${output} · raisonnement ${reasoning}`,
  probeEncrypted: 'Raisonnement chiffré',
  yes: 'oui',
  no: 'non',
  probeCost: 'Coût de cet appel',
  duplicate: 'Dupliquer',
  duplicateName: 'Nom de la copie',
  duplicateConfirm: 'Dupliquer sous',
  duplicated: 'Dupliqué.',
  delete: 'Supprimer',
  deleteConfirmTitle: (name: string) => `Supprimer l'instance ${name} ?`,
  deleteConfirmBody:
    "Supprime la configuration de l'endpoint et son .env. Impossible de savoir ici si un autre déploiement la sélectionne.",
  deleted: 'Supprimé.',
  pricingTitle: 'Tarification',
  pricingDescription:
    'Les enregistrements historiques gardent le tarif en vigueur au moment de la requête. Les tarifs personnalisés remplacent les valeurs par défaut du module par modèle et par base de coût.',
  pricingUnset: "Pas de tarification personnalisée : les prix du module s'appliquent s'ils existent ; sinon seuls les tokens sont enregistrés.",
  meters: {
    input: 'Entrée',
    cachedInput: 'Succès de cache',
    uncachedInput: 'Entrée hors cache',
    output: 'Sortie',
    reasoning: 'Raisonnement',
    total: 'Total',
  },
  marginal: 'Coût marginal',
  equivalent: 'Coût équivalent API',
  perMillion: (label: string, rate: number) => `${label} ${rate}/M`,
  free: 'Explicitement gratuit',
  bandsNote: "Inclut des paliers d'entrée ou des niveaux de service ; facturé selon l'utilisation réelle et le niveau de service de chaque requête.",
  rateCached: 'Succès de cache / M tokens',
  rateUncached: 'Entrée hors cache / M tokens',
  rateOutput: 'Sortie / M tokens',
  currencyField: 'Devise',
  currencyRequired: 'Saisissez une devise pour enregistrer ce tarif.',
  costFormNote:
    "Les tarifs de base s'appliquent à tous les modèles ; les paliers d'entrée et les niveaux de service se configurent dans les règles complètes ci-dessous.",
  costFormOverridden:
    "La tarification enregistrée a une forme que le formulaire à trois tarifs ne peut pas exprimer ; les règles complètes ci-dessous s'appliquent. Modifier le formulaire les remplace.",
  editFull: 'Règles de tarification avancées (JSON)',
  fullNote:
    "Un tableau vide rétablit le tarif par défaut du module ; un tableau rules vide signifie explicitement gratuit. Les règles complètes prennent en charge les paliers d'entrée, les niveaux de service et des métriques supplémentaires.",
  viewSnapshot: "Voir l'instantané de tarification actif",
};
