import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: 'Guardado; se aplica desde la siguiente solicitud.',
  instancesTitle: 'Instancias de proveedor',
  instancesDescription:
    'Cada instancia conserva su propia conexión, especificación de modelo y precios. Las solicitudes en curso y las sesiones en segundo plano en ejecución mantienen su vinculación actual.',
  activeSuffix: ' · activa',
  instanceField: 'Instancia de proveedor',
  newInstanceName: 'Nombre de la nueva instancia',
  newInstanceUrl: 'URL HTTP(S) del proveedor',
  addInstance: 'Agregar instancia',
  connectionTitle: 'Conexión',
  connectionDescription:
    'La URL y la clave son globales: otros despliegues que seleccionen esta instancia leen la misma copia.',
  baseUrl: 'URL del proveedor',
  secretName: 'Nombre de la variable de la clave',
  secretNamePlaceholder: 'Nombre de la variable de entorno; vacío = sin autenticación',
  secretStatus: 'API Key',
  secretSource: { env: 'entorno del proceso', file: '.env del endpoint', none: 'sin configurar' },
  secretValue: 'Valor de la clave',
  secretValuePlaceholder: 'Solo se escribe en el .env del endpoint; nunca se muestra',
  saveSecret: 'Guardar clave',
  secretSaved: 'Clave escrita en el .env del endpoint.',
  secretNameFirst: 'Guarda el nombre de la variable de la clave antes de escribir un valor de clave.',
  multimodal: 'Acepta entrada de imágenes',
  endpointPath: 'Ruta de la solicitud',
  extraHeaders: 'Encabezados adicionales (objeto JSON)',
  extraBody: 'Cuerpo adicional (objeto JSON)',
  jsonObjectRequired: (label: string) => `${label} debe ser un objeto JSON`,
  advancedProtocolTitle: 'Protocolo y sobrescrituras de solicitud',
  advancedProtocolDescription: 'Opciones avanzadas para endpoints compatibles con OpenAI Responses (ruta personalizada y campos JSON adicionales).',
  modelFieldLabel: 'Identificador del modelo',
  effortFieldLabel: 'Esfuerzo de razonamiento',
  temperatureFieldLabel: 'Temperatura de muestreo',
  specTitle: 'Modelo',
  specDescription: 'Configura el identificador del modelo, el esfuerzo de razonamiento, la temperatura y los límites de tokens de esta instancia.',
  modelName: 'Nombre exacto del modelo',
  fetchModels: 'Obtener modelos',
  modelsFetched: (count: number) => (count === 1 ? 'Se obtuvo 1 modelo.' : `Se obtuvieron ${count} modelos.`),
  modelListFailed: (message: string) => `No se pudo obtener la lista de modelos: ${message}`,
  selectModel: 'Elige un modelo',
  unsupportedTier: (current: string) => `Nivel actual no compatible: ${current}`,
  thinkingOn: 'activado',
  thinkingOff: 'desactivado',
  effortPlaceholder: 'Esfuerzo de razonamiento; vacío = predeterminado del endpoint, none = desactivado',
  effortAria: 'Esfuerzo de razonamiento',
  temperaturePlaceholder: 'Temperatura predeterminada',
  modelAria: 'Modelo',
  tierAria: 'Nivel de razonamiento',
  temperatureAria: 'Temperatura',
  maxTokens: 'Máximo de tokens de salida',
  contextWindow: 'Ventana de contexto',
  serviceTier: 'Nivel de servicio',
  serverDefault: 'Predeterminado del servidor',
  activate: 'Usar como instancia de proveedor activa',
  probe: 'Probar endpoint',
  probeTitle: 'Resultado de la prueba',
  probeStatus: 'Estado',
  probeOk: 'correcto',
  probeFailed: 'falló',
  probeLatency: 'Latencia',
  probeModel: 'Modelo devuelto',
  probeUsage: 'Uso',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `entrada ${input} · en caché ${cached} · salida ${output} · razonamiento ${reasoning}`,
  probeEncrypted: 'Razonamiento cifrado',
  yes: 'sí',
  no: 'no',
  probeCost: 'Costo de esta llamada',
  duplicate: 'Duplicar',
  duplicateName: 'Nombre de la copia',
  duplicateConfirm: 'Duplicar como',
  duplicated: 'Duplicado.',
  delete: 'Eliminar',
  deleteConfirmTitle: (name: string) => `¿Eliminar la instancia ${name}?`,
  deleteConfirmBody:
    'Elimina la configuración del endpoint y su .env. Desde aquí no se puede saber si otro despliegue la selecciona.',
  deleted: 'Eliminado.',
  pricingTitle: 'Precios',
  pricingDescription:
    'Los registros históricos conservan la cotización vigente al momento de la solicitud. Las cotizaciones personalizadas reemplazan los valores predeterminados del módulo por modelo y base de costo.',
  pricingUnset: 'Sin precios personalizados: se aplican los precios del módulo si existen; de lo contrario, solo se registran los tokens.',
  meters: {
    input: 'Entrada',
    cachedInput: 'Acierto de caché',
    uncachedInput: 'Entrada sin caché',
    output: 'Salida',
    reasoning: 'Razonamiento',
    total: 'Total',
  },
  marginal: 'Costo marginal',
  equivalent: 'Costo equivalente de API',
  perMillion: (label: string, rate: number) => `${label} ${rate}/M`,
  free: 'Gratis explícitamente',
  bandsNote: 'Incluye tramos de entrada o niveles de servicio; se factura por el uso real y el nivel de servicio de cada solicitud.',
  rateCached: 'Acierto de caché / M tokens',
  rateUncached: 'Entrada sin caché / M tokens',
  rateOutput: 'Salida / M tokens',
  currencyField: 'Moneda',
  currencyRequired: 'Ingresa una moneda para guardar esta cotización.',
  costFormNote:
    'Las tarifas base se aplican a todos los modelos; los tramos de entrada y los niveles de servicio van en las reglas completas de abajo.',
  costFormOverridden:
    'Los precios guardados tienen una forma que el formulario de tres tarifas no puede expresar; se aplican las reglas completas de abajo. Editar el formulario las reemplaza.',
  editFull: 'Reglas de precios avanzadas (JSON)',
  fullNote:
    'Un arreglo vacío restaura la cotización predeterminada del módulo; un arreglo rules vacío significa gratis explícitamente. Las reglas completas admiten tramos de entrada, niveles de servicio y medidores adicionales.',
  viewSnapshot: 'Ver la instantánea de precios activa',
};
