import type { en } from './strings.ts';

export const panel: Partial<typeof en> = {
  saved: 'Gespeichert; gilt ab der nächsten Anfrage.',
  instancesTitle: 'Anbieter-Instanzen',
  instancesDescription:
    'Jede Instanz speichert ihre eigene Verbindung, Modellspezifikation und Preise. Laufende Anfragen und aktive Hintergrund-Sessions behalten ihre bestehende Bindung.',
  activeSuffix: ' · aktiv',
  instanceField: 'Anbieter-Instanz',
  newInstanceName: 'Name der neuen Instanz',
  newInstanceUrl: 'HTTP(S)-Anbieter-URL',
  addInstance: 'Instanz hinzufügen',
  connectionTitle: 'Verbindung',
  connectionDescription:
    'URL und Schlüssel sind global: Andere Deployments, die diese Instanz wählen, lesen dieselbe Kopie.',
  baseUrl: 'Anbieter-URL',
  secretName: 'Name der Schlüsselvariable',
  secretNamePlaceholder: 'Name der Umgebungsvariable; leer = ohne Authentifizierung',
  secretStatus: 'API Key',
  secretSource: { env: 'Prozessumgebung', file: '.env des Endpunkts', none: 'nicht gesetzt' },
  secretValue: 'Schlüsselwert',
  secretValuePlaceholder: 'Wird nur in die .env des Endpunkts geschrieben; nie angezeigt',
  saveSecret: 'Schlüssel speichern',
  secretSaved: 'Schlüssel in die .env des Endpunkts geschrieben.',
  secretNameFirst: 'Speichere den Namen der Schlüsselvariable, bevor du einen Schlüsselwert schreibst.',
  multimodal: 'Akzeptiert Bildeingabe',
  endpointPath: 'Anfragepfad',
  extraHeaders: 'Zusätzliche Header (JSON-Objekt)',
  extraBody: 'Zusätzlicher Body (JSON-Objekt)',
  jsonObjectRequired: (label: string) => `${label} muss ein JSON-Objekt sein`,
  advancedProtocolTitle: 'Protokoll und Anfrage-Überschreibungen',
  advancedProtocolDescription: 'Erweiterte Optionen für OpenAI-Responses-kompatible Endpunkte (eigener Pfad und zusätzliche JSON-Felder).',
  modelFieldLabel: 'Modellkennung',
  effortFieldLabel: 'Denkaufwand',
  temperatureFieldLabel: 'Sampling-Temperatur',
  specTitle: 'Modell',
  specDescription: 'Lege Modellkennung, Denkaufwand, Temperatur und Token-Limits für diese Instanz fest.',
  modelName: 'Exakter Modellname',
  fetchModels: 'Modelle abrufen',
  modelsFetched: (count: number) => `${count} ${count === 1 ? 'Modell' : 'Modelle'} abgerufen.`,
  modelListFailed: (message: string) => `Modellliste konnte nicht abgerufen werden: ${message}`,
  selectModel: 'Modell wählen',
  unsupportedTier: (current: string) => `Aktuelle Stufe nicht unterstützt: ${current}`,
  thinkingOn: 'an',
  thinkingOff: 'aus',
  effortPlaceholder: 'Denkaufwand; leer = Endpunkt-Standard, none = aus',
  effortAria: 'Denkaufwand',
  temperaturePlaceholder: 'Standardtemperatur',
  modelAria: 'Modell',
  tierAria: 'Denkstufe',
  temperatureAria: 'Temperatur',
  maxTokens: 'Max. Ausgabe-Tokens',
  contextWindow: 'Kontextfenster',
  serviceTier: 'Servicestufe',
  serverDefault: 'Server-Standard',
  activate: 'Als aktive Anbieter-Instanz festlegen',
  probe: 'Endpunkt testen',
  probeTitle: 'Testergebnis',
  probeStatus: 'Status',
  probeOk: 'erfolgreich',
  probeFailed: 'fehlgeschlagen',
  probeLatency: 'Latenz',
  probeModel: 'Zurückgemeldetes Modell',
  probeUsage: 'Verbrauch',
  probeUsageLine: (input: string, cached: string, output: string, reasoning: string) =>
    `Eingabe ${input} · gecacht ${cached} · Ausgabe ${output} · Denkprozess ${reasoning}`,
  probeEncrypted: 'Verschlüsselter Denkprozess',
  yes: 'ja',
  no: 'nein',
  probeCost: 'Kosten dieses Aufrufs',
  duplicate: 'Duplizieren',
  duplicateName: 'Name der Kopie',
  duplicateConfirm: 'Duplizieren als',
  duplicated: 'Dupliziert.',
  delete: 'Löschen',
  deleteConfirmTitle: (name: string) => `Instanz ${name} löschen?`,
  deleteConfirmBody:
    'Entfernt die Endpunktkonfiguration und ihre .env. Ob ein anderes Deployment sie gewählt hat, lässt sich hier nicht feststellen.',
  deleted: 'Gelöscht.',
  pricingTitle: 'Preise',
  pricingDescription:
    'Historische Einträge behalten die Preisangabe, die zum Anfragezeitpunkt galt. Eigene Preisangaben überschreiben die Modulstandards je Modell und Kostenbasis.',
  pricingUnset: 'Keine eigenen Preise: Modulpreise gelten, wenn vorhanden; sonst werden nur Tokens erfasst.',
  meters: {
    input: 'Eingabe',
    cachedInput: 'Cache-Treffer',
    uncachedInput: 'Nicht gecachte Eingabe',
    output: 'Ausgabe',
    reasoning: 'Denkprozess',
    total: 'Gesamt',
  },
  marginal: 'Grenzkosten',
  equivalent: 'API-äquivalente Kosten',
  perMillion: (label: string, rate: number) => `${label} ${rate}/Mio.`,
  free: 'Ausdrücklich kostenlos',
  bandsNote: 'Enthält Eingabestufen oder Servicestufen; abgerechnet nach tatsächlichem Verbrauch und Servicestufe pro Anfrage.',
  rateCached: 'Cache-Treffer / Mio. Tokens',
  rateUncached: 'Nicht gecachte Eingabe / Mio. Tokens',
  rateOutput: 'Ausgabe / Mio. Tokens',
  currencyField: 'Währung',
  currencyRequired: 'Gib eine Währung an, um diese Preisangabe zu speichern.',
  costFormNote:
    'Grundpreise gelten für alle Modelle; Eingabestufen und Servicestufen gehören in die vollständigen Regeln unten.',
  costFormOverridden:
    'Die gespeicherten Preise haben eine Form, die das Formular mit drei Preisen nicht abbilden kann; es gelten die vollständigen Regeln unten. Eine Änderung im Formular ersetzt sie.',
  editFull: 'Erweiterte Preisregeln (JSON)',
  fullNote:
    'Ein leeres Array stellt die Standard-Preisangabe des Moduls wieder her; ein leeres rules-Array bedeutet ausdrücklich kostenlos. Vollständige Regeln unterstützen Eingabestufen, Servicestufen und zusätzliche Messgrößen.',
  viewSnapshot: 'Aktiven Preis-Snapshot anzeigen',
};
