import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: '外観',
  deleteScheme: '配色を削除',
  schemeSheetTitle: '配色',
  schemeSheetDesc: '選択するとすぐに適用され、このブラウザーに保存されます。',
  switchedMode: (label: string) => `「${label}」に切り替えました`,
  switchedScheme: (name: string) => `✓「${name}」に切り替えました`,
  paletteSheetTitle: 'パレット',
  paletteSheetDesc: 'プレビューで変わるのは現在のライトまたはダークの配色だけです。保存すると変更が残ります。',
  schemeName: '配色名',
  colorAria: (label: string) => `${label}の色`,
  hexAria: (label: string) => `${label}の 16 進カラー`,
  previewing: '● プレビュー中（未保存）',
  resetPreview: 'プレビューを破棄',
  previewReset: '保存していないパレットのプレビューを破棄しました',
  confirmDelete: 'もう一度クリックして削除',
  aboutToDelete: (name: string) => `「${name}」を削除します。もう一度クリックして確定してください。`,
  deleteCancelled: '削除をキャンセルしました',
  deleted: (name: string) => `カスタム配色を削除し、「${name}」に戻しました`,
  copyAsNew: '新しい配色としてコピー',
  copySuffix: ' のコピー',
  customSuffix: ' カスタム',
  copied: '✓ 新しいカスタム配色としてコピーしました',
  saveScheme: '配色を保存',
  savedVariant: (appearance: string) => `✓ 現在の${appearance}版を保存しました`,
  customName: (name: string) => `${name} カスタム`,
  savedAsCustom: '✓ 組み込みの配色をカスタム配色として保存しました',
  builtin: '組み込み',
  custom: 'カスタム',
  saveCurrent: '現在の配色を保存',
  saveAsCustom: 'カスタムとして保存',
  builtinHint: '組み込みの配色は上書きできません。パレットを編集してカスタムとして保存してください。',
  saveFailed: (reason: string) => `配色をデプロイに保存できませんでした：${reason}`,
  customHint: 'カスタム配色はそのまま保存できます。ライト版とダーク版は別々に保存されます。',
  specimenTitle: 'コンポーネントの見本',
  thinkLabel: '思考',
  thinkBody: '思考テキストのプレビュー',
  monologBody: '本文のプレビュー',
  chartAria: 'グラフ系列の色のプレビュー',
  navLabel: '外観',
};
