import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Внешний вид',
  deleteScheme: 'Удалить схему',
  schemeSheetTitle: 'Цветовая схема',
  schemeSheetDesc: 'Выбор применяется сразу и сохраняется в этом браузере.',
  switchedMode: (label: string) => `Выбрано: «${label}»`,
  switchedScheme: (name: string) => `✓ Выбрано: «${name}»`,
  paletteSheetTitle: 'Палитра',
  paletteSheetDesc: 'Предпросмотр меняет только текущую светлую или тёмную палитру. Сохраните, чтобы оставить изменения.',
  schemeName: 'Название схемы',
  colorAria: (label: string) => `Цвет: ${label}`,
  hexAria: (label: string) => `Шестнадцатеричный цвет: ${label}`,
  previewing: '● Предпросмотр, ещё не сохранено',
  resetPreview: 'Отменить предпросмотр',
  previewReset: 'Несохранённый предпросмотр палитры отменён',
  confirmDelete: 'Нажмите ещё раз, чтобы подтвердить удаление',
  aboutToDelete: (name: string) => `Схема «${name}» будет удалена; нажмите ещё раз для подтверждения.`,
  deleteCancelled: 'Удаление отменено',
  deleted: (name: string) => `Пользовательская схема удалена, выбрана «${name}»`,
  copyAsNew: 'Копировать как новую схему',
  copySuffix: ' (копия)',
  customSuffix: ' (пользовательская)',
  copied: '✓ Скопировано как новая пользовательская схема',
  saveScheme: 'Сохранить схему',
  savedVariant: (appearance: string) => `✓ Текущий вариант сохранён: ${appearance}`,
  customName: (name: string) => `${name} (пользовательская)`,
  savedAsCustom: '✓ Встроенная схема сохранена как пользовательская',
  builtin: 'Встроенная',
  custom: 'Пользовательская',
  saveCurrent: 'Сохранить текущую схему',
  saveAsCustom: 'Сохранить как пользовательскую',
  builtinHint: 'Встроенные схемы нельзя перезаписать; измените палитру и сохраните её как пользовательскую.',
  saveFailed: (reason: string) => `Палитра не сохранена в развёртывание: ${reason}`,
  customHint: 'Пользовательские схемы сохраняются напрямую; светлый и тёмный варианты независимы.',
  specimenTitle: 'Образцы компонентов',
  thinkLabel: 'Рассуждение',
  thinkBody: 'Предпросмотр текста рассуждения',
  monologBody: 'Предпросмотр текста сообщения',
  chartAria: 'Предпросмотр цветов серий диаграммы',
  navLabel: 'Внешний вид',
};
