import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Darstellung',
  deleteScheme: 'Schema löschen',
  schemeSheetTitle: 'Farbschema',
  schemeSheetDesc: 'Die Auswahl gilt sofort und wird in diesem Browser gespeichert.',
  switchedMode: (label: string) => `Zu „${label}“ gewechselt`,
  switchedScheme: (name: string) => `✓ Zu „${name}“ gewechselt`,
  paletteSheetTitle: 'Farbpalette',
  paletteSheetDesc: 'Die Vorschau ändert nur die aktuelle helle oder dunkle Palette. Speichere, um die Änderungen zu behalten.',
  schemeName: 'Schemaname',
  colorAria: (label: string) => `Farbe ${label}`,
  hexAria: (label: string) => `Hex-Farbe ${label}`,
  previewing: '● Vorschau, noch nicht gespeichert',
  resetPreview: 'Vorschau verwerfen',
  previewReset: 'Ungespeicherte Palettenvorschau verworfen',
  confirmDelete: 'Zum Löschen erneut klicken',
  aboutToDelete: (name: string) => `„${name}“ wird gelöscht; zum Bestätigen erneut klicken.`,
  deleteCancelled: 'Löschen abgebrochen',
  deleted: (name: string) => `Eigenes Schema gelöscht, zurück zu „${name}“`,
  copyAsNew: 'Als neues Schema kopieren',
  copySuffix: ' Kopie',
  customSuffix: ' angepasst',
  copied: '✓ Als neues eigenes Schema kopiert',
  saveScheme: 'Schema speichern',
  savedVariant: (appearance: string) => `✓ Aktuelle Variante „${appearance}“ gespeichert`,
  customName: (name: string) => `${name} angepasst`,
  savedAsCustom: '✓ Integriertes Schema als eigenes Schema gespeichert',
  builtin: 'Integriert',
  custom: 'Eigenes',
  saveCurrent: 'Aktuelles Schema speichern',
  saveAsCustom: 'Als eigenes speichern',
  builtinHint: 'Integrierte Schemas lassen sich nicht überschreiben; bearbeite die Palette und speichere sie als eigenes Schema.',
  saveFailed: (reason: string) => `Die Palette wurde nicht im Deployment gespeichert: ${reason}`,
  customHint: 'Eigene Schemas werden direkt gespeichert; helle und dunkle Variante sind unabhängig.',
  specimenTitle: 'Komponentenvorschau',
  thinkLabel: 'Denkprozess',
  thinkBody: 'Vorschau des Denktexts',
  monologBody: 'Vorschau des Nachrichtentexts',
  chartAria: 'Farbvorschau der Diagrammreihen',
  navLabel: 'Darstellung',
};
