import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: '外觀',
  deleteScheme: '刪除方案',
  schemeSheetTitle: '顏色方案',
  schemeSheetDesc: '選擇後立即套用並儲存在目前瀏覽器。',
  switchedMode: (label: string) => `已切換到「${label}」`,
  switchedScheme: (name: string) => `✓ 已切換到「${name}」`,
  paletteSheetTitle: '調色盤',
  paletteSheetDesc: '預覽僅修改目前淺色或深色配色；儲存後保留。',
  schemeName: '方案名稱',
  colorAria: (label: string) => `${label}顏色`,
  hexAria: (label: string) => `${label}十六進位顏色`,
  previewing: '● 正在預覽，尚未儲存',
  resetPreview: '撤銷預覽',
  previewReset: '已撤銷未儲存的調色預覽',
  confirmDelete: '再次點擊確認刪除',
  aboutToDelete: (name: string) => `即將刪除「${name}」；再次點擊確認。`,
  deleteCancelled: '已取消刪除',
  deleted: (name: string) => `已刪除自訂方案，並切回「${name}」`,
  copyAsNew: '複製為新方案',
  copySuffix: ' 副本',
  customSuffix: ' 自訂',
  copied: '✓ 已複製為新的自訂方案',
  saveScheme: '儲存方案',
  savedVariant: (appearance: string) => `✓ 目前${appearance}變體已儲存`,
  customName: (name: string) => `${name} 自訂`,
  savedAsCustom: '✓ 內建方案已另存為自訂',
  builtin: '內建',
  custom: '自訂',
  saveCurrent: '儲存目前方案',
  saveAsCustom: '另存為自訂',
  builtinHint: '內建方案不可覆寫；調色後可另存為自訂。',
  saveFailed: (reason: string) => `配色未能存進部署：${reason}`,
  customHint: '自訂方案可直接儲存；淺色與黑夜變體互相獨立。',
  specimenTitle: '元件試色',
  thinkLabel: '思考',
  thinkBody: '思考文字預覽',
  monologBody: '正文預覽',
  chartAria: '圖表系列色預覽',
  navLabel: '外觀',
};
