import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Aspetto',
  deleteScheme: 'Elimina schema',
  schemeSheetTitle: 'Schema di colori',
  schemeSheetDesc: 'La selezione si applica subito e viene salvata in questo browser.',
  switchedMode: (label: string) => `Passato a «${label}»`,
  switchedScheme: (name: string) => `✓ Passato a «${name}»`,
  paletteSheetTitle: 'Tavolozza',
  paletteSheetDesc: "L'anteprima modifica solo la tavolozza chiara o scura attuale. Salva per conservare le modifiche.",
  schemeName: 'Nome dello schema',
  colorAria: (label: string) => `Colore ${label}`,
  hexAria: (label: string) => `Colore esadecimale ${label}`,
  previewing: '● Anteprima, non ancora salvata',
  resetPreview: 'Annulla anteprima',
  previewReset: 'Anteprima della tavolozza non salvata annullata',
  confirmDelete: "Clicca di nuovo per confermare l'eliminazione",
  aboutToDelete: (name: string) => `Stai per eliminare «${name}»; clicca di nuovo per confermare.`,
  deleteCancelled: 'Eliminazione annullata',
  deleted: (name: string) => `Schema personalizzato eliminato, tornato a «${name}»`,
  copyAsNew: 'Copia come nuovo schema',
  copySuffix: ' copia',
  customSuffix: ' personalizzato',
  copied: '✓ Copiato come nuovo schema personalizzato',
  saveScheme: 'Salva schema',
  savedVariant: (appearance: string) => `✓ Variante attuale (${appearance}) salvata`,
  customName: (name: string) => `${name} personalizzato`,
  savedAsCustom: '✓ Schema integrato salvato come personalizzato',
  builtin: 'Integrato',
  custom: 'Personalizzato',
  saveCurrent: 'Salva schema attuale',
  saveAsCustom: 'Salva come personalizzato',
  builtinHint: 'Gli schemi integrati non possono essere sovrascritti; modifica la tavolozza e salvala come personalizzata.',
  saveFailed: (reason: string) => `La tavolozza non è stata salvata nel deployment: ${reason}`,
  customHint: 'Gli schemi personalizzati si salvano direttamente; le varianti chiara e scura sono indipendenti.',
  specimenTitle: 'Anteprima componenti',
  thinkLabel: 'Ragionamento',
  thinkBody: 'Anteprima del testo di ragionamento',
  monologBody: 'Anteprima del testo del messaggio',
  chartAria: 'Anteprima dei colori delle serie del grafico',
  navLabel: 'Aspetto',
};
