import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Apariencia',
  deleteScheme: 'Eliminar esquema',
  schemeSheetTitle: 'Esquema de colores',
  schemeSheetDesc: 'La selección se aplica de inmediato y se guarda en este navegador.',
  switchedMode: (label: string) => `Se cambió a “${label}”`,
  switchedScheme: (name: string) => `✓ Se cambió a “${name}”`,
  paletteSheetTitle: 'Paleta',
  paletteSheetDesc: 'La vista previa solo edita la paleta clara u oscura actual. Guarda para conservar los cambios.',
  schemeName: 'Nombre del esquema',
  colorAria: (label: string) => `Color de ${label}`,
  hexAria: (label: string) => `Color hexadecimal de ${label}`,
  previewing: '● Vista previa, aún sin guardar',
  resetPreview: 'Descartar vista previa',
  previewReset: 'Se descartó la vista previa de la paleta sin guardar',
  confirmDelete: 'Haz clic de nuevo para confirmar la eliminación',
  aboutToDelete: (name: string) => `Se eliminará “${name}”; haz clic de nuevo para confirmar.`,
  deleteCancelled: 'Eliminación cancelada',
  deleted: (name: string) => `Esquema personalizado eliminado; se volvió a “${name}”`,
  copyAsNew: 'Copiar como esquema nuevo',
  copySuffix: ' copia',
  customSuffix: ' personalizado',
  copied: '✓ Copiado como un esquema personalizado nuevo',
  saveScheme: 'Guardar esquema',
  savedVariant: (appearance: string) => `✓ Se guardó la variante actual: ${appearance}`,
  customName: (name: string) => `${name} personalizado`,
  savedAsCustom: '✓ Esquema integrado guardado como personalizado',
  builtin: 'Integrado',
  custom: 'Personalizado',
  saveCurrent: 'Guardar esquema actual',
  saveAsCustom: 'Guardar como personalizado',
  builtinHint: 'Los esquemas integrados no se pueden sobrescribir; edita la paleta y guárdala como personalizada.',
  saveFailed: (reason: string) => `La paleta no se guardó en el despliegue: ${reason}`,
  customHint: 'Los esquemas personalizados se guardan directamente; las variantes clara y oscura son independientes.',
  specimenTitle: 'Muestra de componentes',
  thinkLabel: 'Razonamiento',
  thinkBody: 'Vista previa del texto de razonamiento',
  monologBody: 'Vista previa del texto del mensaje',
  chartAria: 'Vista previa de los colores de las series del gráfico',
  navLabel: 'Apariencia',
};
