import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Apparence',
  deleteScheme: 'Supprimer le schéma',
  schemeSheetTitle: 'Schéma de couleurs',
  schemeSheetDesc: "La sélection s'applique immédiatement et est enregistrée dans ce navigateur.",
  switchedMode: (label: string) => `Passé en « ${label} »`,
  switchedScheme: (name: string) => `✓ Passé à « ${name} »`,
  paletteSheetTitle: 'Palette de couleurs',
  paletteSheetDesc: "L'aperçu ne modifie que la palette claire ou sombre actuelle. Enregistrez pour conserver les changements.",
  schemeName: 'Nom du schéma',
  colorAria: (label: string) => `Couleur ${label}`,
  hexAria: (label: string) => `Couleur hexadécimale ${label}`,
  previewing: '● Aperçu, pas encore enregistré',
  resetPreview: "Annuler l'aperçu",
  previewReset: 'Aperçu de palette non enregistré annulé',
  confirmDelete: 'Cliquez à nouveau pour confirmer la suppression',
  aboutToDelete: (name: string) => `Suppression de « ${name} » ; cliquez à nouveau pour confirmer.`,
  deleteCancelled: 'Suppression annulée',
  deleted: (name: string) => `Schéma personnalisé supprimé, retour à « ${name} »`,
  copyAsNew: 'Copier comme nouveau schéma',
  copySuffix: ' copie',
  customSuffix: ' personnalisé',
  copied: '✓ Copié comme nouveau schéma personnalisé',
  saveScheme: 'Enregistrer le schéma',
  savedVariant: (appearance: string) => `✓ Variante actuelle (${appearance}) enregistrée`,
  customName: (name: string) => `${name} personnalisé`,
  savedAsCustom: '✓ Schéma intégré enregistré comme schéma personnalisé',
  builtin: 'Intégré',
  custom: 'Personnalisé',
  saveCurrent: 'Enregistrer le schéma actuel',
  saveAsCustom: 'Enregistrer comme personnalisé',
  builtinHint: 'Les schémas intégrés ne peuvent pas être écrasés ; modifiez la palette et enregistrez-la comme personnalisée.',
  saveFailed: (reason: string) => `La palette n'a pas été enregistrée dans le déploiement : ${reason}`,
  customHint: "Les schémas personnalisés s'enregistrent directement ; les variantes claire et sombre sont indépendantes.",
  specimenTitle: 'Aperçu des composants',
  thinkLabel: 'Raisonnement',
  thinkBody: 'Aperçu du texte de raisonnement',
  monologBody: 'Aperçu du texte du message',
  chartAria: 'Aperçu des couleurs des séries de graphiques',
  navLabel: 'Apparence',
};
