import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Aparência',
  deleteScheme: 'Excluir esquema',
  schemeSheetTitle: 'Esquema de cores',
  schemeSheetDesc: 'A seleção é aplicada na hora e salva neste navegador.',
  switchedMode: (label: string) => `Alterado para “${label}”`,
  switchedScheme: (name: string) => `✓ Alterado para “${name}”`,
  paletteSheetTitle: 'Paleta',
  paletteSheetDesc: 'A prévia edita apenas a paleta clara ou escura atual. Salve para manter as alterações.',
  schemeName: 'Nome do esquema',
  colorAria: (label: string) => `Cor de ${label}`,
  hexAria: (label: string) => `Cor hexadecimal de ${label}`,
  previewing: '● Em prévia, ainda não salvo',
  resetPreview: 'Descartar prévia',
  previewReset: 'Prévia da paleta não salva descartada',
  confirmDelete: 'Clique de novo para confirmar a exclusão',
  aboutToDelete: (name: string) => `“${name}” será excluído; clique de novo para confirmar.`,
  deleteCancelled: 'Exclusão cancelada',
  deleted: (name: string) => `Esquema personalizado excluído; voltou para “${name}”`,
  copyAsNew: 'Copiar como novo esquema',
  copySuffix: ' cópia',
  customSuffix: ' personalizado',
  copied: '✓ Copiado como um novo esquema personalizado',
  saveScheme: 'Salvar esquema',
  savedVariant: (appearance: string) => `✓ Variante atual salva: ${appearance}`,
  customName: (name: string) => `${name} personalizado`,
  savedAsCustom: '✓ Esquema integrado salvo como personalizado',
  builtin: 'Integrado',
  custom: 'Personalizado',
  saveCurrent: 'Salvar esquema atual',
  saveAsCustom: 'Salvar como personalizado',
  builtinHint: 'Esquemas integrados não podem ser sobrescritos; edite a paleta e salve como personalizado.',
  saveFailed: (reason: string) => `A paleta não foi salva na implantação: ${reason}`,
  customHint: 'Esquemas personalizados são salvos diretamente; as variantes clara e escura são independentes.',
  specimenTitle: 'Amostra de componentes',
  thinkLabel: 'Raciocínio',
  thinkBody: 'Prévia do texto de raciocínio',
  monologBody: 'Prévia do texto da mensagem',
  chartAria: 'Prévia das cores das séries do gráfico',
  navLabel: 'Aparência',
};
