import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: '모양',
  deleteScheme: '구성표 삭제',
  schemeSheetTitle: '색 구성표',
  schemeSheetDesc: '선택하면 바로 적용되고 이 브라우저에 저장됩니다.',
  switchedMode: (label: string) => `"${label}"(으)로 전환했습니다`,
  switchedScheme: (name: string) => `✓ "${name}"(으)로 전환했습니다`,
  paletteSheetTitle: '팔레트',
  paletteSheetDesc: '미리 보기는 현재 라이트 또는 다크 팔레트만 바꿉니다. 변경 사항을 유지하려면 저장하세요.',
  schemeName: '구성표 이름',
  colorAria: (label: string) => `${label} 색`,
  hexAria: (label: string) => `${label} 16진수 색`,
  previewing: '● 미리 보는 중, 아직 저장 안 됨',
  resetPreview: '미리 보기 취소',
  previewReset: '저장하지 않은 팔레트 미리 보기를 취소했습니다',
  confirmDelete: '한 번 더 클릭하면 삭제됩니다',
  aboutToDelete: (name: string) => `"${name}"을(를) 삭제합니다. 확인하려면 한 번 더 클릭하세요.`,
  deleteCancelled: '삭제를 취소했습니다',
  deleted: (name: string) => `사용자 지정 구성표를 삭제하고 "${name}"(으)로 되돌렸습니다`,
  copyAsNew: '새 구성표로 복사',
  copySuffix: ' 사본',
  customSuffix: ' 사용자 지정',
  copied: '✓ 새 사용자 지정 구성표로 복사했습니다',
  saveScheme: '구성표 저장',
  savedVariant: (appearance: string) => `✓ 현재 ${appearance} 변형을 저장했습니다`,
  customName: (name: string) => `${name} 사용자 지정`,
  savedAsCustom: '✓ 기본 제공 구성표를 사용자 지정 구성표로 저장했습니다',
  builtin: '기본 제공',
  custom: '사용자 지정',
  saveCurrent: '현재 구성표 저장',
  saveAsCustom: '사용자 지정으로 저장',
  builtinHint: '기본 제공 구성표는 덮어쓸 수 없습니다. 팔레트를 편집한 뒤 사용자 지정으로 저장하세요.',
  saveFailed: (reason: string) => `팔레트를 배포에 저장하지 못했습니다: ${reason}`,
  customHint: '사용자 지정 구성표는 바로 저장됩니다. 라이트와 다크 변형은 서로 독립적입니다.',
  specimenTitle: '구성 요소 견본',
  thinkLabel: '추론',
  thinkBody: '추론 텍스트 미리 보기',
  monologBody: '본문 미리 보기',
  chartAria: '차트 계열 색 미리 보기',
  navLabel: '모양',
};
