import { pick } from '../../core/language.ts';

const zh = {
  pageTitle: '存储',
  sheetTitle: '数据',
  sectionDisk: '落盘 data/（重启后仍在）',
  sectionMemory: '内存暂存（重启即清零）',
  groupDisk: (group: string) => group + ' · 落盘',
  groupMemory: (group: string) => group + ' · 内存暂存',
  nukeAll: '⚠ 一键清空全部',
  clear: '清除',
  dangerTitle: (label: string) => `⚠ 危险操作：${label}`,
  dangerBody: (note: string) => `${note}\n\n确定不可恢复地清除？`,
  clearTitle: (label: string) => `清除「${label}」？`,
  cleared: '已清除',
  clearFailed: (err: string) => '清除失败: ' + err,
  nukeTitle: '⚠⚠ 一键清空全部存储',
  nukeBody: '清除清单中的所有存储项。此操作无法撤销。',
  partialFailed: (keys: string) => '部分失败: ' + keys,
  nukedAll: (count: number) => `✓ 已全部清空（${count} 项）`,
  nukeFailed: (err: string) => '一键清空失败: ' + err,
  noList: '(服务端未挂载存储清单)',
  loadFailed: (err: string) => '存储清单加载失败: ' + err,
  loading: '加载中…',
  navLabel: '存储',
};

const en: typeof zh = {
  pageTitle: 'Storage',
  sheetTitle: 'Data',
  sectionDisk: 'Persisted data/ (survives restart)',
  sectionMemory: 'In-memory (cleared on restart)',
  groupDisk: (group: string) => group + ' · persisted',
  groupMemory: (group: string) => group + ' · in-memory',
  nukeAll: '⚠ Clear everything',
  clear: 'Clear',
  dangerTitle: (label: string) => `⚠ Dangerous: ${label}`,
  dangerBody: (note: string) => `${note}\n\nClear irreversibly?`,
  clearTitle: (label: string) => `Clear "${label}"?`,
  cleared: 'Cleared',
  clearFailed: (err: string) => 'Clear failed: ' + err,
  nukeTitle: '⚠⚠ Clear all storage',
  nukeBody: 'Clear every storage item in the list. This cannot be undone.',
  partialFailed: (keys: string) => 'Partially failed: ' + keys,
  nukedAll: (count: number) => `✓ Everything cleared (${count} items)`,
  nukeFailed: (err: string) => 'Clear all failed: ' + err,
  noList: '(The server has no storage list mounted)',
  loadFailed: (err: string) => 'Failed to load storage list: ' + err,
  loading: 'Loading…',
  navLabel: 'Storage',
};

export const S = pick({ zh, en });
