import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Conexões de modelo', navLabel: 'Conexões de modelo', navGroup: 'Core', create: '+ Nova instância de conexão', newName: 'Instância sem nome',
  createHint: 'Uma instância é um conjunto de configurações do provedor salvo como cartão.',
  empty: 'Ainda não há conexões de modelo', emptyHint: 'Adicione uma conexão de modelo para habilitar a inferência.',
  eraseConfirm: 'Confirmar exclusão',
  connect: 'Conectar', activate: 'Definir como conexão atual', active: 'Modelo atual', missing: 'A conexão de modelo atual não existe: ',
  inUse: (names: string) => `Em uso por: ${names}`, selectedBy: (names: string) => `Selecionada por ${names} (fora de execução)`,
  names: (list: string[]) => list.join(', '),
  readiness: { ready: 'Pronta para conectar', 'needs-setup': 'Precisa de configuração', 'runtime-unavailable': 'Ambiente de execução indisponível', invalid: 'Configuração inválida', 'module-missing': 'Módulo indisponível', draft: 'Rascunho' },
  basic: 'Informações básicas', connection: 'Conexão', modelSection: 'Modelo e geração', moduleSection: 'Configurações do módulo', pricing: 'Preços', advanced: 'Protocolo avançado',
  name: 'Nome da conexão', module: 'Tipo de conexão', url: 'URL da API', key: 'API Key', model: 'Modelo',
  nameHint: 'Letras do alfabeto inglês, dígitos, - ou _; comece com uma letra ou um dígito. Sem espaços nem nomes reservados do sistema.',
  fixedModule: 'O tipo de conexão não pode mudar depois de salvo. Crie outra conexão para usar outro tipo.',
  test: 'Testar conexão', testOk: 'Teste bem-sucedido', testFailed: 'O teste falhou',
  keyEmpty: 'Digite a API Key', fetchModels: 'Buscar lista de modelos', modelList: 'Lista de modelos', modelsFetched: (count: number) => (count === 1 ? '1 modelo obtido.' : `${count} modelos obtidos.`),
  reasoning: 'Esforço de raciocínio', thinking: 'Ativar raciocínio', temperature: 'Temperatura', maxTokens: 'Máximo de tokens de saída', context: 'Limite de contexto', tier: 'Nível de serviço', images: 'Aceitar imagens',
  catalogNoWindow: 'A lista de modelos não informa a janela de contexto deste modelo; preencha com base na documentação do provedor.',
  catalogMaxOutput: (tokens: number) => `A lista de modelos informa uma saída máxima de ${tokens} tokens.`,
  advancedHint: 'Ajuste apenas para gateways de API personalizados ou serviços compatíveis.', secret: 'Variável de ambiente da credencial',
  extraHeaders: 'Cabeçalhos extras (objeto JSON)', extraBody: 'Corpo de requisição extra (objeto JSON)', priceRules: 'Regras de preço completas (array JSON)',
  shared: 'Configuração compartilhada: vários bots podem usar esta conexão. As alterações atualizam esta configuração compartilhada; crie outra conexão se precisar de configurações diferentes.',
  remove: 'Excluir conexão', duplicate: 'Duplicar conexão', cancel: 'Descartar alterações', save: 'Salvar', saved: 'Salvo',
  draftNote: 'As edições ficam neste navegador e são gravadas na configuração ao salvar. API Keys nunca ficam guardadas.',
  chooseModule: 'Escolha um tipo de conexão.', invalidNumber: 'Digite um número dentro do intervalo permitido.',
  contextAboveOutput: 'O limite de contexto deve ser maior que o máximo de tokens de saída.',
  required: 'Obrigatório.', jsonObject: 'Digite um objeto JSON válido.', jsonArray: 'Digite um array JSON válido.',
  unsaved: 'Guardado como rascunho; gravado ao salvar.',
  deleteConfirm: 'Excluir esta conexão e todos os arquivos do diretório dela?', referenced: 'Esta conexão é usada por estes bots e não pode ser excluída: ', reload: 'Recarregar',
};
