import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'モデル接続', navLabel: 'モデル接続', navGroup: 'Core', create: '+ 新しい接続インスタンス', newName: '名前のないインスタンス',
  createHint: 'インスタンスとは、プロバイダー設定の 1 セットをカードとして保存したものです。',
  empty: 'モデル接続はまだありません', emptyHint: 'モデル接続を追加すると推論できるようになります。',
  eraseConfirm: '削除を確定',
  connect: '接続', activate: '現在の接続に設定', active: '現在のモデル', missing: '現在のモデル接続が存在しません。設定での参照：',
  inUse: (names: string) => `使用中：${names}`, selectedBy: (names: string) => `${names} が選択中（未実行）`,
  readiness: { ready: '接続可能', 'needs-setup': '設定が必要', 'runtime-unavailable': '実行環境が未準備', invalid: '設定エラー', 'module-missing': 'モジュールを利用できません', draft: '下書き' },
  basic: '基本情報', connection: '接続', modelSection: 'モデルと生成', moduleSection: 'モジュール設定', pricing: '料金', advanced: '高度なプロトコル',
  name: '接続名', module: '接続の種類', url: 'API URL', key: 'API Key', model: 'モデル',
  nameHint: '英字、数字、- または _ を使い、英字か数字で始めてください。空白とシステム予約名は使えません。',
  fixedModule: '接続の種類は保存後に変更できません。別の種類を使うには新しい接続を作成してください。',
  test: '接続をテスト', testOk: 'テスト成功', testFailed: 'テスト失敗',
  keyEmpty: 'API Key を入力', fetchModels: 'モデル一覧を取得', modelList: 'モデル一覧', modelsFetched: (count: number) => `${count} 個のモデルを取得しました。`,
  reasoning: '推論の強さ', thinking: '推論を有効化', temperature: '温度', maxTokens: '最大出力 token 数', context: 'コンテキスト上限', tier: 'サービス階層', images: '画像を受け付ける',
  catalogNoWindow: 'モデル一覧にこのモデルのコンテキスト上限が記載されていません。プロバイダーのドキュメントを参照して入力してください。',
  catalogMaxOutput: (tokens: number) => `モデル一覧に記載された最大出力は ${tokens} token です。`,
  advancedHint: 'カスタム API ゲートウェイや互換サービスを使う場合にのみ調整してください。', secret: '認証情報の環境変数名',
  extraHeaders: '追加リクエストヘッダー（JSON オブジェクト）', extraBody: '追加リクエストボディ（JSON オブジェクト）', priceRules: '料金ルール全体（JSON 配列）',
  shared: '共有設定：この接続は複数のボットで使えます。変更するとこの共有設定が変わります。異なる設定が必要な場合は新しい接続を作成してください。',
  remove: '接続を削除', duplicate: '接続を複製', cancel: '変更を破棄', save: '保存', saved: '保存しました',
  draftNote: '編集内容はこのブラウザーに一時保存され、保存時に設定へ書き込まれます。API Key は一時保存されません。',
  chooseModule: '接続の種類を選択してください。', invalidNumber: '許容範囲内の数値を入力してください。',
  required: '必須項目です。', jsonObject: '有効な JSON オブジェクトを入力してください。', jsonArray: '有効な JSON 配列を入力してください。',
  unsaved: '下書きとして保持中です。保存時に書き込まれます。',
  deleteConfirm: 'この接続と、そのディレクトリ内のすべてのファイルを削除しますか？', referenced: 'この接続は次のボットで使用中のため削除できません：', reload: '再読み込み',
};
