import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: '模型供應商', navLabel: '模型供應商', navGroup: 'Core', create: '+ 新增供應商實例', newName: '未命名實例',
  createHint: '實例 = 填一組供應商設定儲存成卡片',
  empty: '還沒有模型供應商', emptyHint: '新增一條模型連線後，Cortico 才能進行模型推理。',
  eraseConfirm: '確認刪除',
  connect: '連線', activate: '設為目前供應商', active: '目前模型', missing: '目前模型供應商不存在，設定中引用：',
  inUse: (names: string) => `其他實例使用中：${names}`, selectedBy: (names: string) => `已被 ${names} 選用（未執行）`,
  readiness: { ready: '可連線', 'needs-setup': '需要完善設定', 'runtime-unavailable': '執行環境未就緒', invalid: '設定錯誤', 'module-missing': '模組無法使用', draft: '草稿' },
  basic: '基本資訊', connection: '連線', modelSection: '模型與生成', moduleSection: '模組設定', pricing: '成本與計價', advanced: '進階協定',
  name: '供應商名稱', module: '供應商類型', url: 'API 位址', key: 'API Key', model: '模型',
  nameHint: '英文字母、數字、- 或 _，以字母或數字開頭，不允許空格或系統保留名稱。',
  fixedModule: '供應商類型儲存後不可更改。使用其他類型需新增供應商。',
  test: '測試連線', testOk: '測試成功', testFailed: '測試失敗',
  keyEmpty: '輸入 API Key', fetchModels: '取得模型清單', modelList: '模型清單', modelsFetched: (count: number) => `取得 ${count} 個模型。`,
  reasoning: '推理強度', thinking: '開啟推理', temperature: '溫度', maxTokens: '最大輸出 token', context: '上下文上限', tier: '服務檔位', images: '接受圖片',
  catalogNoWindow: '目錄沒有給出這個模型的上下文上限；請依服務商文件手動填寫。',
  catalogMaxOutput: (tokens: number) => `目錄給出的最大輸出為 ${tokens} token。`,
  advancedHint: '僅在使用自訂 API 閘道或相容服務時調整。', secret: '金鑰環境變數名稱',
  extraHeaders: '附加請求標頭（JSON object）', extraBody: '附加請求內容（JSON object）', priceRules: '完整計價規則（JSON array）',
  shared: '共享設定：此供應商可被多個 Bot 使用。修改會改變這份共享設定；若需要不同參數，建議新增一個供應商。',
  remove: '刪除供應商', duplicate: '複製供應商', cancel: '放棄變更', save: '儲存', saved: '已儲存',
  draftNote: '變更暫存在此瀏覽器，儲存後才寫入設定。API Key 不進暫存。',
  chooseModule: '請選擇供應商類型。', invalidNumber: '請輸入有效範圍內的數值。',
  required: '此項必填。', jsonObject: '請輸入有效的 JSON 物件。', jsonArray: '請輸入有效的 JSON 陣列。',
  unsaved: '已暫存；儲存後寫入設定。',
  deleteConfirm: '刪除供應商及其目錄中的全部檔案？', referenced: '此供應商正在被以下 Bot 使用，不能刪除：', reload: '重新載入',
};
