import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  pageTitle: 'Connexions de modèles', navLabel: 'Connexions de modèles', navGroup: 'Core', create: '+ Nouvelle instance de connexion', newName: 'Instance sans nom',
  createHint: 'Une instance est un ensemble de réglages de fournisseur enregistré sous forme de carte.',
  empty: 'Aucune connexion de modèle', emptyHint: "Ajoutez une connexion de modèle pour activer l'inférence.",
  eraseConfirm: 'Confirmer la suppression',
  connect: 'Connecter', activate: 'Définir comme connexion actuelle', active: 'Modèle actuel', missing: 'Connexion de modèle actuelle introuvable : ',
  inUse: (names: string) => `Utilisée par : ${names}`, selectedBy: (names: string) => `Sélectionnée par ${names} (non lancé)`,
  names: (list: string[]) => list.join(', '),
  readiness: { ready: 'Prête à connecter', 'needs-setup': 'Configuration requise', 'runtime-unavailable': "Environnement d'exécution indisponible", invalid: 'Configuration invalide', 'module-missing': 'Module indisponible', draft: 'Brouillon' },
  basic: 'Informations de base', connection: 'Connexion', modelSection: 'Modèle et génération', moduleSection: 'Réglages du module', pricing: 'Tarification', advanced: 'Protocole avancé',
  name: 'Nom de la connexion', module: 'Type de connexion', url: "URL de l'API", key: 'API Key', model: 'Modèle',
  nameHint: "Lettres anglaises, chiffres, - ou _ ; commence par une lettre ou un chiffre. Pas d'espaces ni de noms système réservés.",
  fixedModule: "Le type de connexion ne peut plus changer après l'enregistrement. Créez une connexion pour utiliser un autre type.",
  test: 'Tester la connexion', testOk: 'Test réussi', testFailed: 'Échec du test',
  keyEmpty: "Saisissez l'API Key", fetchModels: 'Récupérer la liste des modèles', modelList: 'Liste des modèles', modelsFetched: (count: number) => `${count} modèle${count > 1 ? 's' : ''} récupéré${count > 1 ? 's' : ''}.`,
  reasoning: 'Effort de raisonnement', thinking: 'Activer le raisonnement', temperature: 'Température', maxTokens: 'Tokens de sortie max', context: 'Limite de contexte', tier: 'Niveau de service', images: 'Accepter les images',
  catalogNoWindow: "La liste des modèles n'indique pas de fenêtre de contexte pour ce modèle ; renseignez-la d'après la documentation du fournisseur.",
  catalogMaxOutput: (tokens: number) => `La liste des modèles indique une sortie maximale de ${tokens} tokens.`,
  advancedHint: "À ajuster uniquement pour des passerelles d'API personnalisées ou des services compatibles.", secret: "Variable d'environnement de l'identifiant",
  extraHeaders: 'En-têtes supplémentaires (objet JSON)', extraBody: 'Corps de requête supplémentaire (objet JSON)', priceRules: 'Règles de tarification complètes (tableau JSON)',
  shared: 'Configuration partagée : plusieurs bots peuvent utiliser cette connexion. Les modifications mettent à jour cette configuration partagée ; créez une autre connexion si vous avez besoin de réglages différents.',
  remove: 'Supprimer la connexion', duplicate: 'Dupliquer la connexion', cancel: 'Annuler les modifications', save: 'Enregistrer', saved: 'Enregistré',
  draftNote: "Les modifications sont conservées dans ce navigateur et écrites dans la configuration à l'enregistrement. Les API Keys ne sont jamais conservées.",
  chooseModule: 'Choisissez un type de connexion.', invalidNumber: 'Saisissez un nombre dans la plage autorisée.',
  contextAboveOutput: 'La limite de contexte doit être supérieure aux tokens de sortie max.',
  required: 'Obligatoire.', jsonObject: 'Saisissez un objet JSON valide.', jsonArray: 'Saisissez un tableau JSON valide.',
  unsaved: "Conservé comme brouillon ; écrit à l'enregistrement.",
  deleteConfirm: 'Supprimer cette connexion et tous les fichiers de son répertoire ?', referenced: 'Cette connexion est utilisée par ces bots et ne peut pas être supprimée : ', reload: 'Recharger',
};
