import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ 라이트',
  modeDark: '◐ 다크',
  modeSystem: '◒ 시스템 설정',
  appearanceLight: '라이트',
  appearanceDark: '다크',
  groupPaper: '배경 계층',
  groupInk: '텍스트와 테두리',
  groupState: '상호작용과 상태',
  groupTimeline: '터미널 타임라인',
  groupChart: '차트 계열',
  token: {
    paper: '페이지 배경',
    'paper-2': '사이드바 배경',
    sheet: '기본 카드 배경',
    'sheet-2': '보조 카드 배경',
    'sheet-3': '낮춘 바탕',
    ink: '기본 텍스트',
    'ink-soft': '보조 텍스트',
    'ink-dim': '흐린 텍스트',
    line: '가는 테두리',
    'line-2': '일반 테두리',
    'line-strong': '강조 테두리',
    accent: '기본 강조색',
    'accent-2': '보조 강조색',
    'on-accent': '강조색 위 텍스트',
    ok: '성공 / 온라인',
    warn: '알림 / 시스템',
    danger: '위험 / 실패',
    'ink-blue': '에이전트 표시',
    violet: '추론 표시',
    'agent-surface': '에이전트 카드 바탕',
    'world-bg': 'World 이벤트 바탕',
    'world-ink': 'World 이벤트 텍스트',
    'bubble-bg': '보낸 말풍선 바탕',
    'bubble-ink': '보낸 말풍선 텍스트',
    'tool-result': '도구 결과 텍스트',
    'chart-hit': '캐시 적중',
    'chart-miss': '캐시되지 않은 입력',
    'chart-output': '모델 출력',
    'chart-1': '계열 1',
    'chart-2': '계열 2',
    'chart-3': '계열 3',
    'chart-4': '계열 4',
    'chart-5': '계열 5',
    'chart-6': '계열 6',
    'chart-7': '계열 7',
    'chart-8': '계열 8',
  },
  schemeMint: '코텍스 민트',
  schemeMintNote: '로고의 민트색과 같은 계열의 녹색 단계, 중성 회색 배경',
  schemeNavigator: '미래 항해사',
  schemeNavigatorNote: '네이비, 하늘색, 흰색, 연분홍',
  schemeCrabDaisy: '게와 데이지',
  schemeCrabDaisyNote: '테라코타, 더스티 로즈, Claude 웹 회색 계열',
  customScheme: '사용자 지정 구성표',
  customNote: '사용자 지정 색 구성표',
  copyOf: (name: string) => `${name} 사본`,
};
