import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Hell',
  modeDark: '◐ Dunkel',
  modeSystem: '◒ Systemeinstellung',
  appearanceLight: 'Hell',
  appearanceDark: 'Dunkel',
  groupPaper: 'Hintergrundebenen',
  groupInk: 'Text und Rahmen',
  groupState: 'Interaktion und Zustand',
  groupTimeline: 'Terminal-Zeitleiste',
  groupChart: 'Diagrammreihen',
  token: {
    paper: 'Seitenhintergrund',
    'paper-2': 'Seitenleistenhintergrund',
    sheet: 'Hauptkarte',
    'sheet-2': 'Nebenkarte',
    'sheet-3': 'Vertiefter Grund',
    ink: 'Haupttext',
    'ink-soft': 'Sekundärtext',
    'ink-dim': 'Gedämpfter Text',
    line: 'Haarlinie',
    'line-2': 'Normaler Rahmen',
    'line-strong': 'Starker Rahmen',
    accent: 'Hauptakzent',
    'accent-2': 'Nebenakzent',
    'on-accent': 'Text auf Akzent',
    ok: 'Erfolg / online',
    warn: 'Hinweis / System',
    danger: 'Gefahr / Fehler',
    'ink-blue': 'Agent-Markierung',
    violet: 'Denkprozess-Markierung',
    'agent-surface': 'Agent-Kartengrund',
    'world-bg': 'World-Ereignisgrund',
    'world-ink': 'World-Ereignistext',
    'bubble-bg': 'Grund gesendeter Blasen',
    'bubble-ink': 'Text gesendeter Blasen',
    'tool-result': 'Tool-Ergebnistext',
    'chart-hit': 'Cache-Treffer',
    'chart-miss': 'Nicht gecachte Eingabe',
    'chart-output': 'Modellausgabe',
    'chart-1': 'Reihe 1',
    'chart-2': 'Reihe 2',
    'chart-3': 'Reihe 3',
    'chart-4': 'Reihe 4',
    'chart-5': 'Reihe 5',
    'chart-6': 'Reihe 6',
    'chart-7': 'Reihe 7',
    'chart-8': 'Reihe 8',
  },
  schemeMint: 'Cortex-Minze',
  schemeMintNote: 'Logo-Mint und Grüntöne auf neutralem Grau',
  schemeNavigator: 'Zukunftsnavigator',
  schemeNavigatorNote: 'Marineblau, Himmelblau, Weiß und Zartrosa',
  schemeCrabDaisy: 'Krabbe & Gänseblümchen',
  schemeCrabDaisyNote: 'Terrakotta und Altrosa auf Claude-Web-Grautönen',
  customScheme: 'Eigenes Schema',
  customNote: 'Eigene Palette',
  copyOf: (name: string) => `${name} Kopie`,
};
