import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ ライト',
  modeDark: '◐ ダーク',
  modeSystem: '◒ システムに合わせる',
  appearanceLight: 'ライト',
  appearanceDark: 'ダーク',
  groupPaper: '背景の階層',
  groupInk: '文字と境界線',
  groupState: '操作と状態',
  groupTimeline: 'ターミナルのタイムライン',
  groupChart: 'グラフの系列',
  token: {
    paper: 'ページの背景',
    'paper-2': 'サイドバーの背景',
    sheet: 'メインカードの背景',
    'sheet-2': 'サブカードの背景',
    'sheet-3': '沈んだ下地',
    ink: '主要な文字',
    'ink-soft': '補助的な文字',
    'ink-dim': '控えめな文字',
    line: '細い境界線',
    'line-2': '通常の境界線',
    'line-strong': '強調の境界線',
    accent: 'メインのアクセント',
    'accent-2': 'サブのアクセント',
    'on-accent': 'アクセント上の文字',
    ok: '成功 / オンライン',
    warn: '注意 / システム',
    danger: '危険 / 失敗',
    'ink-blue': 'エージェントのマーカー',
    violet: '思考のマーカー',
    'agent-surface': 'エージェントカードの下地',
    'world-bg': 'World イベントの下地',
    'world-ink': 'World イベントの文字',
    'bubble-bg': '送信バブルの下地',
    'bubble-ink': '送信バブルの文字',
    'tool-result': 'ツール結果の文字',
    'chart-hit': 'キャッシュヒット',
    'chart-miss': 'キャッシュ外の入力',
    'chart-output': 'モデル出力',
    'chart-1': '系列 1',
    'chart-2': '系列 2',
    'chart-3': '系列 3',
    'chart-4': '系列 4',
    'chart-5': '系列 5',
    'chart-6': '系列 6',
    'chart-7': '系列 7',
    'chart-8': '系列 8',
  },
  schemeMint: 'コーテックス・ミント',
  schemeMintNote: 'ロゴのミントグリーンと同系色の階調、ニュートラルグレーの背景',
  schemeNavigator: '未来ナビゲーター',
  schemeNavigatorNote: 'ネイビー、スカイブルー、白、淡いピンク',
  schemeCrabDaisy: 'カニとデイジー',
  schemeCrabDaisyNote: 'テラコッタ、くすんだローズ、Claude Web のグレー階調',
  customScheme: 'カスタム配色',
  customNote: 'カスタム配色',
  copyOf: (name: string) => `${name} のコピー`,
};
