import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Chiaro',
  modeDark: '◐ Scuro',
  modeSystem: '◒ Sistema',
  appearanceLight: 'Chiaro',
  appearanceDark: 'Scuro',
  groupPaper: 'Livelli di sfondo',
  groupInk: 'Testo e bordi',
  groupState: 'Interazione e stato',
  groupTimeline: 'Cronologia del terminale',
  groupChart: 'Serie del grafico',
  token: {
    paper: 'Sfondo della pagina',
    'paper-2': 'Sfondo della barra laterale',
    sheet: 'Scheda principale',
    'sheet-2': 'Scheda secondaria',
    'sheet-3': 'Fondo incassato',
    ink: 'Testo principale',
    'ink-soft': 'Testo secondario',
    'ink-dim': 'Testo attenuato',
    line: 'Bordo sottile',
    'line-2': 'Bordo normale',
    'line-strong': 'Bordo marcato',
    accent: 'Accento principale',
    'accent-2': 'Accento secondario',
    'on-accent': "Testo sull'accento",
    ok: 'Successo / online',
    warn: 'Avviso / sistema',
    danger: 'Pericolo / errore',
    'ink-blue': "Marcatore dell'agente",
    violet: 'Marcatore del ragionamento',
    'agent-surface': "Fondo della scheda dell'agente",
    'world-bg': 'Fondo degli eventi World',
    'world-ink': 'Testo degli eventi World',
    'bubble-bg': 'Fondo dei fumetti inviati',
    'bubble-ink': 'Testo dei fumetti inviati',
    'tool-result': 'Testo dei risultati degli strumenti',
    'chart-hit': 'Hit della cache',
    'chart-miss': 'Ingresso non in cache',
    'chart-output': 'Uscita del modello',
    'chart-1': 'Serie 1',
    'chart-2': 'Serie 2',
    'chart-3': 'Serie 3',
    'chart-4': 'Serie 4',
    'chart-5': 'Serie 5',
    'chart-6': 'Serie 6',
    'chart-7': 'Serie 7',
    'chart-8': 'Serie 8',
  },
  schemeMint: 'Menta Cortex',
  schemeMintNote: 'Menta del logo e verdi tono su tono su grigio neutro',
  schemeNavigator: 'Navigatore del futuro',
  schemeNavigatorNote: 'Blu navy, azzurro, bianco e rosa cipria',
  schemeCrabDaisy: 'Granchio e margherita',
  schemeCrabDaisyNote: 'Terracotta e rosa antico sui grigi del web di Claude',
  customScheme: 'Schema personalizzato',
  customNote: 'Tavolozza personalizzata',
  copyOf: (name: string) => `${name} copia`,
};
