import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Claro',
  modeDark: '◐ Oscuro',
  modeSystem: '◒ Sistema',
  appearanceLight: 'Claro',
  appearanceDark: 'Oscuro',
  groupPaper: 'Capas de fondo',
  groupInk: 'Texto y bordes',
  groupState: 'Interacción y estado',
  groupTimeline: 'Línea de tiempo de la terminal',
  groupChart: 'Series de gráficos',
  token: {
    paper: 'Fondo de página',
    'paper-2': 'Fondo de la barra lateral',
    sheet: 'Tarjeta principal',
    'sheet-2': 'Tarjeta secundaria',
    'sheet-3': 'Fondo hundido',
    ink: 'Texto principal',
    'ink-soft': 'Texto secundario',
    'ink-dim': 'Texto atenuado',
    line: 'Borde fino',
    'line-2': 'Borde normal',
    'line-strong': 'Borde marcado',
    accent: 'Acento principal',
    'accent-2': 'Acento secundario',
    'on-accent': 'Texto sobre acento',
    ok: 'Éxito / en línea',
    warn: 'Aviso / sistema',
    danger: 'Peligro / fallo',
    'ink-blue': 'Marcador del agente',
    violet: 'Marcador de razonamiento',
    'agent-surface': 'Fondo de tarjeta del agente',
    'world-bg': 'Fondo de eventos del World',
    'world-ink': 'Texto de eventos del World',
    'bubble-bg': 'Fondo de burbuja enviada',
    'bubble-ink': 'Texto de burbuja enviada',
    'tool-result': 'Texto de resultado de herramienta',
    'chart-hit': 'Acierto de caché',
    'chart-miss': 'Entrada sin caché',
    'chart-output': 'Salida del modelo',
    'chart-1': 'Serie 1',
    'chart-2': 'Serie 2',
    'chart-3': 'Serie 3',
    'chart-4': 'Serie 4',
    'chart-5': 'Serie 5',
    'chart-6': 'Serie 6',
    'chart-7': 'Serie 7',
    'chart-8': 'Serie 8',
  },
  schemeMint: 'Menta cortical',
  schemeMintNote: 'El verde menta del logo y verdes de la misma gama sobre gris neutro',
  schemeNavigator: 'Navegante del futuro',
  schemeNavigatorNote: 'Azul marino, celeste, blanco y rosa pálido',
  schemeCrabDaisy: 'Cangrejo y margarita',
  schemeCrabDaisyNote: 'Terracota y rosa empolvado sobre los grises de la web de Claude',
  customScheme: 'Esquema personalizado',
  customNote: 'Paleta personalizada',
  copyOf: (name: string) => `${name} copia`,
};
