import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Clair',
  modeDark: '◐ Sombre',
  modeSystem: '◒ Système',
  appearanceLight: 'Clair',
  appearanceDark: 'Sombre',
  groupPaper: "Couches d'arrière-plan",
  groupInk: 'Texte et bordures',
  groupState: 'Interaction et état',
  groupTimeline: 'Chronologie du terminal',
  groupChart: 'Séries de graphiques',
  token: {
    paper: 'Fond de page',
    'paper-2': 'Fond de la barre latérale',
    sheet: 'Carte principale',
    'sheet-2': 'Carte secondaire',
    'sheet-3': 'Fond en retrait',
    ink: 'Texte principal',
    'ink-soft': 'Texte secondaire',
    'ink-dim': 'Texte atténué',
    line: 'Bordure fine',
    'line-2': 'Bordure normale',
    'line-strong': 'Bordure marquée',
    accent: 'Accent principal',
    'accent-2': 'Accent secondaire',
    'on-accent': "Texte sur l'accent",
    ok: 'Succès / en ligne',
    warn: 'Avis / système',
    danger: 'Danger / échec',
    'ink-blue': "Marqueur de l'agent",
    violet: 'Marqueur de raisonnement',
    'agent-surface': "Fond des cartes de l'agent",
    'world-bg': 'Fond des événements World',
    'world-ink': 'Texte des événements World',
    'bubble-bg': 'Fond des bulles envoyées',
    'bubble-ink': 'Texte des bulles envoyées',
    'tool-result': "Texte des résultats d'outils",
    'chart-hit': 'Succès de cache',
    'chart-miss': 'Entrée hors cache',
    'chart-output': 'Sortie du modèle',
    'chart-1': 'Série 1',
    'chart-2': 'Série 2',
    'chart-3': 'Série 3',
    'chart-4': 'Série 4',
    'chart-5': 'Série 5',
    'chart-6': 'Série 6',
    'chart-7': 'Série 7',
    'chart-8': 'Série 8',
  },
  schemeMint: 'Menthe Cortex',
  schemeMintNote: 'Menthe du logo et verts en camaïeu sur gris neutre',
  schemeNavigator: 'Navigateur du futur',
  schemeNavigatorNote: 'Bleu marine, bleu ciel, blanc et rose poudré',
  schemeCrabDaisy: 'Crabe et marguerite',
  schemeCrabDaisyNote: 'Terre cuite et vieux rose sur les gris du web Claude',
  customScheme: 'Schéma personnalisé',
  customNote: 'Palette personnalisée',
  copyOf: (name: string) => `${name} copie`,
};
