import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ 淺色',
  modeDark: '◐ 黑夜',
  modeSystem: '◒ 跟隨系統',
  appearanceLight: '淺色',
  appearanceDark: '黑夜',
  groupPaper: '背景層級',
  groupInk: '文字與邊界',
  groupState: '互動與狀態',
  groupTimeline: '終端時間軸',
  groupChart: '圖表系列',
  token: {
    paper: '頁面背景',
    'paper-2': '側欄背景',
    sheet: '主卡片背景',
    'sheet-2': '次級卡片背景',
    'sheet-3': '壓低底色',
    ink: '主要文字',
    'ink-soft': '次級文字',
    'ink-dim': '弱化文字',
    line: '細邊界',
    'line-2': '一般邊界',
    'line-strong': '強調邊界',
    accent: '主強調',
    'accent-2': '次強調',
    'on-accent': '強調色上文字',
    ok: '成功 / 線上',
    warn: '提醒 / 系統',
    danger: '危險 / 失敗',
    'ink-blue': 'Agent 標記',
    violet: '思考標記',
    'agent-surface': 'Agent 卡片底色',
    'world-bg': 'World 事件底色',
    'world-ink': 'World 事件文字',
    'bubble-bg': '傳送氣泡底色',
    'bubble-ink': '傳送氣泡文字',
    'tool-result': '工具結果文字',
    'chart-hit': '快取命中',
    'chart-miss': '未命中輸入',
    'chart-output': '模型輸出',
    'chart-1': '系列 1',
    'chart-2': '系列 2',
    'chart-3': '系列 3',
    'chart-4': '系列 4',
    'chart-5': '系列 5',
    'chart-6': '系列 6',
    'chart-7': '系列 7',
    'chart-8': '系列 8',
  },
  schemeMint: '腦皮質薄荷',
  schemeMintNote: 'Logo 的薄荷綠、同色系層次與中性灰背景',
  schemeNavigator: '未來領航員',
  schemeNavigatorNote: '海軍藍、天藍、白與淡粉',
  schemeCrabDaisy: '螃蟹和雛菊',
  schemeCrabDaisyNote: '赤陶、灰玫瑰與 Claude 網頁灰階',
  customScheme: '自訂方案',
  customNote: '自訂配色',
  copyOf: (name: string) => `${name} 副本`,
};
