import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Claro',
  modeDark: '◐ Escuro',
  modeSystem: '◒ Sistema',
  appearanceLight: 'Claro',
  appearanceDark: 'Escuro',
  groupPaper: 'Camadas de fundo',
  groupInk: 'Texto e bordas',
  groupState: 'Interação e estado',
  groupTimeline: 'Linha do tempo do terminal',
  groupChart: 'Séries de gráficos',
  token: {
    paper: 'Fundo da página',
    'paper-2': 'Fundo da barra lateral',
    sheet: 'Cartão principal',
    'sheet-2': 'Cartão secundário',
    'sheet-3': 'Fundo rebaixado',
    ink: 'Texto principal',
    'ink-soft': 'Texto secundário',
    'ink-dim': 'Texto atenuado',
    line: 'Borda fina',
    'line-2': 'Borda normal',
    'line-strong': 'Borda forte',
    accent: 'Destaque principal',
    'accent-2': 'Destaque secundário',
    'on-accent': 'Texto sobre destaque',
    ok: 'Sucesso / on-line',
    warn: 'Aviso / sistema',
    danger: 'Perigo / falha',
    'ink-blue': 'Marcador do agente',
    violet: 'Marcador de raciocínio',
    'agent-surface': 'Fundo do cartão do agente',
    'world-bg': 'Fundo de eventos do World',
    'world-ink': 'Texto de eventos do World',
    'bubble-bg': 'Fundo do balão enviado',
    'bubble-ink': 'Texto do balão enviado',
    'tool-result': 'Texto do resultado de ferramenta',
    'chart-hit': 'Acerto de cache',
    'chart-miss': 'Entrada sem cache',
    'chart-output': 'Saída do modelo',
    'chart-1': 'Série 1',
    'chart-2': 'Série 2',
    'chart-3': 'Série 3',
    'chart-4': 'Série 4',
    'chart-5': 'Série 5',
    'chart-6': 'Série 6',
    'chart-7': 'Série 7',
    'chart-8': 'Série 8',
  },
  schemeMint: 'Menta cortical',
  schemeMintNote: 'O verde-menta do logo e verdes da mesma família sobre cinza neutro',
  schemeNavigator: 'Navegador do futuro',
  schemeNavigatorNote: 'Azul-marinho, azul-celeste, branco e rosa-claro',
  schemeCrabDaisy: 'Caranguejo e margarida',
  schemeCrabDaisyNote: 'Terracota e rosa antigo sobre os cinzas da web do Claude',
  customScheme: 'Esquema personalizado',
  customNote: 'Paleta personalizada',
  copyOf: (name: string) => `${name} cópia`,
};
