import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  modeLight: '☀ Светлая',
  modeDark: '◐ Тёмная',
  modeSystem: '◒ Как в системе',
  appearanceLight: 'Светлая',
  appearanceDark: 'Тёмная',
  groupPaper: 'Слои фона',
  groupInk: 'Текст и границы',
  groupState: 'Взаимодействие и состояние',
  groupTimeline: 'Лента терминала',
  groupChart: 'Серии диаграмм',
  token: {
    paper: 'Фон страницы',
    'paper-2': 'Фон боковой панели',
    sheet: 'Основная карточка',
    'sheet-2': 'Вторичная карточка',
    'sheet-3': 'Утопленный фон',
    ink: 'Основной текст',
    'ink-soft': 'Вторичный текст',
    'ink-dim': 'Приглушённый текст',
    line: 'Тонкая граница',
    'line-2': 'Обычная граница',
    'line-strong': 'Выделенная граница',
    accent: 'Основной акцент',
    'accent-2': 'Вторичный акцент',
    'on-accent': 'Текст на акценте',
    ok: 'Успех / в сети',
    warn: 'Уведомление / система',
    danger: 'Опасность / сбой',
    'ink-blue': 'Метка агента',
    violet: 'Метка рассуждения',
    'agent-surface': 'Фон карточки агента',
    'world-bg': 'Фон событий World',
    'world-ink': 'Текст событий World',
    'bubble-bg': 'Фон отправленного сообщения',
    'bubble-ink': 'Текст отправленного сообщения',
    'tool-result': 'Текст результата инструмента',
    'chart-hit': 'Попадание в кэш',
    'chart-miss': 'Вход без кэша',
    'chart-output': 'Вывод модели',
    'chart-1': 'Серия 1',
    'chart-2': 'Серия 2',
    'chart-3': 'Серия 3',
    'chart-4': 'Серия 4',
    'chart-5': 'Серия 5',
    'chart-6': 'Серия 6',
    'chart-7': 'Серия 7',
    'chart-8': 'Серия 8',
  },
  schemeMint: 'Кортикальная мята',
  schemeMintNote: 'Мятный цвет логотипа и родственные оттенки зелёного на нейтральном сером',
  schemeNavigator: 'Штурман будущего',
  schemeNavigatorNote: 'Тёмно-синий, небесно-голубой, белый и нежно-розовый',
  schemeCrabDaisy: 'Краб и ромашка',
  schemeCrabDaisyNote: 'Терракота и пыльная роза на серых тонах веб-версии Claude',
  customScheme: 'Пользовательская схема',
  customNote: 'Пользовательская палитра',
  copyOf: (name: string) => `${name} (копия)`,
};
