import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Disattivato',
  tierOn: 'Attivato',
  releaseRequired: 'Il tag della release non può essere vuoto',
  backendUnsupported: (backend: string) => `Nessuna build ufficiale del backend ${backend} per questa piattaforma`,
  runtimeDirString: 'La directory del runtime personale deve essere una stringa',
  positiveInteger: (field: string) => `${field} deve essere un intero positivo`,
  nonNegativeInteger: (field: string) => `${field} deve essere un intero non negativo`,
  extraArgsString: 'Gli argomenti di avvio aggiuntivi devono essere una stringa',
  autoStartBoolean: "L'avvio automatico deve essere un booleano",
  notManaged: 'Questo endpoint non è gestito',
  runtimeNotInstalled: 'Il runtime non è ancora installato',
  runtimeUnsupported: 'Nessuna build ufficiale per questo backend su questa piattaforma; imposta una directory del runtime personale',
  endpointPanel: 'Indirizzo del server',
  endpointPanelDescription: "L'indirizzo su cui ascolta llama-server; un processo gestito si avvia su di esso.",
  runtimePanel: 'Ambiente di runtime',
  runtimePanelDescription: 'Scarica e installa i binari ufficiali di llama.cpp; avvia e arresta il processo llama-server.',
  modelsPanel: 'Modelli',
  modelsPanelDescription: 'Modelli noti a llama-server: in cache, nella directory locale e in download.',
  unknownPanel: 'Pannello sconosciuto',
  unknownMethod: 'Azione sconosciuta',
  instanceNameRequired: "Serve un nome per l'endpoint",
  modelIdRequired: "Serve l'ID del modello",
  queryRequired: 'Serve un termine di ricerca',
  limitRequired: 'Serve un numero di risultati',
  repoRequired: 'Serve un repository',
  bodyRequired: 'Serve un corpo della richiesta',
  serverUnreachable: "llama-server non è raggiungibile; controlla l'URL dell'endpoint e lo stato del server.",
  externalServer: "Sull'endpoint è già in esecuzione un server (avviato esternamente); nessuna presa in carico",
  starting: 'Avvio di llama-server',
  spawnFailed: (message: string) => `Avvio del processo non riuscito: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows non è riuscito ad avviare ${exe} (UNKNOWN). ` +
    "Se l'avvio non riesce, cerca un blocco registrato in Sicurezza di Windows. Se il blocco è confermato, usa un runtime che soddisfi i requisiti di attendibilità.",
  exited: (code: number | null, tail: string) => `Processo terminato code=${code}; coda di stderr: ${tail}`,
  badBaseUrl: (baseUrl: string) => `Impossibile ricavare host/port da baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `Nessun ${exe} nella directory del runtime`,
  healthTimeout: "Il controllo /health è scaduto; controlla l'URL dell'endpoint e lo stato del server.",
  downloadFailed: (file: string, message: string) => `Download di ${file} non riuscito: ${message}`,
  extractFailed: (file: string, message: string) => `Estrazione di ${file} non riuscita: ${message}`,
  installBusy: "È in corso l'installazione di un altro runtime",
  description: 'Connetti o gestisci modelli llama.cpp locali.',
  saveBeforeRuntime: 'Salva la configurazione prima delle operazioni sul runtime.',
  saveBeforeModels: 'Salva la configurazione prima delle operazioni sui modelli.',
};
export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'Ambiente di runtime',
  modelsTitle: 'Modelli',
  managedOff: 'Questo endpoint è gestito esternamente. Attiva la gestione per far gestire a Cortico il suo processo llama-server.',
  enable: 'Attiva gestione',
  disable: 'Disattiva gestione',
  release: 'Versione',
  backend: 'Backend',
  runtimeDir: 'Directory del runtime',
  ownRuntime: 'personale',
  installStatus: 'Installazione',
  installed: 'installato',
  absent: 'non installato',
  downloading: 'download in corso',
  extracting: 'estrazione in corso',
  install: 'Scarica e installa',
  reinstall: 'Reinstalla',
  sacWarning:
    'Il Controllo intelligente delle app di Windows è in modalità imposta. ' +
    "Se l'avvio non riesce, cerca un blocco registrato in Sicurezza di Windows. Se il blocco è confermato, usa un runtime che soddisfi i requisiti di attendibilità.",
  server: 'Processo server',
  serverSection: 'Processo server ed endpoint',
  serverSectionDesc: 'Processo locale llama-server e stato di ascolto.',
  runtimeSection: 'Ambiente di runtime binario',
  runtimeSectionDesc: 'Binari ufficiali di llama.cpp e dipendenze.',
  releaseHint: "Tag della release upstream, ad es. b10930; cambiarlo scarica un'altra build.",
  backendHint: 'Build ufficiali per questa piattaforma; le build CUDA sono abbinate al pacchetto upstream cudart.',
  runtimeDirHint: 'Se impostata, non viene scaricato nulla: la directory contiene llama-server e le sue librerie condivise (compilazione propria, Linux CUDA, build firmate).',
  browse: 'Scegli directory',
  launchSection: 'Parametri di avvio',
  launchSectionDesc: 'Applicati al prossimo avvio di llama-server.',
  contextSize: 'Dimensione del contesto (-c)',
  nGpuLayers: 'Layer GPU (-ngl)',
  parallel: 'Slot paralleli (--parallel)',
  extraArgs: 'Argomenti di avvio aggiuntivi',
  extraArgsHint: 'Divisi sugli spazi e aggiunti alla riga di comando di llama-server.',
  autoStart: 'Avvia il server con il bot',
  copyEndpoint: 'Copia endpoint',
  installRequired: 'Installa il binario del runtime prima di avviare il server',
  status: 'Stato',
  endpoint: 'Endpoint',
  reachable: 'raggiungibile',
  unreachable: 'non raggiungibile',
  pid: 'PID del processo',
  pendingNote: 'Parametri di avvio modificati; arresta e riavvia per applicarli.',
  start: 'Avvia',
  stop: 'Arresta',
  refresh: 'Aggiorna',
  phase: { stopped: 'arrestato', starting: 'in avvio', running: 'in esecuzione', error: 'errore' } as Record<string, string>,
  modelId: 'ID modello',
  modelStatus: 'Stato',
  modality: 'Ingresso',
  path: 'File',
  actions: 'Azioni',
  load: 'Carica',
  unload: 'Rilascia',
  cancel: 'Annulla',
  reload: 'Riscansiona',
  pull: 'Scarica',
  pullPlaceholder: 'Repository HuggingFace, ad es. ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Usa',
  useTitle: 'Inserisci questo modello in «Modello e generazione»',
  search: 'Cerca',
  searchPlaceholder: 'Cerca repository GGUF su HuggingFace, ad es. qwen3',
  searchFailed: (reason: string) => `Ricerca non riuscita: ${reason}`,
  noRepos: 'Nessun repository corrispondente.',
  repo: 'Repository',
  downloads: 'Download',
  likes: 'Mi piace',
  updated: 'Aggiornato',
  showFiles: 'File',
  filesOf: (repo: string) => `File GGUF in ${repo}`,
  noFiles: 'Questo repository non contiene file GGUF.',
  file: 'File',
  size: 'Dimensione',
  tag: 'Tag',
  localDir: 'Directory GGUF locale',
  cacheDir: 'Directory della cache',
  noModels: 'Ancora nessun modello: scaricane uno qui sopra o metti file GGUF nella directory locale e riscansiona.',
  modelStatusLabel: {
    loaded: 'caricato',
    loading: 'caricamento',
    unloaded: 'non caricato',
    downloading: 'download in corso',
    sleeping: 'inattivo',
    failed: 'caricamento non riuscito',
    unknown: 'online',
  } as Record<string, string>,
  serverDown: "llama-server non è raggiungibile; controlla l'URL dell'endpoint e lo stato del server.",
};
