import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Aus',
  tierOn: 'An',
  releaseRequired: 'Das Release-Tag darf nicht leer sein',
  backendUnsupported: (backend: string) => `Kein offizieller Build des Backends ${backend} für diese Plattform`,
  runtimeDirString: 'Das eigene Laufzeitverzeichnis muss ein String sein',
  positiveInteger: (field: string) => `${field} muss eine positive ganze Zahl sein`,
  nonNegativeInteger: (field: string) => `${field} muss eine nicht negative ganze Zahl sein`,
  extraArgsString: 'Zusätzliche Startargumente müssen ein String sein',
  autoStartBoolean: 'Autostart muss ein Boolean sein',
  notManaged: 'Dieser Endpunkt wird nicht verwaltet',
  runtimeNotInstalled: 'Die Laufzeitumgebung ist noch nicht installiert',
  runtimeUnsupported: 'Kein offizieller Build für dieses Backend auf dieser Plattform; gib ein eigenes Laufzeitverzeichnis an',
  endpointPanel: 'Serveradresse',
  endpointPanelDescription: 'Die Adresse, auf der llama-server lauscht; ein verwalteter Prozess startet darauf.',
  runtimePanel: 'Laufzeitumgebung',
  runtimePanelDescription: 'Offizielle llama.cpp-Binärdateien herunterladen und installieren; den llama-server-Prozess starten und stoppen.',
  modelsPanel: 'Modelle',
  modelsPanelDescription: 'Modelle, die llama-server kennt: im Cache, im lokalen Verzeichnis und im Download.',
  unknownPanel: 'Unbekanntes Panel',
  unknownMethod: 'Unbekannte Aktion',
  instanceNameRequired: 'Ein Endpunktname ist erforderlich',
  modelIdRequired: 'Eine Modell-ID ist erforderlich',
  queryRequired: 'Ein Suchbegriff ist erforderlich',
  limitRequired: 'Eine Ergebnisanzahl ist erforderlich',
  repoRequired: 'Ein Repository ist erforderlich',
  bodyRequired: 'Ein Anfrage-Body ist erforderlich',
  serverUnreachable: 'llama-server ist nicht erreichbar; prüfe Endpunkt-URL und Serverstatus.',
  externalServer: 'Am Endpunkt läuft bereits ein Server (extern gestartet); keine Übernahme',
  starting: 'llama-server startet',
  spawnFailed: (message: string) => `Prozessstart fehlgeschlagen: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows konnte ${exe} nicht starten (UNKNOWN). ` +
    'Schlägt der Start fehl, prüfe in der Windows-Sicherheit, ob eine Blockierung protokolliert ist. Ist eine Blockierung bestätigt, nutze eine Laufzeitumgebung, die die Vertrauensanforderungen erfüllt.',
  exited: (code: number | null, tail: string) => `Prozess beendet code=${code}; stderr-Ende: ${tail}`,
  badBaseUrl: (baseUrl: string) => `host/port lässt sich nicht aus baseUrl ableiten: ${baseUrl}`,
  missingBinary: (exe: string) => `Kein ${exe} im Laufzeitverzeichnis`,
  healthTimeout: 'Zeitüberschreitung bei der /health-Prüfung; prüfe Endpunkt-URL und Serverstatus.',
  downloadFailed: (file: string, message: string) => `Download von ${file} fehlgeschlagen: ${message}`,
  extractFailed: (file: string, message: string) => `Entpacken von ${file} fehlgeschlagen: ${message}`,
  installBusy: 'Eine andere Laufzeitumgebung wird gerade installiert',
  description: 'Mit lokalen llama.cpp-Modellen verbinden oder sie verwalten.',
  saveBeforeRuntime: 'Speichere die Konfiguration vor Aktionen an der Laufzeitumgebung.',
  saveBeforeModels: 'Speichere die Konfiguration vor Aktionen an Modellen.',
};
export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'Laufzeitumgebung',
  modelsTitle: 'Modelle',
  managedOff: 'Dieser Endpunkt wird extern verwaltet. Aktiviere die Verwaltung, damit Cortico seinen llama-server-Prozess verwaltet.',
  enable: 'Verwaltung aktivieren',
  disable: 'Verwaltung deaktivieren',
  release: 'Version',
  backend: 'Backend',
  runtimeDir: 'Laufzeitverzeichnis',
  ownRuntime: 'eigene',
  installStatus: 'Installation',
  installed: 'installiert',
  absent: 'nicht installiert',
  downloading: 'wird heruntergeladen',
  extracting: 'wird entpackt',
  install: 'Herunterladen und installieren',
  reinstall: 'Neu installieren',
  sacWarning:
    'Die intelligente App-Steuerung von Windows ist im erzwungenen Modus. ' +
    'Schlägt der Start fehl, prüfe in der Windows-Sicherheit, ob eine Blockierung protokolliert ist. Ist eine Blockierung bestätigt, nutze eine Laufzeitumgebung, die die Vertrauensanforderungen erfüllt.',
  server: 'Serverprozess',
  serverSection: 'Serverprozess und Endpunkt',
  serverSectionDesc: 'Lokaler llama-server-Prozess und Listen-Status.',
  runtimeSection: 'Binäre Laufzeitumgebung',
  runtimeSectionDesc: 'Offizielle llama.cpp-Binärdateien und Abhängigkeiten.',
  releaseHint: 'Upstream-Release-Tag, etwa b10930; eine Änderung lädt einen anderen Build herunter.',
  backendHint: 'Offizielle Builds für diese Plattform; CUDA-Builds werden mit dem Upstream-Paket cudart kombiniert.',
  runtimeDirHint: 'Wenn gesetzt, wird nichts heruntergeladen: Das Verzeichnis enthält llama-server und seine gemeinsamen Bibliotheken (selbst gebaut, Linux CUDA, signierte Builds).',
  browse: 'Verzeichnis wählen',
  launchSection: 'Startparameter',
  launchSectionDesc: 'Gelten beim nächsten Start von llama-server.',
  contextSize: 'Kontextgröße (-c)',
  nGpuLayers: 'GPU-Schichten (-ngl)',
  parallel: 'Parallele Slots (--parallel)',
  extraArgs: 'Zusätzliche Startargumente',
  extraArgsHint: 'An Leerzeichen getrennt und an die llama-server-Befehlszeile angehängt.',
  autoStart: 'Server mit dem Bot starten',
  copyEndpoint: 'Endpunkt kopieren',
  installRequired: 'Installiere die Laufzeit-Binärdatei, bevor du den Server startest',
  status: 'Status',
  endpoint: 'Endpunkt',
  reachable: 'erreichbar',
  unreachable: 'nicht erreichbar',
  pid: 'Prozess-PID',
  pendingNote: 'Startparameter geändert; stoppe und starte neu, um sie anzuwenden.',
  start: 'Starten',
  stop: 'Stoppen',
  refresh: 'Aktualisieren',
  phase: { stopped: 'gestoppt', starting: 'startet', running: 'läuft', error: 'Fehler' } as Record<string, string>,
  modelId: 'Modell-ID',
  modelStatus: 'Status',
  modality: 'Eingabe',
  path: 'Datei',
  actions: 'Aktionen',
  load: 'Laden',
  unload: 'Entladen',
  cancel: 'Abbrechen',
  reload: 'Neu scannen',
  pull: 'Abrufen',
  pullPlaceholder: 'HuggingFace-Repo, z. B. ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Verwenden',
  useTitle: 'Dieses Modell in „Modell und Generierung“ eintragen',
  search: 'Suchen',
  searchPlaceholder: 'GGUF-Repositorys auf HuggingFace suchen, z. B. qwen3',
  searchFailed: (reason: string) => `Suche fehlgeschlagen: ${reason}`,
  noRepos: 'Keine passenden Repositorys.',
  repo: 'Repository',
  downloads: 'Downloads',
  likes: 'Likes',
  updated: 'Aktualisiert',
  showFiles: 'Dateien',
  filesOf: (repo: string) => `GGUF-Dateien in ${repo}`,
  noFiles: 'Dieses Repository enthält keine GGUF-Dateien.',
  file: 'Datei',
  size: 'Größe',
  tag: 'Tag',
  localDir: 'Lokales GGUF-Verzeichnis',
  cacheDir: 'Cache-Verzeichnis',
  noModels: 'Noch keine Modelle: Rufe oben eines ab oder lege GGUF-Dateien ins lokale Verzeichnis und scanne neu.',
  modelStatusLabel: {
    loaded: 'geladen',
    loading: 'lädt',
    unloaded: 'entladen',
    downloading: 'wird heruntergeladen',
    sleeping: 'ruht',
    failed: 'Laden fehlgeschlagen',
    unknown: 'online',
  } as Record<string, string>,
  serverDown: 'llama-server ist nicht erreichbar; prüfe Endpunkt-URL und Serverstatus.',
};
