import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'オフ',
  tierOn: 'オン',
  releaseRequired: 'リリースタグを空にすることはできません',
  backendUnsupported: (backend: string) => `このプラットフォーム向けのバックエンド ${backend} の公式ビルドはありません`,
  runtimeDirString: '独自ランタイムのディレクトリは文字列である必要があります',
  positiveInteger: (field: string) => `${field} は正の整数である必要があります`,
  nonNegativeInteger: (field: string) => `${field} は 0 以上の整数である必要があります`,
  extraArgsString: '追加の起動引数は文字列である必要があります',
  autoStartBoolean: '自動起動はブール値である必要があります',
  notManaged: 'このエンドポイントは管理が有効になっていません',
  runtimeNotInstalled: 'ランタイムがまだインストールされていません',
  runtimeUnsupported: 'このプラットフォームにはこのバックエンドの公式ビルドがありません。独自ランタイムのディレクトリを指定してください',
  endpointPanel: 'サーバーのアドレス',
  endpointPanelDescription: 'llama-server が待ち受けるアドレスです。管理下のプロセスはこのアドレスで起動します。',
  runtimePanel: 'ランタイム',
  runtimePanelDescription: 'llama.cpp 公式バイナリのダウンロードとインストール、llama-server プロセスの起動と停止。',
  modelsPanel: 'モデル',
  modelsPanelDescription: 'llama-server が認識しているモデル：キャッシュ内、ローカルディレクトリ内、ダウンロード中のもの。',
  unknownPanel: '不明なパネルです',
  unknownMethod: '不明な操作です',
  instanceNameRequired: 'エンドポイント名が必要です',
  modelIdRequired: 'モデル ID が必要です',
  queryRequired: '検索語が必要です',
  limitRequired: '結果の件数が必要です',
  repoRequired: 'リポジトリ名が必要です',
  bodyRequired: 'リクエストボディが必要です',
  serverUnreachable: 'llama-server に接続できません。エンドポイントのアドレスとサーバーの状態を確認してください。',
  externalServer: 'エンドポイントでは既にサーバーが動作しています（外部で起動）。引き継ぎません',
  starting: 'llama-server 起動中',
  spawnFailed: (message: string) => `プロセスを起動できませんでした：${message}`,
  spawnBlocked: (exe: string) =>
    `Windows で ${exe} を起動できませんでした（UNKNOWN）。` +
    '起動に失敗した場合は、Windows セキュリティでブロックの記録を確認してください。ブロックが確認された場合は、信頼の要件を満たすランタイムを使ってください。',
  exited: (code: number | null, tail: string) => `プロセスが終了しました code=${code}。stderr の末尾：${tail}`,
  badBaseUrl: (baseUrl: string) => `baseUrl から host/port を取得できません：${baseUrl}`,
  missingBinary: (exe: string) => `ランタイムのディレクトリに ${exe} がありません`,
  healthTimeout: '/health のチェックがタイムアウトしました。エンドポイントのアドレスとサーバーの状態を確認してください。',
  downloadFailed: (file: string, message: string) => `${file} のダウンロードに失敗しました：${message}`,
  extractFailed: (file: string, message: string) => `${file} の展開に失敗しました：${message}`,
  installBusy: '別のランタイムをインストール中です',
  description: 'ローカルの llama.cpp モデルに接続するか、管理します。',
  saveBeforeRuntime: 'ランタイムを操作する前に設定を保存してください。',
  saveBeforeModels: 'モデルを操作する前に設定を保存してください。',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'ランタイム',
  modelsTitle: 'モデル',
  managedOff: 'このエンドポイントは外部で管理されています。管理を有効にすると、Cortico が llama-server プロセスを管理します。',
  enable: '管理を有効化',
  disable: '管理を無効化',
  release: 'リリース',
  backend: 'バックエンド',
  runtimeDir: 'ランタイムのディレクトリ',
  ownRuntime: '独自',
  installStatus: 'インストール',
  installed: 'インストール済み',
  absent: '未インストール',
  downloading: 'ダウンロード中',
  extracting: '展開中',
  install: 'ダウンロードしてインストール',
  reinstall: '再インストール',
  sacWarning:
    'Windows のスマート アプリ コントロールが強制モードになっています。' +
    '起動に失敗した場合は、Windows セキュリティでブロックの記録を確認してください。ブロックが確認された場合は、信頼の要件を満たすランタイムを使ってください。',
  server: 'サーバープロセス',
  serverSection: 'サーバープロセスとエンドポイント',
  serverSectionDesc: 'llama-server のローカルプロセスと待ち受け状態。',
  runtimeSection: 'バイナリの実行環境',
  runtimeSectionDesc: 'llama.cpp 公式バイナリと依存関係の管理。',
  releaseHint: '上流のリリースタグ（例：b10930）。変更すると別のビルドをダウンロードします。',
  backendHint: 'このプラットフォーム向けの公式ビルドです。CUDA 版には上流の cudart パッケージが自動で組み合わされます。',
  runtimeDirHint: '指定するとダウンロードしません。ディレクトリには llama-server とその共有ライブラリが必要です（自前ビルド、Linux CUDA、署名済みビルド）。',
  browse: 'ディレクトリを選択',
  launchSection: '起動パラメーター',
  launchSectionDesc: '次に llama-server を起動したときに反映されます。',
  contextSize: 'コンテキスト長（-c）',
  nGpuLayers: 'GPU レイヤー数（-ngl）',
  parallel: '並列スロット数（--parallel）',
  extraArgs: '追加の起動引数',
  extraArgsHint: '空白で分割して llama-server のコマンドラインに追加します。',
  autoStart: 'ボットの起動時にサーバーも起動',
  copyEndpoint: 'エンドポイントをコピー',
  installRequired: 'サーバーを起動する前にランタイムのバイナリをダウンロードしてインストールしてください',
  status: '状態',
  endpoint: 'エンドポイント',
  reachable: '接続可能',
  unreachable: '接続不可',
  pid: 'プロセス PID',
  pendingNote: '起動パラメーターが変更されました。停止して再度起動すると反映されます。',
  start: '起動',
  stop: '停止',
  refresh: '更新',
  phase: { stopped: '停止中', starting: '起動中', running: '実行中', error: 'エラー' },
  modelId: 'モデル ID',
  modelStatus: '状態',
  modality: '入力',
  path: 'ファイル',
  actions: '操作',
  load: '読み込む',
  unload: '解放',
  cancel: 'キャンセル',
  reload: '再スキャン',
  pull: '取得',
  pullPlaceholder: 'HuggingFace のリポジトリ（例：ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF）',
  use: '使用',
  useTitle: 'このモデルを「モデルと生成」に入力',
  search: '検索',
  searchPlaceholder: 'HuggingFace の GGUF リポジトリを検索（例：qwen3）',
  searchFailed: (reason: string) => `検索に失敗しました：${reason}`,
  noRepos: '一致するリポジトリがありません。',
  repo: 'リポジトリ',
  downloads: 'ダウンロード',
  likes: 'いいね',
  updated: '更新',
  showFiles: 'ファイル',
  filesOf: (repo: string) => `${repo} の GGUF ファイル`,
  noFiles: 'このリポジトリには GGUF ファイルがありません。',
  file: 'ファイル',
  size: 'サイズ',
  tag: 'タグ',
  localDir: 'ローカルの GGUF ディレクトリ',
  cacheDir: 'キャッシュディレクトリ',
  noModels: '利用できる GGUF モデルはまだありません。上の入力欄から取得するか、.gguf ファイルをローカルディレクトリに置いて再スキャンしてください。',
  modelStatusLabel: {
    loaded: '読み込み済み',
    loading: '読み込み中',
    unloaded: '未読み込み',
    downloading: 'ダウンロード中',
    sleeping: 'スリープ中',
    failed: '読み込み失敗',
    unknown: 'オンライン',
  },
  serverDown: 'llama-server に接続できません。エンドポイントのアドレスとサーバーの状態を確認してください。',
};
