import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Desativado',
  tierOn: 'Ativado',
  releaseRequired: 'A tag de versão não pode ficar vazia',
  backendUnsupported: (backend: string) => `Não há build oficial do backend ${backend} para esta plataforma`,
  runtimeDirString: 'O diretório do ambiente de execução próprio deve ser uma string',
  positiveInteger: (field: string) => `${field} deve ser um inteiro positivo`,
  nonNegativeInteger: (field: string) => `${field} deve ser um inteiro não negativo`,
  extraArgsString: 'Os argumentos de inicialização extras devem ser uma string',
  autoStartBoolean: 'A inicialização automática deve ser um booleano',
  notManaged: 'Este endpoint não é gerenciado',
  runtimeNotInstalled: 'O ambiente de execução ainda não está instalado',
  runtimeUnsupported: 'Não há build oficial deste backend para esta plataforma; defina um diretório de ambiente de execução próprio',
  endpointPanel: 'Endereço do servidor',
  endpointPanelDescription: 'O endereço em que o llama-server escuta; um processo gerenciado é iniciado nele.',
  runtimePanel: 'Ambiente de execução',
  runtimePanelDescription: 'Baixe e instale os binários oficiais do llama.cpp; inicie e pare o processo do llama-server.',
  modelsPanel: 'Modelos',
  modelsPanelDescription: 'Modelos que o llama-server conhece: em cache, no diretório local e em download.',
  unknownPanel: 'Painel desconhecido',
  unknownMethod: 'Ação desconhecida',
  instanceNameRequired: 'É necessário um nome de endpoint',
  modelIdRequired: 'É necessário um id de modelo',
  queryRequired: 'É necessário um termo de busca',
  limitRequired: 'É necessária uma quantidade de resultados',
  repoRequired: 'É necessário um repositório',
  bodyRequired: 'É necessário um corpo de requisição',
  serverUnreachable: 'O llama-server está inacessível; verifique a URL do endpoint e o status do servidor.',
  externalServer: 'Já há um servidor em execução no endpoint (iniciado externamente); o controle não será assumido',
  starting: 'Iniciando o llama-server',
  spawnFailed: (message: string) => `Falha ao iniciar o processo: ${message}`,
  spawnBlocked: (exe: string) =>
    `O Windows não conseguiu iniciar ${exe} (UNKNOWN). ` +
    'Se a inicialização falhar, procure um registro de bloqueio na Segurança do Windows. Se o bloqueio for confirmado, use um ambiente de execução que atenda aos requisitos de confiança.',
  exited: (code: number | null, tail: string) => `O processo terminou com code=${code}; final do stderr: ${tail}`,
  badBaseUrl: (baseUrl: string) => `Não é possível obter host/port de baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `Não há ${exe} no diretório do ambiente de execução`,
  healthTimeout: 'A verificação de /health excedeu o tempo limite; verifique a URL do endpoint e o status do servidor.',
  downloadFailed: (file: string, message: string) => `Falha no download de ${file}: ${message}`,
  extractFailed: (file: string, message: string) => `Falha na extração de ${file}: ${message}`,
  installBusy: 'Outro ambiente de execução está sendo instalado',
  description: 'Conecte-se a modelos locais do llama.cpp ou gerencie-os.',
  saveBeforeRuntime: 'Salve a configuração antes de operar o ambiente de execução.',
  saveBeforeModels: 'Salve a configuração antes de operar os modelos.',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'Ambiente de execução',
  modelsTitle: 'Modelos',
  managedOff: 'Este endpoint é gerenciado externamente. Ative o gerenciamento para que o Cortico gerencie o processo do llama-server.',
  enable: 'Ativar gerenciamento',
  disable: 'Desativar gerenciamento',
  release: 'Versão',
  backend: 'Backend',
  runtimeDir: 'Diretório do ambiente de execução',
  ownRuntime: 'próprio',
  installStatus: 'Instalação',
  installed: 'instalado',
  absent: 'não instalado',
  downloading: 'baixando',
  extracting: 'extraindo',
  install: 'Baixar e instalar',
  reinstall: 'Reinstalar',
  sacWarning:
    'O Controle Inteligente de Aplicativos do Windows está no modo imposto. ' +
    'Se a inicialização falhar, procure um registro de bloqueio na Segurança do Windows. Se o bloqueio for confirmado, use um ambiente de execução que atenda aos requisitos de confiança.',
  server: 'Servidor',
  serverSection: 'Processo do servidor e endpoint',
  serverSectionDesc: 'Processo local do llama-server e status de escuta.',
  runtimeSection: 'Ambiente de execução binário',
  runtimeSectionDesc: 'Binário oficial do llama.cpp e dependências.',
  releaseHint: 'Tag de versão do upstream, como b10930; ao mudá-la, outro build é baixado.',
  backendHint: 'Builds oficiais para esta plataforma; builds CUDA vêm acompanhados do pacote cudart do upstream.',
  runtimeDirHint: 'Quando definido, nada é baixado: o diretório contém o llama-server e suas bibliotecas compartilhadas (build próprio, Linux CUDA, builds assinados).',
  browse: 'Escolher diretório',
  launchSection: 'Parâmetros de inicialização',
  launchSectionDesc: 'Aplicados na próxima inicialização do llama-server.',
  contextSize: 'Tamanho do contexto (-c)',
  nGpuLayers: 'Camadas na GPU (-ngl)',
  parallel: 'Slots paralelos (--parallel)',
  extraArgs: 'Argumentos de inicialização extras',
  extraArgsHint: 'Separados por espaços e acrescentados à linha de comando do llama-server.',
  autoStart: 'Iniciar o servidor junto com o bot',
  copyEndpoint: 'Copiar endpoint',
  installRequired: 'Instale o binário do ambiente de execução antes de iniciar o servidor',
  status: 'Status',
  endpoint: 'Endpoint',
  reachable: 'acessível',
  unreachable: 'inacessível',
  pid: 'PID do processo',
  pendingNote: 'Os parâmetros de inicialização mudaram; pare e inicie de novo para aplicá-los.',
  start: 'Iniciar',
  stop: 'Parar',
  refresh: 'Atualizar',
  phase: { stopped: 'parado', starting: 'iniciando', running: 'em execução', error: 'erro' },
  modelId: 'ID do modelo',
  modelStatus: 'Status',
  modality: 'Entrada',
  path: 'Arquivo',
  actions: 'Ações',
  load: 'Carregar',
  unload: 'Descarregar',
  cancel: 'Cancelar',
  reload: 'Reescanear',
  pull: 'Baixar',
  pullPlaceholder: 'Repositório do HuggingFace, ex.: ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Usar',
  useTitle: 'Colocar este modelo na seção Modelo e geração',
  search: 'Buscar',
  searchPlaceholder: 'Busque repositórios GGUF no HuggingFace, ex.: qwen3',
  searchFailed: (reason: string) => `A busca falhou: ${reason}`,
  noRepos: 'Nenhum repositório correspondente.',
  repo: 'Repositório',
  downloads: 'Downloads',
  likes: 'Curtidas',
  updated: 'Atualizado',
  showFiles: 'Arquivos',
  filesOf: (repo: string) => `Arquivos GGUF em ${repo}`,
  noFiles: 'Este repositório não tem arquivos GGUF.',
  file: 'Arquivo',
  size: 'Tamanho',
  tag: 'Etiqueta',
  localDir: 'Diretório GGUF local',
  cacheDir: 'Diretório de cache',
  noModels: 'Ainda não há modelos: baixe um acima ou coloque arquivos GGUF no diretório local e reescaneie.',
  modelStatusLabel: {
    loaded: 'carregado',
    loading: 'carregando',
    unloaded: 'descarregado',
    downloading: 'baixando',
    sleeping: 'em repouso',
    failed: 'falha ao carregar',
    unknown: 'on-line',
  },
  serverDown: 'O llama-server está inacessível; verifique a URL do endpoint e o status do servidor.',
};
