import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Выкл.',
  tierOn: 'Вкл.',
  releaseRequired: 'Тег релиза не может быть пустым',
  backendUnsupported: (backend: string) => `Для этой платформы нет официальной сборки бэкенда ${backend}`,
  runtimeDirString: 'Папка собственной среды выполнения должна быть строкой',
  positiveInteger: (field: string) => `${field}: должно быть положительным целым числом`,
  nonNegativeInteger: (field: string) => `${field}: должно быть неотрицательным целым числом`,
  extraArgsString: 'Дополнительные аргументы запуска должны быть строкой',
  autoStartBoolean: 'Автозапуск должен быть логическим значением',
  notManaged: 'Этот эндпоинт не находится под управлением',
  runtimeNotInstalled: 'Среда выполнения ещё не установлена',
  runtimeUnsupported: 'Для этой платформы нет официальной сборки этого бэкенда; укажите папку собственной среды выполнения',
  endpointPanel: 'Адрес сервера',
  endpointPanelDescription: 'Адрес, который слушает llama-server; управляемый процесс запускается на нём.',
  runtimePanel: 'Среда выполнения',
  runtimePanelDescription: 'Загрузка и установка официальных бинарных файлов llama.cpp; запуск и остановка процесса llama-server.',
  modelsPanel: 'Модели',
  modelsPanelDescription: 'Модели, известные llama-server: в кэше, в локальной папке и скачиваемые.',
  unknownPanel: 'Неизвестная панель',
  unknownMethod: 'Неизвестное действие',
  instanceNameRequired: 'Требуется имя эндпоинта',
  modelIdRequired: 'Требуется id модели',
  queryRequired: 'Требуется поисковый запрос',
  limitRequired: 'Требуется количество результатов',
  repoRequired: 'Требуется репозиторий',
  bodyRequired: 'Требуется тело запроса',
  serverUnreachable: 'llama-server недоступен; проверьте URL эндпоинта и состояние сервера.',
  externalServer: 'На эндпоинте уже работает сервер (запущен извне); управление не перехватывается',
  starting: 'llama-server запускается',
  spawnFailed: (message: string) => `Не удалось запустить процесс: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows не удалось запустить ${exe} (UNKNOWN). ` +
    'Если запуск не удался, проверьте запись о блокировке в «Безопасности Windows». Если блокировка подтверждена, используйте среду выполнения, которая соответствует требованиям доверия.',
  exited: (code: number | null, tail: string) => `Процесс завершился с code=${code}; конец stderr: ${tail}`,
  badBaseUrl: (baseUrl: string) => `Не удаётся получить host/port из baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `В папке среды выполнения нет ${exe}`,
  healthTimeout: 'Истекло время проверки /health; проверьте URL эндпоинта и состояние сервера.',
  downloadFailed: (file: string, message: string) => `Не удалось скачать ${file}: ${message}`,
  extractFailed: (file: string, message: string) => `Не удалось распаковать ${file}: ${message}`,
  installBusy: 'Сейчас устанавливается другая среда выполнения',
  description: 'Подключение к локальным моделям llama.cpp или управление ими.',
  saveBeforeRuntime: 'Сохраните конфигурацию перед операциями со средой выполнения.',
  saveBeforeModels: 'Сохраните конфигурацию перед операциями с моделями.',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'Среда выполнения',
  modelsTitle: 'Модели',
  managedOff: 'Этим эндпоинтом управляют извне. Включите управление, чтобы Cortico управлял процессом llama-server.',
  enable: 'Включить управление',
  disable: 'Отключить управление',
  release: 'Релиз',
  backend: 'Бэкенд',
  runtimeDir: 'Папка среды выполнения',
  ownRuntime: 'своя',
  installStatus: 'Установка',
  installed: 'установлено',
  absent: 'не установлено',
  downloading: 'скачивание',
  extracting: 'распаковка',
  install: 'Скачать и установить',
  reinstall: 'Переустановить',
  sacWarning:
    'Интеллектуальное управление приложениями Windows работает в принудительном режиме. ' +
    'Если запуск не удался, проверьте запись о блокировке в «Безопасности Windows». Если блокировка подтверждена, используйте среду выполнения, которая соответствует требованиям доверия.',
  server: 'Сервер',
  serverSection: 'Процесс сервера и эндпоинт',
  serverSectionDesc: 'Локальный процесс llama-server и состояние прослушивания.',
  runtimeSection: 'Бинарная среда выполнения',
  runtimeSectionDesc: 'Официальные бинарные файлы llama.cpp и зависимости.',
  releaseHint: 'Тег релиза upstream, например b10930; при смене скачивается другая сборка.',
  backendHint: 'Официальные сборки для этой платформы; к сборкам CUDA добавляется пакет cudart из upstream.',
  runtimeDirHint: 'Если задано, ничего не скачивается: в папке должны быть llama-server и его общие библиотеки (собственная сборка, Linux CUDA, подписанные сборки).',
  browse: 'Выбрать папку',
  launchSection: 'Параметры запуска',
  launchSectionDesc: 'Применяются при следующем запуске llama-server.',
  contextSize: 'Размер контекста (-c)',
  nGpuLayers: 'Слои на GPU (-ngl)',
  parallel: 'Параллельные слоты (--parallel)',
  extraArgs: 'Дополнительные аргументы запуска',
  extraArgsHint: 'Разбиваются по пробелам и добавляются в командную строку llama-server.',
  autoStart: 'Запускать сервер вместе с ботом',
  copyEndpoint: 'Копировать эндпоинт',
  installRequired: 'Установите бинарные файлы среды выполнения перед запуском сервера',
  status: 'Состояние',
  endpoint: 'Эндпоинт',
  reachable: 'доступен',
  unreachable: 'недоступен',
  pid: 'PID процесса',
  pendingNote: 'Параметры запуска изменены; остановите и запустите снова, чтобы применить их.',
  start: 'Запустить',
  stop: 'Остановить',
  refresh: 'Обновить',
  phase: { stopped: 'остановлен', starting: 'запускается', running: 'работает', error: 'ошибка' },
  modelId: 'ID модели',
  modelStatus: 'Состояние',
  modality: 'Ввод',
  path: 'Файл',
  actions: 'Действия',
  load: 'Загрузить',
  unload: 'Выгрузить',
  cancel: 'Отмена',
  reload: 'Пересканировать',
  pull: 'Скачать',
  pullPlaceholder: 'Репозиторий HuggingFace, например ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Выбрать',
  useTitle: 'Подставить эту модель в раздел «Модель и генерация»',
  search: 'Поиск',
  searchPlaceholder: 'Поиск репозиториев GGUF на HuggingFace, например qwen3',
  searchFailed: (reason: string) => `Поиск не удался: ${reason}`,
  noRepos: 'Подходящих репозиториев нет.',
  repo: 'Репозиторий',
  downloads: 'Скачивания',
  likes: 'Лайки',
  updated: 'Обновлено',
  showFiles: 'Файлы',
  filesOf: (repo: string) => `Файлы GGUF в ${repo}`,
  noFiles: 'В этом репозитории нет файлов GGUF.',
  file: 'Файл',
  size: 'Размер',
  tag: 'Тег',
  localDir: 'Локальная папка GGUF',
  cacheDir: 'Папка кэша',
  noModels: 'Моделей пока нет: скачайте модель выше или положите файлы GGUF в локальную папку и пересканируйте.',
  modelStatusLabel: {
    loaded: 'загружена',
    loading: 'загружается',
    unloaded: 'выгружена',
    downloading: 'скачивается',
    sleeping: 'спит',
    failed: 'ошибка загрузки',
    unknown: 'в сети',
  },
  serverDown: 'llama-server недоступен; проверьте URL эндпоинта и состояние сервера.',
};
