import { pick, type Language } from '../../core/language.ts';

/** Server side: ConfigGroup titles, validation errors, runtime and server state details. */
const zh = {
  release: 'llama.cpp 版本(release tag)',
  releaseDescription: '上游 GitHub release 的 tag,如 b10930。改了要重新下载。',
  backend: '后端',
  backendDescription: '按本机平台给出的官方构建;CUDA 版自动搭配上游的 cudart 包。',
  runtimeDir: '自备运行时目录',
  runtimeDirDescription: '填了就不下载:目录里要有 llama-server 及其动态库(自编译、Linux CUDA、签过名的构建)。',
  contextSize: '上下文长度(-c)',
  nGpuLayers: 'GPU 层数(-ngl)',
  parallel: '并发槽位(--parallel)',
  extraArgs: '附加启动参数',
  extraArgsDescription: '按空格拆开追加到 llama-server 命令行。',
  autoStart: 'bot 启动时一并起 server',
  launchNote: '启动参数在下一次启动 server 时生效。',
  tierOff: '关闭',
  tierOn: '开启',
  releaseRequired: '版本 tag 不能为空',
  backendUnsupported: (backend: string) => `本机平台没有后端 ${backend} 的官方构建`,
  runtimeDirString: '自备运行时目录必须是字符串',
  positiveInteger: (field: string) => `${field} 必须为正整数`,
  nonNegativeInteger: (field: string) => `${field} 必须为非负整数`,
  extraArgsString: '附加启动参数必须是字符串',
  autoStartBoolean: '自动启动必须是布尔值',
  omitTemplateKwargs: '省略 chat_template_kwargs',
  omitTemplateKwargsDescription:
    '不向端点发送模板开关字段。给只有 chat/completions、对未知字段整单拒绝的网关用;'
    + '思考参数在端点条目的 options.extraBody 里按该端点的方言自带。',
  omitTemplateKwargsBoolean: '省略模板开关必须是布尔值',
  extraBodyObject: '附加请求体必须是对象',
  notManaged: '这条端点没有开启托管',
  runtimeNotInstalled: '运行时还没装好',
  runtimeUnsupported: '本机平台没有这个后端的官方构建,填自备运行时目录',
  runtimePanel: '运行时',
  runtimePanelDescription: 'llama.cpp 官方二进制的下载、安装与 llama-server 进程的启停。',
  modelsPanel: '模型',
  modelsPanelDescription: 'llama-server 认得的模型:缓存里的、本机目录里的,以及正在下载的。',
  unknownPanel: '未知面板',
  unknownMethod: '未知操作',
  instanceNameRequired: '需要端点名',
  modelIdRequired: '需要模型 id',
  bodyRequired: '需要请求体',
  serverUnreachable: 'llama-server 不可达,先启动它',
  externalServer: '端点已有服务在跑(外部启动),不接管',
  starting: 'llama-server 启动中',
  spawnFailed: (message: string) => `进程启动失败: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows 应用控制策略拦下了 ${exe}(智能应用控制对未签名二进制的默认处置)。` +
    '去「Windows 安全中心 → 应用和浏览器控制 → 智能应用控制」关掉,或填一份自己签过名的自备运行时目录。',
  exited: (code: number | null, tail: string) => `进程退出 code=${code};stderr 尾部: ${tail}`,
  badBaseUrl: (baseUrl: string) => `baseUrl 无法解析出 host/port: ${baseUrl}`,
  missingBinary: (exe: string) => `运行时目录里没有 ${exe}`,
  healthTimeout: 'health 检查超时(端口不对,或进程起来了但没监听)',
  downloadFailed: (file: string, message: string) => `下载 ${file} 失败: ${message}`,
  extractFailed: (file: string, message: string) => `解压 ${file} 失败: ${message}`,
  installBusy: '正在安装另一份运行时',
};
const en: typeof zh = {
  release: 'llama.cpp release tag',
  releaseDescription: 'Tag of the upstream GitHub release, e.g. b10930. Changing it means a new download.',
  backend: 'Backend',
  backendDescription: 'Official builds for this platform; CUDA builds are paired with the upstream cudart package.',
  runtimeDir: 'Own runtime directory',
  runtimeDirDescription: 'When set nothing is downloaded: the directory holds llama-server and its shared libraries (self-built, Linux CUDA, signed builds).',
  contextSize: 'Context size (-c)',
  nGpuLayers: 'GPU layers (-ngl)',
  parallel: 'Parallel slots (--parallel)',
  extraArgs: 'Extra launch arguments',
  extraArgsDescription: 'Split on whitespace and appended to the llama-server command line.',
  autoStart: 'Start the server with the bot',
  launchNote: 'Launch parameters apply on the next server start.',
  tierOff: 'Off',
  tierOn: 'On',
  releaseRequired: 'The release tag cannot be empty',
  backendUnsupported: (backend: string) => `No official build of backend ${backend} for this platform`,
  runtimeDirString: 'The own runtime directory must be a string',
  positiveInteger: (field: string) => `${field} must be a positive integer`,
  nonNegativeInteger: (field: string) => `${field} must be a non-negative integer`,
  extraArgsString: 'Extra launch arguments must be a string',
  autoStartBoolean: 'Auto start must be a boolean',
  omitTemplateKwargs: 'Omit chat_template_kwargs',
  omitTemplateKwargsDescription:
    'Never send the template switch field. For OpenAI Chat Completions gateways that reject unknown'
    + ' fields wholesale; carry the endpoint\'s own thinking parameter in options.extraBody of the entry.',
  omitTemplateKwargsBoolean: 'Omit template kwargs must be a boolean',
  extraBodyObject: 'Extra request body must be an object',
  notManaged: 'This endpoint is not managed',
  runtimeNotInstalled: 'The runtime is not installed yet',
  runtimeUnsupported: 'No official build for this backend on this platform; set an own runtime directory',
  runtimePanel: 'Runtime',
  runtimePanelDescription: 'Download and install the official llama.cpp binaries; start and stop the llama-server process.',
  modelsPanel: 'Models',
  modelsPanelDescription: 'Models llama-server knows: cached, in the local directory, and downloading.',
  unknownPanel: 'Unknown panel',
  unknownMethod: 'Unknown action',
  instanceNameRequired: 'An endpoint name is required',
  modelIdRequired: 'A model id is required',
  bodyRequired: 'A request body is required',
  serverUnreachable: 'llama-server is unreachable; start it first',
  externalServer: 'A server is already running at the endpoint (started externally); not taking over',
  starting: 'llama-server starting',
  spawnFailed: (message: string) => `Process failed to start: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows application control blocked ${exe} (Smart App Control's default for unsigned binaries). ` +
    'Turn it off under Windows Security → App & browser control → Smart App Control, or point the own runtime directory at a signed build.',
  exited: (code: number | null, tail: string) => `Process exited code=${code}; stderr tail: ${tail}`,
  badBaseUrl: (baseUrl: string) => `Cannot derive host/port from baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `No ${exe} in the runtime directory`,
  healthTimeout: 'Health check timed out (wrong port, or the process is up but not listening)',
  downloadFailed: (file: string, message: string) => `Download of ${file} failed: ${message}`,
  extractFailed: (file: string, message: string) => `Extraction of ${file} failed: ${message}`,
  installBusy: 'Another runtime is being installed',
};
export type Text = typeof zh;
export const text = (language: Language) => pick(language, { zh, en });

/** Browser side: the two panels pick by `ctx.language`. */
const panelZh = {
  runtimeTitle: '运行时',
  modelsTitle: '模型',
  managedOff: '这条端点连的是已经在跑的 llama-server;要让 Cortico 自己起一个,点「开启托管」。',
  enable: '开启托管',
  disable: '关闭托管',
  release: '版本',
  backend: '后端',
  runtimeDir: '运行时目录',
  ownRuntime: '自备',
  installStatus: '安装',
  installed: '已安装',
  absent: '未安装',
  downloading: '下载中',
  extracting: '解压中',
  install: '下载并安装',
  reinstall: '重新安装',
  sacWarning:
    '本机开着 Windows 智能应用控制(强制态)。llama.cpp 官方二进制未签名,下载完也起不来。' +
    '去「Windows 安全中心 → 应用和浏览器控制 → 智能应用控制」关掉,或填一份自己签过名的自备运行时目录。',
  server: 'server',
  status: '状态',
  endpoint: '端点',
  reachable: '可达',
  unreachable: '不可达',
  pid: 'pid',
  pendingNote: '启动参数已修改;停止并重新启动后生效。',
  start: '启动',
  stop: '停止',
  refresh: '刷新',
  phase: { stopped: '未运行', starting: '启动中', running: '运行中', error: '出错' } as Record<string, string>,
  paramsNote: '版本、后端、上下文长度这些在「参数」页签里改。',
  modelId: '模型 id',
  modelStatus: '状态',
  modality: '输入',
  path: '文件',
  actions: '操作',
  load: '加载',
  unload: '卸载',
  cancel: '取消',
  reload: '重扫',
  pull: '拉取',
  pullPlaceholder: 'HuggingFace 仓库,如 ggml-org/Qwen3-8B-GGUF:Q4_K_M',
  localDir: '本机 GGUF 目录',
  cacheDir: '缓存目录',
  noModels: '还没有模型:上面拉一个,或把 GGUF 放进本机目录后重扫。',
  modelStatusLabel: {
    loaded: '已加载',
    loading: '加载中',
    unloaded: '未加载',
    downloading: '下载中',
    sleeping: '休眠',
    failed: '加载失败',
    unknown: '在线',
  } as Record<string, string>,
  serverDown: 'llama-server 不可达;先在「运行时」里启动它。',
};
const panelEn: typeof panelZh = {
  runtimeTitle: 'Runtime',
  modelsTitle: 'Models',
  managedOff: 'This endpoint connects to a llama-server that is already running; click "Enable hosting" to let Cortico start one.',
  enable: 'Enable hosting',
  disable: 'Disable hosting',
  release: 'Release',
  backend: 'Backend',
  runtimeDir: 'Runtime directory',
  ownRuntime: 'own',
  installStatus: 'Install',
  installed: 'installed',
  absent: 'not installed',
  downloading: 'downloading',
  extracting: 'extracting',
  install: 'Download and install',
  reinstall: 'Reinstall',
  sacWarning:
    'Windows Smart App Control is enforced on this machine. The official llama.cpp binaries are unsigned and will not start after download. ' +
    'Turn it off under Windows Security → App & browser control → Smart App Control, or point the own runtime directory at a signed build.',
  server: 'server',
  status: 'Status',
  endpoint: 'Endpoint',
  reachable: 'reachable',
  unreachable: 'unreachable',
  pid: 'pid',
  pendingNote: 'Launch parameters changed; stop and start again to apply them.',
  start: 'Start',
  stop: 'Stop',
  refresh: 'Refresh',
  phase: { stopped: 'stopped', starting: 'starting', running: 'running', error: 'error' } as Record<string, string>,
  paramsNote: 'Release, backend and context size are edited on the parameters tab.',
  modelId: 'Model id',
  modelStatus: 'Status',
  modality: 'Input',
  path: 'File',
  actions: 'Actions',
  load: 'Load',
  unload: 'Unload',
  cancel: 'Cancel',
  reload: 'Rescan',
  pull: 'Pull',
  pullPlaceholder: 'HuggingFace repo, e.g. ggml-org/Qwen3-8B-GGUF:Q4_K_M',
  localDir: 'Local GGUF directory',
  cacheDir: 'Cache directory',
  noModels: 'No models yet: pull one above, or drop GGUF files into the local directory and rescan.',
  modelStatusLabel: {
    loaded: 'loaded',
    loading: 'loading',
    unloaded: 'unloaded',
    downloading: 'downloading',
    sleeping: 'sleeping',
    failed: 'load failed',
    unknown: 'online',
  } as Record<string, string>,
  serverDown: 'llama-server is unreachable; start it on the Runtime panel first.',
};
export const panel = { zh: panelZh, en: panelEn };
