import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: '關閉',
  tierOn: '開啟',
  releaseRequired: '版本 tag 不能為空',
  backendUnsupported: (backend: string) => `本機平台沒有後端 ${backend} 的官方建置`,
  runtimeDirString: '自備執行階段目錄必須是字串',
  positiveInteger: (field: string) => `${field} 必須為正整數`,
  nonNegativeInteger: (field: string) => `${field} 必須為非負整數`,
  extraArgsString: '附加啟動參數必須是字串',
  autoStartBoolean: '自動啟動必須是布林值',
  notManaged: '這個端點沒有開啟託管',
  runtimeNotInstalled: '執行階段還沒裝好',
  runtimeUnsupported: '本機平台沒有這個後端的官方建置,填自備執行階段目錄',
  endpointPanel: '服務位址',
  endpointPanelDescription: 'llama-server 監聽的位址;託管的處理程序依它啟動。',
  runtimePanel: '執行階段',
  runtimePanelDescription: 'llama.cpp 官方二進位檔的下載、安裝與 llama-server 處理程序的啟停。',
  modelsPanel: '模型',
  modelsPanelDescription: 'llama-server 認得的模型:快取裡的、本機目錄裡的,以及正在下載的。',
  unknownPanel: '未知面板',
  unknownMethod: '未知操作',
  instanceNameRequired: '需要端點名稱',
  modelIdRequired: '需要模型 id',
  queryRequired: '需要搜尋詞',
  limitRequired: '需要結果筆數',
  repoRequired: '需要儲存庫名稱',
  bodyRequired: '需要請求內容',
  serverUnreachable: 'llama-server 無法連線；請檢查端點位址與服務狀態。',
  externalServer: '端點已有服務在跑(外部啟動),不接管',
  starting: 'llama-server 啟動中',
  spawnFailed: (message: string) => `處理程序啟動失敗: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows 啟動 ${exe} 失敗（UNKNOWN）。` +
    '啟動失敗時可在 Windows 安全性核對封鎖記錄；若確認被封鎖，請使用符合信任要求的執行階段。',
  exited: (code: number | null, tail: string) => `處理程序結束 code=${code};stderr 尾部: ${tail}`,
  badBaseUrl: (baseUrl: string) => `baseUrl 無法解析出 host/port: ${baseUrl}`,
  missingBinary: (exe: string) => `執行階段目錄裡沒有 ${exe}`,
  healthTimeout: '/health 檢查逾時；請檢查端點位址與服務狀態。',
  downloadFailed: (file: string, message: string) => `下載 ${file} 失敗: ${message}`,
  extractFailed: (file: string, message: string) => `解壓縮 ${file} 失敗: ${message}`,
  installBusy: '正在安裝另一份執行階段',
  description: '連線或託管本機 llama.cpp 模型。',
  saveBeforeRuntime: '請先儲存設定，再執行執行階段操作。',
  saveBeforeModels: '請先儲存設定，再操作模型。',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: '執行階段',
  modelsTitle: '模型',
  managedOff: '此端點由外部管理；開啟託管後由 Cortico 管理 llama-server 處理程序。',
  enable: '開啟託管',
  disable: '關閉託管',
  release: '版本',
  backend: '後端',
  runtimeDir: '執行階段目錄',
  ownRuntime: '自備',
  installStatus: '安裝',
  installed: '已安裝',
  absent: '未安裝',
  downloading: '下載中',
  extracting: '解壓縮中',
  install: '下載並安裝',
  reinstall: '重新安裝',
  sacWarning:
    '偵測到 Windows 智慧型應用程式控制處於強制模式。' +
    '啟動失敗時可在 Windows 安全性核對封鎖記錄；若確認被封鎖，請使用符合信任要求的執行階段。',
  server: '服務處理程序',
  serverSection: '服務處理程序與端點',
  serverSectionDesc: 'llama-server 本機服務管理與監聽狀態。',
  runtimeSection: '二進位執行環境',
  runtimeSectionDesc: '官方 llama.cpp 二進位套件與執行依賴管理。',
  releaseHint: '上游 release tag，如 b10930；換了要重新下載。',
  backendHint: '依本機平台給出的官方建置;CUDA 版自動搭配上游的 cudart 套件。',
  runtimeDirHint: '填了就不下載:目錄裡要有 llama-server 及其動態函式庫(自行編譯、Linux CUDA、簽過章的建置)。',
  browse: '選擇目錄',
  launchSection: '啟動參數',
  launchSectionDesc: '在下一次啟動 llama-server 時生效。',
  contextSize: '上下文長度(-c)',
  nGpuLayers: 'GPU 層數(-ngl)',
  parallel: '並行槽位(--parallel)',
  extraArgs: '附加啟動參數',
  extraArgsHint: '依空格拆開追加到 llama-server 命令列。',
  autoStart: 'bot 啟動時一併啟動 server',
  copyEndpoint: '複製端點',
  installRequired: '請先下載並安裝執行階段二進位檔，方可啟動服務',
  status: '狀態',
  endpoint: '端點',
  reachable: '可連線',
  unreachable: '無法連線',
  pid: '處理程序 PID',
  pendingNote: '啟動參數已修改;停止並重新啟動後生效。',
  start: '啟動',
  stop: '停止',
  refresh: '重新整理',
  phase: { stopped: '未執行', starting: '啟動中', running: '執行中', error: '出錯' },
  modelId: '模型 ID',
  modelStatus: '狀態',
  modality: '輸入',
  path: '檔案',
  actions: '操作',
  load: '載入',
  unload: '卸載',
  cancel: '取消',
  reload: '重新掃描',
  pull: '拉取',
  pullPlaceholder: 'HuggingFace 儲存庫,如 ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: '選用',
  useTitle: '把這個模型填進「模型與生成」',
  search: '搜尋',
  searchPlaceholder: '搜尋 HuggingFace 上的 GGUF 儲存庫,如 qwen3',
  searchFailed: (reason: string) => `搜尋失敗: ${reason}`,
  noRepos: '沒有符合的儲存庫。',
  repo: '儲存庫',
  downloads: '下載',
  likes: '按讚',
  updated: '更新',
  showFiles: '看檔案',
  filesOf: (repo: string) => `${repo} 裡的 GGUF 檔案`,
  noFiles: '這個儲存庫裡沒有 GGUF 檔案。',
  file: '檔案',
  size: '大小',
  tag: '標籤',
  localDir: '本機 GGUF 目錄',
  cacheDir: '快取目錄',
  noModels: '暫無可用的 GGUF 模型：可透過上方輸入拉取，或將 .gguf 檔案放入本機目錄後點擊重新掃描。',
  modelStatusLabel: {
    loaded: '已載入',
    loading: '載入中',
    unloaded: '未載入',
    downloading: '下載中',
    sleeping: '休眠',
    failed: '載入失敗',
    unknown: '在線',
  },
  serverDown: 'llama-server 無法連線；請檢查端點位址與服務狀態。',
};
