import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Désactivé',
  tierOn: 'Activé',
  releaseRequired: 'Le tag de release ne peut pas être vide',
  backendUnsupported: (backend: string) => `Aucun build officiel du backend ${backend} pour cette plateforme`,
  runtimeDirString: "Le répertoire d'exécution personnel doit être une chaîne",
  positiveInteger: (field: string) => `${field} doit être un entier positif`,
  nonNegativeInteger: (field: string) => `${field} doit être un entier non négatif`,
  extraArgsString: 'Les arguments de lancement supplémentaires doivent être une chaîne',
  autoStartBoolean: 'Le démarrage automatique doit être un booléen',
  notManaged: "Cet endpoint n'est pas géré",
  runtimeNotInstalled: "L'environnement d'exécution n'est pas encore installé",
  runtimeUnsupported: "Aucun build officiel pour ce backend sur cette plateforme ; indiquez votre propre répertoire d'exécution",
  endpointPanel: 'Adresse du serveur',
  endpointPanelDescription: "Adresse d'écoute de llama-server ; un processus géré démarre sur cette adresse.",
  runtimePanel: "Environnement d'exécution",
  runtimePanelDescription: 'Télécharger et installer les binaires officiels de llama.cpp ; démarrer et arrêter le processus llama-server.',
  modelsPanel: 'Modèles',
  modelsPanelDescription: 'Modèles connus de llama-server : en cache, dans le répertoire local et en cours de téléchargement.',
  unknownPanel: 'Panneau inconnu',
  unknownMethod: 'Action inconnue',
  instanceNameRequired: "Un nom d'endpoint est requis",
  modelIdRequired: 'Un identifiant de modèle est requis',
  queryRequired: 'Une requête de recherche est requise',
  limitRequired: 'Un nombre de résultats est requis',
  repoRequired: 'Un dépôt est requis',
  bodyRequired: 'Un corps de requête est requis',
  serverUnreachable: "llama-server est injoignable ; vérifiez l'URL de l'endpoint et l'état du serveur.",
  externalServer: "Un serveur tourne déjà sur l'endpoint (lancé en externe) ; pas de prise de contrôle",
  starting: 'Démarrage de llama-server',
  spawnFailed: (message: string) => `Échec du démarrage du processus : ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows n'a pas pu démarrer ${exe} (UNKNOWN). ` +
    "En cas d'échec au démarrage, cherchez un enregistrement de blocage dans Sécurité Windows. Si un blocage est confirmé, utilisez un environnement d'exécution conforme aux exigences de confiance.",
  exited: (code: number | null, tail: string) => `Le processus s'est terminé code=${code} ; fin de stderr : ${tail}`,
  badBaseUrl: (baseUrl: string) => `Impossible de déduire host/port de baseUrl : ${baseUrl}`,
  missingBinary: (exe: string) => `Aucun ${exe} dans le répertoire d'exécution`,
  healthTimeout: "La vérification /health a expiré ; vérifiez l'URL de l'endpoint et l'état du serveur.",
  downloadFailed: (file: string, message: string) => `Échec du téléchargement de ${file} : ${message}`,
  extractFailed: (file: string, message: string) => `Échec de l'extraction de ${file} : ${message}`,
  installBusy: "Un autre environnement d'exécution est en cours d'installation",
  description: 'Se connecter à des modèles llama.cpp locaux ou les gérer.',
  saveBeforeRuntime: "Enregistrez la configuration avant les opérations sur l'environnement d'exécution.",
  saveBeforeModels: 'Enregistrez la configuration avant les opérations sur les modèles.',
};
export const panel: Partial<typeof panelEn> = {
  runtimeTitle: "Environnement d'exécution",
  modelsTitle: 'Modèles',
  managedOff: 'Cet endpoint est géré en externe. Activez la gestion pour que Cortico gère son processus llama-server.',
  enable: 'Activer la gestion',
  disable: 'Désactiver la gestion',
  release: 'Version',
  backend: 'Backend',
  runtimeDir: "Répertoire d'exécution",
  ownRuntime: 'personnel',
  installStatus: 'Installation',
  installed: 'installé',
  absent: 'non installé',
  downloading: 'téléchargement',
  extracting: 'extraction',
  install: 'Télécharger et installer',
  reinstall: 'Réinstaller',
  sacWarning:
    'Le Contrôle intelligent des applications de Windows est en mode appliqué. ' +
    "En cas d'échec au démarrage, cherchez un enregistrement de blocage dans Sécurité Windows. Si un blocage est confirmé, utilisez un environnement d'exécution conforme aux exigences de confiance.",
  server: 'Serveur',
  serverSection: 'Processus serveur et endpoint',
  serverSectionDesc: "Processus local llama-server et état d'écoute.",
  runtimeSection: "Environnement d'exécution binaire",
  runtimeSectionDesc: 'Binaires officiels de llama.cpp et dépendances.',
  releaseHint: 'Tag de release amont, par ex. b10930 ; le changer télécharge un autre build.',
  backendHint: 'Builds officiels pour cette plateforme ; les builds CUDA sont associés au paquet cudart amont.',
  runtimeDirHint: "Si défini, rien n'est téléchargé : le répertoire contient llama-server et ses bibliothèques partagées (compilé soi-même, Linux CUDA, builds signés).",
  browse: 'Choisir un répertoire',
  launchSection: 'Paramètres de lancement',
  launchSectionDesc: 'Appliqués au prochain démarrage de llama-server.',
  contextSize: 'Taille du contexte (-c)',
  nGpuLayers: 'Couches GPU (-ngl)',
  parallel: 'Slots parallèles (--parallel)',
  extraArgs: 'Arguments de lancement supplémentaires',
  extraArgsHint: 'Découpés sur les espaces et ajoutés à la ligne de commande de llama-server.',
  autoStart: 'Démarrer le serveur avec le bot',
  copyEndpoint: "Copier l'endpoint",
  installRequired: "Installez le binaire d'exécution avant de démarrer le serveur",
  status: 'État',
  endpoint: 'Endpoint',
  reachable: 'joignable',
  unreachable: 'injoignable',
  pid: 'PID du processus',
  pendingNote: 'Paramètres de lancement modifiés ; arrêtez puis redémarrez pour les appliquer.',
  start: 'Démarrer',
  stop: 'Arrêter',
  refresh: 'Actualiser',
  phase: { stopped: 'arrêté', starting: 'démarrage', running: 'en cours', error: 'erreur' } as Record<string, string>,
  modelId: 'ID du modèle',
  modelStatus: 'État',
  modality: 'Entrée',
  path: 'Fichier',
  actions: 'Actions',
  load: 'Charger',
  unload: 'Décharger',
  cancel: 'Annuler',
  reload: 'Réanalyser',
  pull: 'Récupérer',
  pullPlaceholder: 'Dépôt HuggingFace, par ex. ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Utiliser',
  useTitle: 'Placer ce modèle dans « Modèle et génération »',
  search: 'Rechercher',
  searchPlaceholder: 'Rechercher des dépôts GGUF sur HuggingFace, par ex. qwen3',
  searchFailed: (reason: string) => `Échec de la recherche : ${reason}`,
  noRepos: 'Aucun dépôt correspondant.',
  repo: 'Dépôt',
  downloads: 'Téléchargements',
  likes: "J'aime",
  updated: 'Mis à jour',
  showFiles: 'Fichiers',
  filesOf: (repo: string) => `Fichiers GGUF dans ${repo}`,
  noFiles: "Ce dépôt n'a aucun fichier GGUF.",
  file: 'Fichier',
  size: 'Taille',
  tag: 'Étiquette',
  localDir: 'Répertoire GGUF local',
  cacheDir: 'Répertoire du cache',
  noModels: "Aucun modèle pour l'instant : récupérez-en un ci-dessus, ou déposez des fichiers GGUF dans le répertoire local et réanalysez.",
  modelStatusLabel: {
    loaded: 'chargé',
    loading: 'chargement',
    unloaded: 'déchargé',
    downloading: 'téléchargement',
    sleeping: 'en veille',
    failed: 'échec du chargement',
    unknown: 'en ligne',
  } as Record<string, string>,
  serverDown: "llama-server est injoignable ; vérifiez l'URL de l'endpoint et l'état du serveur.",
};
