import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: '끔',
  tierOn: '켬',
  releaseRequired: '릴리스 태그는 비워 둘 수 없습니다',
  backendUnsupported: (backend: string) => `이 플랫폼용 ${backend} 백엔드의 공식 빌드가 없습니다`,
  runtimeDirString: '자체 런타임 디렉터리는 문자열이어야 합니다',
  positiveInteger: (field: string) => `${field}은(는) 양의 정수여야 합니다`,
  nonNegativeInteger: (field: string) => `${field}은(는) 0 이상의 정수여야 합니다`,
  extraArgsString: '추가 실행 인수는 문자열이어야 합니다',
  autoStartBoolean: '자동 시작은 불리언이어야 합니다',
  notManaged: '이 엔드포인트는 관리가 켜져 있지 않습니다',
  runtimeNotInstalled: '런타임이 아직 설치되지 않았습니다',
  runtimeUnsupported: '이 플랫폼에는 이 백엔드의 공식 빌드가 없습니다. 자체 런타임 디렉터리를 지정하세요',
  endpointPanel: '서버 주소',
  endpointPanelDescription: 'llama-server가 수신하는 주소이며, 관리되는 프로세스는 이 주소로 시작됩니다.',
  runtimePanel: '런타임',
  runtimePanelDescription: 'llama.cpp 공식 바이너리 다운로드와 설치, llama-server 프로세스 시작과 중지.',
  modelsPanel: '모델',
  modelsPanelDescription: 'llama-server가 아는 모델: 캐시에 있는 것, 로컬 디렉터리에 있는 것, 다운로드 중인 것.',
  unknownPanel: '알 수 없는 패널',
  unknownMethod: '알 수 없는 작업',
  instanceNameRequired: '엔드포인트 이름이 필요합니다',
  modelIdRequired: '모델 ID가 필요합니다',
  queryRequired: '검색어가 필요합니다',
  limitRequired: '결과 개수가 필요합니다',
  repoRequired: '저장소 이름이 필요합니다',
  bodyRequired: '요청 본문이 필요합니다',
  serverUnreachable: 'llama-server에 연결할 수 없습니다. 엔드포인트 주소와 서버 상태를 확인하세요.',
  externalServer: '엔드포인트에서 이미 서버가 실행 중입니다(외부에서 시작). 관리를 넘겨받지 않습니다',
  starting: 'llama-server 시작 중',
  spawnFailed: (message: string) => `프로세스를 시작하지 못했습니다: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows에서 ${exe}을(를) 시작하지 못했습니다(UNKNOWN). ` +
    '시작에 실패하면 Windows 보안에서 차단 기록을 확인하세요. 차단이 확인되면 신뢰 요구 사항을 충족하는 런타임을 쓰세요.',
  exited: (code: number | null, tail: string) => `프로세스 종료 code=${code}; stderr 끝부분: ${tail}`,
  badBaseUrl: (baseUrl: string) => `baseUrl에서 host/port를 알아낼 수 없습니다: ${baseUrl}`,
  missingBinary: (exe: string) => `런타임 디렉터리에 ${exe}이(가) 없습니다`,
  healthTimeout: '/health 검사 시간이 초과되었습니다. 엔드포인트 주소와 서버 상태를 확인하세요.',
  downloadFailed: (file: string, message: string) => `${file} 다운로드 실패: ${message}`,
  extractFailed: (file: string, message: string) => `${file} 압축 해제 실패: ${message}`,
  installBusy: '다른 런타임을 설치하는 중입니다',
  description: '로컬 llama.cpp 모델에 연결하거나 관리합니다.',
  saveBeforeRuntime: '런타임 작업 전에 설정을 저장하세요.',
  saveBeforeModels: '모델 작업 전에 설정을 저장하세요.',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: '런타임',
  modelsTitle: '모델',
  managedOff: '이 엔드포인트는 외부에서 관리됩니다. 관리를 켜면 Cortico가 llama-server 프로세스를 관리합니다.',
  enable: '관리 켜기',
  disable: '관리 끄기',
  release: '릴리스',
  backend: '백엔드',
  runtimeDir: '런타임 디렉터리',
  ownRuntime: '자체',
  installStatus: '설치',
  installed: '설치됨',
  absent: '설치 안 됨',
  downloading: '다운로드 중',
  extracting: '압축 해제 중',
  install: '다운로드 및 설치',
  reinstall: '다시 설치',
  sacWarning:
    'Windows 스마트 앱 컨트롤이 강제 모드입니다. ' +
    '시작에 실패하면 Windows 보안에서 차단 기록을 확인하세요. 차단이 확인되면 신뢰 요구 사항을 충족하는 런타임을 쓰세요.',
  server: '서버 프로세스',
  serverSection: '서버 프로세스 및 엔드포인트',
  serverSectionDesc: 'llama-server 로컬 프로세스와 수신 상태.',
  runtimeSection: '바이너리 실행 환경',
  runtimeSectionDesc: 'llama.cpp 공식 바이너리와 종속성 관리.',
  releaseHint: '업스트림 릴리스 태그(예: b10930)입니다. 바꾸면 다른 빌드를 다운로드합니다.',
  backendHint: '이 플랫폼용 공식 빌드입니다. CUDA 빌드에는 업스트림 cudart 패키지가 자동으로 함께 붙습니다.',
  runtimeDirHint: '지정하면 다운로드하지 않습니다. 디렉터리에 llama-server와 공유 라이브러리가 있어야 합니다(직접 빌드, Linux CUDA, 서명된 빌드).',
  browse: '디렉터리 선택',
  launchSection: '실행 매개변수',
  launchSectionDesc: '다음에 llama-server를 시작할 때 적용됩니다.',
  contextSize: '컨텍스트 길이(-c)',
  nGpuLayers: 'GPU 레이어 수(-ngl)',
  parallel: '병렬 슬롯(--parallel)',
  extraArgs: '추가 실행 인수',
  extraArgsHint: '공백으로 나눠 llama-server 명령줄에 덧붙입니다.',
  autoStart: '봇 시작 시 서버도 시작',
  copyEndpoint: '엔드포인트 복사',
  installRequired: '서버를 시작하려면 먼저 런타임 바이너리를 다운로드해 설치하세요',
  status: '상태',
  endpoint: '엔드포인트',
  reachable: '연결 가능',
  unreachable: '연결 불가',
  pid: '프로세스 PID',
  pendingNote: '실행 매개변수가 바뀌었습니다. 중지한 뒤 다시 시작하면 적용됩니다.',
  start: '시작',
  stop: '중지',
  refresh: '새로 고침',
  phase: { stopped: '중지됨', starting: '시작 중', running: '실행 중', error: '오류' },
  modelId: '모델 ID',
  modelStatus: '상태',
  modality: '입력',
  path: '파일',
  actions: '작업',
  load: '로드',
  unload: '언로드',
  cancel: '취소',
  reload: '다시 검색',
  pull: '가져오기',
  pullPlaceholder: 'HuggingFace 저장소, 예: ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: '사용',
  useTitle: '이 모델을 "모델 및 생성"에 채우기',
  search: '검색',
  searchPlaceholder: 'HuggingFace의 GGUF 저장소 검색, 예: qwen3',
  searchFailed: (reason: string) => `검색 실패: ${reason}`,
  noRepos: '일치하는 저장소가 없습니다.',
  repo: '저장소',
  downloads: '다운로드',
  likes: '좋아요',
  updated: '업데이트',
  showFiles: '파일 보기',
  filesOf: (repo: string) => `${repo}의 GGUF 파일`,
  noFiles: '이 저장소에는 GGUF 파일이 없습니다.',
  file: '파일',
  size: '크기',
  tag: '태그',
  localDir: '로컬 GGUF 디렉터리',
  cacheDir: '캐시 디렉터리',
  noModels: '사용할 수 있는 GGUF 모델이 아직 없습니다. 위 입력란에서 가져오거나 .gguf 파일을 로컬 디렉터리에 넣고 다시 검색하세요.',
  modelStatusLabel: {
    loaded: '로드됨',
    loading: '로드 중',
    unloaded: '언로드됨',
    downloading: '다운로드 중',
    sleeping: '절전',
    failed: '로드 실패',
    unknown: '온라인',
  },
  serverDown: 'llama-server에 연결할 수 없습니다. 엔드포인트 주소와 서버 상태를 확인하세요.',
};
