import type { en, panelEn } from './strings.ts';

export const text: Partial<typeof en> = {
  tierOff: 'Desactivado',
  tierOn: 'Activado',
  releaseRequired: 'La etiqueta de versión no puede estar vacía',
  backendUnsupported: (backend: string) => `No hay una compilación oficial del backend ${backend} para esta plataforma`,
  runtimeDirString: 'El directorio del entorno de ejecución propio debe ser una cadena',
  positiveInteger: (field: string) => `${field} debe ser un entero positivo`,
  nonNegativeInteger: (field: string) => `${field} debe ser un entero no negativo`,
  extraArgsString: 'Los argumentos de inicio adicionales deben ser una cadena',
  autoStartBoolean: 'El inicio automático debe ser un booleano',
  notManaged: 'Este endpoint no está gestionado',
  runtimeNotInstalled: 'El entorno de ejecución aún no está instalado',
  runtimeUnsupported: 'No hay compilación oficial de este backend para esta plataforma; define un directorio de entorno de ejecución propio',
  endpointPanel: 'Dirección del servidor',
  endpointPanelDescription: 'La dirección en la que escucha llama-server; un proceso gestionado se inicia en ella.',
  runtimePanel: 'Entorno de ejecución',
  runtimePanelDescription: 'Descarga e instala los binarios oficiales de llama.cpp; inicia y detiene el proceso de llama-server.',
  modelsPanel: 'Modelos',
  modelsPanelDescription: 'Modelos que conoce llama-server: en caché, en el directorio local y en descarga.',
  unknownPanel: 'Panel desconocido',
  unknownMethod: 'Acción desconocida',
  instanceNameRequired: 'Se requiere un nombre de endpoint',
  modelIdRequired: 'Se requiere un id de modelo',
  queryRequired: 'Se requiere un término de búsqueda',
  limitRequired: 'Se requiere una cantidad de resultados',
  repoRequired: 'Se requiere un repositorio',
  bodyRequired: 'Se requiere un cuerpo de solicitud',
  serverUnreachable: 'No se puede acceder a llama-server; revisa la URL del endpoint y el estado del servidor.',
  externalServer: 'Ya hay un servidor en ejecución en el endpoint (iniciado externamente); no se toma el control',
  starting: 'Iniciando llama-server',
  spawnFailed: (message: string) => `No se pudo iniciar el proceso: ${message}`,
  spawnBlocked: (exe: string) =>
    `Windows no pudo iniciar ${exe} (UNKNOWN). ` +
    'Si el inicio falla, busca un registro de bloqueo en Seguridad de Windows. Si se confirma el bloqueo, usa un entorno de ejecución que cumpla los requisitos de confianza.',
  exited: (code: number | null, tail: string) => `El proceso terminó con code=${code}; final de stderr: ${tail}`,
  badBaseUrl: (baseUrl: string) => `No se puede obtener host/port de baseUrl: ${baseUrl}`,
  missingBinary: (exe: string) => `No hay ${exe} en el directorio del entorno de ejecución`,
  healthTimeout: 'La comprobación de /health agotó el tiempo de espera; revisa la URL del endpoint y el estado del servidor.',
  downloadFailed: (file: string, message: string) => `Falló la descarga de ${file}: ${message}`,
  extractFailed: (file: string, message: string) => `Falló la extracción de ${file}: ${message}`,
  installBusy: 'Se está instalando otro entorno de ejecución',
  description: 'Conéctate a modelos locales de llama.cpp o gestiónalos.',
  saveBeforeRuntime: 'Guarda la configuración antes de operar el entorno de ejecución.',
  saveBeforeModels: 'Guarda la configuración antes de operar los modelos.',
};

export const panel: Partial<typeof panelEn> = {
  runtimeTitle: 'Entorno de ejecución',
  modelsTitle: 'Modelos',
  managedOff: 'Este endpoint se gestiona externamente. Activa la gestión para que Cortico administre su proceso de llama-server.',
  enable: 'Activar gestión',
  disable: 'Desactivar gestión',
  release: 'Versión',
  backend: 'Backend',
  runtimeDir: 'Directorio del entorno de ejecución',
  ownRuntime: 'propio',
  installStatus: 'Instalación',
  installed: 'instalado',
  absent: 'no instalado',
  downloading: 'descargando',
  extracting: 'extrayendo',
  install: 'Descargar e instalar',
  reinstall: 'Reinstalar',
  sacWarning:
    'El Control inteligente de aplicaciones de Windows está en modo obligatorio. ' +
    'Si el inicio falla, busca un registro de bloqueo en Seguridad de Windows. Si se confirma el bloqueo, usa un entorno de ejecución que cumpla los requisitos de confianza.',
  server: 'Servidor',
  serverSection: 'Proceso del servidor y endpoint',
  serverSectionDesc: 'Proceso local de llama-server y estado de escucha.',
  runtimeSection: 'Entorno de ejecución binario',
  runtimeSectionDesc: 'Binario oficial de llama.cpp y sus dependencias.',
  releaseHint: 'Etiqueta de versión de upstream, como b10930; al cambiarla se descarga otra compilación.',
  backendHint: 'Compilaciones oficiales para esta plataforma; las compilaciones CUDA se combinan con el paquete cudart de upstream.',
  runtimeDirHint: 'Si se define, no se descarga nada: el directorio contiene llama-server y sus bibliotecas compartidas (compilación propia, Linux CUDA, compilaciones firmadas).',
  browse: 'Elegir directorio',
  launchSection: 'Parámetros de inicio',
  launchSectionDesc: 'Se aplican en el próximo inicio de llama-server.',
  contextSize: 'Tamaño de contexto (-c)',
  nGpuLayers: 'Capas en GPU (-ngl)',
  parallel: 'Ranuras paralelas (--parallel)',
  extraArgs: 'Argumentos de inicio adicionales',
  extraArgsHint: 'Se separan por espacios y se agregan a la línea de comandos de llama-server.',
  autoStart: 'Iniciar el servidor junto con el bot',
  copyEndpoint: 'Copiar endpoint',
  installRequired: 'Instala el binario del entorno de ejecución antes de iniciar el servidor',
  status: 'Estado',
  endpoint: 'Endpoint',
  reachable: 'accesible',
  unreachable: 'inaccesible',
  pid: 'PID del proceso',
  pendingNote: 'Los parámetros de inicio cambiaron; detén e inicia de nuevo para aplicarlos.',
  start: 'Iniciar',
  stop: 'Detener',
  refresh: 'Actualizar',
  phase: { stopped: 'detenido', starting: 'iniciando', running: 'en ejecución', error: 'con error' },
  modelId: 'ID del modelo',
  modelStatus: 'Estado',
  modality: 'Entrada',
  path: 'Archivo',
  actions: 'Acciones',
  load: 'Cargar',
  unload: 'Liberar',
  cancel: 'Cancelar',
  reload: 'Volver a escanear',
  pull: 'Descargar',
  pullPlaceholder: 'Repositorio de HuggingFace, p. ej. ggml-org/Qwen2.5-Coder-7B-Instruct-GGUF',
  use: 'Usar',
  useTitle: 'Poner este modelo en la sección Modelo y generación',
  search: 'Buscar',
  searchPlaceholder: 'Busca repositorios GGUF en HuggingFace, p. ej. qwen3',
  searchFailed: (reason: string) => `Falló la búsqueda: ${reason}`,
  noRepos: 'No hay repositorios que coincidan.',
  repo: 'Repositorio',
  downloads: 'Descargas',
  likes: 'Me gusta',
  updated: 'Actualizado',
  showFiles: 'Archivos',
  filesOf: (repo: string) => `Archivos GGUF en ${repo}`,
  noFiles: 'Este repositorio no tiene archivos GGUF.',
  file: 'Archivo',
  size: 'Tamaño',
  tag: 'Etiqueta',
  localDir: 'Directorio GGUF local',
  cacheDir: 'Directorio de caché',
  noModels: 'Aún no hay modelos: descarga uno arriba o coloca archivos GGUF en el directorio local y vuelve a escanear.',
  modelStatusLabel: {
    loaded: 'cargado',
    loading: 'cargando',
    unloaded: 'no cargado',
    downloading: 'descargando',
    sleeping: 'en reposo',
    failed: 'falló la carga',
    unknown: 'en línea',
  },
  serverDown: 'No se puede acceder a llama-server; revisa la URL del endpoint y el estado del servidor.',
};
