import type { consoleEn, panelEn } from './strings.ts';

export const consoleText: Partial<typeof consoleEn> = {
  orientation: 'Cómo existe la Persona y notas sobre su metacognición.',
  constitution: 'Los principios a largo plazo de la Persona. Los cambios se aplican tras recargar el prefijo del sistema o al iniciar un contexto nuevo.',
  memoryNote: 'Convenciones de memoria: cómo se guardan los archivos del bot y cuándo aparecen por sí solos.',
  workspaceLabel: 'Espacio de trabajo (archivos de memoria que el bot escribió por sí mismo)',
  workspaceNote: 'Se borran de forma irrecuperable todos los archivos del espacio de trabajo excepto la constitución; la constitución y los puntos de control de la personalidad no se tocan',
  workspaceStat: (n: number) => `${n} archivo${n === 1 ? '' : 's'} (además de la constitución)`,
  workspaceCleared: (n: number) => `Se ${n === 1 ? 'borró' : 'borraron'} ${n} archivo${n === 1 ? '' : 's'} del espacio de trabajo; la constitución no se tocó`,
  firstTurnUser: 'Primer turno · entrada del usuario',
  firstTurnUserDesc: 'El mensaje de usuario del primer turno sintetizado. Si este o la respuesta están vacíos, el turno completo no se inyecta.',
  firstTurnThinking: 'Primer turno · razonamiento',
  firstTurnThinkingDesc: 'El razonamiento (reasoning_content) del primer turno sintetizado del asistente; vacío = el turno no lleva ninguno. El dialecto openai-responses-compat no devuelve razonamiento, así que esta parte nunca se envía a esos endpoints.',
  firstTurnReply: 'Primer turno · respuesta',
  firstTurnReplyDesc: 'El texto de respuesta del asistente en el primer turno sintetizado.',
};
export const panelText: Partial<typeof panelEn> = {
  workspace: 'Espacio de trabajo',
  workspaceDesc: 'Al guardar se hace un commit en el repositorio Git del espacio de trabajo, con operator como autor.',
  history: 'Historial de versiones',
  saved: 'Guardado',
  removed: 'Eliminado',
  renamed: 'Renombrado',
  committed: (done: string, hash: string) => `${done}, con commit (${hash})`,
  notCommitted: (done: string) => `${done} (sin commit en git: no hay cambios o git no está disponible)`,
  missingArg: (what: string) => `Falta ${what}`,
  movedOrDeleted: 'El archivo se movió o se eliminó',
  changedBeforeSave: 'El archivo se modificó en otro lugar; vuelve a cargarlo antes de guardar',
  changedBeforeRemove: 'El archivo se modificó en otro lugar; vuelve a cargarlo antes de eliminarlo',
  changedBeforeRename: 'El archivo se modificó en otro lugar; vuelve a cargarlo antes de renombrarlo',
  fileMissing: (path: string) => `El archivo no existe: ${path}`,
  isDirectory: (path: string) => `${path} es una carpeta, no un archivo`,
  tooLargeToPreview: 'El archivo supera 1MB; no se muestra la vista previa',
  binaryFile: 'Archivo binario; no se muestra la vista previa',
  contentNotString: 'content debe ser una cadena',
  nulInText: 'El texto no puede contener caracteres NUL',
  tooLargeToSave: 'El archivo supera 1MB y no se guardó',
  nameTaken: 'Ya existe un archivo con ese nombre',
  unknownMethod: (panel: string, method: string) => `Método de panel desconocido: ${panel}.${method}`,
  unknownPanel: (panel: string) => `Panel desconocido: ${panel}`,
};
