import type { consoleEn, panelEn } from './strings.ts';

export const consoleText: Partial<typeof consoleEn> = {
  orientation: 'Wie die Persona existiert, und Hinweise zu ihrer Metakognition.',
  constitution: 'Die langfristigen Grundsätze der Persona. Änderungen gelten nach einem Neuladen des Systempräfixes oder ab einem neuen Kontext.',
  memoryNote: 'Memory-Konventionen: wie die Dateien des Bots gespeichert werden und wann sie von selbst auftauchen.',
  workspaceLabel: 'Arbeitsbereich (Memory-Dateien, die der Bot selbst geschrieben hat)',
  workspaceNote: 'Alle Dateien im Arbeitsbereich außer der Verfassung werden unwiderruflich gelöscht; Verfassung und Persona-Checkpoints bleiben unberührt',
  workspaceStat: (n: number) => `${n} ${n === 1 ? 'Datei' : 'Dateien'} (außer der Verfassung)`,
  workspaceCleared: (n: number) => `${n} ${n === 1 ? 'Datei' : 'Dateien'} im Arbeitsbereich gelöscht; die Verfassung bleibt unberührt`,
  firstTurnUser: 'Erste Runde · Nutzereingabe',
  firstTurnUserDesc: 'Die user-Nachricht der synthetischen ersten Runde. Ist sie oder die Antwort leer, wird die ganze Runde nicht eingefügt.',
  firstTurnThinking: 'Erste Runde · Denkprozess',
  firstTurnThinkingDesc: 'Der Denkprozess (reasoning_content) der synthetischen ersten assistant-Runde; leer = die Runde enthält keinen. Der Dialekt openai-responses-compat gibt keinen Denkprozess zurück, daher wird dieser Teil an solche Endpunkte nie gesendet.',
  firstTurnReply: 'Erste Runde · Antwort',
  firstTurnReplyDesc: 'Der Antworttext des assistant in der synthetischen ersten Runde.',
};
export const panelText: Partial<typeof panelEn> = {
  workspace: 'Arbeitsbereich',
  workspaceDesc: 'Speichern erstellt einen Commit im Git-Repository des Arbeitsbereichs, mit operator als Autor.',
  history: 'Versionsverlauf',
  saved: 'Gespeichert',
  removed: 'Gelöscht',
  renamed: 'Umbenannt',
  committed: (done: string, hash: string) => `${done} und committet (${hash})`,
  notCommitted: (done: string) => `${done} (kein Git-Commit: keine Änderungen oder Git nicht verfügbar)`,
  missingArg: (what: string) => `${what} fehlt`,
  movedOrDeleted: 'Die Datei wurde verschoben oder gelöscht',
  changedBeforeSave: 'Die Datei wurde anderswo geändert; lade sie neu, bevor du speicherst',
  changedBeforeRemove: 'Die Datei wurde anderswo geändert; lade sie neu, bevor du sie löschst',
  changedBeforeRename: 'Die Datei wurde anderswo geändert; lade sie neu, bevor du sie umbenennst',
  fileMissing: (path: string) => `Datei existiert nicht: ${path}`,
  isDirectory: (path: string) => `${path} ist ein Ordner, keine Datei`,
  tooLargeToPreview: 'Die Datei ist größer als 1MB, keine Vorschau',
  binaryFile: 'Binärdatei, keine Vorschau',
  contentNotString: 'content muss ein String sein',
  nulInText: 'Der Text darf keine NUL-Zeichen enthalten',
  tooLargeToSave: 'Die Datei ist größer als 1MB und wurde nicht gespeichert',
  nameTaken: 'Eine Datei mit diesem Namen existiert bereits',
  unknownMethod: (panel: string, method: string) => `Unbekannte Panel-Methode: ${panel}.${method}`,
  unknownPanel: (panel: string) => `Unbekanntes Panel: ${panel}`,
};
