import type { consoleEn, panelEn } from './strings.ts';

export const consoleText: Partial<typeof consoleEn> = {
  orientation: 'Come esiste la Persona e note sulla sua metacognizione.',
  constitution: 'I principi a lungo termine della Persona. Le modifiche hanno effetto dopo il ricaricamento del prefisso di sistema o quando inizia un nuovo contesto.',
  memoryNote: 'Convenzioni di Memory: come sono archiviati i file del bot e quando riemergono da soli.',
  workspaceLabel: 'Area di lavoro (file di memoria scritti dal bot stesso)',
  workspaceNote: "Tutti i file dell'area di lavoro tranne la costituzione vengono eliminati in modo irreversibile; la costituzione e i checkpoint della Persona restano invariati",
  workspaceStat: (n: number) => `${n} file (esclusa la costituzione)`,
  workspaceCleared: (n: number) => `${n} file dell'area di lavoro ${n === 1 ? 'eliminato' : 'eliminati'}; la costituzione resta invariata`,
  firstTurnUser: 'Primo turno · input utente',
  firstTurnUserDesc: "Il messaggio user del primo turno sintetico. Se questo o la risposta è vuoto, l'intero turno non viene inserito.",
  firstTurnThinking: 'Primo turno · ragionamento',
  firstTurnThinkingDesc: "Il ragionamento (reasoning_content) del primo turno assistant sintetico; vuoto = il turno non ne contiene. Il dialetto openai-responses-compat non restituisce il ragionamento, quindi questa parte non viene mai inviata a tali endpoint.",
  firstTurnReply: 'Primo turno · risposta',
  firstTurnReplyDesc: 'Il testo della risposta assistant del primo turno sintetico.',
};
export const panelText: Partial<typeof panelEn> = {
  workspace: 'Area di lavoro',
  workspaceDesc: "Il salvataggio crea un commit nel repository Git dell'area di lavoro, con autore operator.",
  history: 'Cronologia versioni',
  saved: 'Salvato',
  removed: 'Eliminato',
  renamed: 'Rinominato',
  committed: (done: string, hash: string) => `${done}, commit eseguito (${hash})`,
  notCommitted: (done: string) => `${done} (nessun commit git: nessuna modifica o git non disponibile)`,
  missingArg: (what: string) => `Manca ${what}`,
  movedOrDeleted: 'Il file è stato spostato o eliminato',
  changedBeforeSave: 'Il file è stato modificato altrove; ricaricalo prima di salvare',
  changedBeforeRemove: 'Il file è stato modificato altrove; ricaricalo prima di eliminarlo',
  changedBeforeRename: 'Il file è stato modificato altrove; ricaricalo prima di rinominarlo',
  fileMissing: (path: string) => `Il file non esiste: ${path}`,
  isDirectory: (path: string) => `${path} è una cartella, non un file`,
  tooLargeToPreview: 'Il file supera 1MB, nessuna anteprima',
  binaryFile: 'File binario, nessuna anteprima',
  contentNotString: 'content deve essere una stringa',
  nulInText: 'Il testo non può contenere caratteri NUL',
  tooLargeToSave: 'Il file supera 1MB e non è stato salvato',
  nameTaken: 'Esiste già un file con questo nome',
  unknownMethod: (panel: string, method: string) => `Metodo del pannello sconosciuto: ${panel}.${method}`,
  unknownPanel: (panel: string) => `Pannello sconosciuto: ${panel}`,
};
