import type { consoleEn, panelEn } from './strings.ts';

export const consoleText: Partial<typeof consoleEn> = {
  orientation: 'Como a Persona existe e notas sobre sua metacognição.',
  constitution: 'Os princípios de longo prazo da Persona. As alterações valem após recarregar o prefixo de sistema ou quando um novo contexto começa.',
  memoryNote: 'Convenções de memória: como os arquivos do bot são armazenados e quando surgem por conta própria.',
  workspaceLabel: 'Espaço de trabalho (arquivos de memória que o próprio bot escreveu)',
  workspaceNote: 'Todos os arquivos do espaço de trabalho, exceto a constituição, são excluídos sem possibilidade de recuperação; a constituição e os pontos de controle da personalidade não são alterados',
  workspaceStat: (n: number) => `${n} arquivo${n === 1 ? '' : 's'} (além da constituição)`,
  workspaceCleared: (n: number) => `${n} arquivo${n === 1 ? '' : 's'} do espaço de trabalho ${n === 1 ? 'excluído' : 'excluídos'}; a constituição não foi alterada`,
  firstTurnUser: 'Primeiro turno · entrada do usuário',
  firstTurnUserDesc: 'A mensagem de usuário do primeiro turno sintetizado. Se ela ou a resposta estiver vazia, o turno inteiro não é injetado.',
  firstTurnThinking: 'Primeiro turno · raciocínio',
  firstTurnThinkingDesc: 'O raciocínio (reasoning_content) do primeiro turno sintetizado do assistente; vazio = o turno não leva nenhum. O dialeto openai-responses-compat não retorna raciocínio, então esta parte nunca é enviada para esses endpoints.',
  firstTurnReply: 'Primeiro turno · resposta',
  firstTurnReplyDesc: 'O texto de resposta do assistente no primeiro turno sintetizado.',
};
export const panelText: Partial<typeof panelEn> = {
  workspace: 'Espaço de trabalho',
  workspaceDesc: 'Salvar faz um commit no repositório Git do espaço de trabalho, com operator como autor.',
  history: 'Histórico de versões',
  saved: 'Salvo',
  removed: 'Excluído',
  renamed: 'Renomeado',
  committed: (done: string, hash: string) => `${done}, com commit (${hash})`,
  notCommitted: (done: string) => `${done} (sem commit no git: nenhuma alteração ou git indisponível)`,
  missingArg: (what: string) => `Falta ${what}`,
  movedOrDeleted: 'O arquivo foi movido ou excluído',
  changedBeforeSave: 'O arquivo foi alterado em outro lugar; recarregue-o antes de salvar',
  changedBeforeRemove: 'O arquivo foi alterado em outro lugar; recarregue-o antes de excluir',
  changedBeforeRename: 'O arquivo foi alterado em outro lugar; recarregue-o antes de renomear',
  fileMissing: (path: string) => `O arquivo não existe: ${path}`,
  isDirectory: (path: string) => `${path} é uma pasta, não um arquivo`,
  tooLargeToPreview: 'O arquivo passa de 1MB; sem prévia',
  binaryFile: 'Arquivo binário; sem prévia',
  contentNotString: 'content precisa ser uma string',
  nulInText: 'O texto não pode conter caracteres NUL',
  tooLargeToSave: 'O arquivo passa de 1MB e não foi salvo',
  nameTaken: 'Já existe um arquivo com esse nome',
  unknownMethod: (panel: string, method: string) => `Método de painel desconhecido: ${panel}.${method}`,
  unknownPanel: (panel: string) => `Painel desconhecido: ${panel}`,
};
