import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: '拡張機能',
  navGroup: 'Core',
  introTitle: '拡張機能',
  scope: '拡張機能は共有の拡張機能ディレクトリにインストールされ、インストールと削除はプロセスの再起動後に反映されます。拡張機能を削除すると共有パッケージが削除されます。',
  tabs: { world: 'World 拡張機能', provider: 'プロバイダー拡張機能', bot: 'ボットテンプレート' },

  installedTitle: 'インストール済み',
  market: '拡張機能マーケット',
  manual: '手動インストール',
  refresh: '↻ 更新',
  restartProcess: 'プロセスを再起動',

  stateLoaded: '読み込み済み',
  stateFailed: '読み込み失敗',
  statePendingRestart: '再起動待ち',
  stateRemoved: 'アンインストール済み、再起動待ち',
  enabled: 'このボットに読み込み済み',
  disabled: 'インストール済み、未読み込み',
  adopted: 'このボットで使用中',
  template: 'インストール済み、インスタンスを作成可能',
  hidden: 'エージェントから非表示',
  runtimeVersion: (version: string) => `プロセスはまだ ${version} を使用中`,

  providerManagement: 'プロバイダー拡張機能は、この共有環境を使うボットに提供されます。',
  idleManagement: 'World の有効化と無効化は World ページで行います。組み込みの拡張機能は削除できません。',
  createBody: 'Cortico を実行しているコンピューターでプロジェクトのターミナルを開き、pnpm start --new を実行して、このボットテンプレートを選んで新しいインスタンスを作成してください。',

  restartConfirmTitle: 'プロセスを再起動しますか？',
  restartNoLoopTitle: '手動での起動が必要です',
  restartConfirmBody: 'プロセスが再起動します。',
  restartNoLoopBody: 'プロセスが終了し、手動で再起動する必要があります。続行しますか？',
  stepIncomplete: '未完了',
  doneRestartSupervised: '終了しました。再起動を待っています',
  doneRestart: '終了しました',
  resultDefault: 'シャットダウン手順を実行しました。',
  reloadWait: 'このボットの新しいプロセスの準備ができるのを待っています…',
  otherBot: 'このポートは別のボットが使用しているため、復帰を中止しました。',
  restartManual: 'プロセスが終了しました。ターミナルで手動で起動してください。このページは準備ができるまで待機します。',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: '更新',
  updateCheckFailed: (detail: string) => `更新の確認に失敗しました：${detail}`,
  noteConsoleMissing: 'ブラウザー用のビルド成果物がありません。拡張機能ディレクトリでビルドしてから、プロセスを再起動してください。',
  noExtensions: '拡張機能はまだインストールされていません',
  listLoadFailed: (msg: string) => `拡張機能の一覧を読み込めませんでした：${msg}`,

  eraseConfirm: '削除を確定',
  remove: '拡張機能を削除',
  removeInUse: 'このボットで使用中です。無効にしてから削除してください。',
  removeBody: 'このパッケージを共有の拡張機能ディレクトリから削除します。プロセスの再起動後に反映されます。これを使っている他のボットにも影響します。Memory、保存済みの設定、ローカルの拡張機能ソースは削除されません。',
  builtin: '組み込み',
  builtinNote: 'Cortico に同梱されているため、個別には削除できません。',

  installedAction: 'インストール',
  updatedAction: '更新',
  deletedAction: '削除',
  progress: (action: string, name: string) => `${action}中：${name}…`,
  completed: (action: string, name: string) => `${action}が完了しました：${name}。`,
  restartNeeded: 'プロセスの再起動後に反映されます。',
  syncedFailed: '操作は完了しましたが、一覧が同期されていません。更新してください。',

  filterPlaceholder: '絞り込み：パッケージ名、説明、キーワード',
  installedFilter: '絞り込み：名前、種類、説明',
  sortLabel: {
    downloads: 'ダウンロード数（30 日）',
    date: '最近の公開',
    name: '名前',
  },
  hideInstalled: 'インストール済みを隠す',
  perPage: '1 ページの表示数',
  automaticCount: (n: number) => `自動（${n}）`,
  shown: (from: number, to: number, total: number) => `${total} 件中 ${from}–${to} 件を表示`,
  prevPage: '‹ 前へ',
  nextPage: '次へ ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: '読み込み中…',
  noPackages: 'npm にはまだこの種類のパッケージがありません',
  noHits: '一致するパッケージがありません',
  searchFailed: (msg: string) => `読み込みに失敗しました：${msg}`,
  partial: 'npm の検索結果は一部のみ表示しています。正確なパッケージ名は手動インストールで指定してください。',

  loadingDetail: 'パッケージ情報を読み込み中…',
  introduction: '説明',
  information: '情報',
  deprecated: (note: string) => `npm で非推奨とされています：${note}`,
  packageName: 'パッケージ名',
  authorLabel: '作成者',
  unknownAuthor: '未記載',
  fieldInstalledVersion: 'インストール済みのバージョン',
  directory: 'インストール先',
  runtime: '実行中のバージョン',
  fieldVersion: '最新バージョン',
  fieldLicense: 'ライセンス',
  released: '公開日',
  fieldReleases: 'リリース',
  releaseCount: (n: number, created: string) => `${n} バージョン${created ? `、初回公開 ${created}` : ''}`,
  fieldSize: 'サイズ',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} ファイル`,
  fieldMaintainers: 'メンテナー',
  fieldNode: 'Node',
  fieldDeps: '依存関係',
  none: 'なし',
  fieldKeywords: 'キーワード',
  fieldDownloads: 'ダウンロード',
  fieldDependents: '被依存',
  fieldHistory: 'バージョン履歴',
  noHistory: 'リリース履歴はありません。',
  currentVersion: '現在のバージョン',
  installVersion: 'このバージョンをインストール',
  localVersionNote: 'ローカルリンクでは npm のバージョンを切り替えられません。',
  versionConfirmTitle: 'このバージョンをインストールしますか？',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? '未インストール'} → ${target}\n共有パッケージが変更され、これを使っている他のボットにも影響します。再起動後に反映されます。設定と Memory は保持されます。`,
  linkNames: { npm: 'npm パッケージページ', repository: 'ソースリポジトリ', homepage: 'プロジェクトのホームページ', bugs: '問題を報告' },
  install: 'インストール',
  alreadyInstalled: 'インストール済み',

  npm: 'npm からインストール',
  local: 'ローカルディレクトリからインストール',
  npmHelp: 'npm パッケージ名を入力してください。@バージョンまたはタグを付けられます。Web ページの URL は入力しないでください。',
  localHelp: 'Cortico を実行しているコンピューター上の、package.json を含む拡張機能ディレクトリを選択してください。拡張機能はリンクで接続されます。ソースを更新した後は再ビルドと再起動が必要になる場合があります。インストールの記録を削除してもソースディレクトリは削除されません。',
  folder: 'フォルダーを選択',
  pathLabel: '拡張機能のプロジェクトディレクトリ',
  packageLabel: 'パッケージ名とバージョン',
  check: '有効性を確認',
  checkOk: '確認に合格しました',
  invalidInput: '有効な npm パッケージ名を入力してください。明確なバージョンまたはタグを付けられます。',

  version: (v: string) => `バージョン：${v}`,
  author: (v: string) => `作成者：${v}`,
  downloads: (total: string, month: string, week: string) => `累計 ${total} · 30 日 ${month} · 7 日 ${week}`,
  labelled: (label: string, value: string) => `${label}：${value}`,
  metaSeparator: '　',
  listSeparator: '、',
};
