import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Extensões',
  navGroup: 'Core',
  introTitle: 'Extensões',
  scope: 'As extensões são instaladas no diretório compartilhado de extensões; instalar e excluir têm efeito após reiniciar o processo. Excluir uma extensão remove o pacote compartilhado.',
  tabs: { world: 'Extensões de World', provider: 'Extensões de provedor', bot: 'Modelos de Bot' },

  installedTitle: 'Instaladas',
  market: 'Mercado de extensões',
  manual: 'Instalação manual',
  refresh: '↻ Atualizar',
  restartProcess: 'Reiniciar processo',

  stateLoaded: 'Carregada',
  stateFailed: 'Falha ao carregar',
  statePendingRestart: 'Reinício pendente',
  stateRemoved: 'Desinstalada, reinício pendente',
  enabled: 'Carregada neste Bot',
  disabled: 'Instalada, não carregada',
  adopted: 'Em uso por este Bot',
  template: 'Instalada; pronta para criar instâncias',
  hidden: 'Oculta para o agente',
  runtimeVersion: (version: string) => `O processo ainda usa ${version}`,

  providerManagement: 'As extensões de provedor atendem aos Bots que usam este ambiente compartilhado.',
  idleManagement: 'Ative ou desative Worlds na página de World. Extensões integradas não podem ser excluídas.',
  createBody: 'Abra um terminal no projeto Cortico no host dele, execute pnpm start --new e selecione este modelo de Bot para criar uma nova instância.',

  restartConfirmTitle: 'Reiniciar o processo?',
  restartNoLoopTitle: 'Inicialização manual necessária',
  restartConfirmBody: 'O processo será reiniciado.',
  restartNoLoopBody: 'O processo será encerrado e precisará ser reiniciado manualmente. Continuar?',
  stepIncomplete: 'não concluída',
  doneRestartSupervised: 'Encerrado; aguardando reinício',
  doneRestart: 'Encerrado',
  resultDefault: 'Etapas de desligamento executadas.',
  reloadWait: 'Aguardando um novo processo deste Bot ficar pronto…',
  otherBot: 'Outro Bot está usando esta porta. A recuperação foi interrompida.',
  restartManual: 'O processo foi encerrado. Inicie-o manualmente no terminal; esta página vai aguardar até que esteja pronto.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Atualizar',
  updateCheckFailed: (detail: string) => `Falha ao verificar atualizações: ${detail}`,
  noteConsoleMissing: 'Pacote do navegador ausente. Compile no diretório da extensão e reinicie o processo.',
  noExtensions: 'Nenhuma extensão instalada ainda',
  listLoadFailed: (msg: string) => `Falha ao carregar a lista de extensões: ${msg}`,

  eraseConfirm: 'Confirmar exclusão',
  remove: 'Excluir extensão',
  removeInUse: 'Em uso por este Bot. Desative-a antes de excluir.',
  removeBody: 'Remove este pacote do diretório compartilhado de extensões; tem efeito após reiniciar o processo. Outros Bots que o usam são afetados. A Memory, a configuração salva e os diretórios de código-fonte locais são mantidos.',
  builtin: 'Integrada',
  builtinNote: 'Incluída no Cortico; não pode ser excluída separadamente.',

  installedAction: 'Instalação',
  updatedAction: 'Atualização',
  deletedAction: 'Exclusão',
  progress: (action: string, name: string) => `${action} em andamento: ${name}…`,
  completed: (action: string, name: string) => `${action} concluída: ${name}.`,
  restartNeeded: 'Tem efeito após reiniciar o processo.',
  syncedFailed: 'Operação concluída, mas a lista está dessincronizada. Atualize para tentar de novo.',

  filterPlaceholder: 'Filtrar: nome, descrição, palavras-chave',
  installedFilter: 'Filtrar: nome, tipo, descrição',
  sortLabel: {
    downloads: 'Downloads (30 dias)',
    date: 'Publicadas recentemente',
    name: 'Nome',
  },
  hideInstalled: 'Ocultar instaladas',
  perPage: 'Por página',
  automaticCount: (n: number) => `Automático (${n})`,
  shown: (from: number, to: number, total: number) => `Mostrando ${from}–${to} de ${total}`,
  prevPage: '‹ Anterior',
  nextPage: 'Próxima ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Carregando…',
  noPackages: 'Ainda não há pacotes deste tipo no npm',
  noHits: 'Nenhum pacote correspondente',
  searchFailed: (msg: string) => `Falha ao carregar: ${msg}`,
  partial: 'Os resultados do npm estão incompletos. Use a instalação manual para um nome de pacote exato.',

  loadingDetail: 'Carregando informações do pacote…',
  introduction: 'Descrição',
  information: 'Informações',
  deprecated: (note: string) => `Obsoleto no npm: ${note}`,
  packageName: 'Pacote',
  authorLabel: 'Autor',
  unknownAuthor: 'Não informado',
  fieldInstalledVersion: 'Versão instalada',
  directory: 'Local de instalação',
  runtime: 'Versão em execução',
  fieldVersion: 'Mais recente',
  fieldLicense: 'Licença',
  released: 'Publicado',
  fieldReleases: 'Versões',
  releaseCount: (n: number, created: string) => `${n} ${n === 1 ? 'versão' : 'versões'}${created ? `, a primeira em ${created}` : ''}`,
  fieldSize: 'Tamanho',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} ${files === 1 ? 'arquivo' : 'arquivos'}`,
  fieldMaintainers: 'Mantenedores',
  fieldNode: 'Node',
  fieldDeps: 'Dependências',
  none: 'nenhuma',
  fieldKeywords: 'Palavras-chave',
  fieldDownloads: 'Downloads',
  fieldDependents: 'Dependentes',
  fieldHistory: 'Histórico de versões',
  noHistory: 'Nenhum histórico de versões disponível.',
  currentVersion: 'Versão atual',
  installVersion: 'Instalar esta versão',
  localVersionNote: 'Links locais não podem trocar de versão do npm.',
  versionConfirmTitle: 'Instalar esta versão?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'Não instalado'} → ${target}\nIsto altera o pacote compartilhado e afeta outros Bots que o usam. Tem efeito após reiniciar. A configuração e a Memory são mantidas.`,
  linkNames: { npm: 'Pacote npm', repository: 'Repositório do código-fonte', homepage: 'Página do projeto', bugs: 'Relatar um problema' },
  install: 'Instalar',
  alreadyInstalled: 'Instalada',

  npm: 'Do npm',
  local: 'De um diretório local',
  npmHelp: 'Digite um nome de pacote npm, opcionalmente seguido de @versão ou uma tag. Não digite a URL de um site.',
  localHelp: 'Selecione um diretório que contenha package.json no host do Cortico. Extensões locais são vinculadas; alterações no código-fonte podem exigir recompilar e reiniciar. Excluir a instalação mantém o código-fonte.',
  folder: 'Escolher pasta',
  pathLabel: 'Diretório da extensão',
  packageLabel: 'Pacote e versão',
  check: 'Verificar extensão',
  checkOk: 'Verificação aprovada',
  invalidInput: 'Digite um nome de pacote npm válido, opcionalmente com uma versão exata ou tag.',

  version: (v: string) => `Versão: ${v}`,
  author: (v: string) => `Autor: ${v}`,
  downloads: (total: string, month: string, week: string) => `Total ${total} · 30 d ${month} · 7 d ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
