import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Extensions',
  navGroup: 'Core',
  introTitle: 'Extensions',
  scope: "Les extensions sont installées dans le répertoire d'extensions partagé ; l'installation et la suppression prennent effet après le redémarrage du processus. Supprimer une extension retire le paquet partagé.",
  tabs: { world: 'Extensions World', provider: 'Extensions de fournisseur', bot: 'Modèles de bot' },

  installedTitle: 'Installées',
  market: "Catalogue d'extensions",
  manual: 'Installation manuelle',
  refresh: '↻ Actualiser',
  restartProcess: 'Redémarrer le processus',

  stateLoaded: 'Chargée',
  stateFailed: 'Échec du chargement',
  statePendingRestart: 'Redémarrage requis',
  stateRemoved: 'Désinstallée, redémarrage requis',
  enabled: 'Chargée dans ce bot',
  disabled: 'Installée, non chargée',
  adopted: 'Utilisée par ce bot',
  template: 'Installée ; prête à créer des instances',
  hidden: "Masquée pour l'agent",
  runtimeVersion: (version: string) => `Le processus utilise encore ${version}`,

  providerManagement: 'Les extensions de fournisseur servent les bots qui utilisent cet environnement partagé.',
  idleManagement: 'Activez ou désactivez les World sur la page World. Les extensions intégrées ne peuvent pas être supprimées.',
  createBody: 'Ouvrez un terminal dans le projet Cortico sur sa machine hôte, lancez pnpm start --new, puis sélectionnez ce modèle de bot pour créer une nouvelle instance.',

  restartConfirmTitle: 'Redémarrer le processus ?',
  restartNoLoopTitle: 'Démarrage manuel requis',
  restartConfirmBody: 'Le processus va redémarrer.',
  restartNoLoopBody: 'Le processus va se terminer et devra être redémarré manuellement. Continuer ?',
  stepIncomplete: 'incomplet',
  doneRestartSupervised: 'Processus terminé ; en attente du redémarrage',
  doneRestart: 'Processus terminé',
  resultDefault: "Étapes d'arrêt exécutées.",
  reloadWait: "En attente qu'un nouveau processus de ce bot soit prêt…",
  otherBot: 'Un autre bot utilise ce port. Récupération arrêtée.',
  restartManual: "Le processus est terminé. Démarrez-le manuellement dans le terminal ; cette page attendra qu'il soit prêt.",

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Mettre à jour',
  updateCheckFailed: (detail: string) => `Échec de la vérification des mises à jour : ${detail}`,
  noteConsoleMissing: "Bundle navigateur manquant. Compilez dans le répertoire de l'extension et redémarrez le processus.",
  noExtensions: 'Aucune extension installée',
  listLoadFailed: (msg: string) => `Échec du chargement de la liste des extensions : ${msg}`,

  eraseConfirm: 'Confirmer la suppression',
  remove: "Supprimer l'extension",
  removeInUse: 'Utilisée par ce bot. Désactivez-la avant de la supprimer.',
  removeBody: "Retire ce paquet du répertoire d'extensions partagé ; prend effet après le redémarrage du processus. Les autres bots qui l'utilisent sont concernés. Memory, la configuration enregistrée et les répertoires sources locaux sont conservés.",
  builtin: 'Intégrée',
  builtinNote: 'Fournie avec Cortico ; ne peut pas être supprimée séparément.',

  installedAction: 'Installation',
  updatedAction: 'Mise à jour',
  deletedAction: 'Suppression',
  progress: (action: string, name: string) => `${action} de ${name} en cours…`,
  completed: (action: string, name: string) => `${action} de ${name} réussie.`,
  restartNeeded: 'Prend effet après le redémarrage du processus.',
  syncedFailed: "Opération terminée, mais la liste n'est pas synchronisée. Actualisez pour réessayer.",

  filterPlaceholder: 'Filtrer : nom, description, mots-clés',
  installedFilter: 'Filtrer : nom, type, description',
  sortLabel: {
    downloads: 'Téléchargements (30 jours)',
    date: 'Publiés récemment',
    name: 'Nom',
  },
  hideInstalled: 'Masquer les installées',
  perPage: 'Par page',
  automaticCount: (n: number) => `Automatique (${n})`,
  shown: (from: number, to: number, total: number) => `${from}–${to} sur ${total}`,
  prevPage: '‹ Précédent',
  nextPage: 'Suivant ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Chargement…',
  noPackages: 'Aucun paquet de ce type sur npm',
  noHits: 'Aucun paquet correspondant',
  searchFailed: (msg: string) => `Échec du chargement : ${msg}`,
  partial: "Les résultats npm sont incomplets. Utilisez l'installation manuelle pour un nom de paquet exact.",

  loadingDetail: 'Chargement des informations du paquet…',
  introduction: 'Présentation',
  information: 'Informations',
  deprecated: (note: string) => `Obsolète sur npm : ${note}`,
  packageName: 'Paquet',
  authorLabel: 'Auteur',
  unknownAuthor: 'Non fourni',
  fieldInstalledVersion: 'Version installée',
  directory: "Emplacement d'installation",
  runtime: "Version en cours d'exécution",
  fieldVersion: 'Dernière',
  fieldLicense: 'Licence',
  released: 'Publié',
  fieldReleases: 'Versions',
  releaseCount: (n: number, created: string) => `${n} version${n > 1 ? 's' : ''}${created ? `, première ${created}` : ''}`,
  fieldSize: 'Taille',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} fichier${files > 1 ? 's' : ''}`,
  fieldMaintainers: 'Mainteneurs',
  fieldNode: 'Node',
  fieldDeps: 'Dépendances',
  none: 'aucune',
  fieldKeywords: 'Mots-clés',
  fieldDownloads: 'Téléchargements',
  fieldDependents: 'Dépendants',
  fieldHistory: 'Historique des versions',
  noHistory: 'Aucun historique de publication.',
  currentVersion: 'Version actuelle',
  installVersion: 'Installer cette version',
  localVersionNote: 'Les liens locaux ne peuvent pas changer de version npm.',
  versionConfirmTitle: 'Installer cette version ?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'Non installé'} → ${target}\nCela modifie le paquet partagé et concerne les autres bots qui l'utilisent. Prend effet après le redémarrage. La configuration et Memory sont conservées.`,
  linkNames: { npm: 'Paquet npm', repository: 'Dépôt source', homepage: 'Page du projet', bugs: 'Signaler un problème' },
  install: 'Installer',
  alreadyInstalled: 'Installé',

  npm: 'Depuis npm',
  local: 'Depuis un répertoire local',
  npmHelp: "Saisissez un nom de paquet npm, éventuellement suivi de @version ou d'un tag. Ne saisissez pas d'URL de site web.",
  localHelp: "Sélectionnez un répertoire contenant package.json sur l'hôte de Cortico. Les extensions locales sont liées ; les modifications du code source peuvent nécessiter une recompilation et un redémarrage. Supprimer l'installation conserve le code source.",
  folder: 'Choisir un dossier',
  pathLabel: "Répertoire de l'extension",
  packageLabel: 'Paquet et version',
  check: "Vérifier l'extension",
  checkOk: 'Vérification réussie',
  invalidInput: 'Saisissez un nom de paquet npm valide, éventuellement avec une version exacte ou un tag.',

  version: (v: string) => `Version : ${v}`,
  author: (v: string) => `Auteur : ${v}`,
  downloads: (total: string, month: string, week: string) => `Total ${total} · 30 j ${month} · 7 j ${week}`,
  labelled: (label: string, value: string) => `${label} : ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
