import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Erweiterungen',
  navGroup: 'Core',
  introTitle: 'Erweiterungen',
  scope: 'Erweiterungen werden im gemeinsamen Erweiterungsverzeichnis installiert; Installieren und Löschen gelten nach dem Neustart des Prozesses. Das Löschen einer Erweiterung entfernt das gemeinsame Paket.',
  tabs: { world: 'World-Erweiterungen', provider: 'Anbieter-Erweiterungen', bot: 'Bot-Vorlagen' },

  installedTitle: 'Installiert',
  market: 'Erweiterungsmarkt',
  manual: 'Manuelle Installation',
  refresh: '↻ Aktualisieren',
  restartProcess: 'Prozess neu starten',

  stateLoaded: 'Geladen',
  stateFailed: 'Laden fehlgeschlagen',
  statePendingRestart: 'Neustart ausstehend',
  stateRemoved: 'Deinstalliert, Neustart ausstehend',
  enabled: 'In diesen Bot geladen',
  disabled: 'Installiert, nicht geladen',
  adopted: 'Von diesem Bot verwendet',
  template: 'Installiert; bereit zum Erstellen von Instanzen',
  hidden: 'Vor dem Agenten verborgen',
  runtimeVersion: (version: string) => `Der Prozess nutzt noch ${version}`,

  providerManagement: 'Anbieter-Erweiterungen dienen den Bots, die diese gemeinsame Umgebung nutzen.',
  idleManagement: 'Aktiviere oder deaktiviere Worlds auf der World-Seite. Integrierte Erweiterungen können nicht gelöscht werden.',
  createBody: 'Öffne auf dem Host ein Terminal im Cortico-Projekt, führe pnpm start --new aus und wähle dann diese Bot-Vorlage, um eine neue Instanz zu erstellen.',

  restartConfirmTitle: 'Prozess neu starten?',
  restartNoLoopTitle: 'Manueller Start erforderlich',
  restartConfirmBody: 'Der Prozess wird neu gestartet.',
  restartNoLoopBody: 'Der Prozess wird beendet und muss manuell neu gestartet werden. Fortfahren?',
  stepIncomplete: 'unvollständig',
  doneRestartSupervised: 'Beendet; warte auf Neustart',
  doneRestart: 'Beendet',
  resultDefault: 'Schritte zum Herunterfahren ausgeführt.',
  reloadWait: 'Warte, bis ein neuer Prozess dieses Bots bereit ist…',
  otherBot: 'Ein anderer Bot nutzt diesen Port. Wiederherstellung gestoppt.',
  restartManual: 'Der Prozess wurde beendet. Starte ihn manuell im Terminal; diese Seite wartet, bis er bereit ist.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Aktualisieren',
  updateCheckFailed: (detail: string) => `Update-Prüfung fehlgeschlagen: ${detail}`,
  noteConsoleMissing: 'Browser-Bundle fehlt. Baue im Erweiterungsverzeichnis und starte den Prozess neu.',
  noExtensions: 'Noch keine Erweiterungen installiert',
  listLoadFailed: (msg: string) => `Erweiterungsliste konnte nicht geladen werden: ${msg}`,

  eraseConfirm: 'Löschen bestätigen',
  remove: 'Erweiterung löschen',
  removeInUse: 'Wird von diesem Bot verwendet. Deaktiviere sie vor dem Löschen.',
  removeBody: 'Entfernt dieses Paket aus dem gemeinsamen Erweiterungsverzeichnis; gilt nach dem Neustart des Prozesses. Andere Bots, die es nutzen, sind betroffen. Memory, gespeicherte Konfiguration und lokale Quellverzeichnisse bleiben erhalten.',
  builtin: 'Integriert',
  builtinNote: 'Wird mit Cortico ausgeliefert; kann nicht einzeln gelöscht werden.',

  installedAction: 'Installation',
  updatedAction: 'Aktualisierung',
  deletedAction: 'Löschen',
  progress: (action: string, name: string) => `${action} von ${name} läuft…`,
  completed: (action: string, name: string) => `${action} von ${name} abgeschlossen.`,
  restartNeeded: 'Gilt nach dem Neustart des Prozesses.',
  syncedFailed: 'Vorgang abgeschlossen, aber die Liste ist nicht synchron. Aktualisiere, um es erneut zu versuchen.',

  filterPlaceholder: 'Filter: Name, Beschreibung, Stichwörter',
  installedFilter: 'Filter: Name, Typ, Beschreibung',
  sortLabel: {
    downloads: 'Downloads (30 Tage)',
    date: 'Kürzlich veröffentlicht',
    name: 'Name',
  },
  hideInstalled: 'Installierte ausblenden',
  perPage: 'Pro Seite',
  automaticCount: (n: number) => `Automatisch (${n})`,
  shown: (from: number, to: number, total: number) => `${from}–${to} von ${total}`,
  prevPage: '‹ Zurück',
  nextPage: 'Weiter ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Lädt…',
  noPackages: 'Noch keine Pakete dieser Art auf npm',
  noHits: 'Keine passenden Pakete',
  searchFailed: (msg: string) => `Laden fehlgeschlagen: ${msg}`,
  partial: 'Die npm-Ergebnisse sind unvollständig. Nutze die manuelle Installation für einen exakten Paketnamen.',

  loadingDetail: 'Paketinformationen werden geladen…',
  introduction: 'Beschreibung',
  information: 'Informationen',
  deprecated: (note: string) => `Auf npm als veraltet markiert: ${note}`,
  packageName: 'Paket',
  authorLabel: 'Autor',
  unknownAuthor: 'Nicht angegeben',
  fieldInstalledVersion: 'Installierte Version',
  directory: 'Installationsort',
  runtime: 'Laufende Version',
  fieldVersion: 'Neueste',
  fieldLicense: 'Lizenz',
  released: 'Veröffentlicht',
  fieldReleases: 'Veröffentlichungen',
  releaseCount: (n: number, created: string) => `${n} ${n === 1 ? 'Version' : 'Versionen'}${created ? `, erste ${created}` : ''}`,
  fieldSize: 'Größe',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} ${files === 1 ? 'Datei' : 'Dateien'}`,
  fieldMaintainers: 'Betreuer',
  fieldNode: 'Node',
  fieldDeps: 'Abhängigkeiten',
  none: 'keine',
  fieldKeywords: 'Stichwörter',
  fieldDownloads: 'Downloads',
  fieldDependents: 'Abhängige',
  fieldHistory: 'Versionsverlauf',
  noHistory: 'Kein Veröffentlichungsverlauf vorhanden.',
  currentVersion: 'Aktuelle Version',
  installVersion: 'Diese Version installieren',
  localVersionNote: 'Lokale Links können keine npm-Version wechseln.',
  versionConfirmTitle: 'Diese Version installieren?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'Nicht installiert'} → ${target}\nDas ändert das gemeinsame Paket und betrifft andere Bots, die es nutzen. Gilt nach dem Neustart. Konfiguration und Memory bleiben erhalten.`,
  linkNames: { npm: 'npm-Paket', repository: 'Quell-Repository', homepage: 'Projekt-Homepage', bugs: 'Problem melden' },
  install: 'Installieren',
  alreadyInstalled: 'Installiert',

  npm: 'Von npm',
  local: 'Aus lokalem Verzeichnis',
  npmHelp: 'Gib einen npm-Paketnamen ein, optional gefolgt von @Version oder einem Tag. Keine Website-URL eingeben.',
  localHelp: 'Wähle auf dem Cortico-Host ein Verzeichnis mit package.json. Lokale Erweiterungen werden verlinkt; Änderungen am Quellcode können Neubauen und Neustarten erfordern. Das Löschen der Installation behält den Quellcode.',
  folder: 'Ordner wählen',
  pathLabel: 'Erweiterungsverzeichnis',
  packageLabel: 'Paket und Version',
  check: 'Erweiterung prüfen',
  checkOk: 'Prüfung bestanden',
  invalidInput: 'Gib einen gültigen npm-Paketnamen ein, optional mit exakter Version oder Tag.',

  version: (v: string) => `Version: ${v}`,
  author: (v: string) => `Autor: ${v}`,
  downloads: (total: string, month: string, week: string) => `Gesamt ${total} · 30 T. ${month} · 7 T. ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
