import { pick } from '../../core/language.ts';

const zh = {
  navLabel: '扩展',
  navGroup: 'Core',
  introTitle: '扩展',
  introDesc: '从 npm 安装第三方 World、LLM Provider 和 bot 包。安装、卸载后需重启进程才能生效。',

  installedTitle: '已安装',
  refresh: '↻ 刷新',
  restartProcess: '重启进程',

  stateLoaded: '已加载',
  stateFailed: '加载失败',
  statePendingRestart: '待重启',
  stateRemoved: '已卸载，待重启',
  stateIdle: '已装，本部署未用',

  groupWorldDesc: '连接外部环境。',
  groupProviderDesc: '连接模型服务。',
  groupBotDesc: '提供 Persona 与 bot 装配。将包名填入 deployment.json 的 bot 字段；每个进程运行一个 bot。',
  groupUnknownTitle: '未识别',
  groupUnknownDesc: 'package.json 缺少有效的 cortico 声明。',

  restartConfirmTitle: '重启进程？',
  restartNoLoopTitle: '需要手动启动',
  restartConfirmBody: '进程将重启。',
  restartNoLoopBody: '进程将退出，需要手动重新启动。继续？',
  finishingToast: '正在关闭…',
  stepIncomplete: '未完成',
  doneRestartSupervised: '已退出，等待重新启动',
  doneRestart: '已退出',
  resultDefault: '关闭步骤已执行。',
  noReceipt: (msg: string) => `未收到关闭结果（${msg}）；进程可能已退出。`,

  uninstallTitle: (name: string) => `卸载「${name}」？`,
  uninstallBody: (name: string) => `从 extensions/ 卸载 ${name}，重启进程后生效。`,
  uninstalling: '正在卸载…',
  uninstalled: '已卸载',
  uninstallFailed: (msg: string) => `卸载失败： ${msg}`,
  uninstall: '卸载',

  installing: '正在安装…',
  installed: '已安装',
  installedVersion: (version: string) => `磁盘版本 ${version}，重启后加载`,
  checkingUpdates: '检查扩展更新…',
  updateCount: (count: number) => `可更新 ${count} 个扩展`,
  updateCheckFailed: (detail: string) => `更新检查失败： ${detail}`,
  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: '更新',
  updateWarningTitle: '新版扩展与当前框架不兼容，仍要更新？',
  installFailed: (msg: string) => `安装失败： ${msg}`,
  installedRestartTitle: '已安装，现在重启进程加载它？',
  installedRestartNote: '进程将重启。',
  installedNoLoopNote: '进程将退出，需要手动重新启动。',

  panelLoaded: '自定义面板已加载',
  noteIdle: '当前部署未引用此扩展。',
  noteConsoleMissing: '缺少浏览器构建产物。请在扩展目录构建，再重启进程。',

  sumLoaded: (n: number) => `已加载 ${n}`,
  sumPending: (n: number) => `待重启 ${n}`,
  sumFailed: (n: number) => `加载失败 ${n}`,
  noExtensions: '还没装任何扩展',
  listLoadFailed: (msg: string) => `扩展清单加载失败： ${msg}`,
  loading: '加载中…',

  searchTitle: '从 npm 安装',
  searchDesc: '扩展拥有与框架相同的文件和网络权限。',
  filterPlaceholder: '筛选：包名、描述、关键字',
  sortLabel: {
    downloads: '按月下载量',
    date: '按最近发布',
    name: '按名字',
    dependents: '按被依赖数',
  },
  hideInstalled: '隐藏已安装',
  searchKeywordNote: (keyword: string) => `列出 npm 上带 ${keyword} 关键字的包。`,
  searching: '读取中…',
  noPackages: 'npm 上还没有这一类的包',
  noHits: '没有匹配的包',
  hitCount: (n: number) => `${n} 个包`,
  hitCountFiltered: (shown: number, total: number) => `${shown} / ${total} 个包`,
  searchFailed: (msg: string) => `读取失败： ${msg}`,
  hitMeta: (version: string, downloads: string, publisher?: string) =>
    `${version} · 月下载 ${downloads}${publisher ? ` · ${publisher}` : ''}`,
  dependents: (n: number) => `被依赖 ${n}`,
  openDetail: '点开看详情',
  prevPage: '‹ 上一页',
  nextPage: '下一页 ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,

  loadingDetail: '读取包信息…',
  detailFailed: (msg: string) => `包信息读取失败： ${msg}`,
  apiPill: (api: number) => `契约 v${api}`,
  hasPanel: '自带控制台面板',
  notLoadable: '不是可装载的扩展',
  deprecated: (note: string) => `npm 上标了弃用： ${note}`,
  installedSpec: (spec: string) => `已安装 ${spec}`,
  fieldVersion: '最新版本',
  fieldReleases: '发布',
  releaseCount: (n: number, created: string) => `${n} 个版本${created ? `，首发 ${created}` : ''}`,
  fieldHistory: '近几版',
  fieldLicense: '许可证',
  fieldSize: '体积',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} 个文件`,
  fieldNode: 'Node',
  fieldDeps: '依赖',
  fieldDownloads: '下载',
  perMonth: (count: string) => `${count} / 月`,
  fieldDependents: '被依赖',
  fieldMaintainers: '维护者',
  fieldKeywords: '关键字',
  none: '无',
  linkRepo: '源代码仓库',
  linkHome: '主页',
  linkBugs: '问题反馈',
  install: '安装',
  alreadyInstalled: '已安装',

  manualTitle: '手动安装',
  manualDesc: '包名（可带 @版本）或含 package.json 的本机目录。本机目录通过链接安装。',
  manualPlaceholder: '@scope/name@1.2.0 或 ../my-module',
  manualEmpty: '先填包名或目录',
};

const en: typeof zh = {
  navLabel: 'Extensions',
  navGroup: 'Core',
  introTitle: 'Extensions',
  introDesc: 'Install third-party Worlds, LLM providers and bot packages from npm. '
    + 'Installations and removals take effect after restarting the process.',

  installedTitle: 'Installed',
  refresh: '↻ Refresh',
  restartProcess: 'Restart process',

  stateLoaded: 'Loaded',
  stateFailed: 'Load failed',
  statePendingRestart: 'Restart pending',
  stateRemoved: 'Uninstalled, restart pending',
  stateIdle: 'Installed, unused by this deployment',

  groupWorldDesc: 'Connects to an external environment.',
  groupProviderDesc: 'Connects to a model service.',
  groupBotDesc: 'Provides a Persona and bot assembly. Set the package name in the bot field of deployment.json; each process runs one bot.',
  groupUnknownTitle: 'Unrecognised',
  groupUnknownDesc: 'package.json has no valid cortico declaration.',

  restartConfirmTitle: 'Restart the process?',
  restartNoLoopTitle: 'Manual startup required',
  restartConfirmBody: 'The process will restart.',
  restartNoLoopBody: 'The process will exit and must be restarted manually. Continue?',
  finishingToast: 'Shutting down…',
  stepIncomplete: 'incomplete',
  doneRestartSupervised: 'Exited; waiting to restart',
  doneRestart: 'Exited',
  resultDefault: 'Shutdown steps executed.',
  noReceipt: (msg: string) => `No shutdown result received (${msg}); the process may have exited.`,

  uninstallTitle: (name: string) => `Uninstall "${name}"?`,
  uninstallBody: (name: string) => `Uninstall ${name} from extensions/. Takes effect after restarting the process.`,
  uninstalling: 'Uninstalling…',
  uninstalled: 'Uninstalled',
  uninstallFailed: (msg: string) => `Uninstall failed: ${msg}`,
  uninstall: 'Uninstall',

  installing: 'Installing…',
  installed: 'Installed',
  installedVersion: (version: string) => `On disk ${version}; loads after restart`,
  checkingUpdates: 'Checking extension updates…',
  updateCount: (count: number) => `${count} extension updates available`,
  updateCheckFailed: (detail: string) => `Update check failed: ${detail}`,
  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Update',
  updateWarningTitle: 'The new extension is incompatible with this framework. Update anyway?',
  installFailed: (msg: string) => `Install failed: ${msg}`,
  installedRestartTitle: 'Installed. Restart the process now to load it?',
  installedRestartNote: 'The process will restart.',
  installedNoLoopNote: 'The process will exit and must be restarted manually.',

  panelLoaded: 'Custom panel loaded',
  noteIdle: 'This deployment does not reference the extension.',
  noteConsoleMissing: 'Browser bundle missing. Build in the extension directory and restart the process.',

  sumLoaded: (n: number) => `${n} loaded`,
  sumPending: (n: number) => `${n} restart pending`,
  sumFailed: (n: number) => `${n} failed`,
  noExtensions: 'No extensions installed yet',
  listLoadFailed: (msg: string) => `Extension list failed to load: ${msg}`,
  loading: 'Loading…',

  searchTitle: 'Install from npm',
  searchDesc: 'Extensions have the same file and network access as the framework.',
  filterPlaceholder: 'Filter: name, description, keywords',
  sortLabel: {
    downloads: 'Monthly downloads',
    date: 'Recently published',
    name: 'Name',
    dependents: 'Dependents',
  },
  hideInstalled: 'Hide installed',
  searchKeywordNote: (keyword: string) => `Lists npm packages carrying the ${keyword} keyword.`,
  searching: 'Loading…',
  noPackages: 'No packages of this kind on npm yet',
  noHits: 'No matching packages',
  hitCount: (n: number) => `${n} packages`,
  hitCountFiltered: (shown: number, total: number) => `${shown} / ${total} packages`,
  searchFailed: (msg: string) => `Loading failed: ${msg}`,
  hitMeta: (version: string, downloads: string, publisher?: string) =>
    `${version} · ${downloads}/month${publisher ? ` · ${publisher}` : ''}`,
  dependents: (n: number) => `${n} dependents`,
  openDetail: 'Open for details',
  prevPage: '‹ Previous',
  nextPage: 'Next ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,

  loadingDetail: 'Loading package info…',
  detailFailed: (msg: string) => `Package info failed to load: ${msg}`,
  apiPill: (api: number) => `API v${api}`,
  hasPanel: 'Ships a console panel',
  notLoadable: 'Not a loadable extension',
  deprecated: (note: string) => `Deprecated on npm: ${note}`,
  installedSpec: (spec: string) => `Installed ${spec}`,
  fieldVersion: 'Latest',
  fieldReleases: 'Releases',
  releaseCount: (n: number, created: string) => `${n} versions${created ? `, first ${created}` : ''}`,
  fieldHistory: 'Recent',
  fieldLicense: 'License',
  fieldSize: 'Size',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} files`,
  fieldNode: 'Node',
  fieldDeps: 'Dependencies',
  fieldDownloads: 'Downloads',
  perMonth: (count: string) => `${count}/month`,
  fieldDependents: 'Dependents',
  fieldMaintainers: 'Maintainers',
  fieldKeywords: 'Keywords',
  none: 'none',
  linkRepo: 'Repository',
  linkHome: 'Homepage',
  linkBugs: 'Issues',
  install: 'Install',
  alreadyInstalled: 'Installed',

  manualTitle: 'Manual install',
  manualDesc: 'A package name (optionally @version) or a local directory containing package.json. Local directories are installed as links.',
  manualPlaceholder: '@scope/name@1.2.0 or ../my-module',
  manualEmpty: 'Fill in a package name or directory first',
};

export const S = pick({ zh, en });
