import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: '擴充功能',
  navGroup: 'Core',
  introTitle: '擴充功能',
  scope: '擴充功能安裝在共用的擴充功能目錄中，安裝與刪除在處理程序重新啟動後生效。刪除擴充功能會移除共用安裝套件。',
  tabs: { world: 'World 擴充功能', provider: '供應商擴充功能', bot: 'Bot 範本' },

  installedTitle: '已安裝',
  market: '擴充功能市集',
  manual: '手動安裝',
  refresh: '↻ 重新整理',
  restartProcess: '重新啟動處理程序',

  stateLoaded: '已載入',
  stateFailed: '載入失敗',
  statePendingRestart: '待重新啟動',
  stateRemoved: '已解除安裝，待重新啟動',
  enabled: '已載入到本 Bot',
  disabled: '已安裝，未載入',
  adopted: '目前 Bot 正在採用',
  template: '已安裝，可建立實例',
  hidden: '對 Agent 隱藏',
  runtimeVersion: (version: string) => `目前處理程序仍為 ${version}`,

  providerManagement: '供應商擴充功能供共用環境中的 Bot 使用。',
  idleManagement: '在 World 頁啟用或停用 World；內建擴充功能不能刪除。',
  createBody: '在執行 Cortico 的電腦上開啟專案終端機，執行 pnpm start --new，選擇此 Bot 範本並建立新實例。',

  restartConfirmTitle: '重新啟動處理程序？',
  restartNoLoopTitle: '需要手動啟動',
  restartConfirmBody: '處理程序將重新啟動。',
  restartNoLoopBody: '處理程序將結束，需要手動重新啟動。繼續？',
  stepIncomplete: '未完成',
  doneRestartSupervised: '已結束，等待重新啟動',
  doneRestart: '已結束',
  resultDefault: '關閉步驟已執行。',
  reloadWait: '等待目前 Bot 的新處理程序就緒…',
  otherBot: '此連接埠已由另一個 Bot 使用，已停止恢復。',
  restartManual: '處理程序已結束，請在終端機手動啟動；此頁面會等待就緒。',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: '更新',
  updateCheckFailed: (detail: string) => `更新檢查失敗： ${detail}`,
  noteConsoleMissing: '缺少瀏覽器建置產物。請在擴充功能目錄建置，再重新啟動處理程序。',
  noExtensions: '還沒安裝任何擴充功能',
  listLoadFailed: (msg: string) => `擴充功能清單載入失敗： ${msg}`,

  eraseConfirm: '確認刪除',
  remove: '刪除擴充功能',
  removeInUse: '正在本 Bot 中使用，停用後才能刪除。',
  removeBody: '將從共用擴充功能目錄移除此擴充套件，重新啟動處理程序後生效。使用它的其他 Bot 也會受到影響。不會刪除 Memory、既有設定或本機擴充功能原始碼。',
  builtin: '內建擴充功能',
  builtinNote: '隨 Cortico 提供，不能單獨刪除。',

  installedAction: '安裝',
  updatedAction: '更新',
  deletedAction: '刪除',
  progress: (action: string, name: string) => `正在${action}：${name}…`,
  completed: (action: string, name: string) => `${action}成功：${name}。`,
  restartNeeded: '重新啟動處理程序後生效。',
  syncedFailed: '操作已完成，但清單未同步；請重新整理。',

  filterPlaceholder: '篩選：套件名稱、描述、關鍵字',
  installedFilter: '篩選：名稱、類型、描述',
  sortLabel: {
    downloads: '依近 30 天下載量',
    date: '依最近發布',
    name: '依名稱',
  },
  hideInstalled: '隱藏已安裝',
  perPage: '每頁顯示',
  automaticCount: (n: number) => `自動（${n}）`,
  shown: (from: number, to: number, total: number) => `顯示 ${from}–${to}，共 ${total} 個`,
  prevPage: '‹ 上一頁',
  nextPage: '下一頁 ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: '讀取中…',
  noPackages: 'npm 上還沒有這一類的套件',
  noHits: '沒有符合的套件',
  searchFailed: (msg: string) => `讀取失敗： ${msg}`,
  partial: '僅顯示部分 npm 搜尋結果，請使用手動安裝查找確切套件名稱。',

  loadingDetail: '讀取套件資訊…',
  introduction: '簡介',
  information: '資訊',
  deprecated: (note: string) => `npm 上標了棄用： ${note}`,
  packageName: '套件名稱',
  authorLabel: '作者',
  unknownAuthor: '未提供',
  fieldInstalledVersion: '已安裝版本',
  directory: '安裝位置',
  runtime: '執行版本',
  fieldVersion: '最新版本',
  fieldLicense: '授權條款',
  released: '發布日期',
  fieldReleases: '發布',
  releaseCount: (n: number, created: string) => `${n} 個版本${created ? `，首發 ${created}` : ''}`,
  fieldSize: '大小',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} 個檔案`,
  fieldMaintainers: '維護者',
  fieldNode: 'Node',
  fieldDeps: '相依套件',
  none: '無',
  fieldKeywords: '關鍵字',
  fieldDownloads: '下載',
  fieldDependents: '被相依',
  fieldHistory: '歷史版本',
  noHistory: '暫無發布歷史。',
  currentVersion: '目前版本',
  installVersion: '安裝此版本',
  localVersionNote: '本機連結不能切換 npm 版本。',
  versionConfirmTitle: '安裝此版本？',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? '未安裝'} → ${target}\n將修改共用安裝套件，使用它的其他 Bot 也會受到影響。重新啟動處理程序後生效。設定和 Memory 保留。`,
  linkNames: { npm: 'npm 套件頁面', repository: '原始碼儲存庫', homepage: '專案首頁', bugs: '問題回報' },
  install: '安裝',
  alreadyInstalled: '已安裝',

  npm: '從 npm 安裝',
  local: '從本機目錄安裝',
  npmHelp: '輸入 npm 套件名稱，可附帶 @版本或標籤；不要填寫網頁連結。',
  localHelp: '選擇執行 Cortico 的電腦上包含 package.json 的擴充功能目錄。擴充功能透過連結接入；更新原始碼後可能需要重新建置並重新啟動。刪除安裝記錄不會刪除來源目錄。',
  folder: '選擇資料夾',
  pathLabel: '擴充功能專案目錄',
  packageLabel: '套件名稱與版本',
  check: '檢查有效性',
  checkOk: '檢查通過',
  invalidInput: '請輸入有效的 npm 套件名稱，可附帶明確版本或標籤。',

  version: (v: string) => `版本：${v}`,
  author: (v: string) => `作者：${v}`,
  downloads: (total: string, month: string, week: string) => `累計 ${total} · 30 天 ${month} · 7 天 ${week}`,
  labelled: (label: string, value: string) => `${label}：${value}`,
  metaSeparator: '　',
  listSeparator: '、',
};
