import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: '확장',
  navGroup: 'Core',
  introTitle: '확장',
  scope: '확장은 공유 확장 디렉터리에 설치되며, 설치와 삭제는 프로세스를 재시작한 뒤 적용됩니다. 확장을 삭제하면 공유 패키지가 제거됩니다.',
  tabs: { world: 'World 확장', provider: '공급자 확장', bot: '봇 템플릿' },

  installedTitle: '설치됨',
  market: '확장 마켓',
  manual: '수동 설치',
  refresh: '↻ 새로 고침',
  restartProcess: '프로세스 재시작',

  stateLoaded: '로드됨',
  stateFailed: '로드 실패',
  statePendingRestart: '재시작 대기',
  stateRemoved: '제거됨, 재시작 대기',
  enabled: '이 봇에 로드됨',
  disabled: '설치됨, 로드 안 됨',
  adopted: '이 봇에서 사용 중',
  template: '설치됨, 인스턴스 생성 가능',
  hidden: '에이전트에게 숨김',
  runtimeVersion: (version: string) => `프로세스는 아직 ${version} 사용 중`,

  providerManagement: '공급자 확장은 이 공유 환경을 쓰는 봇에 제공됩니다.',
  idleManagement: 'World는 World 페이지에서 활성화하거나 비활성화하세요. 기본 제공 확장은 삭제할 수 없습니다.',
  createBody: 'Cortico를 실행하는 컴퓨터에서 프로젝트 터미널을 열고 pnpm start --new를 실행한 뒤, 이 봇 템플릿을 선택해 새 인스턴스를 만드세요.',

  restartConfirmTitle: '프로세스를 재시작하시겠습니까?',
  restartNoLoopTitle: '수동 시작 필요',
  restartConfirmBody: '프로세스가 재시작됩니다.',
  restartNoLoopBody: '프로세스가 종료되며 직접 다시 시작해야 합니다. 계속하시겠습니까?',
  stepIncomplete: '미완료',
  doneRestartSupervised: '종료됨, 다시 시작 대기 중',
  doneRestart: '종료됨',
  resultDefault: '종료 단계를 실행했습니다.',
  reloadWait: '이 봇의 새 프로세스가 준비되기를 기다리는 중…',
  otherBot: '다른 봇이 이 포트를 사용 중이어서 복구를 중단했습니다.',
  restartManual: '프로세스가 종료되었습니다. 터미널에서 직접 시작하세요. 이 페이지는 준비될 때까지 기다립니다.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: '업데이트',
  updateCheckFailed: (detail: string) => `업데이트 확인 실패: ${detail}`,
  noteConsoleMissing: '브라우저 빌드 결과물이 없습니다. 확장 디렉터리에서 빌드한 뒤 프로세스를 재시작하세요.',
  noExtensions: '아직 설치된 확장이 없습니다',
  listLoadFailed: (msg: string) => `확장 목록을 불러오지 못했습니다: ${msg}`,

  eraseConfirm: '삭제 확인',
  remove: '확장 삭제',
  removeInUse: '이 봇에서 사용 중입니다. 비활성화한 뒤 삭제하세요.',
  removeBody: '공유 확장 디렉터리에서 이 패키지를 제거하며, 프로세스를 재시작한 뒤 적용됩니다. 이 패키지를 쓰는 다른 봇도 영향을 받습니다. Memory, 저장된 설정, 로컬 확장 소스는 삭제되지 않습니다.',
  builtin: '기본 제공',
  builtinNote: 'Cortico에 포함되어 있어 따로 삭제할 수 없습니다.',

  installedAction: '설치',
  updatedAction: '업데이트',
  deletedAction: '삭제',
  progress: (action: string, name: string) => `${action} 중: ${name}…`,
  completed: (action: string, name: string) => `${action} 완료: ${name}.`,
  restartNeeded: '프로세스를 재시작한 뒤 적용됩니다.',
  syncedFailed: '작업은 끝났지만 목록이 동기화되지 않았습니다. 새로 고치세요.',

  filterPlaceholder: '필터: 패키지 이름, 설명, 키워드',
  installedFilter: '필터: 이름, 유형, 설명',
  sortLabel: {
    downloads: '다운로드 수(최근 30일)',
    date: '최근 게시순',
    name: '이름순',
  },
  hideInstalled: '설치된 항목 숨기기',
  perPage: '페이지당 표시',
  automaticCount: (n: number) => `자동(${n})`,
  shown: (from: number, to: number, total: number) => `전체 ${total}개 중 ${from}–${to} 표시`,
  prevPage: '‹ 이전',
  nextPage: '다음 ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: '불러오는 중…',
  noPackages: 'npm에 아직 이 종류의 패키지가 없습니다',
  noHits: '일치하는 패키지가 없습니다',
  searchFailed: (msg: string) => `불러오지 못했습니다: ${msg}`,
  partial: 'npm 검색 결과의 일부만 표시됩니다. 정확한 패키지 이름은 수동 설치로 지정하세요.',

  loadingDetail: '패키지 정보를 불러오는 중…',
  introduction: '소개',
  information: '정보',
  deprecated: (note: string) => `npm에서 사용 중단으로 표시됨: ${note}`,
  packageName: '패키지 이름',
  authorLabel: '작성자',
  unknownAuthor: '제공되지 않음',
  fieldInstalledVersion: '설치된 버전',
  directory: '설치 위치',
  runtime: '실행 중인 버전',
  fieldVersion: '최신 버전',
  fieldLicense: '라이선스',
  released: '게시일',
  fieldReleases: '릴리스',
  releaseCount: (n: number, created: string) => `버전 ${n}개${created ? `, 최초 게시 ${created}` : ''}`,
  fieldSize: '크기',
  sizeAndFiles: (size: string, files: number) => `${size} · 파일 ${files}개`,
  fieldMaintainers: '관리자',
  fieldNode: 'Node',
  fieldDeps: '종속성',
  none: '없음',
  fieldKeywords: '키워드',
  fieldDownloads: '다운로드',
  fieldDependents: '이 패키지에 의존하는 패키지',
  fieldHistory: '버전 기록',
  noHistory: '릴리스 기록이 없습니다.',
  currentVersion: '현재 버전',
  installVersion: '이 버전 설치',
  localVersionNote: '로컬 링크는 npm 버전을 전환할 수 없습니다.',
  versionConfirmTitle: '이 버전을 설치하시겠습니까?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? '설치 안 됨'} → ${target}\n공유 패키지가 바뀌므로 이를 쓰는 다른 봇도 영향을 받습니다. 재시작한 뒤 적용됩니다. 설정과 Memory는 유지됩니다.`,
  linkNames: { npm: 'npm 패키지 페이지', repository: '소스 저장소', homepage: '프로젝트 홈페이지', bugs: '문제 보고' },
  install: '설치',
  alreadyInstalled: '설치됨',

  npm: 'npm에서 설치',
  local: '로컬 디렉터리에서 설치',
  npmHelp: 'npm 패키지 이름을 입력하세요. @버전이나 태그를 붙일 수 있습니다. 웹 페이지 URL은 입력하지 마세요.',
  localHelp: 'Cortico를 실행하는 컴퓨터에서 package.json이 있는 확장 디렉터리를 선택하세요. 로컬 확장은 링크로 연결되며, 소스를 바꾼 뒤에는 다시 빌드하고 재시작해야 할 수 있습니다. 설치 기록을 삭제해도 소스 디렉터리는 남습니다.',
  folder: '폴더 선택',
  pathLabel: '확장 프로젝트 디렉터리',
  packageLabel: '패키지 이름과 버전',
  check: '유효성 검사',
  checkOk: '검사 통과',
  invalidInput: '올바른 npm 패키지 이름을 입력하세요. 정확한 버전이나 태그를 붙일 수 있습니다.',

  version: (v: string) => `버전: ${v}`,
  author: (v: string) => `작성자: ${v}`,
  downloads: (total: string, month: string, week: string) => `누적 ${total} · 30일 ${month} · 7일 ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
