import type { en } from './strings.ts';

const pluralRules = new Intl.PluralRules('ru');
const plural = (n: number, one: string, few: string, many: string) => {
  const form = pluralRules.select(n);
  return form === 'one' ? one : form === 'many' ? many : few;
};

export const S: Partial<typeof en> = {
  navLabel: 'Расширения',
  navGroup: 'Core',
  introTitle: 'Расширения',
  scope: 'Расширения устанавливаются в общую папку расширений; установка и удаление вступают в силу после перезапуска процесса. Удаление расширения удаляет общий пакет.',
  tabs: { world: 'Расширения World', provider: 'Расширения провайдеров', bot: 'Шаблоны ботов' },

  installedTitle: 'Установленные',
  market: 'Каталог расширений',
  manual: 'Ручная установка',
  refresh: '↻ Обновить',
  restartProcess: 'Перезапустить процесс',

  stateLoaded: 'Загружено',
  stateFailed: 'Ошибка загрузки',
  statePendingRestart: 'Ожидает перезапуска',
  stateRemoved: 'Удалено, ожидает перезапуска',
  enabled: 'Загружено в этот бот',
  disabled: 'Установлено, не загружено',
  adopted: 'Используется этим ботом',
  template: 'Установлено; можно создавать экземпляры',
  hidden: 'Скрыто от агента',
  runtimeVersion: (version: string) => `Процесс всё ещё использует ${version}`,

  providerManagement: 'Расширения провайдеров обслуживают ботов, использующих эту общую среду.',
  idleManagement: 'Включайте и отключайте World на странице World. Встроенные расширения удалить нельзя.',
  createBody: 'Откройте терминал в проекте Cortico на его хосте, выполните pnpm start --new, затем выберите этот шаблон бота, чтобы создать новый экземпляр.',

  restartConfirmTitle: 'Перезапустить процесс?',
  restartNoLoopTitle: 'Требуется ручной запуск',
  restartConfirmBody: 'Процесс будет перезапущен.',
  restartNoLoopBody: 'Процесс завершится, и его нужно будет запустить вручную. Продолжить?',
  stepIncomplete: 'не выполнен',
  doneRestartSupervised: 'Завершён; ожидание перезапуска',
  doneRestart: 'Завершён',
  resultDefault: 'Шаги выключения выполнены.',
  reloadWait: 'Ожидание готовности нового процесса этого бота…',
  otherBot: 'Этот порт использует другой бот. Восстановление остановлено.',
  restartManual: 'Процесс завершился. Запустите его вручную в терминале; эта страница дождётся готовности.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Обновить',
  updateCheckFailed: (detail: string) => `Не удалось проверить обновления: ${detail}`,
  noteConsoleMissing: 'Нет сборки для браузера. Соберите её в папке расширения и перезапустите процесс.',
  noExtensions: 'Расширения пока не установлены',
  listLoadFailed: (msg: string) => `Не удалось загрузить список расширений: ${msg}`,

  eraseConfirm: 'Подтвердить удаление',
  remove: 'Удалить расширение',
  removeInUse: 'Используется этим ботом. Отключите его перед удалением.',
  removeBody: 'Удаляет этот пакет из общей папки расширений; вступает в силу после перезапуска процесса. Это затронет другие боты, которые его используют. Memory, сохранённая конфигурация и локальные папки с исходным кодом сохраняются.',
  builtin: 'Встроенное',
  builtinNote: 'Входит в Cortico; удалить отдельно нельзя.',

  installedAction: 'Установка',
  updatedAction: 'Обновление',
  deletedAction: 'Удаление',
  progress: (action: string, name: string) => `${action} ${name}…`,
  completed: (action: string, name: string) => `${action} ${name}: готово.`,
  restartNeeded: 'Вступит в силу после перезапуска процесса.',
  syncedFailed: 'Операция выполнена, но список не синхронизирован. Обновите, чтобы повторить.',

  filterPlaceholder: 'Фильтр: имя, описание, ключевые слова',
  installedFilter: 'Фильтр: имя, тип, описание',
  sortLabel: {
    downloads: 'Скачивания (30 дней)',
    date: 'Недавно опубликованные',
    name: 'Имя',
  },
  hideInstalled: 'Скрыть установленные',
  perPage: 'На странице',
  automaticCount: (n: number) => `Авто (${n})`,
  shown: (from: number, to: number, total: number) => `Показано ${from}–${to} из ${total}`,
  prevPage: '‹ Назад',
  nextPage: 'Далее ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Загрузка…',
  noPackages: 'В npm пока нет пакетов этого типа',
  noHits: 'Подходящих пакетов нет',
  searchFailed: (msg: string) => `Ошибка загрузки: ${msg}`,
  partial: 'Результаты npm неполные. Для точного имени пакета используйте ручную установку.',

  loadingDetail: 'Загрузка сведений о пакете…',
  introduction: 'Описание',
  information: 'Сведения',
  deprecated: (note: string) => `Устарело в npm: ${note}`,
  packageName: 'Пакет',
  authorLabel: 'Автор',
  unknownAuthor: 'Не указан',
  fieldInstalledVersion: 'Установленная версия',
  directory: 'Место установки',
  runtime: 'Работающая версия',
  fieldVersion: 'Последняя',
  fieldLicense: 'Лицензия',
  released: 'Опубликовано',
  fieldReleases: 'Релизы',
  releaseCount: (n: number, created: string) => `${n} ${plural(n, 'версия', 'версии', 'версий')}${created ? `, первая ${created}` : ''}`,
  fieldSize: 'Размер',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} ${plural(files, 'файл', 'файла', 'файлов')}`,
  fieldMaintainers: 'Сопровождающие',
  fieldNode: 'Node',
  fieldDeps: 'Зависимости',
  none: 'нет',
  fieldKeywords: 'Ключевые слова',
  fieldDownloads: 'Скачивания',
  fieldDependents: 'Зависимые пакеты',
  fieldHistory: 'История версий',
  noHistory: 'История релизов недоступна.',
  currentVersion: 'Текущая версия',
  installVersion: 'Установить эту версию',
  localVersionNote: 'Локальные ссылки не могут переключать версии npm.',
  versionConfirmTitle: 'Установить эту версию?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'Не установлено'} → ${target}\nЭто изменит общий пакет и затронет другие боты, которые его используют. Вступит в силу после перезапуска. Конфигурация и Memory сохраняются.`,
  linkNames: { npm: 'Пакет npm', repository: 'Репозиторий исходного кода', homepage: 'Сайт проекта', bugs: 'Сообщить о проблеме' },
  install: 'Установить',
  alreadyInstalled: 'Установлено',

  npm: 'Из npm',
  local: 'Из локальной папки',
  npmHelp: 'Введите имя пакета npm, при необходимости с @версией или тегом. Не вводите URL сайта.',
  localHelp: 'Выберите на хосте Cortico папку, содержащую package.json. Локальные расширения подключаются ссылкой; после изменений исходного кода может потребоваться пересборка и перезапуск. При удалении установки исходный код сохраняется.',
  folder: 'Выбрать папку',
  pathLabel: 'Папка расширения',
  packageLabel: 'Пакет и версия',
  check: 'Проверить расширение',
  checkOk: 'Проверка пройдена',
  invalidInput: 'Введите корректное имя пакета npm, при необходимости с точной версией или тегом.',

  version: (v: string) => `Версия: ${v}`,
  author: (v: string) => `Автор: ${v}`,
  downloads: (total: string, month: string, week: string) => `Всего ${total} · 30 дн. ${month} · 7 дн. ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
