import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Estensioni',
  navGroup: 'Core',
  introTitle: 'Estensioni',
  scope: "Le estensioni sono installate nella directory condivisa delle estensioni; installazione ed eliminazione hanno effetto dopo il riavvio del processo. Eliminare un'estensione rimuove il pacchetto condiviso.",
  tabs: { world: 'Estensioni World', provider: 'Estensioni provider', bot: 'Template di bot' },

  installedTitle: 'Installate',
  market: 'Catalogo estensioni',
  manual: 'Installazione manuale',
  refresh: '↻ Aggiorna',
  restartProcess: 'Riavvia processo',

  stateLoaded: 'Caricata',
  stateFailed: 'Caricamento non riuscito',
  statePendingRestart: 'Riavvio in sospeso',
  stateRemoved: 'Disinstallata, riavvio in sospeso',
  enabled: 'Caricata in questo bot',
  disabled: 'Installata, non caricata',
  adopted: 'Usata da questo bot',
  template: 'Installata; pronta per creare istanze',
  hidden: "Nascosta all'agente",
  runtimeVersion: (version: string) => `Il processo usa ancora ${version}`,

  providerManagement: 'Le estensioni provider servono i bot che usano questo ambiente condiviso.',
  idleManagement: 'Attiva o disattiva i World nella pagina World. Le estensioni integrate non possono essere eliminate.',
  createBody: 'Apri un terminale nel progetto Cortico sul suo host, esegui pnpm start --new, poi seleziona questo template di bot per creare una nuova istanza.',

  restartConfirmTitle: 'Riavviare il processo?',
  restartNoLoopTitle: 'Avvio manuale necessario',
  restartConfirmBody: 'Il processo verrà riavviato.',
  restartNoLoopBody: 'Il processo terminerà e dovrà essere riavviato manualmente. Continuare?',
  stepIncomplete: 'incompleto',
  doneRestartSupervised: 'Terminato; in attesa del riavvio',
  doneRestart: 'Terminato',
  resultDefault: 'Passaggi di arresto eseguiti.',
  reloadWait: 'In attesa che un nuovo processo di questo bot sia pronto…',
  otherBot: 'Un altro bot usa questa porta. Ripristino interrotto.',
  restartManual: 'Il processo è terminato. Avvialo manualmente nel terminale; questa pagina attenderà che sia pronto.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Aggiorna',
  updateCheckFailed: (detail: string) => `Controllo aggiornamenti non riuscito: ${detail}`,
  noteConsoleMissing: "Bundle del browser mancante. Esegui la build nella directory dell'estensione e riavvia il processo.",
  noExtensions: 'Ancora nessuna estensione installata',
  listLoadFailed: (msg: string) => `Caricamento dell'elenco delle estensioni non riuscito: ${msg}`,

  eraseConfirm: 'Conferma eliminazione',
  remove: 'Elimina estensione',
  removeInUse: 'In uso da questo bot. Disattivala prima di eliminarla.',
  removeBody: 'Rimuove questo pacchetto dalla directory condivisa delle estensioni; ha effetto dopo il riavvio del processo. Gli altri bot che lo usano ne risentono. Memory, la configurazione salvata e le directory sorgente locali vengono conservate.',
  builtin: 'Integrata',
  builtinNote: 'Inclusa in Cortico; non può essere eliminata separatamente.',

  installedAction: 'Installazione',
  updatedAction: 'Aggiornamento',
  deletedAction: 'Eliminazione',
  progress: (action: string, name: string) => `${action} di ${name} in corso…`,
  completed: (action: string, name: string) => `Operazione completata: ${action.toLowerCase()} di ${name}.`,
  restartNeeded: 'Ha effetto dopo il riavvio del processo.',
  syncedFailed: "Operazione completata, ma l'elenco non è sincronizzato. Aggiorna per riprovare.",

  filterPlaceholder: 'Filtra: nome, descrizione, parole chiave',
  installedFilter: 'Filtra: nome, tipo, descrizione',
  sortLabel: {
    downloads: 'Download (30 giorni)',
    date: 'Pubblicati di recente',
    name: 'Nome',
  },
  hideInstalled: 'Nascondi installate',
  perPage: 'Per pagina',
  automaticCount: (n: number) => `Automatico (${n})`,
  shown: (from: number, to: number, total: number) => `${from}–${to} di ${total}`,
  prevPage: '‹ Precedente',
  nextPage: 'Successiva ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Caricamento…',
  noPackages: 'Ancora nessun pacchetto di questo tipo su npm',
  noHits: 'Nessun pacchetto corrispondente',
  searchFailed: (msg: string) => `Caricamento non riuscito: ${msg}`,
  partial: "I risultati npm sono incompleti. Usa l'installazione manuale per un nome di pacchetto esatto.",

  loadingDetail: 'Caricamento informazioni pacchetto…',
  introduction: 'Descrizione',
  information: 'Informazioni',
  deprecated: (note: string) => `Deprecato su npm: ${note}`,
  packageName: 'Pacchetto',
  authorLabel: 'Autore',
  unknownAuthor: 'Non fornito',
  fieldInstalledVersion: 'Versione installata',
  directory: 'Percorso di installazione',
  runtime: 'Versione in esecuzione',
  fieldVersion: 'Ultima',
  fieldLicense: 'Licenza',
  released: 'Pubblicato',
  fieldReleases: 'Rilasci',
  releaseCount: (n: number, created: string) => `${n} ${n === 1 ? 'versione' : 'versioni'}${created ? `, la prima ${created}` : ''}`,
  fieldSize: 'Dimensione',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} file`,
  fieldMaintainers: 'Manutentori',
  fieldNode: 'Node',
  fieldDeps: 'Dipendenze',
  none: 'nessuna',
  fieldKeywords: 'Parole chiave',
  fieldDownloads: 'Download',
  fieldDependents: 'Dipendenti',
  fieldHistory: 'Cronologia versioni',
  noHistory: 'Nessuna cronologia di rilascio disponibile.',
  currentVersion: 'Versione attuale',
  installVersion: 'Installa questa versione',
  localVersionNote: 'I collegamenti locali non possono cambiare versione npm.',
  versionConfirmTitle: 'Installare questa versione?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'Non installato'} → ${target}\nModifica il pacchetto condiviso e coinvolge gli altri bot che lo usano. Ha effetto dopo il riavvio. Configurazione e Memory vengono conservate.`,
  linkNames: { npm: 'Pacchetto npm', repository: 'Repository dei sorgenti', homepage: 'Home page del progetto', bugs: 'Segnala un problema' },
  install: 'Installa',
  alreadyInstalled: 'Installato',

  npm: 'Da npm',
  local: 'Da una directory locale',
  npmHelp: "Inserisci un nome di pacchetto npm, eventualmente seguito da @versione o da un tag. Non inserire l'URL di un sito web.",
  localHelp: "Seleziona una directory contenente package.json sull'host di Cortico. Le estensioni locali vengono collegate; le modifiche ai sorgenti possono richiedere una nuova build e un riavvio. Eliminare l'installazione conserva i sorgenti.",
  folder: 'Scegli cartella',
  pathLabel: "Directory dell'estensione",
  packageLabel: 'Pacchetto e versione',
  check: 'Verifica estensione',
  checkOk: 'Verifica superata',
  invalidInput: 'Inserisci un nome di pacchetto npm valido, eventualmente con una versione esatta o un tag.',

  version: (v: string) => `Versione: ${v}`,
  author: (v: string) => `Autore: ${v}`,
  downloads: (total: string, month: string, week: string) => `Totale ${total} · 30 g ${month} · 7 g ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
