import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  navLabel: 'Extensiones',
  navGroup: 'Core',
  introTitle: 'Extensiones',
  scope: 'Las extensiones se instalan en el directorio compartido de extensiones; instalar y eliminar surten efecto después de reiniciar el proceso. Eliminar una extensión quita el paquete compartido.',
  tabs: { world: 'Extensiones de World', provider: 'Extensiones de proveedor', bot: 'Plantillas de Bot' },

  installedTitle: 'Instaladas',
  market: 'Mercado de extensiones',
  manual: 'Instalación manual',
  refresh: '↻ Actualizar',
  restartProcess: 'Reiniciar proceso',

  stateLoaded: 'Cargada',
  stateFailed: 'Falló la carga',
  statePendingRestart: 'Reinicio pendiente',
  stateRemoved: 'Desinstalada, reinicio pendiente',
  enabled: 'Cargada en este Bot',
  disabled: 'Instalada, sin cargar',
  adopted: 'En uso por este Bot',
  template: 'Instalada; lista para crear instancias',
  hidden: 'Oculta para el agente',
  runtimeVersion: (version: string) => `El proceso aún usa ${version}`,

  providerManagement: 'Las extensiones de proveedor sirven a los Bots que usan este entorno compartido.',
  idleManagement: 'Activa o desactiva los Worlds en la página de World. Las extensiones integradas no se pueden eliminar.',
  createBody: 'Abre una terminal en el proyecto Cortico en su equipo anfitrión, ejecuta pnpm start --new y selecciona esta plantilla de Bot para crear una instancia nueva.',

  restartConfirmTitle: '¿Reiniciar el proceso?',
  restartNoLoopTitle: 'Se requiere inicio manual',
  restartConfirmBody: 'El proceso se reiniciará.',
  restartNoLoopBody: 'El proceso se cerrará y habrá que reiniciarlo manualmente. ¿Continuar?',
  stepIncomplete: 'incompleto',
  doneRestartSupervised: 'Cerrado; esperando el reinicio',
  doneRestart: 'Cerrado',
  resultDefault: 'Pasos de apagado ejecutados.',
  reloadWait: 'Esperando a que un proceso nuevo de este Bot esté listo…',
  otherBot: 'Otro Bot está usando este puerto. Se detuvo la recuperación.',
  restartManual: 'El proceso terminó. Inícialo manualmente en la terminal; esta página esperará a que esté listo.',

  updateVersions: (current: string, latest: string) => `${current} → ${latest}`,
  updateAction: 'Actualizar',
  updateCheckFailed: (detail: string) => `Falló la búsqueda de actualizaciones: ${detail}`,
  noteConsoleMissing: 'Falta el paquete del navegador. Compila en el directorio de la extensión y reinicia el proceso.',
  noExtensions: 'Aún no hay extensiones instaladas',
  listLoadFailed: (msg: string) => `No se pudo cargar la lista de extensiones: ${msg}`,

  eraseConfirm: 'Confirmar eliminación',
  remove: 'Eliminar extensión',
  removeInUse: 'Este Bot la está usando. Desactívala antes de eliminarla.',
  removeBody: 'Quita este paquete del directorio compartido de extensiones; surte efecto después de reiniciar el proceso. Afecta a otros Bots que lo usen. Memory, la configuración guardada y los directorios de código fuente locales se conservan.',
  builtin: 'Integrada',
  builtinNote: 'Incluida con Cortico; no se puede eliminar por separado.',

  installedAction: 'Instalación',
  updatedAction: 'Actualización',
  deletedAction: 'Eliminación',
  progress: (action: string, name: string) => `${action} en curso: ${name}…`,
  completed: (action: string, name: string) => `${action} completada: ${name}.`,
  restartNeeded: 'Surte efecto después de reiniciar el proceso.',
  syncedFailed: 'La operación se completó, pero la lista no está sincronizada. Actualiza para reintentar.',

  filterPlaceholder: 'Filtrar: nombre, descripción, palabras clave',
  installedFilter: 'Filtrar: nombre, tipo, descripción',
  sortLabel: {
    downloads: 'Descargas (30 días)',
    date: 'Publicadas recientemente',
    name: 'Nombre',
  },
  hideInstalled: 'Ocultar instaladas',
  perPage: 'Por página',
  automaticCount: (n: number) => `Automático (${n})`,
  shown: (from: number, to: number, total: number) => `Mostrando ${from}–${to} de ${total}`,
  prevPage: '‹ Anterior',
  nextPage: 'Siguiente ›',
  pageOf: (page: number, pages: number) => `${page} / ${pages}`,
  searching: 'Cargando…',
  noPackages: 'Aún no hay paquetes de este tipo en npm',
  noHits: 'No hay paquetes que coincidan',
  searchFailed: (msg: string) => `Falló la carga: ${msg}`,
  partial: 'Los resultados de npm están incompletos. Usa la instalación manual para un nombre de paquete exacto.',

  loadingDetail: 'Cargando información del paquete…',
  introduction: 'Descripción',
  information: 'Información',
  deprecated: (note: string) => `Obsoleto en npm: ${note}`,
  packageName: 'Paquete',
  authorLabel: 'Autor',
  unknownAuthor: 'No indicado',
  fieldInstalledVersion: 'Versión instalada',
  directory: 'Ubicación de instalación',
  runtime: 'Versión en ejecución',
  fieldVersion: 'Más reciente',
  fieldLicense: 'Licencia',
  released: 'Publicada',
  fieldReleases: 'Versiones',
  releaseCount: (n: number, created: string) => `${n} ${n === 1 ? 'versión' : 'versiones'}${created ? `, la primera el ${created}` : ''}`,
  fieldSize: 'Tamaño',
  sizeAndFiles: (size: string, files: number) => `${size} · ${files} ${files === 1 ? 'archivo' : 'archivos'}`,
  fieldMaintainers: 'Mantenedores',
  fieldNode: 'Node',
  fieldDeps: 'Dependencias',
  none: 'ninguna',
  fieldKeywords: 'Palabras clave',
  fieldDownloads: 'Descargas',
  fieldDependents: 'Dependientes',
  fieldHistory: 'Historial de versiones',
  noHistory: 'No hay historial de versiones disponible.',
  currentVersion: 'Versión actual',
  installVersion: 'Instalar esta versión',
  localVersionNote: 'Los enlaces locales no pueden cambiar de versión de npm.',
  versionConfirmTitle: '¿Instalar esta versión?',
  versionConfirmBody: (name: string, current: string | null, target: string) => `${name}\n${current ?? 'No instalada'} → ${target}\nEsto cambia el paquete compartido y afecta a otros Bots que lo usan. Surte efecto después de reiniciar. La configuración y Memory se conservan.`,
  linkNames: { npm: 'Paquete npm', repository: 'Repositorio de código fuente', homepage: 'Página del proyecto', bugs: 'Informar un problema' },
  install: 'Instalar',
  alreadyInstalled: 'Instalada',

  npm: 'Desde npm',
  local: 'Desde un directorio local',
  npmHelp: 'Ingresa un nombre de paquete npm, opcionalmente seguido de @versión o una etiqueta. No ingreses la URL de un sitio web.',
  localHelp: 'Selecciona un directorio que contenga package.json en el equipo anfitrión de Cortico. Las extensiones locales se enlazan; los cambios en el código fuente pueden requerir recompilar y reiniciar. Al eliminar la instalación se conserva el código fuente.',
  folder: 'Elegir carpeta',
  pathLabel: 'Directorio de la extensión',
  packageLabel: 'Paquete y versión',
  check: 'Verificar extensión',
  checkOk: 'Verificación aprobada',
  invalidInput: 'Ingresa un nombre de paquete npm válido, opcionalmente con una versión exacta o una etiqueta.',

  version: (v: string) => `Versión: ${v}`,
  author: (v: string) => `Autor: ${v}`,
  downloads: (total: string, month: string, week: string) => `Total ${total} · 30 d ${month} · 7 d ${week}`,
  labelled: (label: string, value: string) => `${label}: ${value}`,
  metaSeparator: ' · ',
  listSeparator: ', ',
};
