import { pick } from '../../core/language.ts';
const zh = {
  tabs: { world: 'World 扩展', provider: '供应商扩展', bot: 'Bot 模板' },
  scope: '扩展安装在共享环境中，可供多个 Bot 使用；加载和卸载仅作用于当前 Bot。彻底删除会移除共享扩展包。',
  enabled: '已加载到本 Bot', disabled: '已安装，未加载', adopted: '当前 Bot 正在采用', template: '已安装，可创建实例',
  load: '加载到本 Bot', unload: '从本 Bot 卸载', loadRestart: '重启后加载', manage: '管理 World', details: '详情',
  remove: '彻底删除', removeBody: '将从共享扩展环境移除此扩展包。使用它的其他 Bot 也会受到影响。此操作不会删除 Bot 的记忆、已有配置或本地扩展源码。检查范围为已知部署及此共享环境登记的运行实例。',
  unloadBody: '仅停止当前 Bot 使用此扩展，保留安装包与配置。',
  create: '创建实例说明', createBody: '在运行 Cortico 的电脑上打开项目终端，执行 pnpm start --new，选择此 Bot 模板并创建新实例。',
  partial: '仅显示部分 npm 搜索结果，请使用手动安装查找确切包名。',
  market: '扩展市场', manual: '手动安装', npm: '从 npm 安装', local: '从本机目录安装', check: '检查扩展',
  npmHelp: '输入 npm 包名，可附带 @版本或标签；不要填写网页链接。',
  localHelp: '选择运行 Cortico 的电脑上包含 package.json 的扩展目录。扩展通过链接接入；更新源码后可能需要重新构建并重启。删除安装记录不会删除源目录。',
  folder: '选择文件夹', pathLabel: '扩展项目目录', packageLabel: '包名与版本',
  working: '操作进行中…', unknown: '结果尚未确认，正在查询操作状态…', rolledBack: '操作失败，已恢复原安装状态。', repair: '需要修复，请查看详情。',
  committed: '操作已完成。', syncedFailed: '操作已完成，但列表未同步；请刷新。', checkOk: '检查通过', invalidInput: '请输入有效的 npm 包名，可附带明确版本或标签。',
  reloadWait: '等待当前 Bot 的新进程就绪…', reloadTimeout: '尚未检测到新进程就绪。可继续检测，无需重复重启。',
  otherBot: '此端口已由另一 Bot 使用，已停止恢复。', retry: '继续检测', restartManual: '进程已退出，请在终端手动启动；此页面会等待就绪。',
  shown: (from: number, to: number, total: number) => `显示 ${from}–${to}，共 ${total} 个`,
  inspect: '在已安装中查看', hidden: '对 Agent 隐藏', runtimeVersion: (version: string) => `当前进程仍为 ${version}`,
};
const en: typeof zh = {
  tabs: { world: 'World extensions', provider: 'Provider extensions', bot: 'Bot templates' },
  scope: 'Packages are shared across Bots. Loading and unloading apply only to this Bot. Permanent deletion removes the shared package.',
  enabled: 'Loaded into this Bot', disabled: 'Installed, not loaded', adopted: 'Used by this Bot', template: 'Installed; ready to create instances',
  load: 'Load into this Bot', unload: 'Unload from this Bot', loadRestart: 'Load after restart', manage: 'Manage World', details: 'Details',
  remove: 'Delete permanently', removeBody: 'Remove this package from the shared environment. Other Bots may be affected. Memory, saved configuration and local source directories are retained. Checks cover known deployments and running instances registered with this shared environment.',
  unloadBody: 'Stop this Bot from using the extension. Keep the package and configuration.',
  create: 'Create an instance', createBody: 'Open a terminal in the Cortico project on its host, run pnpm start --new, then select this Bot template to create a new instance.',
  partial: 'npm results are incomplete. Use manual installation for an exact package name.',
  market: 'Extension market', manual: 'Manual install', npm: 'From npm', local: 'From a local directory', check: 'Check extension',
  npmHelp: 'Enter an npm package name, optionally followed by @version or a tag. Do not enter a website URL.',
  localHelp: 'Select a directory containing package.json on the Cortico host. Local extensions are linked; source changes may require rebuilding and restarting. Deleting the installation retains the source.',
  folder: 'Choose folder', pathLabel: 'Extension directory', packageLabel: 'Package and version',
  working: 'Operation in progress…', unknown: 'Result unknown; checking operation status…', rolledBack: 'Operation failed. The previous installation was restored.', repair: 'Repair required. Open details.',
  committed: 'Operation completed.', syncedFailed: 'Operation completed, but the list is out of sync. Refresh to retry.', checkOk: 'Check passed', invalidInput: 'Enter a valid npm package name, optionally with an exact version or tag.',
  reloadWait: 'Waiting for a new process of this Bot to become ready…', reloadTimeout: 'The new process is not ready yet. Continue checking without requesting another restart.',
  otherBot: 'Another Bot is using this port. Recovery stopped.', retry: 'Continue checking', restartManual: 'The process exited. Start it manually in the terminal; this page will wait for readiness.',
  shown: (from, to, total) => `Showing ${from}–${to} of ${total}`,
  inspect: 'View installed', hidden: 'Hidden from the Agent', runtimeVersion: version => `Process still uses ${version}`,
};
export const V = pick({ zh, en });
