import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'System-Prompt',
  introDesc: 'Strg+S speichert Vorlagen; lade neu, um das Präfix der aktuellen Session zu aktualisieren. Abschnitte aus dem Code sind schreibgeschützt.',
  reloadSession: 'Aktuelle Session neu laden',
  reloading: 'Wird neu geladen…',
  prefixReloaded: 'Präfix neu geladen',
  leaveUnsaved: 'Ungespeicherte Änderungen gehen verloren. Verlassen?',
  saving: 'Speichert…',
  saved: 'Gespeichert',
  saveFailedFor: (title: string, msg: string) => `${title} konnte nicht gespeichert werden: ${msg}`,
  savedList: (names: string) => `✓ ${names} gespeichert; gilt nach dem Neuladen`,
  dirtyCount: (n: number) => `${n} ungespeicherte ${n === 1 ? 'Änderung' : 'Änderungen'} (Strg+S)`,
  fillNowMultiline: 'Aktueller Wert (mehrzeiliger Block)',
  fillNow: 'Aktueller Wert',
  varUnreported: 'Variable nicht bereitgestellt; ihr Platzhalter bleibt unverändert.',
  varEmpty: '(gerade leer; fällt auf den Standardtext zurück)',
  flagEditable: (key, origin) =>
    `Bearbeitbar: ${key}${origin === 'deployment' ? ' (Überschreibung dieses Deployments)' : origin === 'package' ? ' (Überschreibung des Pakets; Speichern macht sie zur Überschreibung dieses Deployments)' : origin === 'module' ? ' (World-Standard; Speichern macht ihn zur Überschreibung dieses Deployments)' : ''}`,
  flagReadonly: 'Aus dem Code, schreibgeschützt',
  sourceMissing: (key: string) => `Quelle „${key}“ nicht gefunden`,
  fromCode: 'Aus dem Code',
  originDeployment: 'Überschreibung dieses Deployments',
  originPackage: 'Überschreibung des Bot-Pakets',
  originWorld: 'World-Standard',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'Das Präfix ist gerade leer',
  prefixUnavailable: 'Präfixvorschau nicht verfügbar.',
  prefixStats: (n: number, tok: string) => `${n} ${n === 1 ? 'Block' : 'Blöcke'} · gerendert etwa ${tok} Tokens`,
  loadFailed: (msg: string) => `Laden fehlgeschlagen: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} hat keinen bereitgestellten Wert; Platzhalter bleiben unverändert`,
  warnUnusedVars: (list: string) => `${list} deklariert, aber nicht verwendet`,
  varPanelTitle: 'Platzhalter in dieser Vorlage',
  multiline: 'mehrzeilig',
  varUnreportedShort: 'Variable nicht bereitgestellt',
  varEmptyShort: '(gerade leer; fällt auf den Standardtext zurück)',
  leaveUnsavedNamed: (names: string) => `Es gibt ungespeicherte Vorlagenänderungen (${names}). Verlassen und verwerfen?`,
  editableTemplate: 'bearbeitbare Vorlage',
  cardDescDefault: 'Wird in der Quelldatei gespeichert; gilt für die aktuelle Session nach einem Neuladen des Systempräfixes.',
  loadedFromDeployment: 'Deployment-Überschreibung geladen.',
  loadedFromPackage: 'Überschreibung des Bot-Pakets geladen; Speichern schreibt die Deployment-Überschreibung.',
  loadedFromWorld: 'World-Standard geladen; Speichern schreibt die Deployment-Überschreibung.',
  loadedFromSource: 'Aus der Quelldatei geladen',
  unsaved: '● Ungespeichert',
  saveToFile: 'In Datei speichern',
  resetToWorld: 'Deployment-Überschreibung entfernen',
  savedResult: (result: string) => `✓ ${result}; gilt nach einem Neuladen des Präfixes`,
  saveFailed: (msg: string) => `Speichern fehlgeschlagen: ${msg}`,
  saveFailedToast: 'Speichern fehlgeschlagen',
  resetTitle: (title: string) => `Deployment-Überschreibung für „${title}“ löschen?`,
  resetBody: 'Nach dem Löschen gilt die Überschreibung des Bot-Pakets oder, falls das Paket keine hat, der World-Standard. Ungespeicherte Änderungen gehen verloren.',
  resetting: 'Wird wiederhergestellt…',
  resetDone: 'Deployment-Überschreibung entfernt',
  resetFailed: (msg: string) => `Wiederherstellen fehlgeschlagen: ${msg}`,
  resetFailedToast: 'Wiederherstellen fehlgeschlagen',
  noTemplatesScoped: 'Keine bearbeitbaren Vorlagen unter diesem Eigentümer',
  noTemplates: 'Keine bearbeitbaren Prompt-Vorlagen',
  templatesLoadFailed: (msg: string) => `Vorlagen konnten nicht geladen werden: ${msg}`,

  // editor.ts
  saveHintDirty: 'Strg+S zum Speichern',
};
