import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'Prompt système',
  introDesc: 'Ctrl+S enregistre les modèles ; rechargez pour mettre à jour le préfixe de la session actuelle. Les sections issues du code sont en lecture seule.',
  reloadSession: 'Recharger la session actuelle',
  reloading: 'Rechargement…',
  prefixReloaded: 'Préfixe rechargé',
  leaveUnsaved: 'Les modifications non enregistrées seront perdues. Quitter ?',
  saving: 'Enregistrement…',
  saved: 'Enregistré',
  saveFailedFor: (title: string, msg: string) => `Échec de l'enregistrement de ${title} : ${msg}`,
  savedList: (names: string) => `✓ Enregistré : ${names} ; prend effet après rechargement`,
  dirtyCount: (n: number) => `${n} modification${n > 1 ? 's' : ''} non enregistrée${n > 1 ? 's' : ''} (Ctrl+S)`,
  fillNowMultiline: 'Valeur actuelle (bloc multiligne)',
  fillNow: 'Valeur actuelle',
  varUnreported: 'Variable non fournie ; son espace réservé reste inchangé.',
  varEmpty: '(vide pour le moment ; utilise le texte par défaut)',
  flagEditable: (key, origin) =>
    `Modifiable : ${key}${origin === 'deployment' ? ' (surcharge de ce déploiement)' : origin === 'package' ? " (surcharge du paquet ; l'enregistrement en fait la surcharge de ce déploiement)" : origin === 'module' ? " (défaut du World ; l'enregistrement en fait la surcharge de ce déploiement)" : ''}`,
  flagReadonly: 'Issu du code, lecture seule',
  sourceMissing: (key: string) => `Source « ${key} » introuvable`,
  fromCode: 'Issu du code',
  originDeployment: 'Surcharge de ce déploiement',
  originPackage: 'Surcharge du paquet bot',
  originWorld: 'Défaut du World',
  listSep: ', ',
  warnSep: ' ; ',
  prefixEmpty: 'Le préfixe est vide pour le moment',
  prefixUnavailable: 'Aperçu du préfixe indisponible.',
  prefixStats: (n: number, tok: string) => `${n} bloc${n > 1 ? 's' : ''} · environ ${tok} tokens après rendu`,
  loadFailed: (msg: string) => `Échec du chargement : ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} n'a pas de valeur fournie ; les espaces réservés restent inchangés`,
  warnUnusedVars: (list: string) => `${list} déclaré mais inutilisé`,
  varPanelTitle: 'Espaces réservés de ce modèle',
  multiline: 'multiligne',
  varUnreportedShort: 'Variable non fournie',
  varEmptyShort: '(vide pour le moment ; utilise le texte par défaut)',
  leaveUnsavedNamed: (names: string) => `Des modifications de modèles ne sont pas enregistrées (${names}). Quitter et les abandonner ?`,
  editableTemplate: 'modèle modifiable',
  cardDescDefault: 'Enregistré dans le fichier source ; prend effet pour la session actuelle après un rechargement du préfixe système.',
  loadedFromDeployment: 'Surcharge du déploiement chargée.',
  loadedFromPackage: "Surcharge du paquet bot chargée ; l'enregistrement écrit la surcharge du déploiement.",
  loadedFromWorld: "Défaut du World chargé ; l'enregistrement écrit la surcharge du déploiement.",
  loadedFromSource: 'Chargé depuis le fichier source',
  unsaved: '● Non enregistré',
  saveToFile: 'Enregistrer dans le fichier',
  resetToWorld: 'Supprimer la surcharge de déploiement',
  savedResult: (result: string) => `✓ ${result} ; prend effet après un rechargement du préfixe`,
  saveFailed: (msg: string) => `Échec de l'enregistrement : ${msg}`,
  saveFailedToast: "Échec de l'enregistrement",
  resetTitle: (title: string) => `Supprimer la surcharge de déploiement de « ${title} » ?`,
  resetBody: "Après suppression, la surcharge du paquet bot est utilisée, ou le défaut du World si le paquet n'en a pas. Les modifications non enregistrées seront perdues.",
  resetting: 'Restauration…',
  resetDone: 'Surcharge de déploiement supprimée',
  resetFailed: (msg: string) => `Échec de la restauration : ${msg}`,
  resetFailedToast: 'Échec de la restauration',
  noTemplatesScoped: 'Aucun modèle modifiable pour ce propriétaire',
  noTemplates: 'Aucun modèle de prompt modifiable',
  templatesLoadFailed: (msg: string) => `Échec du chargement des modèles : ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S pour enregistrer',
};
