import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'Prompt di sistema',
  introDesc: 'Ctrl+S salva i template; ricarica per aggiornare il prefisso della sessione attuale. Le sezioni provenienti dal codice sono in sola lettura.',
  reloadSession: 'Ricarica sessione attuale',
  reloading: 'Ricaricamento…',
  prefixReloaded: 'Prefisso ricaricato',
  leaveUnsaved: 'Le modifiche non salvate andranno perse. Uscire?',
  saving: 'Salvataggio…',
  saved: 'Salvato',
  saveFailedFor: (title: string, msg: string) => `Salvataggio di ${title} non riuscito: ${msg}`,
  savedList: (names: string) => `✓ Salvato: ${names}; ha effetto dopo il ricaricamento`,
  dirtyCount: (n: number) => `${n} ${n === 1 ? 'modifica non salvata' : 'modifiche non salvate'} (Ctrl+S)`,
  fillNowMultiline: 'Valore attuale (blocco multiriga)',
  fillNow: 'Valore attuale',
  varUnreported: 'Variabile non fornita; il suo segnaposto resta invariato.',
  varEmpty: '(vuoto in questo momento; ricade sul testo predefinito)',
  flagEditable: (key, origin) =>
    `Modificabile: ${key}${origin === 'deployment' ? ' (override di questo deployment)' : origin === 'package' ? " (override del pacchetto; salvando diventa l'override di questo deployment)" : origin === 'module' ? " (predefinito del World; salvando diventa l'override di questo deployment)" : ''}`,
  flagReadonly: 'Dal codice, sola lettura',
  sourceMissing: (key: string) => `Fonte «${key}» non trovata`,
  fromCode: 'Dal codice',
  originDeployment: 'Override di questo deployment',
  originPackage: 'Override del pacchetto bot',
  originWorld: 'Predefinito del World',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'Il prefisso è vuoto in questo momento',
  prefixUnavailable: 'Anteprima del prefisso non disponibile.',
  prefixStats: (n: number, tok: string) => `${n} ${n === 1 ? 'blocco' : 'blocchi'} · circa ${tok} token dopo il rendering`,
  loadFailed: (msg: string) => `Caricamento non riuscito: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} non ha un valore fornito; i segnaposto restano invariati`,
  warnUnusedVars: (list: string) => `${list} dichiarato ma non usato`,
  varPanelTitle: 'Segnaposto in questo template',
  multiline: 'multiriga',
  varUnreportedShort: 'Variabile non fornita',
  varEmptyShort: '(vuoto in questo momento; ricade sul testo predefinito)',
  leaveUnsavedNamed: (names: string) => `Ci sono modifiche ai template non salvate (${names}). Uscire e scartarle?`,
  editableTemplate: 'template modificabile',
  cardDescDefault: 'Salvato nel file sorgente; ha effetto sulla sessione attuale dopo il ricaricamento del prefisso di sistema.',
  loadedFromDeployment: "Caricato l'override del deployment.",
  loadedFromPackage: "Caricato l'override del pacchetto bot; il salvataggio scrive l'override del deployment.",
  loadedFromWorld: "Caricato il predefinito del World; il salvataggio scrive l'override del deployment.",
  loadedFromSource: 'Caricato dal file sorgente',
  unsaved: '● Non salvato',
  saveToFile: 'Salva nel file',
  resetToWorld: "Rimuovi l'override del deployment",
  savedResult: (result: string) => `✓ ${result}; ha effetto dopo il ricaricamento del prefisso`,
  saveFailed: (msg: string) => `Salvataggio non riuscito: ${msg}`,
  saveFailedToast: 'Salvataggio non riuscito',
  resetTitle: (title: string) => `Eliminare l'override del deployment per «${title}»?`,
  resetBody: "Dopo l'eliminazione si usa l'override del pacchetto bot o, se il pacchetto non ne ha, il predefinito del World. Le modifiche non salvate andranno perse.",
  resetting: 'Ripristino…',
  resetDone: 'Override del deployment rimosso',
  resetFailed: (msg: string) => `Ripristino non riuscito: ${msg}`,
  resetFailedToast: 'Ripristino non riuscito',
  noTemplatesScoped: 'Nessun template modificabile per questo proprietario',
  noTemplates: 'Nessun template di prompt modificabile',
  templatesLoadFailed: (msg: string) => `Caricamento dei template non riuscito: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S per salvare',
};
