import type { EnvPromptOrigin } from '../../../../core/prefix.ts';
import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'システムプロンプト',
  introDesc: 'Ctrl+S でテンプレートを保存し、再読み込みすると現在のセッションのプレフィックスが更新されます。コード由来のセクションは読み取り専用です。',
  reloadSession: '現在のセッションを再読み込み',
  reloading: '再読み込み中…',
  prefixReloaded: 'プレフィックスを再読み込みしました',
  leaveUnsaved: '保存していない変更は失われます。移動しますか？',
  saving: '保存中…',
  saved: '保存しました',
  saveFailedFor: (title: string, msg: string) => `${title} を保存できませんでした：${msg}`,
  savedList: (names: string) => `✓ ${names} を保存しました。再読み込み後に反映されます`,
  dirtyCount: (n: number) => `未保存の変更が ${n} 箇所あります（Ctrl+S）`,
  fillNowMultiline: '現在の値（複数行ブロック）',
  fillNow: '現在の値',
  varUnreported: 'この変数は提供されていません。プレースホルダーはそのまま残ります。',
  varEmpty: '（現在は空のため、既定の文面になります）',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `編集可：${key}${origin === 'deployment' ? '（このデプロイの上書き）' : origin === 'package' ? '（ボットパッケージの上書き。保存するとこのデプロイの上書きになります）' : origin === 'module' ? '（World の既定。保存するとこのデプロイの上書きになります）' : ''}`,
  flagReadonly: 'コード由来、読み取り専用',
  sourceMissing: (key: string) => `ソース「${key}」が見つかりません`,
  fromCode: 'コード由来',
  originDeployment: 'このデプロイの上書き',
  originPackage: 'ボットパッケージの上書き',
  originWorld: 'World の既定',
  listSep: '、',
  warnSep: '。',
  prefixEmpty: 'プレフィックスは現在空です',
  prefixUnavailable: 'プレフィックスのプレビューを利用できません。',
  prefixStats: (n: number, tok: string) => `${n} ブロック · 展開後 約 ${tok} tokens`,
  loadFailed: (msg: string) => `読み込みに失敗しました：${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `テンプレート内の ${list} には値が提供されていないため、プレースホルダーはそのまま残ります`,
  warnUnusedVars: (list: string) => `${list} は宣言されていますが使われていません`,
  varPanelTitle: 'このテンプレートのプレースホルダー',
  multiline: '複数行',
  varUnreportedShort: 'この変数は提供されていません',
  varEmptyShort: '（現在は空のため、既定の文面になります）',
  leaveUnsavedNamed: (names: string) => `保存していないテンプレートの変更があります（${names}）。破棄して移動しますか？`,
  editableTemplate: '編集可能なテンプレート',
  cardDescDefault: 'ソースファイルに保存します。システムプレフィックスを再読み込みすると現在のセッションに反映されます。',
  loadedFromDeployment: 'このデプロイの上書きファイルを読み込みました。',
  loadedFromPackage: 'ボットパッケージの上書きを読み込みました。保存するとこのデプロイの上書きファイルに書き込みます。',
  loadedFromWorld: 'World の既定テンプレートを読み込みました。保存するとこのデプロイの上書きファイルに書き込みます。',
  loadedFromSource: 'ソースファイルから読み込みました',
  unsaved: '● 未保存',
  saveToFile: 'ファイルに保存',
  resetToWorld: 'デプロイの上書きを削除',
  savedResult: (result: string) => `✓ ${result}。プレフィックスの再読み込み後に反映されます`,
  saveFailed: (msg: string) => `保存に失敗しました：${msg}`,
  saveFailedToast: '保存に失敗しました',
  resetTitle: (title: string) => `「${title}」のデプロイの上書きを削除しますか？`,
  resetBody: '削除後はボットパッケージの上書き版を使い、パッケージに上書きがなければ World の既定版を使います。保存していない変更は失われます。',
  resetting: '元に戻しています…',
  resetDone: 'デプロイの上書きを削除しました',
  resetFailed: (msg: string) => `元に戻せませんでした：${msg}`,
  resetFailedToast: '元に戻せませんでした',
  noTemplatesScoped: 'この所属には編集可能なテンプレートがありません',
  noTemplates: '編集可能なプロンプトテンプレートがありません',
  templatesLoadFailed: (msg: string) => `テンプレートを読み込めませんでした：${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S で保存',
};
