import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'Prompt del sistema',
  introDesc: 'Ctrl+S guarda las plantillas; recarga para actualizar el prefijo de la sesión actual. Las secciones que vienen del código son de solo lectura.',
  reloadSession: 'Recargar sesión actual',
  reloading: 'Recargando…',
  prefixReloaded: 'Prefijo recargado',
  leaveUnsaved: 'Los cambios sin guardar se perderán. ¿Salir?',
  saving: 'Guardando…',
  saved: 'Guardado',
  saveFailedFor: (title: string, msg: string) => `No se pudo guardar ${title}: ${msg}`,
  savedList: (names: string) => `✓ Se guardó ${names}; se aplica al recargar`,
  dirtyCount: (n: number) => `${n} ${n === 1 ? 'cambio sin guardar' : 'cambios sin guardar'} (Ctrl+S)`,
  fillNowMultiline: 'Valor en este momento (bloque multilínea)',
  fillNow: 'Valor en este momento',
  varUnreported: 'La variable no se proporcionó; su marcador de posición queda sin cambios.',
  varEmpty: '(vacío en este momento; se usa el texto predeterminado)',
  flagEditable: (key, origin) =>
    `Se puede editar: ${key}${origin === 'deployment' ? ' (sobrescritura de este despliegue)' : origin === 'package' ? ' (sobrescritura del paquete; al guardar pasa a ser la sobrescritura de este despliegue)' : origin === 'module' ? ' (predeterminado del World; al guardar pasa a ser la sobrescritura de este despliegue)' : ''}`,
  flagReadonly: 'Viene del código, solo lectura',
  sourceMissing: (key: string) => `No se encontró la fuente “${key}”`,
  fromCode: 'Desde el código',
  originDeployment: 'Sobrescritura de este despliegue',
  originPackage: 'Sobrescritura del paquete del bot',
  originWorld: 'Predeterminado del World',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'El prefijo está vacío en este momento',
  prefixUnavailable: 'La vista previa del prefijo no está disponible.',
  prefixStats: (n: number, tok: string) => `${n} ${n === 1 ? 'bloque' : 'bloques'} · unos ${tok} tokens renderizados`,
  loadFailed: (msg: string) => `Falló la carga: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} no tiene un valor proporcionado; los marcadores de posición quedan sin cambios`,
  warnUnusedVars: (list: string) => `${list} se declaró pero no se usa`,
  varPanelTitle: 'Marcadores de posición de esta plantilla',
  multiline: 'multilínea',
  varUnreportedShort: 'Variable no proporcionada',
  varEmptyShort: '(vacío en este momento; se usa el texto predeterminado)',
  leaveUnsavedNamed: (names: string) => `Hay cambios sin guardar en plantillas (${names}). ¿Salir y descartarlos?`,
  editableTemplate: 'plantilla editable',
  cardDescDefault: 'Se guarda en el archivo de origen; se aplica a la sesión actual tras recargar el prefijo del sistema.',
  loadedFromDeployment: 'Se cargó la sobrescritura del despliegue.',
  loadedFromPackage: 'Se cargó la sobrescritura del paquete del bot; al guardar se escribe la sobrescritura del despliegue.',
  loadedFromWorld: 'Se cargó el predeterminado del World; al guardar se escribe la sobrescritura del despliegue.',
  loadedFromSource: 'Cargado desde el archivo de origen',
  unsaved: '● Sin guardar',
  saveToFile: 'Guardar en el archivo',
  resetToWorld: 'Quitar sobrescritura del despliegue',
  savedResult: (result: string) => `✓ ${result}; se aplica tras recargar el prefijo`,
  saveFailed: (msg: string) => `No se pudo guardar: ${msg}`,
  saveFailedToast: 'No se pudo guardar',
  resetTitle: (title: string) => `¿Eliminar la sobrescritura del despliegue de “${title}”?`,
  resetBody: 'Tras eliminarla se usa la sobrescritura del paquete del bot o, si el paquete no tiene una, el predeterminado del World. Los cambios sin guardar se perderán.',
  resetting: 'Restaurando…',
  resetDone: 'Sobrescritura del despliegue eliminada',
  resetFailed: (msg: string) => `No se pudo restaurar: ${msg}`,
  resetFailedToast: 'No se pudo restaurar',
  noTemplatesScoped: 'No hay plantillas editables de este propietario',
  noTemplates: 'No hay plantillas de prompt editables',
  templatesLoadFailed: (msg: string) => `No se pudieron cargar las plantillas: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S para guardar',
};
