import type { EnvPromptOrigin } from '../../../../core/prefix.ts';
import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: '시스템 프롬프트',
  introDesc: 'Ctrl+S로 템플릿을 저장하고, 다시 불러오면 현재 세션의 프리픽스가 업데이트됩니다. 코드에서 온 섹션은 읽기 전용입니다.',
  reloadSession: '현재 세션 다시 불러오기',
  reloading: '다시 불러오는 중…',
  prefixReloaded: '프리픽스를 다시 불러왔습니다',
  leaveUnsaved: '저장하지 않은 변경 사항은 사라집니다. 나가시겠습니까?',
  saving: '저장 중…',
  saved: '저장했습니다',
  saveFailedFor: (title: string, msg: string) => `${title}을(를) 저장하지 못했습니다: ${msg}`,
  savedList: (names: string) => `✓ ${names} 저장함. 다시 불러온 뒤 적용됩니다`,
  dirtyCount: (n: number) => `저장하지 않은 변경 ${n}곳(Ctrl+S)`,
  fillNowMultiline: '현재 채워질 값(여러 줄 블록)',
  fillNow: '현재 채워질 값',
  varUnreported: '이 변수는 제공되지 않았습니다. 자리 표시자는 그대로 남습니다.',
  varEmpty: '(지금은 비어 있어 기본 문구가 쓰임)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `편집 가능: ${key}${origin === 'deployment' ? ' (이 배포의 재정의)' : origin === 'package' ? ' (봇 패키지의 재정의, 저장하면 이 배포의 재정의가 됨)' : origin === 'module' ? ' (World 기본값, 저장하면 이 배포의 재정의가 됨)' : ''}`,
  flagReadonly: '코드에서 옴, 읽기 전용',
  sourceMissing: (key: string) => `소스 "${key}"을(를) 찾을 수 없습니다`,
  fromCode: '코드에서 옴',
  originDeployment: '이 배포의 재정의',
  originPackage: '봇 패키지 재정의',
  originWorld: 'World 기본값',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: '프리픽스가 지금 비어 있습니다',
  prefixUnavailable: '프리픽스 미리 보기를 사용할 수 없습니다.',
  prefixStats: (n: number, tok: string) => `블록 ${n}개 · 렌더링 후 약 ${tok} tokens`,
  loadFailed: (msg: string) => `불러오지 못했습니다: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `템플릿의 ${list}에 제공된 값이 없어 자리 표시자가 그대로 남습니다`,
  warnUnusedVars: (list: string) => `${list}은(는) 선언했지만 쓰이지 않습니다`,
  varPanelTitle: '이 템플릿의 자리 표시자',
  multiline: '여러 줄',
  varUnreportedShort: '제공되지 않은 변수',
  varEmptyShort: '(지금은 비어 있어 기본 문구가 쓰임)',
  leaveUnsavedNamed: (names: string) => `저장하지 않은 템플릿 변경 사항이 있습니다(${names}). 버리고 나가시겠습니까?`,
  editableTemplate: '편집 가능한 템플릿',
  cardDescDefault: '소스 파일에 저장됩니다. 시스템 프리픽스를 다시 불러오면 현재 세션에 적용됩니다.',
  loadedFromDeployment: '이 배포의 재정의 파일을 불러왔습니다.',
  loadedFromPackage: '봇 패키지 재정의를 불러왔습니다. 저장하면 이 배포의 재정의 파일에 기록됩니다.',
  loadedFromWorld: 'World 기본 템플릿을 불러왔습니다. 저장하면 이 배포의 재정의 파일에 기록됩니다.',
  loadedFromSource: '소스 파일에서 불러왔습니다',
  unsaved: '● 저장 안 됨',
  saveToFile: '파일에 저장',
  resetToWorld: '배포 재정의 제거',
  savedResult: (result: string) => `✓ ${result}. 프리픽스를 다시 불러온 뒤 적용됩니다`,
  saveFailed: (msg: string) => `저장하지 못했습니다: ${msg}`,
  saveFailedToast: '저장 실패',
  resetTitle: (title: string) => `"${title}"의 배포 재정의를 삭제하시겠습니까?`,
  resetBody: '삭제하면 봇 패키지의 재정의 버전을 쓰고, 패키지에 재정의가 없으면 World 기본 버전을 씁니다. 저장하지 않은 변경 사항은 사라집니다.',
  resetting: '복원하는 중…',
  resetDone: '배포 재정의를 제거했습니다',
  resetFailed: (msg: string) => `복원하지 못했습니다: ${msg}`,
  resetFailedToast: '복원 실패',
  noTemplatesScoped: '이 소유자 아래에는 편집할 수 있는 템플릿이 없습니다',
  noTemplates: '편집할 수 있는 프롬프트 템플릿이 없습니다',
  templatesLoadFailed: (msg: string) => `템플릿을 불러오지 못했습니다: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S로 저장',
};
