import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: 'Prompt de sistema',
  introDesc: 'Ctrl+S salva os modelos; recarregue para atualizar o prefixo da sessão atual. Seções vindas do código são somente leitura.',
  reloadSession: 'Recarregar sessão atual',
  reloading: 'Recarregando…',
  prefixReloaded: 'Prefixo recarregado',
  leaveUnsaved: 'As alterações não salvas serão perdidas. Sair?',
  saving: 'Salvando…',
  saved: 'Salvo',
  saveFailedFor: (title: string, msg: string) => `Falha ao salvar ${title}: ${msg}`,
  savedList: (names: string) => `✓ Salvo: ${names}; vale após recarregar`,
  dirtyCount: (n: number) => `${n} ${n === 1 ? 'alteração não salva' : 'alterações não salvas'} (Ctrl+S)`,
  fillNowMultiline: 'Valor neste momento (bloco de várias linhas)',
  fillNow: 'Valor neste momento',
  varUnreported: 'Variável não fornecida; o marcador de posição fica inalterado.',
  varEmpty: '(vazio neste momento; usa o texto padrão)',
  flagEditable: (key, origin) =>
    `Editável: ${key}${origin === 'deployment' ? ' (substituição desta implantação)' : origin === 'package' ? ' (substituição do pacote; salvar a torna a substituição desta implantação)' : origin === 'module' ? ' (padrão do World; salvar o torna a substituição desta implantação)' : ''}`,
  flagReadonly: 'Vem do código, somente leitura',
  sourceMissing: (key: string) => `Fonte “${key}” não encontrada`,
  fromCode: 'Do código',
  originDeployment: 'Substituição desta implantação',
  originPackage: 'Substituição do pacote do bot',
  originWorld: 'Padrão do World',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'O prefixo está vazio neste momento',
  prefixUnavailable: 'Prévia do prefixo indisponível.',
  prefixStats: (n: number, tok: string) => `${n} ${n === 1 ? 'bloco' : 'blocos'} · cerca de ${tok} tokens renderizados`,
  loadFailed: (msg: string) => `Falha ao carregar: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} não tem valor fornecido; os marcadores de posição ficam inalterados`,
  warnUnusedVars: (list: string) => `${list} declarado, mas não usado`,
  varPanelTitle: 'Marcadores de posição deste modelo',
  multiline: 'várias linhas',
  varUnreportedShort: 'Variável não fornecida',
  varEmptyShort: '(vazio neste momento; usa o texto padrão)',
  leaveUnsavedNamed: (names: string) => `Há alterações não salvas em modelos (${names}). Sair e descartá-las?`,
  editableTemplate: 'modelo editável',
  cardDescDefault: 'Salvo no arquivo de origem; vale para a sessão atual após recarregar o prefixo de sistema.',
  loadedFromDeployment: 'Substituição da implantação carregada.',
  loadedFromPackage: 'Substituição do pacote do bot carregada; salvar grava a substituição da implantação.',
  loadedFromWorld: 'Padrão do World carregado; salvar grava a substituição da implantação.',
  loadedFromSource: 'Carregado do arquivo de origem',
  unsaved: '● Não salvo',
  saveToFile: 'Salvar no arquivo',
  resetToWorld: 'Remover substituição da implantação',
  savedResult: (result: string) => `✓ ${result}; vale após recarregar o prefixo`,
  saveFailed: (msg: string) => `Falha ao salvar: ${msg}`,
  saveFailedToast: 'Falha ao salvar',
  resetTitle: (title: string) => `Excluir a substituição da implantação de “${title}”?`,
  resetBody: 'Após a exclusão, usa a substituição do pacote do bot ou, se o pacote não tiver uma, o padrão do World. As alterações não salvas serão perdidas.',
  resetting: 'Restaurando…',
  resetDone: 'Substituição da implantação removida',
  resetFailed: (msg: string) => `Falha ao restaurar: ${msg}`,
  resetFailedToast: 'Falha ao restaurar',
  noTemplatesScoped: 'Nenhum modelo editável deste proprietário',
  noTemplates: 'Nenhum modelo de prompt editável',
  templatesLoadFailed: (msg: string) => `Falha ao carregar os modelos: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S para salvar',
};
