import type { EnvPromptOrigin } from '../../../../core/prefix.ts';
import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  title: '系統提示詞',
  introDesc: 'Ctrl+S 儲存範本，重新載入後更新目前 session 前綴。來自程式碼的段落唯讀。',
  reloadSession: '重新載入目前 session',
  reloading: '正在重新載入…',
  prefixReloaded: '前綴已重新載入',
  leaveUnsaved: '未儲存的修改將遺失。離開？',
  saving: '儲存中…',
  saved: '已儲存',
  saveFailedFor: (title: string, msg: string) => `${title} 儲存失敗：${msg}`,
  savedList: (names: string) => `✓ 已儲存 ${names}；重新載入後生效`,
  dirtyCount: (n: number) => `${n} 處變更還沒儲存（Ctrl+S）`,
  fillNowMultiline: '此刻填入（多行區塊）',
  fillNow: '此刻填入',
  varUnreported: '未提供此變數；預留位置將原樣保留。',
  varEmpty: '(此刻為空，會落到預設文案)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `可編輯：${key}${origin === 'deployment' ? '（本部署的覆蓋）' : origin === 'package' ? '（bot 套件覆蓋；儲存寫入部署覆蓋）' : origin === 'module' ? '（World 預設；儲存後成為本部署的覆蓋）' : ''}`,
  flagReadonly: '來自程式碼，唯讀',
  sourceMissing: (key: string) => `來源「${key}」找不到`,
  fromCode: '來自程式碼',
  originDeployment: '本部署的覆蓋',
  originPackage: 'bot 套件覆蓋',
  originWorld: 'World 預設',
  listSep: '、',
  warnSep: '；',
  prefixEmpty: '前綴現在是空的',
  prefixUnavailable: '前綴預覽無法使用。',
  prefixStats: (n: number, tok: string) => `${n} 塊 · 算繪後約 ${tok} tokens`,
  loadFailed: (msg: string) => `載入失敗：${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `範本裡的 ${list} 未提供值，預留位置將原樣保留`,
  warnUnusedVars: (list: string) => `${list} 宣告了但沒用到`,
  varPanelTitle: '這份範本的預留位置',
  multiline: '多行',
  varUnreportedShort: '未提供此變數',
  varEmptyShort: '(此刻為空,會落到預設文案)',
  leaveUnsavedNamed: (names: string) => `有未儲存的範本變更（${names}）。離開並放棄？`,
  editableTemplate: '可編輯範本',
  cardDescDefault: '儲存到來源檔案；重新載入系統前綴後對目前 session 生效。',
  loadedFromDeployment: '已載入本部署覆蓋檔案。',
  loadedFromPackage: '已載入 bot 套件覆蓋；儲存寫入本部署覆蓋檔案。',
  loadedFromWorld: '已載入 World 預設範本；儲存寫入本部署覆蓋檔案。',
  loadedFromSource: '已從來源檔案載入',
  unsaved: '● 未儲存',
  saveToFile: '儲存到檔案',
  resetToWorld: '移除部署覆蓋',
  savedResult: (result: string) => `✓ ${result}；重新載入前綴後生效`,
  saveFailed: (msg: string) => `儲存失敗：${msg}`,
  saveFailedToast: '儲存失敗',
  resetTitle: (title: string) => `刪除「${title}」的部署覆蓋？`,
  resetBody: '刪除後使用 bot 套件的覆蓋版本；沒有套件覆蓋時使用 World 預設版本。未儲存的修改將遺失。',
  resetting: '還原中…',
  resetDone: '已移除部署覆蓋',
  resetFailed: (msg: string) => `還原失敗：${msg}`,
  resetFailedToast: '還原失敗',
  noTemplatesScoped: '這個歸屬下沒有可編輯的範本',
  noTemplates: '沒有可編輯的提示詞範本',
  templatesLoadFailed: (msg: string) => `範本載入失敗：${msg}`,

  // editor.ts
  saveHintDirty: '按 Ctrl+S 儲存',
};
