import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git no disponible',
  noRepo: 'todavía no hay repositorio',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'cambios sin commit' : 'limpio'} · ${checkpoints} ${checkpoints === 1 ? 'punto de control' : 'puntos de control'}`,
  historyLoading: 'Leyendo el historial de commits…',
  historyFailed: 'Historial de versiones no disponible',
  mediumTitle: 'Estado del medio',
  mediumDesc: 'El espacio de trabajo es su propio repositorio git, aparte del repositorio del proyecto. Las ediciones hechas en la consola reciben commit de inmediato, con operator como autor.',
  rowStatus: 'Estado',
  rowWorkspace: 'Espacio de trabajo',
  dirty: 'Cambios sin commit',
  clean: 'Limpio',
  rowCheckpoints: 'Puntos de control',
  noCheckpoints: '(todavía ninguno)',
  rowLastCommit: 'Último commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Registro de commits',
  logDesc: 'Haz clic en un commit para desplegar el diff que introdujo. Hasta 100 commits; escribe una ruta para ver solo un archivo.',
  pathFilter: 'Solo esta ruta, p. ej. CONSTITUTION.md',
  filter: 'Filtrar',
  clear: 'Limpiar',
  commitCount: (n: number) => `${n} ${n === 1 ? 'commit' : 'commits'}`,
  noCommitsInRange: 'Todavía no hay commits en este rango',
  noRepoYet: 'El espacio de trabajo todavía no tiene repositorio',
  loadingDiff: 'Cargando diff…',
  copyDiff: 'Copiar diff',
  diffFailed: (error: string) => `Falló el diff: ${error}`,
  fullTextHint: 'Para ver una versión completa, abre el archivo en “Espacio de trabajo” y presiona “Historial”.',
  templateBlank: 'En blanco',
  templateNote: 'Nota',
  untitled: 'Archivo nuevo',
  treeLoading: 'Leyendo el árbol del espacio de trabajo…',
  workspaceFailed: 'Espacio de trabajo no disponible',
  workspaceTitle: 'Espacio de trabajo',
  workspaceDesc: 'Al guardar se hace un commit en el repositorio Git del espacio de trabajo, con operator como autor.',
  filterFiles: 'Filtrar nombres de archivo…',
  newFile: 'Nuevo',
  refresh: 'Actualizar',
  noFileOpen: 'No hay archivo abierto',
  save: 'Guardar',
  revert: 'Revertir',
  find: 'Buscar',
  history: 'Historial',
  rename: 'Renombrar',
  remove: 'Eliminar',
  modeEdit: 'Editar',
  modeSplit: 'Dividido',
  modePreview: 'Vista previa',
  replaceWith: 'Reemplazar con',
  noMatches: 'Sin coincidencias',
  previous: 'Anterior',
  next: 'Siguiente',
  replace: 'Reemplazar',
  replaceAll: 'Reemplazar todo',
  close: 'Cerrar',
  leaveGuard: 'El espacio de trabajo tiene cambios sin guardar; si sales, se descartan.',
  noMatchingFiles: 'No hay archivos que coincidan',
  emptyRoot: (root: string) => `${root}/ está vacío`,
  discardTitle: '¿Descartar los cambios sin guardar?',
  discardBody: (path: string) => `${path} tiene cambios sin guardar. Si abres otro archivo, se descartan.`,
  opening: (path: string) => `Abriendo ${path}…`,
  readFailed: 'No se pudo leer',
  readFailedDetail: (error: string) => `No se pudo leer: ${error}`,
  saving: 'Guardando…',
  saveFailed: (error: string) => `No se pudo guardar: ${error}`,
  revertTitle: '¿Descartar los cambios actuales sin guardar?',
  reverted: 'Se restauró la última versión guardada',
  removeTitle: (path: string) => `¿Eliminar ${path}?`,
  removeBody: 'Los cambios sin guardar se perderán. Las versiones con commit se pueden restaurar desde “Historial de versiones”.',
  removed: 'Archivo eliminado',
  removeFailed: (error: string) => `No se pudo eliminar: ${error}`,
  fileNamePlaceholder: 'nombre.md',
  create: 'Crear',
  needFileName: 'Escribe un nombre de archivo',
  creating: 'Creando…',
  createFailed: (error: string) => `No se pudo crear: ${error}`,
  fieldDir: 'Carpeta',
  fieldName: 'Nombre de archivo',
  fieldTemplate: 'Plantilla',
  fieldBody: 'Contenido',
  newFileTitle: 'Archivo nuevo',
  saveBeforeRename: 'Guarda o descarta tus cambios antes de renombrar',
  needNewPath: 'Escribe una ruta nueva distinta',
  renameFailed: (error: string) => `No se pudo renombrar: ${error}`,
  currentPath: (path: string) => `Actual: ${path}`,
  newPath: (root: string) => `Ruta nueva (relativa a ${root}/)`,
  renameTitle: 'Renombrar / mover',
  fileHistoryLoading: 'Cargando historial…',
  fileHistoryFailed: (error: string) => `No se pudo cargar el historial: ${error}`,
  backToEditor: '← Volver al editor',
  noFileHistory: 'Este archivo todavía no tiene historial de commits',
  viewFull: 'Ver texto completo',
  restoreDraft: 'Restaurar como borrador actual',
  restored: 'Se cargó la versión anterior; se aplica al guardar',
  copyFull: 'Copiar texto completo',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Lín. ${line}, col. ${col} · ${lines} ${lines === 1 ? 'línea' : 'líneas'}, ${chars} ${chars === 1 ? 'carácter' : 'caracteres'} · ${dirty ? '● Sin guardar' : '✓ Guardado'}`,
  matches: (n: number) => `${n} ${n === 1 ? 'coincidencia' : 'coincidencias'}`,
};
