import type { en } from './strings.ts';

const pluralRules = new Intl.PluralRules('ru');
const plural = (n: number, one: string, few: string, many: string) => {
  const form = pluralRules.select(n);
  return form === 'one' ? one : form === 'many' ? many : few;
};

export const S: Partial<typeof en> = {
  gitUnavailable: 'git недоступен',
  noRepo: 'репозитория ещё нет',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'есть незакоммиченные изменения' : 'чисто'} · ${checkpoints} ${plural(checkpoints, 'контрольная точка', 'контрольные точки', 'контрольных точек')}`,
  historyLoading: 'Чтение истории коммитов…',
  historyFailed: 'История версий недоступна',
  mediumTitle: 'Состояние носителя',
  mediumDesc: 'Рабочая область — отдельный git-репозиторий, не связанный с репозиторием проекта. Правки из консоли коммитятся сразу от имени operator.',
  rowStatus: 'Состояние',
  rowWorkspace: 'Рабочая область',
  dirty: 'Есть незакоммиченные изменения',
  clean: 'Чисто',
  rowCheckpoints: 'Контрольные точки',
  noCheckpoints: '(пока нет)',
  rowLastCommit: 'Последний коммит',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Журнал коммитов',
  logDesc: 'Нажмите на коммит, чтобы развернуть внесённый им diff. Не больше 100 коммитов; укажите путь, чтобы смотреть только один файл.',
  pathFilter: 'Только этот путь, например CONSTITUTION.md',
  filter: 'Фильтр',
  clear: 'Сбросить',
  commitCount: (n: number) => `${n} ${plural(n, 'коммит', 'коммита', 'коммитов')}`,
  noCommitsInRange: 'В этом диапазоне пока нет коммитов',
  noRepoYet: 'У рабочей области пока нет репозитория',
  loadingDiff: 'Загрузка diff…',
  copyDiff: 'Копировать diff',
  diffFailed: (error: string) => `Не удалось получить diff: ${error}`,
  fullTextHint: 'Чтобы увидеть версию целиком, откройте файл в разделе «Рабочая область» и нажмите «История».',
  templateBlank: 'Пустой',
  templateNote: 'Заметка',
  untitled: 'Новый файл',
  treeLoading: 'Чтение дерева рабочей области…',
  workspaceFailed: 'Рабочая область недоступна',
  workspaceTitle: 'Рабочая область',
  workspaceDesc: 'При сохранении создаётся коммит в Git-репозитории рабочей области от имени operator.',
  filterFiles: 'Фильтр по имени файла…',
  newFile: 'Новый',
  refresh: 'Обновить',
  noFileOpen: 'Файл не открыт',
  save: 'Сохранить',
  revert: 'Откатить',
  find: 'Найти',
  history: 'История',
  rename: 'Переименовать',
  remove: 'Удалить',
  modeEdit: 'Правка',
  modeSplit: 'Рядом',
  modePreview: 'Просмотр',
  replaceWith: 'Заменить на',
  noMatches: 'Нет совпадений',
  previous: 'Назад',
  next: 'Далее',
  replace: 'Заменить',
  replaceAll: 'Заменить все',
  close: 'Закрыть',
  leaveGuard: 'В рабочей области есть несохранённые изменения; если уйти, они будут потеряны.',
  noMatchingFiles: 'Нет подходящих файлов',
  emptyRoot: (root: string) => `Папка ${root}/ пуста`,
  discardTitle: 'Отменить несохранённые изменения?',
  discardBody: (path: string) => `В ${path} есть несохранённые изменения. Если открыть другой файл, они будут потеряны.`,
  opening: (path: string) => `Открытие ${path}…`,
  readFailed: 'Не удалось прочитать',
  readFailedDetail: (error: string) => `Не удалось прочитать: ${error}`,
  saving: 'Сохранение…',
  saveFailed: (error: string) => `Не удалось сохранить: ${error}`,
  revertTitle: 'Отменить текущие несохранённые изменения?',
  reverted: 'Восстановлена последняя сохранённая версия',
  removeTitle: (path: string) => `Удалить ${path}?`,
  removeBody: 'Несохранённые изменения будут потеряны. Закоммиченные версии можно восстановить в разделе «История версий».',
  removed: 'Файл удалён',
  removeFailed: (error: string) => `Не удалось удалить: ${error}`,
  fileNamePlaceholder: 'имя.md',
  create: 'Создать',
  needFileName: 'Укажите имя файла',
  creating: 'Создание…',
  createFailed: (error: string) => `Не удалось создать: ${error}`,
  fieldDir: 'Папка',
  fieldName: 'Имя файла',
  fieldTemplate: 'Шаблон',
  fieldBody: 'Содержимое',
  newFileTitle: 'Новый файл',
  saveBeforeRename: 'Сохраните или отмените изменения перед переименованием',
  needNewPath: 'Укажите другой новый путь',
  renameFailed: (error: string) => `Не удалось переименовать: ${error}`,
  currentPath: (path: string) => `Сейчас: ${path}`,
  newPath: (root: string) => `Новый путь (относительно ${root}/)`,
  renameTitle: 'Переименовать / переместить',
  fileHistoryLoading: 'Загрузка истории…',
  fileHistoryFailed: (error: string) => `Не удалось загрузить историю: ${error}`,
  backToEditor: '← Назад к редактору',
  noFileHistory: 'У этого файла пока нет истории коммитов',
  viewFull: 'Показать полностью',
  restoreDraft: 'Восстановить как текущий черновик',
  restored: 'Старая версия загружена; она вступит в силу после сохранения',
  copyFull: 'Копировать полностью',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Стр. ${line}, стлб. ${col} · ${lines} ${plural(lines, 'строка', 'строки', 'строк')}, ${chars} ${plural(chars, 'символ', 'символа', 'символов')} · ${dirty ? '● Не сохранено' : '✓ Сохранено'}`,
  matches: (n: number) => `${n} ${plural(n, 'совпадение', 'совпадения', 'совпадений')}`,
};
