import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git nicht verfügbar',
  noRepo: 'noch kein Repository',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'nicht committete Änderungen' : 'sauber'} · ${checkpoints} ${checkpoints === 1 ? 'Checkpoint' : 'Checkpoints'}`,
  historyLoading: 'Commit-Verlauf wird gelesen…',
  historyFailed: 'Versionsverlauf nicht verfügbar',
  mediumTitle: 'Status des Mediums',
  mediumDesc: 'Der Arbeitsbereich ist ein eigenes Git-Repository, getrennt vom Projekt-Repository. Änderungen in der Konsole werden sofort committet, mit operator als Autor.',
  rowStatus: 'Status',
  rowWorkspace: 'Arbeitsbereich',
  dirty: 'Nicht committete Änderungen',
  clean: 'Sauber',
  rowCheckpoints: 'Checkpoints',
  noCheckpoints: '(noch keine)',
  rowLastCommit: 'Letzter Commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Commit-Log',
  logDesc: 'Klicke auf einen Commit, um den Diff aufzuklappen, den er eingeführt hat. Höchstens 100 Commits; gib einen Pfad ein, um nur eine Datei zu sehen.',
  pathFilter: 'Nur dieser Pfad, z. B. CONSTITUTION.md',
  filter: 'Filtern',
  clear: 'Zurücksetzen',
  commitCount: (n: number) => `${n} ${n === 1 ? 'Commit' : 'Commits'}`,
  noCommitsInRange: 'In diesem Bereich gibt es noch keine Commits',
  noRepoYet: 'Der Arbeitsbereich hat noch kein Repository',
  loadingDiff: 'Diff wird geladen…',
  copyDiff: 'Diff kopieren',
  diffFailed: (error: string) => `Diff fehlgeschlagen: ${error}`,
  fullTextHint: 'Um eine Version vollständig zu sehen, öffne die Datei unter „Arbeitsbereich“ und klicke auf „Verlauf“.',
  templateBlank: 'Leer',
  templateNote: 'Notiz',
  untitled: 'Neue Datei',
  treeLoading: 'Verzeichnisbaum des Arbeitsbereichs wird gelesen…',
  workspaceFailed: 'Arbeitsbereich nicht verfügbar',
  workspaceTitle: 'Arbeitsbereich',
  workspaceDesc: 'Speichern erstellt einen Commit im Git-Repository des Arbeitsbereichs, mit operator als Autor.',
  filterFiles: 'Dateinamen filtern…',
  newFile: 'Neu',
  refresh: 'Aktualisieren',
  noFileOpen: 'Keine Datei geöffnet',
  save: 'Speichern',
  revert: 'Wiederherstellen',
  find: 'Suchen',
  history: 'Verlauf',
  rename: 'Umbenennen',
  remove: 'Löschen',
  modeEdit: 'Bearbeiten',
  modeSplit: 'Geteilt',
  modePreview: 'Vorschau',
  replaceWith: 'Ersetzen durch',
  noMatches: 'Keine Treffer',
  previous: 'Zurück',
  next: 'Weiter',
  replace: 'Ersetzen',
  replaceAll: 'Alle ersetzen',
  close: 'Schließen',
  leaveGuard: 'Im Arbeitsbereich gibt es ungespeicherte Änderungen; beim Verlassen gehen sie verloren.',
  noMatchingFiles: 'Keine passenden Dateien',
  emptyRoot: (root: string) => `${root}/ ist leer`,
  discardTitle: 'Ungespeicherte Änderungen verwerfen?',
  discardBody: (path: string) => `${path} hat ungespeicherte Änderungen. Wenn du eine andere Datei öffnest, gehen sie verloren.`,
  opening: (path: string) => `${path} wird geöffnet…`,
  readFailed: 'Lesen fehlgeschlagen',
  readFailedDetail: (error: string) => `Lesen fehlgeschlagen: ${error}`,
  saving: 'Wird gespeichert…',
  saveFailed: (error: string) => `Speichern fehlgeschlagen: ${error}`,
  revertTitle: 'Aktuelle ungespeicherte Änderungen verwerfen?',
  reverted: 'Zuletzt gespeicherte Version wiederhergestellt',
  removeTitle: (path: string) => `${path} löschen?`,
  removeBody: 'Ungespeicherte Änderungen gehen verloren. Committete Versionen lassen sich über „Versionsverlauf“ wiederherstellen.',
  removed: 'Datei gelöscht',
  removeFailed: (error: string) => `Löschen fehlgeschlagen: ${error}`,
  fileNamePlaceholder: 'name.md',
  create: 'Erstellen',
  needFileName: 'Gib einen Dateinamen ein',
  creating: 'Wird erstellt…',
  createFailed: (error: string) => `Erstellen fehlgeschlagen: ${error}`,
  fieldDir: 'Ordner',
  fieldName: 'Dateiname',
  fieldTemplate: 'Vorlage',
  fieldBody: 'Inhalt',
  newFileTitle: 'Neue Datei',
  saveBeforeRename: 'Speichere oder verwirf deine Änderungen vor dem Umbenennen',
  needNewPath: 'Gib einen anderen neuen Pfad ein',
  renameFailed: (error: string) => `Umbenennen fehlgeschlagen: ${error}`,
  currentPath: (path: string) => `Aktuell: ${path}`,
  newPath: (root: string) => `Neuer Pfad (relativ zu ${root}/)`,
  renameTitle: 'Umbenennen / verschieben',
  fileHistoryLoading: 'Verlauf wird geladen…',
  fileHistoryFailed: (error: string) => `Verlauf konnte nicht geladen werden: ${error}`,
  backToEditor: '← Zurück zum Editor',
  noFileHistory: 'Diese Datei hat noch keinen Commit-Verlauf',
  viewFull: 'Volltext anzeigen',
  restoreDraft: 'Als aktuellen Entwurf wiederherstellen',
  restored: 'Alte Version geladen; sie wird beim Speichern übernommen',
  copyFull: 'Volltext kopieren',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Zeile ${line}, Spalte ${col} · ${lines} ${lines === 1 ? 'Zeile' : 'Zeilen'}, ${chars} Zeichen · ${dirty ? '● Nicht gespeichert' : '✓ Gespeichert'}`,
  matches: (n: number) => `${n} Treffer`,
};
