import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git indisponible',
  noRepo: 'pas encore de dépôt',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'modifications non commitées' : 'propre'} · ${checkpoints} point${checkpoints > 1 ? 's' : ''} de contrôle`,
  historyLoading: "Lecture de l'historique des commits…",
  historyFailed: 'Historique des versions indisponible',
  mediumTitle: 'État du support',
  mediumDesc: "L'espace de travail est son propre dépôt git, distinct du dépôt du projet. Les modifications faites dans la console sont commitées immédiatement, signées operator.",
  rowStatus: 'État',
  rowWorkspace: 'Espace de travail',
  dirty: 'Modifications non commitées',
  clean: 'Propre',
  rowCheckpoints: 'Points de contrôle',
  noCheckpoints: '(aucun pour le moment)',
  rowLastCommit: 'Dernier commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Journal des commits',
  logDesc: "Cliquez sur un commit pour afficher le diff qu'il a introduit. 100 commits au plus ; saisissez un chemin pour ne voir qu'un fichier.",
  pathFilter: 'Seulement ce chemin, p. ex. CONSTITUTION.md',
  filter: 'Filtrer',
  clear: 'Effacer',
  commitCount: (n: number) => `${n} commit${n > 1 ? 's' : ''}`,
  noCommitsInRange: 'Aucun commit dans cette plage pour le moment',
  noRepoYet: "L'espace de travail n'a pas encore de dépôt",
  loadingDiff: 'Chargement du diff…',
  copyDiff: 'Copier le diff',
  diffFailed: (error: string) => `Échec du diff : ${error}`,
  fullTextHint: 'Pour voir une version en entier, ouvrez le fichier dans « Espace de travail » puis appuyez sur « Historique ».',
  templateBlank: 'Vide',
  templateNote: 'Note',
  untitled: 'Nouveau fichier',
  treeLoading: "Lecture de l'arborescence de l'espace de travail…",
  workspaceFailed: 'Espace de travail indisponible',
  workspaceTitle: 'Espace de travail',
  workspaceDesc: "L'enregistrement crée un commit dans le dépôt Git de l'espace de travail, signé operator.",
  filterFiles: 'Filtrer les noms de fichiers…',
  newFile: 'Nouveau',
  refresh: 'Actualiser',
  noFileOpen: 'Aucun fichier ouvert',
  save: 'Enregistrer',
  revert: 'Rétablir',
  find: 'Rechercher',
  history: 'Historique',
  rename: 'Renommer',
  remove: 'Supprimer',
  modeEdit: 'Édition',
  modeSplit: 'Partagé',
  modePreview: 'Aperçu',
  replaceWith: 'Remplacer par',
  noMatches: 'Aucune correspondance',
  previous: 'Précédent',
  next: 'Suivant',
  replace: 'Remplacer',
  replaceAll: 'Tout remplacer',
  close: 'Fermer',
  leaveGuard: "L'espace de travail contient des modifications non enregistrées ; quitter la page les abandonne.",
  noMatchingFiles: 'Aucun fichier correspondant',
  emptyRoot: (root: string) => `${root}/ est vide`,
  discardTitle: 'Abandonner les modifications non enregistrées ?',
  discardBody: (path: string) => `${path} contient des modifications non enregistrées. Ouvrir un autre fichier les abandonne.`,
  opening: (path: string) => `Ouverture de ${path}…`,
  readFailed: 'Échec de la lecture',
  readFailedDetail: (error: string) => `Échec de la lecture : ${error}`,
  saving: 'Enregistrement…',
  saveFailed: (error: string) => `Échec de l'enregistrement : ${error}`,
  revertTitle: 'Abandonner les modifications actuelles non enregistrées ?',
  reverted: 'Dernière version enregistrée rétablie',
  removeTitle: (path: string) => `Supprimer ${path} ?`,
  removeBody: 'Les modifications non enregistrées seront perdues. Les versions commitées peuvent être restaurées depuis « Historique des versions ».',
  removed: 'Fichier supprimé',
  removeFailed: (error: string) => `Échec de la suppression : ${error}`,
  fileNamePlaceholder: 'nom.md',
  create: 'Créer',
  needFileName: 'Saisissez un nom de fichier',
  creating: 'Création…',
  createFailed: (error: string) => `Échec de la création : ${error}`,
  fieldDir: 'Dossier',
  fieldName: 'Nom du fichier',
  fieldTemplate: 'Modèle',
  fieldBody: 'Contenu',
  newFileTitle: 'Nouveau fichier',
  saveBeforeRename: 'Enregistrez ou abandonnez vos modifications avant de renommer',
  needNewPath: 'Saisissez un nouveau chemin différent',
  renameFailed: (error: string) => `Échec du renommage : ${error}`,
  currentPath: (path: string) => `Actuel : ${path}`,
  newPath: (root: string) => `Nouveau chemin (relatif à ${root}/)`,
  renameTitle: 'Renommer / déplacer',
  fileHistoryLoading: "Chargement de l'historique…",
  fileHistoryFailed: (error: string) => `Échec du chargement de l'historique : ${error}`,
  backToEditor: "← Retour à l'éditeur",
  noFileHistory: "Ce fichier n'a pas encore d'historique de commits",
  viewFull: 'Voir le texte complet',
  restoreDraft: 'Restaurer comme brouillon actuel',
  restored: "Ancienne version chargée ; elle s'applique à l'enregistrement",
  copyFull: 'Copier le texte complet',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Ligne ${line}, col. ${col} · ${lines} ligne${lines > 1 ? 's' : ''}, ${chars} caractère${chars > 1 ? 's' : ''} · ${dirty ? '● Non enregistré' : '✓ Enregistré'}`,
  matches: (n: number) => `${n} occurrence${n > 1 ? 's' : ''}`,
};
