import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git を利用できません',
  noRepo: 'まだリポジトリがありません',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? '未コミットの変更あり' : 'クリーン'} · チェックポイント ${checkpoints} 個`,
  historyLoading: 'コミット履歴を読み込み中…',
  historyFailed: 'バージョン履歴を利用できません',
  mediumTitle: '媒体の状態',
  mediumDesc: 'ワークスペースはそれ自体が git リポジトリです（プロジェクトのリポジトリとは別）。コンソールでの編集はすぐにコミットされます（operator 名義）。',
  rowStatus: '状態',
  rowWorkspace: 'ワークスペース',
  dirty: '未コミットの変更あり',
  clean: 'クリーン',
  rowCheckpoints: 'チェックポイント',
  noCheckpoints: '（まだありません）',
  rowLastCommit: '最新のコミット',
  names: (list: string[]) => list.join('、'),
  logTitle: 'コミット履歴',
  logDesc: 'クリックすると、そのコミットで入った diff を展開します。最大 100 件です。パスを入力すると、そのファイルだけを表示します。',
  pathFilter: 'このパスのみ（例：CONSTITUTION.md）',
  filter: '絞り込む',
  clear: 'クリア',
  commitCount: (n: number) => `${n} 件`,
  noCommitsInRange: 'この範囲にはまだコミットがありません',
  noRepoYet: 'ワークスペースにはまだリポジトリがありません',
  loadingDiff: 'diff を読み込み中…',
  copyDiff: 'diff をコピー',
  diffFailed: (error: string) => `diff の取得に失敗しました：${error}`,
  fullTextHint: 'あるバージョンの全文を見るには、「ワークスペース」でそのファイルを開いて「履歴」を押してください。',
  templateBlank: '空白',
  templateNote: 'メモ',
  untitled: '新しいファイル',
  treeLoading: 'ワークスペースのディレクトリツリーを読み込み中…',
  workspaceFailed: 'ワークスペースを利用できません',
  workspaceTitle: 'ワークスペース',
  workspaceDesc: '保存すると operator の名義でワークスペースの Git リポジトリにコミットされます。',
  filterFiles: 'ファイル名で絞り込む…',
  newFile: '新規',
  refresh: '更新',
  noFileOpen: 'ファイルが開かれていません',
  save: '保存',
  revert: '元に戻す',
  find: '検索',
  history: '履歴',
  rename: '名前を変更',
  remove: '削除',
  modeEdit: '編集',
  modeSplit: '分割',
  modePreview: 'プレビュー',
  replaceWith: '置換後の文字列',
  noMatches: '一致なし',
  previous: '前へ',
  next: '次へ',
  replace: '置換',
  replaceAll: 'すべて置換',
  close: '閉じる',
  leaveGuard: 'ワークスペースに保存されていない変更があります。移動すると変更は破棄されます。',
  noMatchingFiles: '一致するファイルはありません',
  emptyRoot: (root: string) => `${root}/ は空です`,
  discardTitle: '保存されていない変更を破棄しますか？',
  discardBody: (path: string) => `${path} には保存されていない変更があります。別のファイルを開くと、これらの変更は破棄されます。`,
  opening: (path: string) => `${path} を開いています…`,
  readFailed: '読み込みに失敗しました',
  readFailedDetail: (error: string) => `読み込みに失敗しました：${error}`,
  saving: '保存中…',
  saveFailed: (error: string) => `保存に失敗しました：${error}`,
  revertTitle: '現在の保存されていない変更を破棄しますか？',
  reverted: '最後に保存したバージョンに戻しました',
  removeTitle: (path: string) => `${path} を削除しますか？`,
  removeBody: '保存されていない変更は失われます。コミット済みのバージョンは「バージョン履歴」から復元できます。',
  removed: 'ファイルを削除しました',
  removeFailed: (error: string) => `削除に失敗しました：${error}`,
  fileNamePlaceholder: 'ファイル名.md',
  create: '作成',
  needFileName: 'ファイル名を入力してください',
  creating: '作成中…',
  createFailed: (error: string) => `作成に失敗しました：${error}`,
  fieldDir: 'フォルダー',
  fieldName: 'ファイル名',
  fieldTemplate: 'テンプレート',
  fieldBody: '本文',
  newFileTitle: '新しいファイル',
  saveBeforeRename: '名前を変更する前に、変更を保存するか破棄してください',
  needNewPath: '別の新しいパスを入力してください',
  renameFailed: (error: string) => `名前の変更に失敗しました：${error}`,
  currentPath: (path: string) => `現在：${path}`,
  newPath: (root: string) => `新しいパス（${root}/ からの相対パス）`,
  renameTitle: '名前の変更 / 移動',
  fileHistoryLoading: '履歴を読み込み中…',
  fileHistoryFailed: (error: string) => `履歴の読み込みに失敗しました：${error}`,
  backToEditor: '← エディターに戻る',
  noFileHistory: 'このファイルにはまだコミット履歴がありません',
  viewFull: '全文を表示',
  restoreDraft: '現在の下書きとして復元',
  restored: '古いバージョンを読み込みました。保存すると反映されます',
  copyFull: '全文をコピー',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `${line} 行 ${col} 列 · ${lines} 行 ${chars} 文字 · ${dirty ? '● 未保存' : '✓ 保存済み'}`,
  matches: (n: number) => `${n} 件`,
};
