import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git non disponibile',
  noRepo: 'ancora nessun repository',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'modifiche non committate' : 'pulito'} · ${checkpoints} checkpoint`,
  historyLoading: 'Lettura della cronologia dei commit…',
  historyFailed: 'Cronologia versioni non disponibile',
  mediumTitle: 'Stato del supporto',
  mediumDesc: "L'area di lavoro è un repository git a sé, separato dal repository del progetto. Le modifiche fatte dalla console vengono committate subito, con autore operator.",
  rowStatus: 'Stato',
  rowWorkspace: 'Area di lavoro',
  dirty: 'Modifiche non committate',
  clean: 'Pulito',
  rowCheckpoints: 'Checkpoint',
  noCheckpoints: '(ancora nessuno)',
  rowLastCommit: 'Ultimo commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Log dei commit',
  logDesc: 'Fai clic su un commit per espandere il diff che ha introdotto. Al massimo 100 commit; inserisci un percorso per vedere un solo file.',
  pathFilter: 'Solo questo percorso, es. CONSTITUTION.md',
  filter: 'Filtra',
  clear: 'Cancella',
  commitCount: (n: number) => `${n} commit`,
  noCommitsInRange: 'Ancora nessun commit in questo intervallo',
  noRepoYet: "L'area di lavoro non ha ancora un repository",
  loadingDiff: 'Caricamento del diff…',
  copyDiff: 'Copia diff',
  diffFailed: (error: string) => `Diff non riuscito: ${error}`,
  fullTextHint: 'Per vedere una versione per intero, apri il file in «Area di lavoro» e premi «Cronologia».',
  templateBlank: 'Vuoto',
  templateNote: 'Nota',
  untitled: 'Nuovo file',
  treeLoading: "Lettura dell'albero dell'area di lavoro…",
  workspaceFailed: 'Area di lavoro non disponibile',
  workspaceTitle: 'Area di lavoro',
  workspaceDesc: "Il salvataggio crea un commit nel repository Git dell'area di lavoro, con autore operator.",
  filterFiles: 'Filtra i nomi dei file…',
  newFile: 'Nuovo',
  refresh: 'Aggiorna',
  noFileOpen: 'Nessun file aperto',
  save: 'Salva',
  revert: 'Ripristina',
  find: 'Trova',
  history: 'Cronologia',
  rename: 'Rinomina',
  remove: 'Elimina',
  modeEdit: 'Modifica',
  modeSplit: 'Diviso',
  modePreview: 'Anteprima',
  replaceWith: 'Sostituisci con',
  noMatches: 'Nessuna corrispondenza',
  previous: 'Precedente',
  next: 'Successivo',
  replace: 'Sostituisci',
  replaceAll: 'Sostituisci tutto',
  close: 'Chiudi',
  leaveGuard: "Nell'area di lavoro ci sono modifiche non salvate; uscendo vengono scartate.",
  noMatchingFiles: 'Nessun file corrispondente',
  emptyRoot: (root: string) => `${root}/ è vuoto`,
  discardTitle: 'Scartare le modifiche non salvate?',
  discardBody: (path: string) => `${path} ha modifiche non salvate. Aprendo un altro file vengono scartate.`,
  opening: (path: string) => `Apertura di ${path}…`,
  readFailed: 'Lettura non riuscita',
  readFailedDetail: (error: string) => `Lettura non riuscita: ${error}`,
  saving: 'Salvataggio…',
  saveFailed: (error: string) => `Salvataggio non riuscito: ${error}`,
  revertTitle: 'Scartare le modifiche attuali non salvate?',
  reverted: "Ripristinata l'ultima versione salvata",
  removeTitle: (path: string) => `Eliminare ${path}?`,
  removeBody: 'Le modifiche non salvate andranno perse. Le versioni committate si possono ripristinare da «Cronologia versioni».',
  removed: 'File eliminato',
  removeFailed: (error: string) => `Eliminazione non riuscita: ${error}`,
  fileNamePlaceholder: 'nome.md',
  create: 'Crea',
  needFileName: 'Inserisci un nome file',
  creating: 'Creazione…',
  createFailed: (error: string) => `Creazione non riuscita: ${error}`,
  fieldDir: 'Cartella',
  fieldName: 'Nome file',
  fieldTemplate: 'Modello',
  fieldBody: 'Contenuto',
  newFileTitle: 'Nuovo file',
  saveBeforeRename: 'Salva o scarta le modifiche prima di rinominare',
  needNewPath: 'Inserisci un nuovo percorso diverso',
  renameFailed: (error: string) => `Rinomina non riuscita: ${error}`,
  currentPath: (path: string) => `Attuale: ${path}`,
  newPath: (root: string) => `Nuovo percorso (relativo a ${root}/)`,
  renameTitle: 'Rinomina / sposta',
  fileHistoryLoading: 'Caricamento della cronologia…',
  fileHistoryFailed: (error: string) => `Caricamento della cronologia non riuscito: ${error}`,
  backToEditor: "← Torna all'editor",
  noFileHistory: 'Questo file non ha ancora una cronologia dei commit',
  viewFull: 'Vedi testo completo',
  restoreDraft: 'Ripristina come bozza attuale',
  restored: 'Versione precedente caricata; ha effetto al salvataggio',
  copyFull: 'Copia testo completo',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Riga ${line}, col. ${col} · ${lines} ${lines === 1 ? 'riga' : 'righe'}, ${chars} ${chars === 1 ? 'carattere' : 'caratteri'} · ${dirty ? '● Non salvato' : '✓ Salvato'}`,
  matches: (n: number) => `${n} ${n === 1 ? 'corrispondenza' : 'corrispondenze'}`,
};
