import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git을 사용할 수 없음',
  noRepo: '아직 저장소가 없음',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? '커밋하지 않은 변경 있음' : '깨끗함'} · 체크포인트 ${checkpoints}개`,
  historyLoading: '커밋 기록을 읽는 중…',
  historyFailed: '버전 기록을 사용할 수 없습니다',
  mediumTitle: '매체 상태',
  mediumDesc: '작업 공간은 그 자체로 git 저장소입니다(프로젝트 저장소와 별개). 콘솔에서 편집하면 바로 커밋됩니다(작성자 operator).',
  rowStatus: '상태',
  rowWorkspace: '작업 공간',
  dirty: '커밋하지 않은 변경 있음',
  clean: '깨끗함',
  rowCheckpoints: '체크포인트',
  noCheckpoints: '(아직 없음)',
  rowLastCommit: '최근 커밋',
  names: (list: string[]) => list.join(', '),
  logTitle: '커밋 기록',
  logDesc: '커밋을 클릭하면 그 커밋이 들여온 diff를 펼칩니다. 최대 100개이며, 경로를 입력하면 그 파일만 봅니다.',
  pathFilter: '이 경로만 보기(예: CONSTITUTION.md)',
  filter: '필터',
  clear: '지우기',
  commitCount: (n: number) => `${n}개`,
  noCommitsInRange: '이 범위에는 아직 커밋이 없습니다',
  noRepoYet: '작업 공간에 아직 저장소가 없습니다',
  loadingDiff: 'diff 불러오는 중…',
  copyDiff: 'diff 복사',
  diffFailed: (error: string) => `diff 실패: ${error}`,
  fullTextHint: '어떤 버전의 전체 내용을 보려면 "작업 공간"에서 그 파일을 열고 "기록"을 누르세요.',
  templateBlank: '빈 파일',
  templateNote: '노트',
  untitled: '새 파일',
  treeLoading: '작업 공간 디렉터리 트리를 읽는 중…',
  workspaceFailed: '작업 공간을 사용할 수 없습니다',
  workspaceTitle: '작업 공간',
  workspaceDesc: '저장하면 operator 이름으로 작업 공간 Git 저장소에 커밋됩니다.',
  filterFiles: '파일 이름 필터…',
  newFile: '새로 만들기',
  refresh: '새로 고침',
  noFileOpen: '열린 파일 없음',
  save: '저장',
  revert: '되돌리기',
  find: '찾기',
  history: '기록',
  rename: '이름 변경',
  remove: '삭제',
  modeEdit: '편집',
  modeSplit: '분할',
  modePreview: '미리 보기',
  replaceWith: '바꿀 내용',
  noMatches: '일치 항목 없음',
  previous: '이전',
  next: '다음',
  replace: '바꾸기',
  replaceAll: '모두 바꾸기',
  close: '닫기',
  leaveGuard: '작업 공간에 저장하지 않은 변경이 있습니다. 나가면 변경 내용이 버려집니다.',
  noMatchingFiles: '일치하는 파일 없음',
  emptyRoot: (root: string) => `${root}/ 폴더가 비어 있습니다`,
  discardTitle: '저장하지 않은 변경을 버릴까요?',
  discardBody: (path: string) => `${path}에 저장하지 않은 변경이 있습니다. 다른 파일을 열면 이 변경은 버려집니다.`,
  opening: (path: string) => `${path} 여는 중…`,
  readFailed: '읽기 실패',
  readFailedDetail: (error: string) => `읽기 실패: ${error}`,
  saving: '저장 중…',
  saveFailed: (error: string) => `저장 실패: ${error}`,
  revertTitle: '현재 저장하지 않은 수정을 버릴까요?',
  reverted: '마지막으로 저장한 버전으로 되돌렸습니다',
  removeTitle: (path: string) => `${path}을(를) 삭제할까요?`,
  removeBody: '저장하지 않은 수정은 사라집니다. 커밋된 버전은 "버전 기록"에서 복원할 수 있습니다.',
  removed: '파일을 삭제했습니다',
  removeFailed: (error: string) => `삭제 실패: ${error}`,
  fileNamePlaceholder: '파일이름.md',
  create: '만들기',
  needFileName: '파일 이름을 입력하세요',
  creating: '만드는 중…',
  createFailed: (error: string) => `만들기 실패: ${error}`,
  fieldDir: '폴더',
  fieldName: '파일 이름',
  fieldTemplate: '템플릿',
  fieldBody: '본문',
  newFileTitle: '새 파일',
  saveBeforeRename: '이름을 바꾸기 전에 수정을 저장하거나 버리세요',
  needNewPath: '다른 새 경로를 입력하세요',
  renameFailed: (error: string) => `이름 변경 실패: ${error}`,
  currentPath: (path: string) => `현재: ${path}`,
  newPath: (root: string) => `새 경로(${root}/ 기준)`,
  renameTitle: '이름 변경 / 이동',
  fileHistoryLoading: '기록 불러오는 중…',
  fileHistoryFailed: (error: string) => `기록 불러오기 실패: ${error}`,
  backToEditor: '← 편집기로 돌아가기',
  noFileHistory: '이 파일에는 아직 커밋 기록이 없습니다',
  viewFull: '전체 보기',
  restoreDraft: '현재 초안으로 복원',
  restored: '이전 버전을 불러왔습니다. 저장하면 적용됩니다',
  copyFull: '전체 복사',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `${line}행 ${col}열 · ${lines}행 ${chars}자 · ${dirty ? '● 저장 안 됨' : '✓ 저장됨'}`,
  matches: (n: number) => `${n}개`,
};
