import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git 無法使用',
  noRepo: '還沒有建立儲存庫',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? '有未提交的改動' : '乾淨'} · ${checkpoints} 個存檔點`,
  historyLoading: '讀取提交歷史…',
  historyFailed: '版本歷史無法使用',
  mediumTitle: '介質狀態',
  mediumDesc: '工作區本身是一個 git 儲存庫(與專案儲存庫無關)。控制台的編輯會立即提交(署名 operator)。',
  rowStatus: '狀態',
  rowWorkspace: '工作區',
  dirty: '有未提交的改動',
  clean: '乾淨',
  rowCheckpoints: '存檔點',
  noCheckpoints: '(還沒有)',
  rowLastCommit: '最近提交',
  names: (list: string[]) => list.join('、'),
  logTitle: '提交紀錄',
  logDesc: '點一筆展開它引入的 diff。最多 100 筆;填路徑可只看某個檔案。',
  pathFilter: '只看某個路徑,例如 CONSTITUTION.md',
  filter: '篩選',
  clear: '清除',
  commitCount: (n: number) => `${n} 筆`,
  noCommitsInRange: '這個範圍裡還沒有提交',
  noRepoYet: '工作區還沒有建立儲存庫',
  loadingDiff: '載入 diff…',
  copyDiff: '複製 diff',
  diffFailed: (error: string) => `diff 失敗: ${error}`,
  fullTextHint: '想看某個版本的全文,到「工作區」開啟那份檔案再按「歷史」。',
  templateBlank: '空白',
  templateNote: '筆記',
  untitled: '新檔案',
  treeLoading: '讀取工作區目錄樹…',
  workspaceFailed: '工作區無法使用',
  workspaceTitle: '工作區',
  workspaceDesc: '儲存時以 operator 署名提交到工作區的 Git 儲存庫。',
  filterFiles: '篩選檔案名稱…',
  newFile: '新增',
  refresh: '重新整理',
  noFileOpen: '還沒有開啟檔案',
  save: '儲存',
  revert: '還原',
  find: '尋找',
  history: '歷史',
  rename: '改名',
  remove: '刪除',
  modeEdit: '編輯',
  modeSplit: '分欄',
  modePreview: '預覽',
  replaceWith: '取代為',
  noMatches: '沒有相符項目',
  previous: '上一個',
  next: '下一個',
  replace: '取代',
  replaceAll: '全部取代',
  close: '關閉',
  leaveGuard: '工作區裡有未儲存的改動,離開會捨棄它們。',
  noMatchingFiles: '沒有相符的檔案',
  emptyRoot: (root: string) => `${root}/ 是空的`,
  discardTitle: '捨棄未儲存的改動?',
  discardBody: (path: string) => `${path} 改過還沒儲存。開啟別的檔案會捨棄這些改動。`,
  opening: (path: string) => `正在開啟 ${path}…`,
  readFailed: '讀取失敗',
  readFailedDetail: (error: string) => `讀取失敗: ${error}`,
  saving: '儲存中…',
  saveFailed: (error: string) => `儲存失敗: ${error}`,
  revertTitle: '捨棄目前未儲存的修改?',
  reverted: '已還原到最近儲存的版本',
  removeTitle: (path: string) => `刪除 ${path}?`,
  removeBody: '未儲存的修改將遺失。已提交的版本可從「版本歷史」還原。',
  removed: '檔案已刪除',
  removeFailed: (error: string) => `刪除失敗: ${error}`,
  fileNamePlaceholder: '檔名.md',
  create: '建立',
  needFileName: '請填寫檔名',
  creating: '建立中…',
  createFailed: (error: string) => `建立失敗: ${error}`,
  fieldDir: '資料夾',
  fieldName: '檔名',
  fieldTemplate: '範本',
  fieldBody: '內文',
  newFileTitle: '新增檔案',
  saveBeforeRename: '請先儲存或捨棄修改,再改名',
  needNewPath: '請輸入不同的新路徑',
  renameFailed: (error: string) => `改名失敗: ${error}`,
  currentPath: (path: string) => `目前:${path}`,
  newPath: (root: string) => `新路徑(相對於 ${root}/)`,
  renameTitle: '改名 / 移動',
  fileHistoryLoading: '載入歷史…',
  fileHistoryFailed: (error: string) => `歷史載入失敗: ${error}`,
  backToEditor: '← 返回編輯器',
  noFileHistory: '這個檔案還沒有提交歷史',
  viewFull: '檢視全文',
  restoreDraft: '還原為目前草稿',
  restored: '已載入舊版本，儲存後生效',
  copyFull: '複製全文',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `第 ${line} 行 第 ${col} 欄 · ${lines} 行 ${chars} 字 · ${dirty ? '● 未儲存' : '✓ 已儲存'}`,
  matches: (n: number) => `${n} 處`,
};
