import { pick, type Language } from 'cortico/core/language.ts';
import { S as zhHant } from './strings.zh-Hant.ts';
import { S as ja } from './strings.ja.ts';
import { S as ko } from './strings.ko.ts';
import { S as fr } from './strings.fr.ts';
import { S as de } from './strings.de.ts';
import { S as es419 } from './strings.es-419.ts';
import { S as ptBR } from './strings.pt-BR.ts';
import { S as it } from './strings.it.ts';
import { S as ru } from './strings.ru.ts';

/** 「工作区」与「版本历史」两块面板的浏览器端文案。 */
const zh = {
  // shared.ts
  gitUnavailable: 'git 不可用',
  noRepo: '还没有建仓',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? '有未提交改动' : '干净'} · ${checkpoints} 个存档点`,
  // history.ts
  historyLoading: '读取提交历史…',
  historyFailed: '版本历史不可用',
  mediumTitle: '介质状态',
  mediumDesc: '工作区自己是一个 git 仓(与项目仓无关)。控制台的编辑立即提交(署名 operator)。',
  rowStatus: '状态',
  rowWorkspace: '工作区',
  dirty: '有未提交改动',
  clean: '干净',
  rowCheckpoints: '存档点',
  noCheckpoints: '(还没有)',
  rowLastCommit: '最近提交',
  names: (list: string[]) => list.join('、'),
  logTitle: '提交流水',
  logDesc: '点一条展开它引入的 diff。最多 100 条;填路径可只看某个档案。',
  pathFilter: '只看某个路径,如 CONSTITUTION.md',
  filter: '过滤',
  clear: '清除',
  commitCount: (n: number) => `${n} 条`,
  noCommitsInRange: '这个范围里还没有提交',
  noRepoYet: '工作区还没有建仓',
  loadingDiff: '加载 diff…',
  copyDiff: '复制 diff',
  diffFailed: (error: string) => `diff 失败: ${error}`,
  fullTextHint: '想看某个版本的全文,去「工作区」打开那份档案再按「历史」。',
  // workspace.ts
  templateBlank: '空白',
  templateNote: '笔记',
  untitled: '新档案',
  treeLoading: '读取工作区目录树…',
  workspaceFailed: '工作区不可用',
  workspaceTitle: '工作区',
  workspaceDesc: '保存时以 operator 署名提交到工作区的 Git 仓库。',
  filterFiles: '过滤档案名…',
  newFile: '新建',
  refresh: '刷新',
  noFileOpen: '还没有打开档案',
  save: '保存',
  revert: '还原',
  find: '查找',
  history: '历史',
  rename: '改名',
  remove: '删除',
  modeEdit: '编辑',
  modeSplit: '分栏',
  modePreview: '预览',
  replaceWith: '替换为',
  noMatches: '无匹配',
  previous: '上一个',
  next: '下一个',
  replace: '替换',
  replaceAll: '全部替换',
  close: '关闭',
  leaveGuard: '工作区里有未保存的改动,离开会丢弃它们。',
  noMatchingFiles: '没有匹配的档案',
  emptyRoot: (root: string) => `${root}/ 是空的`,
  discardTitle: '放弃未保存的改动?',
  discardBody: (path: string) => `${path} 改过还没保存。打开别的档案会丢掉这些改动。`,
  opening: (path: string) => `正在展开 ${path}…`,
  readFailed: '读取失败',
  readFailedDetail: (error: string) => `读取失败: ${error}`,
  saving: '保存中…',
  saveFailed: (error: string) => `保存失败: ${error}`,
  revertTitle: '放弃当前未保存的修改?',
  reverted: '已恢复到最近保存的版本',
  removeTitle: (path: string) => `删除 ${path}?`,
  removeBody: '未保存的修改将丢失。已提交的版本可从「版本历史」恢复。',
  removed: '档案已删除',
  removeFailed: (error: string) => `删除失败: ${error}`,
  fileNamePlaceholder: '文件名.md',
  create: '创建',
  needFileName: '请填写文件名',
  creating: '创建中…',
  createFailed: (error: string) => `创建失败: ${error}`,
  fieldDir: '目录',
  fieldName: '文件名',
  fieldTemplate: '模板',
  fieldBody: '正文',
  newFileTitle: '新建档案',
  saveBeforeRename: '请先保存或放弃修改,再重命名',
  needNewPath: '请输入不同的新路径',
  renameFailed: (error: string) => `改名失败: ${error}`,
  currentPath: (path: string) => `当前:${path}`,
  newPath: (root: string) => `新路径(相对 ${root}/)`,
  renameTitle: '改名 / 移动',
  fileHistoryLoading: '加载历史…',
  fileHistoryFailed: (error: string) => `历史加载失败: ${error}`,
  backToEditor: '← 返回编辑器',
  noFileHistory: '这个档案还没有提交历史',
  viewFull: '查看全文',
  restoreDraft: '恢复为当前草稿',
  restored: '已载入旧版本，保存后生效',
  copyFull: '复制全文',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `第 ${line} 行 第 ${col} 列 · ${lines} 行 ${chars} 字 · ${dirty ? '● 未保存' : '✓ 已保存'}`,
  matches: (n: number) => `${n} 处`,
};
export const en: typeof zh = {
  gitUnavailable: 'git unavailable',
  noRepo: 'no repository yet',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'uncommitted changes' : 'clean'} · ${checkpoints} checkpoint${checkpoints === 1 ? '' : 's'}`,
  historyLoading: 'Reading commit history…',
  historyFailed: 'Version history unavailable',
  mediumTitle: 'Medium status',
  mediumDesc: 'The workspace is its own git repository, separate from the project repository. Console edits are committed immediately, authored as operator.',
  rowStatus: 'Status',
  rowWorkspace: 'Workspace',
  dirty: 'Uncommitted changes',
  clean: 'Clean',
  rowCheckpoints: 'Checkpoints',
  noCheckpoints: '(none yet)',
  rowLastCommit: 'Last commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Commit log',
  logDesc: 'Click a commit to expand the diff it introduced. Up to 100 commits; enter a path to see one file only.',
  pathFilter: 'Only this path, e.g. CONSTITUTION.md',
  filter: 'Filter',
  clear: 'Clear',
  commitCount: (n: number) => `${n} commit${n === 1 ? '' : 's'}`,
  noCommitsInRange: 'No commits in this range yet',
  noRepoYet: 'The workspace has no repository yet',
  loadingDiff: 'Loading diff…',
  copyDiff: 'Copy diff',
  diffFailed: (error: string) => `Diff failed: ${error}`,
  fullTextHint: 'To see a version in full, open the file in “Workspace” and press “History”.',
  templateBlank: 'Blank',
  templateNote: 'Note',
  untitled: 'New file',
  treeLoading: 'Reading the workspace tree…',
  workspaceFailed: 'Workspace unavailable',
  workspaceTitle: 'Workspace',
  workspaceDesc: 'Saving commits to the workspace Git repository, authored as operator.',
  filterFiles: 'Filter file names…',
  newFile: 'New',
  refresh: 'Refresh',
  noFileOpen: 'No file open',
  save: 'Save',
  revert: 'Revert',
  find: 'Find',
  history: 'History',
  rename: 'Rename',
  remove: 'Delete',
  modeEdit: 'Edit',
  modeSplit: 'Split',
  modePreview: 'Preview',
  replaceWith: 'Replace with',
  noMatches: 'No matches',
  previous: 'Previous',
  next: 'Next',
  replace: 'Replace',
  replaceAll: 'Replace all',
  close: 'Close',
  leaveGuard: 'The workspace has unsaved changes; leaving discards them.',
  noMatchingFiles: 'No matching files',
  emptyRoot: (root: string) => `${root}/ is empty`,
  discardTitle: 'Discard unsaved changes?',
  discardBody: (path: string) => `${path} has unsaved changes. Opening another file discards them.`,
  opening: (path: string) => `Opening ${path}…`,
  readFailed: 'Read failed',
  readFailedDetail: (error: string) => `Read failed: ${error}`,
  saving: 'Saving…',
  saveFailed: (error: string) => `Save failed: ${error}`,
  revertTitle: 'Discard the current unsaved changes?',
  reverted: 'Restored the last saved version',
  removeTitle: (path: string) => `Delete ${path}?`,
  removeBody: 'Unsaved changes will be lost. Committed versions can be restored from “Version history”.',
  removed: 'File deleted',
  removeFailed: (error: string) => `Delete failed: ${error}`,
  fileNamePlaceholder: 'name.md',
  create: 'Create',
  needFileName: 'Enter a file name',
  creating: 'Creating…',
  createFailed: (error: string) => `Create failed: ${error}`,
  fieldDir: 'Folder',
  fieldName: 'File name',
  fieldTemplate: 'Template',
  fieldBody: 'Content',
  newFileTitle: 'New file',
  saveBeforeRename: 'Save or discard your changes before renaming',
  needNewPath: 'Enter a different new path',
  renameFailed: (error: string) => `Rename failed: ${error}`,
  currentPath: (path: string) => `Current: ${path}`,
  newPath: (root: string) => `New path (relative to ${root}/)`,
  renameTitle: 'Rename / move',
  fileHistoryLoading: 'Loading history…',
  fileHistoryFailed: (error: string) => `Loading history failed: ${error}`,
  backToEditor: '← Back to editor',
  noFileHistory: 'This file has no commit history yet',
  viewFull: 'View full text',
  restoreDraft: 'Restore as current draft',
  restored: 'Loaded the old version; it takes effect when saved',
  copyFull: 'Copy full text',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Ln ${line}, Col ${col} · ${lines} line${lines === 1 ? '' : 's'}, ${chars} char${chars === 1 ? '' : 's'} · ${dirty ? '● Unsaved' : '✓ Saved'}`,
  matches: (n: number) => `${n} match${n === 1 ? '' : 'es'}`,
};
export const workspaceText = (language: Language) => pick(language, {
  zh, en, 'zh-Hant': zhHant, ja, ko, fr, de, 'es-419': es419, 'pt-BR': ptBR, it, ru,
});
