import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  gitUnavailable: 'git indisponível',
  noRepo: 'ainda sem repositório',
  gitLine: (head: string, dirty: boolean, checkpoints: number) =>
    `git ${head} · ${dirty ? 'alterações sem commit' : 'limpo'} · ${checkpoints} ${checkpoints === 1 ? 'ponto de controle' : 'pontos de controle'}`,
  historyLoading: 'Lendo o histórico de commits…',
  historyFailed: 'Histórico de versões indisponível',
  mediumTitle: 'Estado do meio',
  mediumDesc: 'O espaço de trabalho é um repositório git próprio, separado do repositório do projeto. As edições feitas no console recebem commit na hora, com operator como autor.',
  rowStatus: 'Estado',
  rowWorkspace: 'Espaço de trabalho',
  dirty: 'Alterações sem commit',
  clean: 'Limpo',
  rowCheckpoints: 'Pontos de controle',
  noCheckpoints: '(nenhum ainda)',
  rowLastCommit: 'Último commit',
  names: (list: string[]) => list.join(', '),
  logTitle: 'Log de commits',
  logDesc: 'Clique em um commit para expandir o diff que ele introduziu. Até 100 commits; informe um caminho para ver só um arquivo.',
  pathFilter: 'Só este caminho, ex.: CONSTITUTION.md',
  filter: 'Filtrar',
  clear: 'Limpar',
  commitCount: (n: number) => `${n} ${n === 1 ? 'commit' : 'commits'}`,
  noCommitsInRange: 'Ainda não há commits neste intervalo',
  noRepoYet: 'O espaço de trabalho ainda não tem repositório',
  loadingDiff: 'Carregando diff…',
  copyDiff: 'Copiar diff',
  diffFailed: (error: string) => `Falha no diff: ${error}`,
  fullTextHint: 'Para ver uma versão completa, abra o arquivo em “Espaço de trabalho” e clique em “Histórico”.',
  templateBlank: 'Em branco',
  templateNote: 'Nota',
  untitled: 'Novo arquivo',
  treeLoading: 'Lendo a árvore do espaço de trabalho…',
  workspaceFailed: 'Espaço de trabalho indisponível',
  workspaceTitle: 'Espaço de trabalho',
  workspaceDesc: 'Salvar faz um commit no repositório Git do espaço de trabalho, com operator como autor.',
  filterFiles: 'Filtrar nomes de arquivo…',
  newFile: 'Novo',
  refresh: 'Atualizar',
  noFileOpen: 'Nenhum arquivo aberto',
  save: 'Salvar',
  revert: 'Reverter',
  find: 'Localizar',
  history: 'Histórico',
  rename: 'Renomear',
  remove: 'Excluir',
  modeEdit: 'Editar',
  modeSplit: 'Dividido',
  modePreview: 'Prévia',
  replaceWith: 'Substituir por',
  noMatches: 'Nenhuma correspondência',
  previous: 'Anterior',
  next: 'Próximo',
  replace: 'Substituir',
  replaceAll: 'Substituir tudo',
  close: 'Fechar',
  leaveGuard: 'O espaço de trabalho tem alterações não salvas; se você sair, elas serão descartadas.',
  noMatchingFiles: 'Nenhum arquivo correspondente',
  emptyRoot: (root: string) => `${root}/ está vazio`,
  discardTitle: 'Descartar alterações não salvas?',
  discardBody: (path: string) => `${path} tem alterações não salvas. Abrir outro arquivo as descarta.`,
  opening: (path: string) => `Abrindo ${path}…`,
  readFailed: 'Falha na leitura',
  readFailedDetail: (error: string) => `Falha na leitura: ${error}`,
  saving: 'Salvando…',
  saveFailed: (error: string) => `Falha ao salvar: ${error}`,
  revertTitle: 'Descartar as alterações atuais não salvas?',
  reverted: 'A última versão salva foi restaurada',
  removeTitle: (path: string) => `Excluir ${path}?`,
  removeBody: 'As alterações não salvas serão perdidas. Versões com commit podem ser restauradas em “Histórico de versões”.',
  removed: 'Arquivo excluído',
  removeFailed: (error: string) => `Falha ao excluir: ${error}`,
  fileNamePlaceholder: 'nome.md',
  create: 'Criar',
  needFileName: 'Informe um nome de arquivo',
  creating: 'Criando…',
  createFailed: (error: string) => `Falha ao criar: ${error}`,
  fieldDir: 'Pasta',
  fieldName: 'Nome do arquivo',
  fieldTemplate: 'Modelo',
  fieldBody: 'Conteúdo',
  newFileTitle: 'Novo arquivo',
  saveBeforeRename: 'Salve ou descarte suas alterações antes de renomear',
  needNewPath: 'Informe um novo caminho diferente',
  renameFailed: (error: string) => `Falha ao renomear: ${error}`,
  currentPath: (path: string) => `Atual: ${path}`,
  newPath: (root: string) => `Novo caminho (relativo a ${root}/)`,
  renameTitle: 'Renomear / mover',
  fileHistoryLoading: 'Carregando histórico…',
  fileHistoryFailed: (error: string) => `Falha ao carregar o histórico: ${error}`,
  backToEditor: '← Voltar ao editor',
  noFileHistory: 'Este arquivo ainda não tem histórico de commits',
  viewFull: 'Ver texto completo',
  restoreDraft: 'Restaurar como rascunho atual',
  restored: 'Versão antiga carregada; ela passa a valer ao salvar',
  copyFull: 'Copiar texto completo',
  cursor: (line: number, col: number, lines: number, chars: number, dirty: boolean) =>
    `Lin. ${line}, col. ${col} · ${lines} ${lines === 1 ? 'linha' : 'linhas'}, ${chars} ${chars === 1 ? 'caractere' : 'caracteres'} · ${dirty ? '● Não salvo' : '✓ Salvo'}`,
  matches: (n: number) => `${n} ${n === 1 ? 'ocorrência' : 'ocorrências'}`,
};
