import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: 'Anfragen werden beim Start gebunden; Änderungen gelten ab der nächsten Anfrage.',
  baseUrl: 'Anbieter-URL',
  secret: 'Umgebungsvariable für das Secret',
  secretDescription: 'Gib den Variablennamen ein; die Deployment-Umgebung liefert das Secret.',
  multimodal: 'Bildeingabe aktivieren',
  activeInstanceLamp: 'Aktive Anbieter-Instanz',
  availableLamp: 'Nutzbarer Endpunkt',
  availableLampNone: 'Kein nutzbarer Endpunkt',
  availableLampReady: (name: string) => `${name} ist nutzbar`,
  instancesBadge: 'Instanzen',
  settingsPanel: 'Instanzen und Modelle',
  settingsPanelDescription: 'Speichere das Endpunktmodell, die Preise und den aktiven Endpunkt dieses Deployments.',
  endpointBlock: 'Verbindung',
  endpointBlockDescription: 'Anbieter-URL und API Key.',
  modelBlock: 'Modell und Generierung',
  modelBlockDescription: 'Modellname und Generierungsparameter; die Modellliste kommt vom Endpunkt.',
  pricingBlock: 'Preise',
  protocolBlock: 'Erweitertes Protokoll',
  protocolBlockDescription: 'Nur für eigene API-Gateways oder kompatible Dienste anpassen.',
  saved: 'Parameter gespeichert; sie gelten ab der nächsten Anfrage.',
  unknownGroup: 'Unbekannte Anbieter-Parametergruppe',
  groupOutOfScope: 'Eine Anbieter-Parametergruppe kann nur ihre eigene Instanz ändern',
  kindChange: 'Der Modultyp einer bestehenden Instanz kann nicht geändert werden',
  unknownInstance: 'Unbekannte Anbieter-Instanz',
  foreignInstance: 'Die Anbieter-Instanz gehört nicht zu diesem Modul',
  unknownPanel: 'Unbekanntes Anbieter-Panel',
  bodyRequired: 'Ein Konfigurationsobjekt der Instanz ist erforderlich',
  nameRequired: 'Ein Instanzname ist erforderlich',
  nameFormat: 'Instanznamen dürfen nur Buchstaben, Ziffern, Unterstriche und Bindestriche enthalten',
  nameTaken: 'Der Instanzname existiert bereits',
  specRequired: 'Ein Modellspezifikationsobjekt ist erforderlich',
  unknownMethod: 'Unbekannte Anbieter-Aktion',
  optionsObject: 'Native Optionen müssen ein Objekt sein',
  deleteActive: 'Die aktive Anbieter-Instanz kann nicht gelöscht werden; aktiviere zuerst eine andere Instanz',
  secretNameRequired: 'Lege den Namen der Secret-Umgebungsvariable fest, bevor du einen Schlüsselwert schreibst',
  secretValueInvalid: 'Der Schlüsselwert darf nicht leer sein und keine Leerzeichen enthalten',
  modelsUnsupported: 'Dieses Modul listet keine Modelle auf',
  probeNoResponses: 'Die Anfrage lieferte 404; prüfe Anbieter-URL, Endpunktpfad und unterstützte APIs.',
  probeAuth: 'Authentifizierung fehlgeschlagen: Prüfe den Namen der Secret-Variable und den Schlüsselwert',
  probeUnreachable: 'Verbindung oder Antwortstream fehlgeschlagen; prüfe Netzwerk, Anbieter-URL und Proxy.',
  moduleMissing: 'Das Anbietermodul ist nicht verfügbar.',
  modelMissing: 'Ein Modell ist erforderlich.',
  apiKeyMissing: 'Ein API Key ist erforderlich.',
};
