import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: "Le richieste si vincolano all'avvio; le modifiche valgono dalla richiesta successiva.",
  baseUrl: 'URL del provider',
  secret: 'Variabile di ambiente del secret',
  secretDescription: "Inserisci il nome della variabile; l'ambiente di deployment fornisce il secret.",
  multimodal: 'Abilita input immagini',
  activeInstanceLamp: 'Istanza del provider attiva',
  availableLamp: 'Endpoint utilizzabile',
  availableLampNone: 'Nessun endpoint utilizzabile',
  availableLampReady: (name: string) => `${name} è utilizzabile`,
  instancesBadge: 'Istanze',
  settingsPanel: 'Istanze e modelli',
  settingsPanelDescription: "Salva il modello dell'endpoint, i prezzi e l'endpoint attivo di questo deployment.",
  endpointBlock: 'Connessione',
  endpointBlockDescription: 'URL del provider e API Key.',
  modelBlock: 'Modello e generazione',
  modelBlockDescription: "Nome del modello e parametri di generazione; l'elenco dei modelli arriva dall'endpoint.",
  pricingBlock: 'Prezzi',
  protocolBlock: 'Protocollo avanzato',
  protocolBlockDescription: 'Modifica solo per gateway API personalizzati o servizi compatibili.',
  saved: 'Parametri salvati; valgono dalla richiesta successiva.',
  unknownGroup: 'Gruppo di parametri del provider sconosciuto',
  groupOutOfScope: 'Un gruppo di parametri del provider può modificare solo la propria istanza',
  kindChange: "Il tipo di modulo di un'istanza esistente non può essere cambiato",
  unknownInstance: 'Istanza del provider sconosciuta',
  foreignInstance: "L'istanza del provider non appartiene a questo modulo",
  unknownPanel: 'Pannello del provider sconosciuto',
  bodyRequired: "Serve un oggetto di configurazione dell'istanza",
  nameRequired: "Serve un nome per l'istanza",
  nameFormat: 'I nomi delle istanze possono contenere solo lettere, cifre, trattini bassi e trattini',
  nameTaken: "Il nome dell'istanza esiste già",
  specRequired: 'Serve un oggetto di specifica del modello',
  unknownMethod: 'Azione del provider sconosciuta',
  optionsObject: 'Le opzioni native devono essere un oggetto',
  deleteActive: "L'istanza del provider attiva non può essere eliminata; attiva prima un'altra istanza",
  secretNameRequired: 'Imposta il nome della variabile di ambiente del secret prima di scrivere un valore della chiave',
  secretValueInvalid: 'Il valore della chiave non può essere vuoto né contenere spazi',
  modelsUnsupported: 'Questo modulo non elenca modelli',
  probeNoResponses: "La richiesta ha restituito 404; controlla l'URL del provider, il percorso dell'endpoint e le API supportate.",
  probeAuth: 'Autenticazione non riuscita: controlla il nome della variabile del secret e il valore della chiave',
  probeUnreachable: "La connessione o lo stream di risposta non è riuscito; controlla la rete, l'URL del provider e il proxy.",
  moduleMissing: 'Il modulo del provider non è disponibile.',
  modelMissing: 'Serve un modello.',
  apiKeyMissing: 'Serve una API Key.',
};
