import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: 'リクエストは開始時に割り当てが固定されます。変更は次のリクエストから反映されます。',
  baseUrl: 'プロバイダー URL',
  secret: 'シークレットの環境変数',
  secretDescription: '変数名を入力してください。シークレットの値はデプロイ環境から提供されます。',
  multimodal: '画像入力を有効化',
  activeInstanceLamp: '現在のプロバイダーインスタンス',
  availableLamp: '利用可能なエンドポイント',
  availableLampNone: '利用可能なエンドポイントがありません',
  availableLampReady: (name: string) => `${name} を利用できます`,
  instancesBadge: 'インスタンス',
  settingsPanel: 'インスタンスとモデル',
  settingsPanelDescription: 'エンドポイントのモデル、料金、このデプロイで使うエンドポイントを保存します。',
  endpointBlock: '接続',
  endpointBlockDescription: 'モデルサービスの URL と API Key。',
  modelBlock: 'モデルと生成',
  modelBlockDescription: 'モデル名と生成パラメーター。モデル一覧はエンドポイントから取得します。',
  pricingBlock: '料金',
  protocolBlock: '高度なプロトコル',
  protocolBlockDescription: 'カスタム API ゲートウェイや互換サービスを使う場合にのみ調整してください。',
  saved: 'パラメーターを保存しました。次のリクエストから反映されます。',
  unknownGroup: '不明なプロバイダーのパラメーターグループです',
  groupOutOfScope: 'プロバイダーのパラメーターグループは自身のインスタンスしか変更できません',
  kindChange: '既存のインスタンスのモジュールの種類は変更できません',
  unknownInstance: '不明なプロバイダーインスタンスです',
  foreignInstance: 'このプロバイダーインスタンスはこのモジュールに属していません',
  unknownPanel: '不明なプロバイダーパネルです',
  bodyRequired: 'インスタンスの設定オブジェクトが必要です',
  nameRequired: 'インスタンス名が必要です',
  nameFormat: 'インスタンス名に使えるのは英字、数字、アンダースコア、ハイフンだけです',
  nameTaken: 'このインスタンス名は既に存在します',
  specRequired: 'モデル設定のオブジェクトが必要です',
  unknownMethod: '不明なプロバイダー操作です',
  optionsObject: 'ネイティブオプションはオブジェクトである必要があります',
  deleteActive: '現在のプロバイダーインスタンスは削除できません。先に別のインスタンスを有効にしてください',
  secretNameRequired: 'キーの値を書き込む前に、シークレットの環境変数名を設定してください',
  secretValueInvalid: 'キーの値は空にできず、空白も含められません',
  modelsUnsupported: 'このモジュールはモデル一覧を提供していません',
  probeNoResponses: 'リクエストが 404 を返しました。プロバイダー URL、エンドポイントのパス、サービスが対応している API を確認してください。',
  probeAuth: '認証に失敗しました：シークレットの変数名とキーの値を確認してください',
  probeUnreachable: '接続または応答ストリームに失敗しました。ネットワーク、プロバイダー URL、プロキシを確認してください。',
  moduleMissing: 'プロバイダーモジュールを利用できません。',
  modelMissing: 'モデルを選択してください。',
  apiKeyMissing: 'API Key を設定してください。',
};
