import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: 'As requisições são vinculadas no início; as alterações valem a partir da próxima requisição.',
  baseUrl: 'URL do provedor',
  secret: 'Variável de ambiente do segredo',
  secretDescription: 'Digite o nome da variável; o ambiente de implantação fornece o segredo.',
  multimodal: 'Ativar entrada de imagens',
  activeInstanceLamp: 'Instância de provedor ativa',
  availableLamp: 'Endpoint utilizável',
  availableLampNone: 'Nenhum endpoint utilizável',
  availableLampReady: (name: string) => `${name} pode ser usado`,
  instancesBadge: 'Instâncias',
  settingsPanel: 'Instâncias e modelos',
  settingsPanelDescription: 'Salva o modelo do endpoint, os preços e o endpoint ativo desta implantação.',
  endpointBlock: 'Conexão',
  endpointBlockDescription: 'URL do provedor e API Key.',
  modelBlock: 'Modelo e geração',
  modelBlockDescription: 'Nome do modelo e parâmetros de geração; a lista de modelos vem do endpoint.',
  pricingBlock: 'Preços',
  protocolBlock: 'Protocolo avançado',
  protocolBlockDescription: 'Ajuste apenas para gateways de API personalizados ou serviços compatíveis.',
  saved: 'Parâmetros salvos; valem a partir da próxima requisição.',
  unknownGroup: 'Grupo de parâmetros de provedor desconhecido',
  groupOutOfScope: 'Um grupo de parâmetros de provedor só pode modificar a própria instância',
  kindChange: 'O tipo de módulo de uma instância existente não pode ser alterado',
  unknownInstance: 'Instância de provedor desconhecida',
  foreignInstance: 'A instância de provedor não pertence a este módulo',
  unknownPanel: 'Painel de provedor desconhecido',
  bodyRequired: 'É necessário um objeto de configuração da instância',
  nameRequired: 'É necessário um nome de instância',
  nameFormat: 'Nomes de instância só podem conter letras, dígitos, sublinhados e hifens',
  nameTaken: 'O nome de instância já existe',
  specRequired: 'É necessário um objeto de especificação do modelo',
  unknownMethod: 'Ação de provedor desconhecida',
  optionsObject: 'As opções nativas devem ser um objeto',
  deleteActive: 'A instância de provedor ativa não pode ser excluída; ative outra instância primeiro',
  secretNameRequired: 'Defina o nome da variável de ambiente do segredo antes de gravar um valor de chave',
  secretValueInvalid: 'O valor da chave não pode ficar vazio nem conter espaços em branco',
  modelsUnsupported: 'Este módulo não lista modelos',
  probeNoResponses: 'A requisição retornou 404; verifique a URL do provedor, o caminho do endpoint e as APIs suportadas.',
  probeAuth: 'Falha na autenticação: verifique o nome da variável do segredo e o valor da chave',
  probeUnreachable: 'A conexão ou o fluxo de resposta falhou; verifique a rede, a URL do provedor e o proxy.',
  moduleMissing: 'O módulo do provedor está indisponível.',
  modelMissing: 'É necessário escolher um modelo.',
  apiKeyMissing: 'É necessário configurar a API Key.',
};
