import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: '요청은 시작할 때 연결이 고정되며, 변경 사항은 다음 요청부터 적용됩니다.',
  baseUrl: '공급자 URL',
  secret: '비밀 값 환경 변수',
  secretDescription: '변수 이름을 입력하세요. 비밀 값은 배포 환경에서 제공합니다.',
  multimodal: '이미지 입력 사용',
  activeInstanceLamp: '현재 공급자 인스턴스',
  availableLamp: '사용 가능한 엔드포인트',
  availableLampNone: '사용 가능한 엔드포인트 없음',
  availableLampReady: (name: string) => `${name} 사용 가능`,
  instancesBadge: '인스턴스',
  settingsPanel: '인스턴스와 모델',
  settingsPanelDescription: '엔드포인트 모델, 가격, 이 배포가 쓰는 엔드포인트를 저장합니다.',
  endpointBlock: '연결',
  endpointBlockDescription: '모델 서비스의 URL과 API Key.',
  modelBlock: '모델 및 생성',
  modelBlockDescription: '모델 이름과 생성 매개변수. 모델 목록은 엔드포인트에서 가져옵니다.',
  pricingBlock: '가격',
  protocolBlock: '고급 프로토콜',
  protocolBlockDescription: '사용자 지정 API 게이트웨이나 호환 서비스를 쓸 때만 조정하세요.',
  saved: '매개변수를 저장했습니다. 다음 요청부터 적용됩니다.',
  unknownGroup: '알 수 없는 공급자 매개변수 그룹',
  groupOutOfScope: '공급자 매개변수 그룹은 자신이 속한 인스턴스만 수정할 수 있습니다',
  kindChange: '기존 인스턴스의 모듈 유형은 바꿀 수 없습니다',
  unknownInstance: '알 수 없는 공급자 인스턴스',
  foreignInstance: '이 공급자 인스턴스는 이 모듈에 속하지 않습니다',
  unknownPanel: '알 수 없는 공급자 패널',
  bodyRequired: '인스턴스 설정 객체가 필요합니다',
  nameRequired: '인스턴스 이름이 필요합니다',
  nameFormat: '인스턴스 이름에는 영문자, 숫자, 밑줄, 하이픈만 쓸 수 있습니다',
  nameTaken: '이미 있는 인스턴스 이름입니다',
  specRequired: '모델 사양 객체가 필요합니다',
  unknownMethod: '알 수 없는 공급자 작업',
  optionsObject: '네이티브 옵션은 객체여야 합니다',
  deleteActive: '현재 공급자 인스턴스는 삭제할 수 없습니다. 먼저 다른 인스턴스를 활성화하세요',
  secretNameRequired: '키 값을 기록하기 전에 비밀 값 환경 변수 이름을 설정하세요',
  secretValueInvalid: '키 값은 비어 있거나 공백을 포함할 수 없습니다',
  modelsUnsupported: '이 모듈은 모델 목록을 제공하지 않습니다',
  probeNoResponses: '요청이 404를 반환했습니다. 공급자 URL, 엔드포인트 경로, 서비스가 지원하는 API를 확인하세요.',
  probeAuth: '인증 실패: 비밀 값 변수 이름과 키 값을 확인하세요',
  probeUnreachable: '연결 또는 응답 스트림에 실패했습니다. 네트워크, 공급자 URL, 프록시를 확인하세요.',
  moduleMissing: '공급자 모듈을 사용할 수 없습니다.',
  modelMissing: '모델을 선택하세요.',
  apiKeyMissing: 'API Key를 설정하세요.',
};
