import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: '請求綁定在開始時固定；修改後從下一次請求生效。',
  baseUrl: '供應位址',
  secret: '金鑰環境變數',
  secretDescription: '填寫變數名稱；金鑰內容由部署環境提供。',
  multimodal: '啟用影像輸入',
  activeInstanceLamp: '目前供應實例',
  availableLamp: '可用端點',
  availableLampNone: '沒有可用端點',
  availableLampReady: (name: string) => `${name} 可用`,
  instancesBadge: '實例',
  settingsPanel: '實例與模型',
  settingsPanelDescription: '儲存端點模型、價目及目前部署使用的端點。',
  endpointBlock: '連線',
  endpointBlockDescription: '模型服務的位址與 API Key。',
  modelBlock: '模型與生成',
  modelBlockDescription: '模型名稱與生成參數;模型清單從端點擷取。',
  pricingBlock: '成本與計價',
  protocolBlock: '進階協定',
  protocolBlockDescription: '僅在使用自訂 API 閘道或相容服務時調整。',
  saved: '參數已儲存；下一次請求生效。',
  unknownGroup: '未知 Provider 參數群組',
  groupOutOfScope: 'Provider 參數群組只能修改所屬實例',
  kindChange: '不能改變既有實例的模組類型',
  unknownInstance: '未知供應實例',
  foreignInstance: '供應實例不屬於此模組',
  unknownPanel: '未知 Provider 面板',
  bodyRequired: '需要實例設定物件',
  nameRequired: '需要實例名稱',
  nameFormat: '實例名稱只能包含字母、數字、底線與連字號',
  nameTaken: '實例名稱已存在',
  specRequired: '需要模型檔物件',
  unknownMethod: '未知 Provider 操作',
  optionsObject: '原生參數必須是物件',
  deleteActive: '目前供應實例不能刪除;先啟用別的實例',
  secretNameRequired: '先填寫金鑰環境變數名稱,再寫入金鑰值',
  secretValueInvalid: '金鑰值不能為空或含空白',
  modelsUnsupported: '此模組不提供模型清單',
  probeNoResponses: '請求回傳 404；請檢查供應位址、端點路徑及服務支援的 API。',
  probeAuth: '驗證失敗:檢查金鑰變數名稱與金鑰值',
  probeUnreachable: '連線或回應串流失敗；請檢查網路、供應位址與代理伺服器。',
  moduleMissing: '供應商模組無法使用。',
  modelMissing: '請選擇模型。',
  apiKeyMissing: '請設定 API Key。',
};
