import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: 'Las solicitudes se vinculan al iniciar; los cambios se aplican desde la siguiente solicitud.',
  baseUrl: 'URL del proveedor',
  secret: 'Variable de entorno del secreto',
  secretDescription: 'Ingresa el nombre de la variable; el entorno de despliegue proporciona el secreto.',
  multimodal: 'Activar entrada de imágenes',
  activeInstanceLamp: 'Instancia de proveedor activa',
  availableLamp: 'Endpoint utilizable',
  availableLampNone: 'Ningún endpoint utilizable',
  availableLampReady: (name: string) => `${name} se puede usar`,
  instancesBadge: 'Instancias',
  settingsPanel: 'Instancias y modelos',
  settingsPanelDescription: 'Guarda el modelo del endpoint, los precios y el endpoint activo de este despliegue.',
  endpointBlock: 'Conexión',
  endpointBlockDescription: 'URL del proveedor y API Key.',
  modelBlock: 'Modelo y generación',
  modelBlockDescription: 'Nombre del modelo y parámetros de generación; la lista de modelos proviene del endpoint.',
  pricingBlock: 'Precios',
  protocolBlock: 'Protocolo avanzado',
  protocolBlockDescription: 'Ajústalo solo para gateways de API personalizados o servicios compatibles.',
  saved: 'Parámetros guardados; se aplican desde la siguiente solicitud.',
  unknownGroup: 'Grupo de parámetros de proveedor desconocido',
  groupOutOfScope: 'Un grupo de parámetros de proveedor solo puede modificar su propia instancia',
  kindChange: 'No se puede cambiar el tipo de módulo de una instancia existente',
  unknownInstance: 'Instancia de proveedor desconocida',
  foreignInstance: 'La instancia de proveedor no pertenece a este módulo',
  unknownPanel: 'Panel de proveedor desconocido',
  bodyRequired: 'Se requiere un objeto de configuración de instancia',
  nameRequired: 'Se requiere un nombre de instancia',
  nameFormat: 'Los nombres de instancia solo pueden contener letras, dígitos, guiones bajos y guiones',
  nameTaken: 'El nombre de instancia ya existe',
  specRequired: 'Se requiere un objeto de especificación del modelo',
  unknownMethod: 'Acción de proveedor desconocida',
  optionsObject: 'Las opciones nativas deben ser un objeto',
  deleteActive: 'No se puede eliminar la instancia de proveedor activa; primero activa otra instancia',
  secretNameRequired: 'Define el nombre de la variable de entorno del secreto antes de escribir un valor de clave',
  secretValueInvalid: 'El valor de la clave no puede estar vacío ni contener espacios en blanco',
  modelsUnsupported: 'Este módulo no lista modelos',
  probeNoResponses: 'La solicitud devolvió 404; revisa la URL del proveedor, la ruta del endpoint y las API compatibles.',
  probeAuth: 'Falló la autenticación: revisa el nombre de la variable del secreto y el valor de la clave',
  probeUnreachable: 'Falló la conexión o el flujo de respuesta; revisa la red, la URL del proveedor y el proxy.',
  moduleMissing: 'El módulo del proveedor no está disponible.',
  modelMissing: 'Se requiere un modelo.',
  apiKeyMissing: 'Se requiere la API Key.',
};
