import type { en } from './strings.ts';

export const text: Partial<typeof en> = {
  connectionDescription: "Les requêtes sont liées à leur départ ; les modifications s'appliquent dès la requête suivante.",
  baseUrl: 'URL du fournisseur',
  secret: "Variable d'environnement du secret",
  secretDescription: "Saisissez le nom de la variable ; l'environnement de déploiement fournit le secret.",
  multimodal: "Activer l'entrée d'images",
  activeInstanceLamp: 'Instance de fournisseur active',
  availableLamp: 'Endpoint utilisable',
  availableLampNone: 'Aucun endpoint utilisable',
  availableLampReady: (name: string) => `${name} est utilisable`,
  instancesBadge: 'Instances',
  settingsPanel: 'Instances et modèles',
  settingsPanelDescription: "Enregistrer le modèle de l'endpoint, la tarification et l'endpoint actif de ce déploiement.",
  endpointBlock: 'Connexion',
  endpointBlockDescription: 'URL du fournisseur et API Key.',
  modelBlock: 'Modèle et génération',
  modelBlockDescription: "Nom du modèle et paramètres de génération ; la liste des modèles provient de l'endpoint.",
  pricingBlock: 'Tarification',
  protocolBlock: 'Protocole avancé',
  protocolBlockDescription: "À ajuster uniquement pour des passerelles d'API personnalisées ou des services compatibles.",
  saved: "Paramètres enregistrés ; ils s'appliquent dès la requête suivante.",
  unknownGroup: 'Groupe de paramètres de fournisseur inconnu',
  groupOutOfScope: 'Un groupe de paramètres de fournisseur ne peut modifier que sa propre instance',
  kindChange: "Le type de module d'une instance existante ne peut pas être modifié",
  unknownInstance: 'Instance de fournisseur inconnue',
  foreignInstance: "L'instance de fournisseur n'appartient pas à ce module",
  unknownPanel: 'Panneau de fournisseur inconnu',
  bodyRequired: "Un objet de configuration d'instance est requis",
  nameRequired: "Un nom d'instance est requis",
  nameFormat: "Les noms d'instance ne peuvent contenir que des lettres, des chiffres, des traits de soulignement et des tirets",
  nameTaken: "Ce nom d'instance existe déjà",
  specRequired: 'Un objet de spécification de modèle est requis',
  unknownMethod: 'Action de fournisseur inconnue',
  optionsObject: 'Les options natives doivent être un objet',
  deleteActive: "L'instance de fournisseur active ne peut pas être supprimée ; activez d'abord une autre instance",
  secretNameRequired: "Définissez le nom de la variable d'environnement du secret avant d'écrire une valeur de clé",
  secretValueInvalid: "La valeur de clé ne peut pas être vide ni contenir d'espaces",
  modelsUnsupported: 'Ce module ne liste pas de modèles',
  probeNoResponses: "La requête a renvoyé 404 ; vérifiez l'URL du fournisseur, le chemin de l'endpoint et les API prises en charge.",
  probeAuth: "Échec de l'authentification : vérifiez le nom de la variable du secret et la valeur de clé",
  probeUnreachable: "La connexion ou le flux de réponse a échoué ; vérifiez le réseau, l'URL du fournisseur et le proxy.",
  moduleMissing: 'Le module du fournisseur est indisponible.',
  modelMissing: 'Un modèle est requis.',
  apiKeyMissing: 'Une API Key est requise.',
};
