import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '使用量とコスト',
  navGroup: 'Core',
  pageTitle: '使用量とコスト',
  bucketAuto: '自動',
  bucketMinute: '分',
  bucketHour: '時間',
  bucketDay: '日',
  bucketWeek: '週',
  bucketMonth: '月',
  presetToday: '今日',
  preset3: '過去 3 日',
  preset7: '過去 7 日',
  preset30: '過去 30 日',
  preset90: '過去 90 日',
  presetCustom: 'カスタム',
  metricCost: 'コスト',
  liveRefresh: '自動更新',
  liveRefreshTitle: (sec: number) => `${sec} 秒ごとに再取得します。このページを離れると停止します`,
  refresh: '更新',
  granularity: '粒度',
  autoCurrency: '通貨を自動選択',
  basisMarginal: '限界費用',
  basisEquivalent: 'API 換算コスト',
  ledger: '台帳',
  compTitle: 'コストの内訳',
  mainTitle: '使用量の推移',
  mainDesc: '種類、呼び出し用途、モデルを組み合わせて分割できます。',
  split: '分割',
  dimType: '種類',
  dimRole: '呼び出し用途',
  dimModel: 'モデル',
  sortByShare: '割合で並べ替え',
  sortByShareTitle: '各部分を割合の大きい順に積み上げる',
  callTitle: 'API 呼び出し回数',
  headCalls: '呼び出し',
  headInput: '入力 tok',
  headOutput: '出力 tok',
  headCache: 'キャッシュヒット',
  headCost: 'コスト',
  headAvg: '平均単価',
  byRole: '呼び出し用途別',
  byModel: 'モデル別',
  byInstance: 'モデル接続別',
  dimInstance: 'モデル接続',
  cardKnownCost: '判明している費用の小計',
  unknown: '不明',
  cardCalls: '呼び出し回数',
  cardAvgCost: '成功した呼び出しの平均単価',
  partialMark: ' +未計上',
  approxTok: (tok: string) => `≈ ${tok} tok / 回`,
  cardInput: '入力 token',
  hitRate: (pct: string) => `ヒット率 ${pct}`,
  cardOutput: '出力 token',
  reasoningShare: (pct: string) => `思考 ${pct}`,
  cardCacheRate: 'キャッシュヒット率',
  cardCoverage: '料金の適用範囲',
  unpriced: (n: number) => `${n} 回は現在の台帳で料金を完全には計算できていません`,
  cardPeak: 'ピーク',
  cardFailed: '失敗した呼び出し',
  failedCalls: (n: string) => `${n} 回`,
  burned: (tok: string) => `消費 ≈ ${tok} tok`,
  noCostData: 'コストのデータはまだありません',
  partCacheHit: 'キャッシュ済みの入力',
  partCacheMiss: 'キャッシュ外の入力',
  partOutput: '出力',
  partOther: 'その他の費用',
  noData: 'データなし',
  autoBucket: (label: string) => `自動 → ${label}単位`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} 区間`,
  compUnpriced: (n: number) => `${n} 回の呼び出しは現在の台帳で料金を完全には計算できていないため、コストには判明している部分だけを含みます。`,
  stale: (err: string, at: string) => `更新に失敗しました：${err}。以下は ${at} に取得した結果です。`,
  billingHint: 'リクエスト時点の料金スナップショットで集計しています。' +
    '合計には失敗、プリエンプト、診断のリクエストも含みます。通貨と費用の基準は別々に集計します。',
  unknownUsage: (n: number) => ` ${n} 件のリクエストは使用量またはキャッシュの内訳が不完全です。`,
  ledgerError: (pending: number, error: string) => ` 台帳の保存でエラーが発生し、${pending} 件が書き込み待ちです：${error}`,
  loadFailed: (msg: string) => '使用量を読み込めませんでした：' + msg,
  loading: '読み込み中…',

  // chart.ts
  total: '合計',
  totalPrefix: '合計 ',
  callsUnit: ' 回',
  weekShort: (s: string) => s + ' 週',
  weekFull: (bucket: string) => bucket + ' から · 週',
  monthFull: (bucket: string) => bucket + ' · 月',
  restOmitted: '… 残りは省略',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `呼び出し ${calls} · ヒット率 ${hitRate} · 思考 ${reasoning}`,
  tipUnpriced: (n: number) => `${n} 回は料金を完全には計算できていないため、コストの棒には判明している部分だけを含みます`,
  noCalls: 'この範囲に呼び出しの記録はありません',

  // labels.ts
  typeCacheHit: 'キャッシュヒット',
  typeCacheMiss: 'キャッシュ外の入力',
  typeOutput: '出力',
  typeOther: 'その他の費用 / 未分類の入力',
};
