import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '用量與成本',
  navGroup: 'Core',
  pageTitle: '用量與成本',
  bucketAuto: '自動',
  bucketMinute: '分',
  bucketHour: '時',
  bucketDay: '天',
  bucketWeek: '週',
  bucketMonth: '月',
  presetToday: '今天',
  preset3: '近 3 天',
  preset7: '近 7 天',
  preset30: '近 30 天',
  preset90: '近 90 天',
  presetCustom: '自訂',
  metricCost: '成本',
  liveRefresh: '自動重新整理',
  liveRefreshTitle: (sec: number) => `每 ${sec} 秒重新取得一次；離開本頁自動停止`,
  refresh: '重新整理',
  granularity: '粒度',
  autoCurrency: '自動幣別',
  rateHint: '儲存到 Core 設定 usage.rates，修改後立即重新換算',
  rateSaveFailed: (why: string) => `匯率沒有儲存：${why}`,
  basisMarginal: '邊際費用',
  basisEquivalent: '等價 API 成本',
  ledger: '帳本',
  compTitle: '成本構成',
  mainTitle: '用量時間序列',
  mainDesc: '可組合類型、呼叫用途與模型進行拆分。',
  split: '拆分',
  dimType: '類型',
  dimRole: '呼叫用途',
  dimModel: '模型',
  sortByShare: '依占比排序',
  sortByShareTitle: '依各部分占比從大到小堆疊',
  callTitle: 'API 呼叫次數',
  headCalls: '呼叫',
  headInput: '輸入 tok',
  headOutput: '輸出 tok',
  headCache: '快取命中',
  headCost: '成本',
  headAvg: '均價',
  byRole: '依呼叫用途',
  byModel: '依模型',
  byInstance: '依模型連線',
  dimInstance: '模型連線',
  cardKnownCost: '已知費用小計',
  unknown: '未知',
  cardCalls: '呼叫次數',
  cardAvgCost: '成功呼叫均價',
  partialMark: ' +未計價',
  approxTok: (tok: string) => `≈ ${tok} tok / 次`,
  cardInput: '輸入 token',
  hitRate: (pct: string) => `命中率 ${pct}`,
  cardOutput: '輸出 token',
  reasoningShare: (pct: string) => `思維鏈 ${pct}`,
  cardCacheRate: '快取命中率',
  cardCoverage: '報價覆蓋',
  unpriced: (n: number) => `${n} 次在目前帳本未完整計價`,
  cardPeak: '峰值',
  cardFailed: '失敗流',
  failedCalls: (n: string) => `${n} 次`,
  burned: (tok: string) => `消耗 ≈ ${tok} tok`,
  noCostData: '暫無成本資料',
  partCacheHit: '命中快取輸入',
  partCacheMiss: '未命中輸入',
  partOutput: '輸出',
  partOther: '其他費用',
  noData: '無資料',
  autoBucket: (label: string) => `自動 → 依${label}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} 桶`,
  compUnpriced: (n: number) => `${n} 次呼叫在目前帳本未完整計價，成本只含已知部分。`,
  stale: (err: string, at: string) => `重新整理失敗：${err}。下方是 ${at} 取回的結果。`,
  billingHint: '依請求時的報價快照統計。' +
    '總量包含失敗、搶占與診斷請求；幣別和費用口徑分別彙總。',
  unknownUsage: (n: number) => ` ${n} 次請求的用量或快取分布不完整。`,
  ledgerError: (pending: number, error: string) => ` 帳目儲存異常，${pending} 筆待寫入：${error}`,
  loadFailed: (msg: string) => '用量載入失敗: ' + msg,
  loading: '載入中…',

  // chart.ts
  total: '合計',
  totalPrefix: '合計 ',
  callsUnit: ' 次',
  weekShort: (s: string) => s + '週',
  weekFull: (bucket: string) => bucket + ' 起 · 週',
  monthFull: (bucket: string) => bucket + ' · 月',
  restOmitted: '… 其餘從略',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `呼叫 ${calls} · 命中率 ${hitRate} · 思維鏈 ${reasoning}`,
  tipUnpriced: (n: number) => `${n} 次未完整計價，成本柱只含已知部分`,
  noCalls: '這個範圍內沒有呼叫記錄',

  // labels.ts
  typeCacheHit: '命中快取',
  typeCacheMiss: '未命中輸入',
  typeOutput: '輸出',
  typeOther: '其他費用 / 未分布輸入',
};
