import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Verbrauch & Kosten',
  navGroup: 'Core',
  pageTitle: 'Verbrauch & Kosten',
  bucketAuto: 'Automatisch',
  bucketMinute: 'Minute',
  bucketHour: 'Stunde',
  bucketDay: 'Tag',
  bucketWeek: 'Woche',
  bucketMonth: 'Monat',
  presetToday: 'Heute',
  preset3: 'Letzte 3 Tage',
  preset7: 'Letzte 7 Tage',
  preset30: 'Letzte 30 Tage',
  preset90: 'Letzte 90 Tage',
  presetCustom: 'Benutzerdefiniert',
  metricCost: 'Kosten',
  liveRefresh: 'Auto-Aktualisierung',
  liveRefreshTitle: (sec: number) => `Lädt alle ${sec} s neu; stoppt, wenn du diese Seite verlässt`,
  refresh: 'Aktualisieren',
  granularity: 'Granularität',
  autoCurrency: 'Währung automatisch',
  rateHint: 'Wird in der Core-Konfiguration (usage.rates) gespeichert; der Bericht rechnet sofort neu um',
  rateSaveFailed: (why: string) => `Kurs nicht gespeichert: ${why}`,
  basisMarginal: 'Grenzkosten',
  basisEquivalent: 'Äquivalente API-Kosten',
  ledger: 'Journal',
  compTitle: 'Kostenaufschlüsselung',
  mainTitle: 'Verbrauch im Zeitverlauf',
  mainDesc: 'Kombiniere die Dimensionen Typ, Zweck und Modell.',
  split: 'Aufteilen',
  dimType: 'Typ',
  dimRole: 'Zweck',
  dimModel: 'Modell',
  sortByShare: 'Nach Anteil sortieren',
  sortByShareTitle: 'Teile vom größten zum kleinsten Anteil stapeln',
  callTitle: 'API-Aufrufe',
  headCalls: 'Aufrufe',
  headInput: 'Eingabe-tok',
  headOutput: 'Ausgabe-tok',
  headCache: 'Cache-Treffer',
  headCost: 'Kosten',
  headAvg: 'Ø Preis',
  byRole: 'Nach Zweck',
  byModel: 'Nach Modell',
  byInstance: 'Nach Modellverbindung',
  dimInstance: 'Verbindung',
  cardKnownCost: 'Zwischensumme bekannter Kosten',
  unknown: 'unbekannt',
  cardCalls: 'Aufrufe',
  cardAvgCost: 'Ø pro erfolgreichem Aufruf',
  partialMark: ' +ohne Preis',
  approxTok: (tok: string) => `≈ ${tok} tok / Aufruf`,
  cardInput: 'Eingabe-Tokens',
  hitRate: (pct: string) => `Trefferquote ${pct}`,
  cardOutput: 'Ausgabe-Tokens',
  reasoningShare: (pct: string) => `Denkprozess ${pct}`,
  cardCacheRate: 'Cache-Trefferquote',
  cardCoverage: 'Preisabdeckung',
  unpriced: (n: number) => `${n} ${n === 1 ? 'Aufruf' : 'Aufrufe'} im aktuellen Journal nicht vollständig bepreist`,
  cardPeak: 'Spitze',
  cardFailed: 'Fehlgeschlagene Aufrufe',
  failedCalls: (n: string) => `${n} ${n === '1' ? 'Aufruf' : 'Aufrufe'}`,
  burned: (tok: string) => `verbraucht ≈ ${tok} tok`,
  noCostData: 'Noch keine Kostendaten',
  partCacheHit: 'Gecachte Eingabe',
  partCacheMiss: 'Nicht gecachte Eingabe',
  partOutput: 'Ausgabe',
  partOther: 'Sonstige Kosten',
  noData: 'Keine Daten',
  autoBucket: (label: string) => `Automatisch → nach ${label}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} ${buckets === 1 ? 'Intervall' : 'Intervalle'}`,
  compUnpriced: (n: number) => `${n} ${n === 1 ? 'Aufruf ist' : 'Aufrufe sind'} im aktuellen Journal nicht vollständig bepreist; die Kosten enthalten nur den bekannten Teil.`,
  stale: (err: string, at: string) => `Aktualisierung fehlgeschlagen: ${err}. Die Ergebnisse unten stammen von ${at}.`,
  billingHint: 'Berechnet aus dem Preis-Snapshot zum Anfragezeitpunkt. ' +
    'Die Summen enthalten fehlgeschlagene, verdrängte und Diagnose-Anfragen; Währungen und Kostenbasen werden getrennt summiert.',
  unknownUsage: (n: number) => ` ${n} ${n === 1 ? 'Anfrage hat' : 'Anfragen haben'} eine unvollständige Verbrauchs- oder Cache-Aufschlüsselung.`,
  ledgerError: (pending: number, error: string) => ` Speicherfehler im Journal, ${pending} ${pending === 1 ? 'Eintrag' : 'Einträge'} ausstehend: ${error}`,
  loadFailed: (msg: string) => 'Verbrauch konnte nicht geladen werden: ' + msg,
  loading: 'Lädt…',

  // chart.ts
  total: 'Summe',
  totalPrefix: 'Summe ',
  callsUnit: ' Aufrufe',
  weekShort: (s: string) => s + ' Wo.',
  weekFull: (bucket: string) => bucket + ' · Woche',
  monthFull: (bucket: string) => bucket + ' · Monat',
  restOmitted: '… Rest ausgelassen',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `Aufrufe ${calls} · Trefferquote ${hitRate} · Denkprozess ${reasoning}`,
  tipUnpriced: (n: number) => `${n} ${n === 1 ? 'Aufruf' : 'Aufrufe'} nicht vollständig bepreist; der Kostenbalken enthält nur den bekannten Teil`,
  noCalls: 'Keine Aufrufe in diesem Zeitraum',

  // labels.ts
  typeCacheHit: 'Gecacht',
  typeCacheMiss: 'Nicht gecachte Eingabe',
  typeOutput: 'Ausgabe',
  typeOther: 'Sonstige Kosten / nicht zugeordnete Eingabe',
};
