import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Uso e costi',
  navGroup: 'Core',
  pageTitle: 'Uso e costi',
  bucketAuto: 'Automatico',
  bucketMinute: 'Minuto',
  bucketHour: 'Ora',
  bucketDay: 'Giorno',
  bucketWeek: 'Settimana',
  bucketMonth: 'Mese',
  presetToday: 'Oggi',
  preset3: 'Ultimi 3 giorni',
  preset7: 'Ultimi 7 giorni',
  preset30: 'Ultimi 30 giorni',
  preset90: 'Ultimi 90 giorni',
  presetCustom: 'Personalizzato',
  metricCost: 'Costo',
  liveRefresh: 'Aggiornamento automatico',
  liveRefreshTitle: (sec: number) => `Ricarica ogni ${sec} s; si ferma quando lasci questa pagina`,
  refresh: 'Aggiorna',
  granularity: 'Granularità',
  autoCurrency: 'Valuta automatica',
  rateHint: 'Cambio inserito: quanto vale 1 USD in questa valuta; il report riconverte appena cambia',
  basisMarginal: 'Costo marginale',
  basisEquivalent: 'Costo API equivalente',
  ledger: 'Registro',
  compTitle: 'Composizione dei costi',
  mainTitle: "Serie temporale dell'uso",
  mainDesc: 'Combina le dimensioni tipo, scopo e modello.',
  split: 'Suddividi',
  dimType: 'Tipo',
  dimRole: 'Scopo',
  dimModel: 'Modello',
  sortByShare: 'Ordina per quota',
  sortByShareTitle: 'Impila le parti dalla quota maggiore alla minore',
  callTitle: 'Chiamate API',
  headCalls: 'Chiamate',
  headInput: 'tok in ingresso',
  headOutput: 'tok in uscita',
  headCache: 'Hit della cache',
  headCost: 'Costo',
  headAvg: 'Prezzo medio',
  byRole: 'Per scopo',
  byModel: 'Per modello',
  byInstance: 'Per connessione al modello',
  dimInstance: 'Connessione',
  cardKnownCost: 'Subtotale dei costi noti',
  unknown: 'sconosciuto',
  cardCalls: 'Chiamate',
  cardAvgCost: 'Media per chiamata riuscita',
  partialMark: ' +senza prezzo',
  approxTok: (tok: string) => `≈ ${tok} tok / chiamata`,
  cardInput: 'Token in ingresso',
  hitRate: (pct: string) => `tasso di hit ${pct}`,
  cardOutput: 'Token in uscita',
  reasoningShare: (pct: string) => `ragionamento ${pct}`,
  cardCacheRate: 'Tasso di hit della cache',
  cardCoverage: 'Copertura dei prezzi',
  unpriced: (n: number) => `${n} ${n === 1 ? 'chiamata non del tutto prezzata' : 'chiamate non del tutto prezzate'} nel registro attuale`,
  cardPeak: 'Picco',
  cardFailed: 'Chiamate non riuscite',
  failedCalls: (n: string) => `${n} ${n === '1' ? 'chiamata' : 'chiamate'}`,
  burned: (tok: string) => `consumati ≈ ${tok} tok`,
  noCostData: 'Ancora nessun dato sui costi',
  partCacheHit: 'Ingresso in cache',
  partCacheMiss: 'Ingresso non in cache',
  partOutput: 'Uscita',
  partOther: 'Altri costi',
  noData: 'Nessun dato',
  autoBucket: (label: string) => `Automatico → per ${label.toLowerCase()}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} ${buckets === 1 ? 'intervallo' : 'intervalli'}`,
  compUnpriced: (n: number) => `${n} ${n === 1 ? 'chiamata non è del tutto prezzata' : 'chiamate non sono del tutto prezzate'} nel registro attuale; i costi includono solo la parte nota.`,
  stale: (err: string, at: string) => `Aggiornamento non riuscito: ${err}. I risultati qui sotto risalgono a ${at}.`,
  billingHint: "Calcolato dall'istantanea dei prezzi al momento della richiesta. " +
    'I totali includono richieste non riuscite, interrotte per prelazione e di diagnostica; valute e basi di costo sono sommate separatamente.',
  unknownUsage: (n: number) => ` ${n} ${n === 1 ? 'richiesta ha' : 'richieste hanno'} una ripartizione di uso o cache incompleta.`,
  ledgerError: (pending: number, error: string) => ` Errore di archiviazione del registro, ${pending} ${pending === 1 ? 'voce' : 'voci'} in attesa: ${error}`,
  loadFailed: (msg: string) => "Caricamento dell'uso non riuscito: " + msg,
  loading: 'Caricamento…',

  // chart.ts
  total: 'Totale',
  totalPrefix: 'Totale ',
  callsUnit: ' chiamate',
  weekShort: (s: string) => s + ' sett.',
  weekFull: (bucket: string) => bucket + ' · settimana',
  monthFull: (bucket: string) => bucket + ' · mese',
  restOmitted: '… resto omesso',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `chiamate ${calls} · tasso di hit ${hitRate} · ragionamento ${reasoning}`,
  tipUnpriced: (n: number) => `${n} ${n === 1 ? 'chiamata non del tutto prezzata' : 'chiamate non del tutto prezzate'}; la barra del costo contiene solo la parte nota`,
  noCalls: 'Nessuna chiamata registrata in questo intervallo',

  // labels.ts
  typeCacheHit: 'In cache',
  typeCacheMiss: 'Ingresso non in cache',
  typeOutput: 'Uscita',
  typeOther: 'Altri costi / ingresso non classificato',
};
