import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Расход и затраты',
  navGroup: 'Core',
  pageTitle: 'Расход и затраты',
  bucketAuto: 'Авто',
  bucketMinute: 'Минута',
  bucketHour: 'Час',
  bucketDay: 'День',
  bucketWeek: 'Неделя',
  bucketMonth: 'Месяц',
  presetToday: 'Сегодня',
  preset3: 'Последние 3 дня',
  preset7: 'Последние 7 дней',
  preset30: 'Последние 30 дней',
  preset90: 'Последние 90 дней',
  presetCustom: 'Свой период',
  metricCost: 'Стоимость',
  liveRefresh: 'Автообновление',
  liveRefreshTitle: (sec: number) => `Запрашивает данные каждые ${sec} с; останавливается, когда вы уходите с этой страницы`,
  refresh: 'Обновить',
  granularity: 'Детализация',
  autoCurrency: 'Валюта автоматически',
  rateHint: 'Сохраняется в конфигурации Core (usage.rates); отчёт сразу пересчитывается',
  rateSaveFailed: (why: string) => `Курс не сохранён: ${why}`,
  basisMarginal: 'Предельная стоимость',
  basisEquivalent: 'Эквивалентная стоимость API',
  ledger: 'Журнал',
  compTitle: 'Структура затрат',
  mainTitle: 'Расход во времени',
  mainDesc: 'Комбинируйте измерения: тип, назначение и модель.',
  split: 'Разбивка',
  dimType: 'Тип',
  dimRole: 'Назначение',
  dimModel: 'Модель',
  sortByShare: 'Сортировать по доле',
  sortByShareTitle: 'Складывать части от большей доли к меньшей',
  callTitle: 'Вызовы API',
  headCalls: 'Вызовы',
  headInput: 'Вход, tok',
  headOutput: 'Выход, tok',
  headCache: 'Попадания в кэш',
  headCost: 'Стоимость',
  headAvg: 'Ср. цена',
  byRole: 'По назначению',
  byModel: 'По модели',
  byInstance: 'По подключению к модели',
  dimInstance: 'Подключение',
  cardKnownCost: 'Подытог известной стоимости',
  unknown: 'неизвестно',
  cardCalls: 'Вызовы',
  cardAvgCost: 'В среднем за успешный вызов',
  partialMark: ' +без цены',
  approxTok: (tok: string) => `≈ ${tok} tok / вызов`,
  cardInput: 'Входные token',
  hitRate: (pct: string) => `попадания ${pct}`,
  cardOutput: 'Выходные token',
  reasoningShare: (pct: string) => `рассуждение ${pct}`,
  cardCacheRate: 'Доля попаданий в кэш',
  cardCoverage: 'Покрытие ценами',
  unpriced: (n: number) => `Вызовов без полной цены в текущем журнале: ${n}`,
  cardPeak: 'Пик',
  cardFailed: 'Неудачные вызовы',
  failedCalls: (n: string) => `${n} выз.`,
  burned: (tok: string) => `израсходовано ≈ ${tok} tok`,
  noCostData: 'Данных о затратах пока нет',
  partCacheHit: 'Вход из кэша',
  partCacheMiss: 'Вход без кэша',
  partOutput: 'Выход',
  partOther: 'Прочие расходы',
  noData: 'Нет данных',
  autoBucket: (label: string) => `Авто → интервал: ${label}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · интервалов: ${buckets}`,
  compUnpriced: (n: number) => `Вызовов без полной цены в текущем журнале: ${n}; стоимость включает только известную часть.`,
  stale: (err: string, at: string) => `Не удалось обновить: ${err}. Ниже результаты, полученные в ${at}.`,
  billingHint: 'Рассчитано по снимку цен на момент запроса. ' +
    'Итоги включают неудачные, вытесненные и диагностические запросы; валюты и основы стоимости суммируются отдельно.',
  unknownUsage: (n: number) => ` Запросов с неполной разбивкой расхода или кэша: ${n}.`,
  ledgerError: (pending: number, error: string) => ` Ошибка хранилища журнала (ожидают записи: ${pending}): ${error}`,
  loadFailed: (msg: string) => 'Не удалось загрузить расход: ' + msg,
  loading: 'Загрузка…',

  // chart.ts
  total: 'Итого',
  totalPrefix: 'Итого ',
  callsUnit: ' выз.',
  weekShort: (s: string) => s + ' нед.',
  weekFull: (bucket: string) => bucket + ' · неделя',
  monthFull: (bucket: string) => bucket + ' · месяц',
  restOmitted: '… остальное опущено',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `вызовы ${calls} · попадания ${hitRate} · рассуждение ${reasoning}`,
  tipUnpriced: (n: number) => `Вызовов без полной цены: ${n}; столбец стоимости включает только известную часть`,
  noCalls: 'В этом диапазоне нет вызовов',

  // labels.ts
  typeCacheHit: 'Из кэша',
  typeCacheMiss: 'Вход без кэша',
  typeOutput: 'Выход',
  typeOther: 'Прочие расходы / неклассифицированный вход',
};
