import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Utilisation et coûts',
  navGroup: 'Core',
  pageTitle: 'Utilisation et coûts',
  bucketAuto: 'Automatique',
  bucketMinute: 'Minute',
  bucketHour: 'Heure',
  bucketDay: 'Jour',
  bucketWeek: 'Semaine',
  bucketMonth: 'Mois',
  presetToday: "Aujourd'hui",
  preset3: '3 derniers jours',
  preset7: '7 derniers jours',
  preset30: '30 derniers jours',
  preset90: '90 derniers jours',
  presetCustom: 'Personnalisé',
  metricCost: 'Coût',
  liveRefresh: 'Actualisation auto',
  liveRefreshTitle: (sec: number) => `Récupère toutes les ${sec} s ; s'arrête quand vous quittez cette page`,
  refresh: 'Actualiser',
  granularity: 'Granularité',
  autoCurrency: 'Devise auto',
  rateHint: 'Enregistré dans la configuration Core (usage.rates) ; le rapport reconvertit aussitôt',
  rateSaveFailed: (why: string) => `Taux non enregistré : ${why}`,
  basisMarginal: 'Coût marginal',
  basisEquivalent: 'Coût API équivalent',
  ledger: 'Registre',
  compTitle: 'Répartition des coûts',
  mainTitle: "Série temporelle d'utilisation",
  mainDesc: 'Combinez les dimensions type, usage et modèle.',
  split: 'Ventiler',
  dimType: 'Type',
  dimRole: 'Usage',
  dimModel: 'Modèle',
  sortByShare: 'Trier par part',
  sortByShareTitle: 'Empiler les parts de la plus grande à la plus petite',
  callTitle: "Appels d'API",
  headCalls: 'Appels',
  headInput: 'tok entrée',
  headOutput: 'tok sortie',
  headCache: 'Succès de cache',
  headCost: 'Coût',
  headAvg: 'Prix moyen',
  byRole: 'Par usage',
  byModel: 'Par modèle',
  byInstance: 'Par connexion de modèle',
  dimInstance: 'Connexion',
  cardKnownCost: 'Sous-total des coûts connus',
  unknown: 'inconnu',
  cardCalls: 'Appels',
  cardAvgCost: 'Moyenne par appel réussi',
  partialMark: ' +non tarifé',
  approxTok: (tok: string) => `≈ ${tok} tok / appel`,
  cardInput: "Tokens d'entrée",
  hitRate: (pct: string) => `taux de succès ${pct}`,
  cardOutput: 'Tokens de sortie',
  reasoningShare: (pct: string) => `raisonnement ${pct}`,
  cardCacheRate: 'Taux de succès du cache',
  cardCoverage: 'Couverture tarifaire',
  unpriced: (n: number) => `${n} appel${n > 1 ? 's' : ''} non entièrement tarifé${n > 1 ? 's' : ''} dans le registre actuel`,
  cardPeak: 'Pic',
  cardFailed: 'Appels échoués',
  failedCalls: (n: string) => `${n} appel${n === '0' || n === '1' ? '' : 's'}`,
  burned: (tok: string) => `consommé ≈ ${tok} tok`,
  noCostData: "Aucune donnée de coût pour l'instant",
  partCacheHit: 'Entrée en cache',
  partCacheMiss: 'Entrée hors cache',
  partOutput: 'Sortie',
  partOther: 'Autres frais',
  noData: 'Aucune donnée',
  autoBucket: (label: string) => `Automatique → par ${label.toLowerCase()}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} intervalle${buckets > 1 ? 's' : ''}`,
  compUnpriced: (n: number) => `${n} appel${n > 1 ? 's' : ''} non entièrement tarifé${n > 1 ? 's' : ''} dans le registre actuel ; les coûts n'incluent que la part connue.`,
  stale: (err: string, at: string) => `Échec de l'actualisation : ${err}. Les résultats ci-dessous datent de ${at}.`,
  billingHint: "Calculé à partir de l'instantané des tarifs au moment de la requête. " +
    'Les totaux incluent les requêtes échouées, préemptées et de diagnostic ; les devises et les bases de coût sont additionnées séparément.',
  unknownUsage: (n: number) => ` ${n} requête${n > 1 ? 's ont' : ' a'} une répartition d'utilisation ou de cache incomplète.`,
  ledgerError: (pending: number, error: string) => ` Erreur de stockage du registre, ${pending} entrée${pending > 1 ? 's' : ''} en attente : ${error}`,
  loadFailed: (msg: string) => "Échec du chargement de l'utilisation : " + msg,
  loading: 'Chargement…',

  // chart.ts
  total: 'Total',
  totalPrefix: 'Total ',
  callsUnit: ' appels',
  weekShort: (s: string) => s + ' sem.',
  weekFull: (bucket: string) => bucket + ' · semaine',
  monthFull: (bucket: string) => bucket + ' · mois',
  restOmitted: '… le reste est omis',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `appels ${calls} · taux de succès ${hitRate} · raisonnement ${reasoning}`,
  tipUnpriced: (n: number) => `${n} appel${n > 1 ? 's' : ''} non entièrement tarifé${n > 1 ? 's' : ''} ; la barre de coût ne contient que la part connue`,
  noCalls: 'Aucun appel enregistré sur cette période',

  // labels.ts
  typeCacheHit: 'En cache',
  typeCacheMiss: 'Entrée hors cache',
  typeOutput: 'Sortie',
  typeOther: 'Autres frais / entrée non classée',
};
