import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: '사용량 및 비용',
  navGroup: 'Core',
  pageTitle: '사용량 및 비용',
  bucketAuto: '자동',
  bucketMinute: '분',
  bucketHour: '시간',
  bucketDay: '일',
  bucketWeek: '주',
  bucketMonth: '월',
  presetToday: '오늘',
  preset3: '최근 3일',
  preset7: '최근 7일',
  preset30: '최근 30일',
  preset90: '최근 90일',
  presetCustom: '사용자 지정',
  metricCost: '비용',
  liveRefresh: '자동 새로 고침',
  liveRefreshTitle: (sec: number) => `${sec}초마다 다시 가져오며, 이 페이지를 떠나면 멈춥니다`,
  refresh: '새로 고침',
  granularity: '단위',
  autoCurrency: '통화 자동',
  rateHint: 'Core 설정 usage.rates에 저장하고 바로 다시 환산합니다',
  rateSaveFailed: (why: string) => `환율을 저장하지 못했습니다: ${why}`,
  basisMarginal: '한계 비용',
  basisEquivalent: 'API 환산 비용',
  ledger: '원장',
  compTitle: '비용 구성',
  mainTitle: '사용량 시계열',
  mainDesc: '유형, 호출 용도, 모델을 조합해 나눠 볼 수 있습니다.',
  split: '나누기',
  dimType: '유형',
  dimRole: '호출 용도',
  dimModel: '모델',
  sortByShare: '비중순 정렬',
  sortByShareTitle: '각 부분을 비중이 큰 순서로 쌓기',
  callTitle: 'API 호출 수',
  headCalls: '호출',
  headInput: '입력 tok',
  headOutput: '출력 tok',
  headCache: '캐시 적중',
  headCost: '비용',
  headAvg: '평균 단가',
  byRole: '호출 용도별',
  byModel: '모델별',
  byInstance: '모델 연결별',
  dimInstance: '모델 연결',
  cardKnownCost: '알려진 비용 소계',
  unknown: '알 수 없음',
  cardCalls: '호출 수',
  cardAvgCost: '성공한 호출 평균 단가',
  partialMark: ' +미산정',
  approxTok: (tok: string) => `≈ ${tok} tok / 회`,
  cardInput: '입력 token',
  hitRate: (pct: string) => `적중률 ${pct}`,
  cardOutput: '출력 token',
  reasoningShare: (pct: string) => `추론 ${pct}`,
  cardCacheRate: '캐시 적중률',
  cardCoverage: '가격 적용 범위',
  unpriced: (n: number) => `${n}회는 현재 원장에서 가격이 완전히 산정되지 않았습니다`,
  cardPeak: '최고치',
  cardFailed: '실패한 호출',
  failedCalls: (n: string) => `${n}회`,
  burned: (tok: string) => `소모 ≈ ${tok} tok`,
  noCostData: '아직 비용 데이터가 없습니다',
  partCacheHit: '캐시된 입력',
  partCacheMiss: '캐시되지 않은 입력',
  partOutput: '출력',
  partOther: '기타 비용',
  noData: '데이터 없음',
  autoBucket: (label: string) => `자동 → ${label} 단위`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · 구간 ${buckets}개`,
  compUnpriced: (n: number) => `호출 ${n}회는 현재 원장에서 가격이 완전히 산정되지 않아 비용에는 알려진 부분만 포함됩니다.`,
  stale: (err: string, at: string) => `새로 고치지 못했습니다: ${err}. 아래는 ${at}에 가져온 결과입니다.`,
  billingHint: '요청 시점의 가격 스냅숏으로 집계합니다. ' +
    '합계에는 실패, 선점, 진단 요청이 포함되며 통화와 비용 기준은 따로 합산합니다.',
  unknownUsage: (n: number) => ` 요청 ${n}건은 사용량 또는 캐시 구성이 불완전합니다.`,
  ledgerError: (pending: number, error: string) => ` 원장 저장 오류, ${pending}건 기록 대기: ${error}`,
  loadFailed: (msg: string) => '사용량을 불러오지 못했습니다: ' + msg,
  loading: '불러오는 중…',

  // chart.ts
  total: '합계',
  totalPrefix: '합계 ',
  callsUnit: '회',
  weekShort: (s: string) => s + ' 주',
  weekFull: (bucket: string) => bucket + ' 시작 · 주',
  monthFull: (bucket: string) => bucket + ' · 월',
  restOmitted: '… 나머지 생략',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `호출 ${calls} · 적중률 ${hitRate} · 추론 ${reasoning}`,
  tipUnpriced: (n: number) => `${n}회는 가격이 완전히 산정되지 않아 비용 막대에는 알려진 부분만 들어 있습니다`,
  noCalls: '이 범위에는 호출 기록이 없습니다',

  // labels.ts
  typeCacheHit: '캐시 적중',
  typeCacheMiss: '캐시되지 않은 입력',
  typeOutput: '출력',
  typeOther: '기타 비용 / 분류되지 않은 입력',
};
