import type { en } from './strings.ts';

const pl = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Uso e custo',
  navGroup: 'Core',
  pageTitle: 'Uso e custo',
  bucketAuto: 'Automático',
  bucketMinute: 'Minuto',
  bucketHour: 'Hora',
  bucketDay: 'Dia',
  bucketWeek: 'Semana',
  bucketMonth: 'Mês',
  presetToday: 'Hoje',
  preset3: 'Últimos 3 dias',
  preset7: 'Últimos 7 dias',
  preset30: 'Últimos 30 dias',
  preset90: 'Últimos 90 dias',
  presetCustom: 'Personalizado',
  metricCost: 'Custo',
  liveRefresh: 'Atualização automática',
  liveRefreshTitle: (sec: number) => `Busca de novo a cada ${sec} s; para ao sair desta página`,
  refresh: 'Atualizar',
  granularity: 'Granularidade',
  autoCurrency: 'Moeda automática',
  rateHint: 'Salvo na configuração do Core (usage.rates); o relatório converte de novo na hora',
  rateSaveFailed: (why: string) => `Câmbio não salvo: ${why}`,
  basisMarginal: 'Custo marginal',
  basisEquivalent: 'Custo equivalente de API',
  ledger: 'Registro',
  compTitle: 'Composição do custo',
  mainTitle: 'Série temporal de uso',
  mainDesc: 'Combine as dimensões de tipo, finalidade e modelo.',
  split: 'Dividir',
  dimType: 'Tipo',
  dimRole: 'Finalidade',
  dimModel: 'Modelo',
  sortByShare: 'Ordenar por participação',
  sortByShareTitle: 'Empilha as partes da maior para a menor participação',
  callTitle: 'Chamadas de API',
  headCalls: 'Chamadas',
  headInput: 'tok de entrada',
  headOutput: 'tok de saída',
  headCache: 'Acertos de cache',
  headCost: 'Custo',
  headAvg: 'Preço médio',
  byRole: 'Por finalidade',
  byModel: 'Por modelo',
  byInstance: 'Por conexão de modelo',
  dimInstance: 'Conexão',
  cardKnownCost: 'Subtotal de custo conhecido',
  unknown: 'desconhecido',
  cardCalls: 'Chamadas',
  cardAvgCost: 'Média por chamada bem-sucedida',
  partialMark: ' +sem preço',
  approxTok: (tok: string) => `≈ ${tok} tok / chamada`,
  cardInput: 'Tokens de entrada',
  hitRate: (pct: string) => `taxa de acerto ${pct}`,
  cardOutput: 'Tokens de saída',
  reasoningShare: (pct: string) => `raciocínio ${pct}`,
  cardCacheRate: 'Taxa de acerto de cache',
  cardCoverage: 'Cobertura de preços',
  unpriced: (n: number) => `${n} ${pl(n, 'chamada sem preço completo', 'chamadas sem preço completo')} no registro atual`,
  cardPeak: 'Pico',
  cardFailed: 'Chamadas com falha',
  failedCalls: (n: string) => `${n} ${n === '1' ? 'chamada' : 'chamadas'}`,
  burned: (tok: string) => `consumiu ≈ ${tok} tok`,
  noCostData: 'Ainda não há dados de custo',
  partCacheHit: 'Entrada em cache',
  partCacheMiss: 'Entrada sem cache',
  partOutput: 'Saída',
  partOther: 'Outras cobranças',
  noData: 'Sem dados',
  autoBucket: (label: string) => `Automático → por ${label}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} ${pl(buckets, 'intervalo', 'intervalos')}`,
  compUnpriced: (n: number) => `${n} ${pl(n, 'chamada não tem', 'chamadas não têm')} preço completo no registro atual; os custos incluem só a parte conhecida.`,
  stale: (err: string, at: string) => `Falha ao atualizar: ${err}. Os resultados abaixo são de ${at}.`,
  billingHint: 'Calculado com o snapshot de preços do momento da requisição. ' +
    'Os totais incluem requisições com falha, interrompidas e de diagnóstico; moedas e bases de custo são somadas separadamente.',
  unknownUsage: (n: number) => ` ${n} ${pl(n, 'requisição tem', 'requisições têm')} um detalhamento de uso ou de cache incompleto.`,
  ledgerError: (pending: number, error: string) => ` Erro no armazenamento do registro, ${pending} ${pl(pending, 'entrada pendente', 'entradas pendentes')}: ${error}`,
  loadFailed: (msg: string) => 'Falha ao carregar o uso: ' + msg,
  loading: 'Carregando…',

  // chart.ts
  total: 'Total',
  totalPrefix: 'Total ',
  callsUnit: ' chamadas',
  weekShort: (s: string) => s + ' sem.',
  weekFull: (bucket: string) => bucket + ' · semana',
  monthFull: (bucket: string) => bucket + ' · mês',
  restOmitted: '… restante omitido',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `chamadas ${calls} · taxa de acerto ${hitRate} · raciocínio ${reasoning}`,
  tipUnpriced: (n: number) => `${n} ${pl(n, 'chamada sem preço completo', 'chamadas sem preço completo')}; a barra de custo inclui só a parte conhecida`,
  noCalls: 'Nenhuma chamada registrada neste intervalo',

  // labels.ts
  typeCacheHit: 'Em cache',
  typeCacheMiss: 'Entrada sem cache',
  typeOutput: 'Saída',
  typeOther: 'Outras cobranças / entrada não classificada',
};
