import type { en } from './strings.ts';

const pl = (n: number, one: string, many: string) => (n === 1 ? one : many);

export const S: Partial<typeof en> = {
  // index.ts
  navLabel: 'Uso y costo',
  navGroup: 'Core',
  pageTitle: 'Uso y costo',
  bucketAuto: 'Automático',
  bucketMinute: 'Minuto',
  bucketHour: 'Hora',
  bucketDay: 'Día',
  bucketWeek: 'Semana',
  bucketMonth: 'Mes',
  presetToday: 'Hoy',
  preset3: 'Últimos 3 días',
  preset7: 'Últimos 7 días',
  preset30: 'Últimos 30 días',
  preset90: 'Últimos 90 días',
  presetCustom: 'Personalizado',
  metricCost: 'Costo',
  liveRefresh: 'Actualización automática',
  liveRefreshTitle: (sec: number) => `Vuelve a consultar cada ${sec} s; se detiene al salir de esta página`,
  refresh: 'Actualizar',
  granularity: 'Granularidad',
  autoCurrency: 'Moneda automática',
  basisMarginal: 'Costo marginal',
  basisEquivalent: 'Costo equivalente de API',
  ledger: 'Libro',
  compTitle: 'Desglose de costos',
  mainTitle: 'Serie temporal de uso',
  mainDesc: 'Combina las dimensiones de tipo, propósito y modelo.',
  split: 'Dividir',
  dimType: 'Tipo',
  dimRole: 'Propósito',
  dimModel: 'Modelo',
  sortByShare: 'Ordenar por proporción',
  sortByShareTitle: 'Apila las partes de mayor a menor proporción',
  callTitle: 'Llamadas a la API',
  headCalls: 'Llamadas',
  headInput: 'tok de entrada',
  headOutput: 'tok de salida',
  headCache: 'Aciertos de caché',
  headCost: 'Costo',
  headAvg: 'Precio prom.',
  byRole: 'Por propósito',
  byModel: 'Por modelo',
  byInstance: 'Por conexión de modelo',
  dimInstance: 'Conexión',
  cardKnownCost: 'Subtotal de costo conocido',
  unknown: 'desconocido',
  cardCalls: 'Llamadas',
  cardAvgCost: 'Promedio por llamada exitosa',
  partialMark: ' +sin precio',
  approxTok: (tok: string) => `≈ ${tok} tok / llamada`,
  cardInput: 'Tokens de entrada',
  hitRate: (pct: string) => `tasa de aciertos ${pct}`,
  cardOutput: 'Tokens de salida',
  reasoningShare: (pct: string) => `razonamiento ${pct}`,
  cardCacheRate: 'Tasa de aciertos de caché',
  cardCoverage: 'Cobertura de precios',
  unpriced: (n: number) => `${n} ${pl(n, 'llamada sin precio completo', 'llamadas sin precio completo')} en el libro actual`,
  cardPeak: 'Pico',
  cardFailed: 'Llamadas fallidas',
  failedCalls: (n: string) => `${n} ${n === '1' ? 'llamada' : 'llamadas'}`,
  burned: (tok: string) => `consumió ≈ ${tok} tok`,
  noCostData: 'Aún no hay datos de costo',
  partCacheHit: 'Entrada en caché',
  partCacheMiss: 'Entrada sin caché',
  partOutput: 'Salida',
  partOther: 'Otros cargos',
  noData: 'Sin datos',
  autoBucket: (label: string) => `Automático → por ${label}`,
  rangeHint: (from: string, to: string, buckets: number, timezone: string | null) =>
    `${from} ~ ${to}${timezone ? ` (${timezone})` : ''} · ${buckets} ${pl(buckets, 'intervalo', 'intervalos')}`,
  compUnpriced: (n: number) => `${n} ${pl(n, 'llamada no tiene', 'llamadas no tienen')} precio completo en el libro actual; los costos solo incluyen la parte conocida.`,
  stale: (err: string, at: string) => `Falló la actualización: ${err}. Los resultados de abajo son de ${at}.`,
  billingHint: 'Calculado con la instantánea de precios del momento de la solicitud. ' +
    'Los totales incluyen solicitudes fallidas, interrumpidas y de diagnóstico; las monedas y las bases de costo se suman por separado.',
  unknownUsage: (n: number) => ` ${n} ${pl(n, 'solicitud tiene', 'solicitudes tienen')} un desglose de uso o de caché incompleto.`,
  ledgerError: (pending: number, error: string) => ` Error en el almacenamiento del libro, ${pending} ${pl(pending, 'entrada pendiente', 'entradas pendientes')}: ${error}`,
  loadFailed: (msg: string) => 'No se pudo cargar el uso: ' + msg,
  loading: 'Cargando…',

  // chart.ts
  total: 'Total',
  totalPrefix: 'Total ',
  callsUnit: ' llamadas',
  weekShort: (s: string) => s + ' sem.',
  weekFull: (bucket: string) => bucket + ' · semana',
  monthFull: (bucket: string) => bucket + ' · mes',
  restOmitted: '… resto omitido',
  tipFoot: (calls: number, hitRate: string, reasoning: string) =>
    `llamadas ${calls} · tasa de aciertos ${hitRate} · razonamiento ${reasoning}`,
  tipUnpriced: (n: number) => `${n} ${pl(n, 'llamada sin precio completo', 'llamadas sin precio completo')}; la barra de costo solo incluye la parte conocida`,
  noCalls: 'No hay llamadas registradas en este rango',

  // labels.ts
  typeCacheHit: 'En caché',
  typeCacheMiss: 'Entrada sin caché',
  typeOutput: 'Salida',
  typeOther: 'Otros cargos / entrada sin clasificar',
};
