import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: '일시 중지됨: 이벤트는 그대로 저장되어 대기열에 쌓이지만 깨우기는 전달되지 않습니다',
  resumed: '재개됨: 쌓인 이벤트를 한 번에 전달합니다',
  exitShutdown: '프로세스가 곧 종료됩니다',
  exitSupervised: '프로세스가 곧 종료되며 런처가 바로 다시 시작합니다',
  exitSupervisedPaused: '프로세스가 곧 종료되며 런처가 바로 다시 시작합니다. 다시 시작한 뒤에는 이벤트 전달이 일시 중지되어 있으니 실행 상태에서 재개하세요',
  exitUnsupervised: '프로세스가 곧 종료됩니다. 런처 루프가 감지되지 않았으므로 직접 다시 시작해야 합니다',
  shutdownSkipped: (n: number, labels: string[]) => `로컬 종료는 끝났지만 ${n}개 단계가 완료되지 않았습니다: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `로컬 종료 완료(${n}개 단계 모두 완료)`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status}(${detail}). 수동 조치: ${manualAction}`, '.'),
  externalVerified: '; 외부 상태 점검에서 모두 종료가 확인되었습니다',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: '실행 제어를 사용할 수 없습니다',
  shutdownUnavailable: '종료 제어를 사용할 수 없습니다',
  restartUnavailable: '재시작 제어를 사용할 수 없습니다',
  hostRejected: '허용되지 않는 Host입니다',
  crossSiteRejected: '교차 사이트 요청을 거부했습니다',
  wrongPassword: '비밀번호가 틀렸습니다',
  loginRequired: '로그인이 필요합니다',
  avatarUnavailable: '아바타 저장소를 사용할 수 없습니다',
  avatarNotPng: '아바타는 유효한 PNG 이미지여야 합니다',
  themeUnavailable: '테마 기록을 사용할 수 없습니다',
  sessionsUnavailable: '세션 관찰을 사용할 수 없습니다',
  debugUnavailable: '디버그 채널을 사용할 수 없습니다',
  onboardingUnavailable: '온보딩 표시를 사용할 수 없습니다',
  worldVisibilityUnavailable: 'World 표시 전환을 사용할 수 없습니다',
  worldActivationUnavailable: 'World 활성화 전환을 사용할 수 없습니다',
  worldRestartUnavailable: 'World 재시작을 사용할 수 없습니다',
  extensionsUnavailable: '확장 관리를 사용할 수 없습니다',
  extensionCheckUnavailable: '확장 검사를 사용할 수 없습니다',
  promptsUnavailable: '프롬프트 템플릿 편집을 사용할 수 없습니다',
  prefixPreviewUnavailable: '프리픽스 미리 보기를 사용할 수 없습니다',
  toolSchemasUnavailable: '도구 schema를 사용할 수 없습니다',
  prefixReloadUnavailable: '세션 프리픽스 다시 불러오기를 사용할 수 없습니다',
  configUnavailable: '설정 항목 선언을 사용할 수 없습니다',
  missingField: (name: string) => `${name}이(가) 없습니다`,
  missingPackage: '패키지 이름이 없습니다',
  missingPackageOrPath: '패키지 이름 또는 경로가 없습니다',
  notBoolean: (name: string) => `${name}은(는) 불리언이어야 합니다`,
  notString: (name: string) => `${name}은(는) 문자열이어야 합니다`,
  badKind: (kind: string) => `kind는 world, provider, bot 중 하나여야 합니다(현재 ${kind})`,
  argsNotJson: 'args가 올바른 JSON이 아닙니다',
  argsNotArray: 'args는 JSON 배열이어야 합니다',
  noSession: (id: string) => `해당 세션이 없습니다: ${id}`,
  noStoragePart: (key: string) => `해당 저장소 항목이 없습니다: ${key}`,
  noStorageParts: '서버에 저장소 목록이 마운트되지 않았습니다',
  statFailed: (error: string) => `통계 실패: ${error}`,
  promptTooLarge: '프롬프트가 1MB를 넘어 저장하지 않았습니다',
  npmSearchFailed: (error: string) => `npm 검색 실패: ${error}`,
  unknownConfigGroup: (id: string) => `알 수 없는 설정 그룹: ${id}`,
  streamFailed: (error: string) => `스트림 오류: ${error}`,
  streamResolveFailed: (error: string) => `스트림 확인 실패: ${error}`,
  fileNotAbsolute: 'provider가 절대 경로가 아닌 파일 경로를 반환했습니다',
  fileInvalid: 'provider가 잘못된 파일 설명을 반환했습니다',
  fileSizeMismatch: 'provider 파일 크기가 선언과 일치하지 않습니다',
  fileTruncated: 'provider 파일이 검증 중에 잘렸습니다',
  fileHashMismatch: 'provider 파일 hash가 선언과 일치하지 않습니다',
  noPage: (pageId: string) => `해당 provider가 없습니다: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `provider ${pageId}이(가) 패널 ${panelId}을(를) 선언하지 않았습니다`,
  postOnly: (panelId: string, method: string) => `패널 ${panelId}의 메서드 ${method}은(는) POST만 받습니다`,
  noPanelSurface: (pageId: string) => `provider ${pageId}에 패널 데이터 면이 없습니다`,
  noStreamSurface: (pageId: string) => `provider ${pageId}에 스트림 면이 없습니다`,
  pickerNul: (name: string) => `${name}에 NUL 문자를 넣을 수 없습니다`,
  pickerBadExtension: (value: string) => `잘못된 파일 확장자: ${value}`,
  pickerBodyNotObject: '요청 본문은 객체여야 합니다',
  pickerBadKind: 'kind는 file 또는 directory여야 합니다',
  pickerBadExtensions: 'extensions는 문자열 배열이어야 합니다',
  pickerMissing: (path: string) => `선택한 경로가 없습니다: ${path}`,
  pickerNotFile: (path: string) => `선택한 경로가 파일이 아닙니다: ${path}`,
  pickerNotDirectory: (path: string) => `선택한 경로가 폴더가 아닙니다: ${path}`,
  pickerWrongType: (extensions: string[]) => `파일 형식은 ${extensions.join(' / ')}이어야 합니다`,
  pickerTitleFile: '파일 선택',
  pickerTitleDirectory: '폴더 선택',
  pickerSupportedFiles: '지원되는 파일',
  pickerAllFiles: '모든 파일',
  pickerNoPowerShell: '이 컴퓨터에서 PowerShell을 찾을 수 없어 경로 선택기를 열 수 없습니다',
  pickerNoOsascript: '이 컴퓨터에서 osascript를 찾을 수 없어 경로 선택기를 열 수 없습니다',
  pickerNoLinuxTool: '이 컴퓨터에 사용할 수 있는 경로 선택기가 없습니다. zenity 또는 kdialog를 설치하세요',
  pickerFailed: (error: string) => `이 컴퓨터의 경로 선택기를 열 수 없습니다: ${error}`,
  pickerUnsupported: (platform: string) => `이 플랫폼에는 기본 경로 선택기가 없습니다: ${platform}`,
};
