import { pick, punctuate, type Language } from '../core/language.ts';
import { serverText as zhHant } from './strings.zh-Hant.ts';
import { serverText as ja } from './strings.ja.ts';
import { serverText as ko } from './strings.ko.ts';
import { serverText as fr } from './strings.fr.ts';
import { serverText as de } from './strings.de.ts';
import { serverText as es419 } from './strings.es-419.ts';
import { serverText as ptBR } from './strings.pt-BR.ts';
import { serverText as it } from './strings.it.ts';
import { serverText as ru } from './strings.ru.ts';

/** 服务端回给控制台的文案:运行控制回执、关机账、接口报错与本机路径选择器,按请求的界面语言。 */
const zh = {
  paused: '已暂停:事件照常落库排队,不投递唤醒',
  resumed: '已继续:积压事件一次性投递',
  exitShutdown: '进程即将退出',
  exitSupervised: '进程即将退出,启动器随即重新拉起',
  exitSupervisedPaused: '进程即将退出,启动器随即重新拉起;回来时事件投递是暂停的,要在运行状态里按继续',
  exitUnsupervised: '进程即将退出;没有检测到启动器循环,需要手动重新启动',
  shutdownSkipped: (n: number, labels: string[]) => `本地关机完成,但有 ${n} 步没走完:${labels.join('、')}`,
  shutdownComplete: (n: number) => `本地关机完成(${n === 1 ? '1 步已走完' : `${n} 步全部走完`})`,
  externalUnverified: (items: string[]) => `。[P0] ${items.join('')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status}（${detail}）。人工动作:${manualAction}`, '。'),
  externalVerified: '；外部状态均已确认结束',
  /** 关机账的整句:本地结果、外部状态与退出说明。 */
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '，')}${exit}`,
  runUnavailable: '运行控制不可用',
  shutdownUnavailable: '关机控制不可用',
  restartUnavailable: '重启控制不可用',
  hostRejected: 'Host 不被接受',
  crossSiteRejected: '跨站请求被拒绝',
  wrongPassword: '密码不对',
  loginRequired: '需要登录',
  avatarUnavailable: '头像存储不可用',
  avatarNotPng: '头像必须是有效的 PNG 图片',
  themeUnavailable: '主题记录不可用',
  sessionsUnavailable: 'session 观察不可用',
  debugUnavailable: '调试通道不可用',
  onboardingUnavailable: '开场引导标记不可用',
  worldVisibilityUnavailable: 'World 可见性开关不可用',
  worldActivationUnavailable: 'World 激活开关不可用',
  worldRestartUnavailable: 'World 重启不可用',
  extensionsUnavailable: '扩展管理不可用',
  extensionCheckUnavailable: '扩展检查不可用',
  promptsUnavailable: '提示词模板编辑不可用',
  prefixPreviewUnavailable: '前缀预览不可用',
  toolSchemasUnavailable: '工具 schema 不可用',
  prefixReloadUnavailable: 'session 前缀重载不可用',
  configUnavailable: '配置项声明不可用',
  missingField: (name: string) => `缺少 ${name}`,
  missingPackage: '缺少包名',
  missingPackageOrPath: '缺少包名或路径',
  notBoolean: (name: string) => `${name} 必须是布尔值`,
  notString: (name: string) => `${name} 必须是字符串`,
  badKind: (kind: string) => `kind 只能是 world、provider 或 bot,现在是 ${kind}`,
  argsNotJson: 'args 不是合法 JSON',
  argsNotArray: 'args 必须是 JSON 数组',
  noSession: (id: string) => `没有这个 session: ${id}`,
  noStoragePart: (key: string) => `没有这个存储部分: ${key}`,
  noStorageParts: '服务端未挂载存储清单',
  statFailed: (error: string) => `统计失败: ${error}`,
  promptTooLarge: '提示词超过 1MB，拒绝保存',
  npmSearchFailed: (error: string) => `npm 搜索失败: ${error}`,
  unknownConfigGroup: (id: string) => `未知配置组: ${id}`,
  streamFailed: (error: string) => `流式面出错: ${error}`,
  streamResolveFailed: (error: string) => `流解析失败: ${error}`,
  fileNotAbsolute: 'provider 返回了非绝对文件路径',
  fileInvalid: 'provider 返回了无效文件描述',
  fileSizeMismatch: 'provider 文件大小与声明不匹配',
  fileTruncated: 'provider 文件在校验期间被截断',
  fileHashMismatch: 'provider 文件 hash 与声明不匹配',
  // console-pages.ts
  noPage: (pageId: string) => `没有这个 provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `provider ${pageId} 没有声明面板: ${panelId}`,
  postOnly: (panelId: string, method: string) => `面板 ${panelId} 的方法 ${method} 只允许 POST`,
  noPanelSurface: (pageId: string) => `provider ${pageId} 没有面板数据面`,
  noStreamSurface: (pageId: string) => `provider ${pageId} 没有流式面`,
  // path-picker.ts
  pickerNul: (name: string) => `${name} 不能含 NUL 字符`,
  pickerBadExtension: (value: string) => `不合法的文件后缀: ${value}`,
  pickerBodyNotObject: '请求体必须是对象',
  pickerBadKind: 'kind 必须是 file 或 directory',
  pickerBadExtensions: 'extensions 必须是字符串数组',
  pickerMissing: (path: string) => `选择的路径不存在: ${path}`,
  pickerNotFile: (path: string) => `选择的路径不是文件: ${path}`,
  pickerNotDirectory: (path: string) => `选择的路径不是目录: ${path}`,
  pickerWrongType: (extensions: string[]) => `文件类型应为 ${extensions.join(' / ')}`,
  pickerTitleFile: '选择文件',
  pickerTitleDirectory: '选择目录',
  pickerSupportedFiles: '支持的文件',
  pickerAllFiles: '所有文件',
  pickerNoPowerShell: '本机找不到 PowerShell，无法打开路径选择器',
  pickerNoOsascript: '本机找不到 osascript，无法打开路径选择器',
  pickerNoLinuxTool: '本机没有可用的路径选择器；请安装 zenity 或 kdialog',
  pickerFailed: (error: string) => `无法打开本机路径选择器: ${error}`,
  pickerUnsupported: (platform: string) => `当前平台不支持本机路径选择器: ${platform}`,
};
export const en: typeof zh = {
  paused: 'Paused: events are still stored and queued, no wake is delivered',
  resumed: 'Resumed: the backlog is delivered in one batch',
  exitShutdown: 'The process is about to exit',
  exitSupervised: 'The process is about to exit; the launcher will start it again',
  exitSupervisedPaused: 'The process is about to exit; the launcher will start it again with event delivery paused, so resume it in the run status',
  exitUnsupervised: 'The process is about to exit; no launcher loop was detected, so it must be started again by hand',
  shutdownSkipped: (n: number, labels: string[]) => `Local shutdown finished, but ${n} step${n === 1 ? '' : 's'} did not complete: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Local shutdown finished (${n === 1 ? '1 step completed' : `all ${n} steps completed`})`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status} (${detail}). Manual action: ${manualAction}`, '.'),
  externalVerified: '; every external state is confirmed ended',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: 'Run control is unavailable',
  shutdownUnavailable: 'Shutdown control is unavailable',
  restartUnavailable: 'Restart control is unavailable',
  hostRejected: 'Host not accepted',
  crossSiteRejected: 'Cross-site request rejected',
  wrongPassword: 'Wrong password',
  loginRequired: 'Sign-in required',
  avatarUnavailable: 'Avatar storage is unavailable',
  avatarNotPng: 'The avatar must be a valid PNG image',
  themeUnavailable: 'Theme record is unavailable',
  sessionsUnavailable: 'Session observation is unavailable',
  debugUnavailable: 'Debug channel is unavailable',
  onboardingUnavailable: 'Onboarding marker is unavailable',
  worldVisibilityUnavailable: 'World visibility switch is unavailable',
  worldActivationUnavailable: 'World activation switch is unavailable',
  worldRestartUnavailable: 'World restart is unavailable',
  extensionsUnavailable: 'Extension management is unavailable',
  extensionCheckUnavailable: 'Extension check is unavailable',
  promptsUnavailable: 'Prompt template editing is unavailable',
  prefixPreviewUnavailable: 'Prefix preview is unavailable',
  toolSchemasUnavailable: 'Tool schemas are unavailable',
  prefixReloadUnavailable: 'Session prefix reload is unavailable',
  configUnavailable: 'Setting declarations are unavailable',
  missingField: (name: string) => `Missing ${name}`,
  missingPackage: 'Missing package name',
  missingPackageOrPath: 'Missing package name or path',
  notBoolean: (name: string) => `${name} must be a boolean`,
  notString: (name: string) => `${name} must be a string`,
  badKind: (kind: string) => `kind must be world, provider or bot, got ${kind}`,
  argsNotJson: 'args is not valid JSON',
  argsNotArray: 'args must be a JSON array',
  noSession: (id: string) => `No such session: ${id}`,
  noStoragePart: (key: string) => `No such storage part: ${key}`,
  noStorageParts: 'The server has no storage list mounted',
  statFailed: (error: string) => `Stats failed: ${error}`,
  promptTooLarge: 'The prompt exceeds 1MB and was not saved',
  npmSearchFailed: (error: string) => `npm search failed: ${error}`,
  unknownConfigGroup: (id: string) => `Unknown setting group: ${id}`,
  streamFailed: (error: string) => `Stream surface failed: ${error}`,
  streamResolveFailed: (error: string) => `Stream resolution failed: ${error}`,
  fileNotAbsolute: 'The provider returned a file path that is not absolute',
  fileInvalid: 'The provider returned an invalid file descriptor',
  fileSizeMismatch: 'The provider file size does not match the declared size',
  fileTruncated: 'The provider file was truncated during verification',
  fileHashMismatch: 'The provider file hash does not match the declared hash',
  noPage: (pageId: string) => `No such provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `Provider ${pageId} declares no panel ${panelId}`,
  postOnly: (panelId: string, method: string) => `Method ${method} of panel ${panelId} only accepts POST`,
  noPanelSurface: (pageId: string) => `Provider ${pageId} has no panel data surface`,
  noStreamSurface: (pageId: string) => `Provider ${pageId} has no stream surface`,
  pickerNul: (name: string) => `${name} must not contain NUL characters`,
  pickerBadExtension: (value: string) => `Invalid file extension: ${value}`,
  pickerBodyNotObject: 'The request body must be an object',
  pickerBadKind: 'kind must be file or directory',
  pickerBadExtensions: 'extensions must be an array of strings',
  pickerMissing: (path: string) => `The chosen path does not exist: ${path}`,
  pickerNotFile: (path: string) => `The chosen path is not a file: ${path}`,
  pickerNotDirectory: (path: string) => `The chosen path is not a directory: ${path}`,
  pickerWrongType: (extensions: string[]) => `The file type must be ${extensions.join(' / ')}`,
  pickerTitleFile: 'Choose a file',
  pickerTitleDirectory: 'Choose a folder',
  pickerSupportedFiles: 'Supported files',
  pickerAllFiles: 'All files',
  pickerNoPowerShell: 'PowerShell was not found on this machine, so the path picker cannot open',
  pickerNoOsascript: 'osascript was not found on this machine, so the path picker cannot open',
  pickerNoLinuxTool: 'No path picker is available on this machine; install zenity or kdialog',
  pickerFailed: (error: string) => `Could not open the path picker on this machine: ${error}`,
  pickerUnsupported: (platform: string) => `This platform has no native path picker: ${platform}`,
};
export const serverText = (language: Language) => pick(language, {
  zh, en, 'zh-Hant': zhHant, ja, ko, fr, de, 'es-419': es419, 'pt-BR': ptBR, it, ru,
});
