import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: '一時停止しました：イベントは通常どおり保存されキューに入りますが、ウェイクは配信されません',
  resumed: '再開しました：滞留していたイベントをまとめて配信します',
  exitShutdown: 'プロセスはまもなく終了します',
  exitSupervised: 'プロセスはまもなく終了し、ランチャーがすぐに再起動します',
  exitSupervisedPaused: 'プロセスはまもなく終了し、ランチャーがすぐに再起動します。再起動後はイベント配信が一時停止しているため、実行状態から再開してください',
  exitUnsupervised: 'プロセスはまもなく終了します。ランチャーのループが検出されなかったため、手動で再起動する必要があります',
  shutdownSkipped: (n: number, labels: string[]) => `ローカルのシャットダウンは完了しましたが、${n} 個の手順が完了していません：${labels.join('、')}`,
  shutdownComplete: (n: number) => `ローカルのシャットダウンが完了しました（全 ${n} 手順が完了）`,
  externalUnverified: (items: string[]) => `。[P0] ${items.join('')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status}（${detail}）。手動対応：${manualAction}`, '。'),
  externalVerified: '。外部状態のチェックではすべて終了を確認しました',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '。')}${exit}`,
  runUnavailable: '実行制御を利用できません',
  shutdownUnavailable: 'シャットダウン制御を利用できません',
  restartUnavailable: '再起動制御を利用できません',
  hostRejected: 'この Host は受け付けられません',
  crossSiteRejected: 'クロスサイトリクエストを拒否しました',
  wrongPassword: 'パスワードが違います',
  loginRequired: 'ログインが必要です',
  avatarUnavailable: 'アバターの保存先を利用できません',
  avatarNotPng: 'アバターは有効な PNG 画像である必要があります',
  themeUnavailable: 'テーマの記録を利用できません',
  sessionsUnavailable: 'セッションの監視を利用できません',
  debugUnavailable: 'デバッグチャネルを利用できません',
  onboardingUnavailable: 'オンボーディングの記録を利用できません',
  worldVisibilityUnavailable: 'World の表示切り替えを利用できません',
  worldActivationUnavailable: 'World の有効化切り替えを利用できません',
  worldRestartUnavailable: 'World の再起動を利用できません',
  extensionsUnavailable: '拡張機能の管理を利用できません',
  extensionCheckUnavailable: '拡張機能のチェックを利用できません',
  promptsUnavailable: 'プロンプトテンプレートの編集を利用できません',
  prefixPreviewUnavailable: 'プレフィックスのプレビューを利用できません',
  toolSchemasUnavailable: 'ツールの schema を利用できません',
  prefixReloadUnavailable: 'セッションのプレフィックスの再読み込みを利用できません',
  configUnavailable: '設定項目の宣言を利用できません',
  missingField: (name: string) => `${name} がありません`,
  missingPackage: 'パッケージ名がありません',
  missingPackageOrPath: 'パッケージ名またはパスがありません',
  notBoolean: (name: string) => `${name} は真偽値である必要があります`,
  notString: (name: string) => `${name} は文字列である必要があります`,
  badKind: (kind: string) => `kind は world、provider、bot のいずれかである必要があります（現在は ${kind}）`,
  argsNotJson: 'args が有効な JSON ではありません',
  argsNotArray: 'args は JSON 配列である必要があります',
  noSession: (id: string) => `そのセッションはありません：${id}`,
  noStoragePart: (key: string) => `そのストレージ項目はありません：${key}`,
  noStorageParts: 'サーバーにストレージ一覧がマウントされていません',
  statFailed: (error: string) => `集計に失敗しました：${error}`,
  promptTooLarge: 'プロンプトが 1MB を超えているため保存しませんでした',
  npmSearchFailed: (error: string) => `npm の検索に失敗しました：${error}`,
  unknownConfigGroup: (id: string) => `不明な設定グループ：${id}`,
  streamFailed: (error: string) => `ストリームでエラーが発生しました：${error}`,
  streamResolveFailed: (error: string) => `ストリームの解決に失敗しました：${error}`,
  fileNotAbsolute: 'provider が絶対パスではないファイルパスを返しました',
  fileInvalid: 'provider が無効なファイル記述を返しました',
  fileSizeMismatch: 'provider のファイルサイズが宣言と一致しません',
  fileTruncated: 'provider のファイルが検証中に切り詰められました',
  fileHashMismatch: 'provider のファイルの hash が宣言と一致しません',
  noPage: (pageId: string) => `その provider はありません：${pageId}`,
  noPanel: (pageId: string, panelId: string) => `provider ${pageId} はパネル ${panelId} を宣言していません`,
  postOnly: (panelId: string, method: string) => `パネル ${panelId} のメソッド ${method} は POST のみ受け付けます`,
  noPanelSurface: (pageId: string) => `provider ${pageId} にはパネルのデータ面がありません`,
  noStreamSurface: (pageId: string) => `provider ${pageId} にはストリーム面がありません`,
  pickerNul: (name: string) => `${name} に NUL 文字を含めることはできません`,
  pickerBadExtension: (value: string) => `無効なファイル拡張子：${value}`,
  pickerBodyNotObject: 'リクエスト本文はオブジェクトである必要があります',
  pickerBadKind: 'kind は file または directory である必要があります',
  pickerBadExtensions: 'extensions は文字列の配列である必要があります',
  pickerMissing: (path: string) => `選択したパスが存在しません：${path}`,
  pickerNotFile: (path: string) => `選択したパスはファイルではありません：${path}`,
  pickerNotDirectory: (path: string) => `選択したパスはフォルダーではありません：${path}`,
  pickerWrongType: (extensions: string[]) => `ファイルの種類は ${extensions.join(' / ')} である必要があります`,
  pickerTitleFile: 'ファイルを選択',
  pickerTitleDirectory: 'フォルダーを選択',
  pickerSupportedFiles: '対応ファイル',
  pickerAllFiles: 'すべてのファイル',
  pickerNoPowerShell: 'このマシンに PowerShell が見つからないため、パス選択ダイアログを開けません',
  pickerNoOsascript: 'このマシンに osascript が見つからないため、パス選択ダイアログを開けません',
  pickerNoLinuxTool: 'このマシンで使えるパス選択ダイアログがありません。zenity または kdialog をインストールしてください',
  pickerFailed: (error: string) => `このマシンのパス選択ダイアログを開けませんでした：${error}`,
  pickerUnsupported: (platform: string) => `このプラットフォームにはネイティブのパス選択ダイアログがありません：${platform}`,
};
