import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: 'Pausado: os eventos continuam sendo armazenados e enfileirados, nenhum despertar é entregue',
  resumed: 'Retomado: os eventos acumulados são entregues em um único lote',
  exitShutdown: 'O processo vai encerrar',
  exitSupervised: 'O processo vai encerrar; o inicializador vai iniciá-lo de novo',
  exitSupervisedPaused: 'O processo vai encerrar; o inicializador vai iniciá-lo de novo com a entrega de eventos pausada, então retome-a no controle de execução',
  exitUnsupervised: 'O processo vai encerrar; nenhum loop de inicializador foi detectado, então é preciso iniciá-lo de novo manualmente',
  shutdownSkipped: (n: number, labels: string[]) =>
    `O desligamento local terminou, mas ${n === 1 ? '1 etapa não foi concluída' : `${n} etapas não foram concluídas`}: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Desligamento local concluído (${n === 1 ? '1 etapa concluída' : `todas as ${n} etapas concluídas`})`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status} (${detail}). Ação manual: ${manualAction}`, '.'),
  externalVerified: '; todas as verificações de estado externo confirmaram o encerramento',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: 'O controle de execução está indisponível',
  shutdownUnavailable: 'O controle de desligamento está indisponível',
  restartUnavailable: 'O controle de reinício está indisponível',
  hostRejected: 'Host não aceito',
  crossSiteRejected: 'Requisição entre sites recusada',
  wrongPassword: 'Senha incorreta',
  loginRequired: 'É preciso entrar',
  avatarUnavailable: 'O armazenamento do avatar está indisponível',
  avatarNotPng: 'O avatar precisa ser uma imagem PNG válida',
  themeUnavailable: 'O registro do tema está indisponível',
  sessionsUnavailable: 'A observação de sessões está indisponível',
  debugUnavailable: 'O canal de depuração está indisponível',
  onboardingUnavailable: 'A marca de boas-vindas está indisponível',
  worldVisibilityUnavailable: 'O controle de visibilidade do World está indisponível',
  worldActivationUnavailable: 'O controle de ativação do World está indisponível',
  worldRestartUnavailable: 'O reinício do World está indisponível',
  extensionsUnavailable: 'O gerenciamento de extensões está indisponível',
  extensionCheckUnavailable: 'A verificação de extensões está indisponível',
  promptsUnavailable: 'A edição de modelos de prompt está indisponível',
  prefixPreviewUnavailable: 'A prévia do prefixo está indisponível',
  toolSchemasUnavailable: 'Os schemas das ferramentas estão indisponíveis',
  prefixReloadUnavailable: 'O recarregamento do prefixo da sessão está indisponível',
  configUnavailable: 'As declarações de configuração estão indisponíveis',
  missingField: (name: string) => `Falta ${name}`,
  missingPackage: 'Falta o nome do pacote',
  missingPackageOrPath: 'Falta o nome do pacote ou o caminho',
  notBoolean: (name: string) => `${name} precisa ser um booleano`,
  notString: (name: string) => `${name} precisa ser uma string`,
  badKind: (kind: string) => `kind precisa ser world, provider ou bot; recebido: ${kind}`,
  argsNotJson: 'args não é um JSON válido',
  argsNotArray: 'args precisa ser um array JSON',
  noSession: (id: string) => `Sessão inexistente: ${id}`,
  noStoragePart: (key: string) => `Parte de armazenamento inexistente: ${key}`,
  noStorageParts: 'O servidor não tem uma lista de armazenamento montada',
  statFailed: (error: string) => `Falha na estatística: ${error}`,
  promptTooLarge: 'O prompt passa de 1MB e não foi salvo',
  npmSearchFailed: (error: string) => `Falha na busca do npm: ${error}`,
  unknownConfigGroup: (id: string) => `Grupo de configuração desconhecido: ${id}`,
  streamFailed: (error: string) => `Erro no stream: ${error}`,
  streamResolveFailed: (error: string) => `Falha ao resolver o stream: ${error}`,
  fileNotAbsolute: 'O provider retornou um caminho de arquivo que não é absoluto',
  fileInvalid: 'O provider retornou um descritor de arquivo inválido',
  fileSizeMismatch: 'O tamanho do arquivo do provider não corresponde ao declarado',
  fileTruncated: 'O arquivo do provider foi truncado durante a verificação',
  fileHashMismatch: 'O hash do arquivo do provider não corresponde ao declarado',
  noPage: (pageId: string) => `Provider inexistente: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `O provider ${pageId} não declara o painel ${panelId}`,
  postOnly: (panelId: string, method: string) => `O método ${method} do painel ${panelId} só aceita POST`,
  noPanelSurface: (pageId: string) => `O provider ${pageId} não tem superfície de dados de painel`,
  noStreamSurface: (pageId: string) => `O provider ${pageId} não tem superfície de stream`,
  pickerNul: (name: string) => `${name} não pode conter caracteres NUL`,
  pickerBadExtension: (value: string) => `Extensão de arquivo inválida: ${value}`,
  pickerBodyNotObject: 'O corpo da requisição precisa ser um objeto',
  pickerBadKind: 'kind precisa ser file ou directory',
  pickerBadExtensions: 'extensions precisa ser um array de strings',
  pickerMissing: (path: string) => `O caminho escolhido não existe: ${path}`,
  pickerNotFile: (path: string) => `O caminho escolhido não é um arquivo: ${path}`,
  pickerNotDirectory: (path: string) => `O caminho escolhido não é uma pasta: ${path}`,
  pickerWrongType: (extensions: string[]) => `O tipo de arquivo precisa ser ${extensions.join(' / ')}`,
  pickerTitleFile: 'Escolher um arquivo',
  pickerTitleDirectory: 'Escolher uma pasta',
  pickerSupportedFiles: 'Arquivos compatíveis',
  pickerAllFiles: 'Todos os arquivos',
  pickerNoPowerShell: 'O PowerShell não foi encontrado neste computador, então o seletor de caminho não pode abrir',
  pickerNoOsascript: 'O osascript não foi encontrado neste computador, então o seletor de caminho não pode abrir',
  pickerNoLinuxTool: 'Nenhum seletor de caminho disponível neste computador; instale o zenity ou o kdialog',
  pickerFailed: (error: string) => `Não foi possível abrir o seletor de caminho deste computador: ${error}`,
  pickerUnsupported: (platform: string) => `Esta plataforma não tem seletor de caminho nativo: ${platform}`,
};
