import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: "En pause : les événements sont toujours stockés et mis en file, aucun réveil n'est livré",
  resumed: "Repris : l'arriéré est livré en un seul lot",
  exitShutdown: 'Le processus va se terminer',
  exitSupervised: 'Le processus va se terminer ; le lanceur le redémarrera',
  exitSupervisedPaused: "Le processus va se terminer ; le lanceur le redémarrera avec la livraison des événements en pause, reprenez-la dans l'état d'exécution",
  exitUnsupervised: 'Le processus va se terminer ; aucune boucle de lanceur détectée, il faut le redémarrer à la main',
  shutdownSkipped: (n: number, labels: string[]) => `Arrêt local terminé, mais ${n} étape${n > 1 ? 's' : ''} non terminée${n > 1 ? 's' : ''} : ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Arrêt local terminé (${n} étape${n > 1 ? 's' : ''} sur ${n} terminée${n > 1 ? 's' : ''})`,
  externalUnverified: (items: string[]) => ` ; [P0] ${items.join(' ; ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    `${label}=${status} (${detail}). Action manuelle : ${manualAction}`,
  externalVerified: " ; chaque contrôle d'état externe a confirmé l'arrêt",
  powerReceipt: (local: string, external: string, exit: string) => `${local}${external}. ${exit}`,
  runUnavailable: "Le contrôle d'exécution est indisponible",
  shutdownUnavailable: "Le contrôle d'arrêt est indisponible",
  restartUnavailable: 'Le contrôle de redémarrage est indisponible',
  hostRejected: 'Host non accepté',
  crossSiteRejected: 'Requête intersite refusée',
  wrongPassword: 'Mot de passe incorrect',
  loginRequired: 'Connexion requise',
  avatarUnavailable: "Le stockage de l'avatar est indisponible",
  avatarNotPng: "L'avatar doit être une image PNG valide",
  themeUnavailable: "L'enregistrement du thème est indisponible",
  sessionsUnavailable: "L'observation des sessions est indisponible",
  debugUnavailable: 'Le canal de débogage est indisponible',
  onboardingUnavailable: "Le marqueur d'accueil est indisponible",
  worldVisibilityUnavailable: 'Le commutateur de visibilité du World est indisponible',
  worldActivationUnavailable: "Le commutateur d'activation du World est indisponible",
  worldRestartUnavailable: 'Le redémarrage du World est indisponible',
  extensionsUnavailable: 'La gestion des extensions est indisponible',
  extensionCheckUnavailable: 'La vérification des extensions est indisponible',
  promptsUnavailable: "L'édition des modèles de prompt est indisponible",
  prefixPreviewUnavailable: "L'aperçu du préfixe est indisponible",
  toolSchemasUnavailable: 'Les schémas des outils sont indisponibles',
  prefixReloadUnavailable: 'Le rechargement du préfixe de session est indisponible',
  configUnavailable: 'Les déclarations de réglages sont indisponibles',
  missingField: (name: string) => `${name} manquant`,
  missingPackage: 'Nom de paquet manquant',
  missingPackageOrPath: 'Nom de paquet ou chemin manquant',
  notBoolean: (name: string) => `${name} doit être un booléen`,
  notString: (name: string) => `${name} doit être une chaîne`,
  badKind: (kind: string) => `kind doit être world, provider ou bot, reçu : ${kind}`,
  argsNotJson: "args n'est pas un JSON valide",
  argsNotArray: 'args doit être un tableau JSON',
  noSession: (id: string) => `Session introuvable : ${id}`,
  noStoragePart: (key: string) => `Partie de stockage introuvable : ${key}`,
  noStorageParts: "Le serveur n'a pas de liste de stockage montée",
  statFailed: (error: string) => `Échec des statistiques : ${error}`,
  promptTooLarge: "Le prompt dépasse 1MB et n'a pas été enregistré",
  npmSearchFailed: (error: string) => `Échec de la recherche npm : ${error}`,
  unknownConfigGroup: (id: string) => `Groupe de réglages inconnu : ${id}`,
  streamFailed: (error: string) => `Erreur du flux : ${error}`,
  streamResolveFailed: (error: string) => `Échec de la résolution du flux : ${error}`,
  fileNotAbsolute: "Le provider a renvoyé un chemin de fichier qui n'est pas absolu",
  fileInvalid: 'Le provider a renvoyé un descripteur de fichier invalide',
  fileSizeMismatch: 'La taille du fichier du provider ne correspond pas à la taille déclarée',
  fileTruncated: 'Le fichier du provider a été tronqué pendant la vérification',
  fileHashMismatch: 'Le hash du fichier du provider ne correspond pas au hash déclaré',
  noPage: (pageId: string) => `Provider introuvable : ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `Le provider ${pageId} ne déclare pas le panneau ${panelId}`,
  postOnly: (panelId: string, method: string) => `La méthode ${method} du panneau ${panelId} n'accepte que POST`,
  noPanelSurface: (pageId: string) => `Le provider ${pageId} n'a pas de surface de données de panneau`,
  noStreamSurface: (pageId: string) => `Le provider ${pageId} n'a pas de surface de flux`,
  pickerNul: (name: string) => `${name} ne doit pas contenir de caractère NUL`,
  pickerBadExtension: (value: string) => `Extension de fichier invalide : ${value}`,
  pickerBodyNotObject: 'Le corps de la requête doit être un objet',
  pickerBadKind: 'kind doit être file ou directory',
  pickerBadExtensions: 'extensions doit être un tableau de chaînes',
  pickerMissing: (path: string) => `Le chemin choisi n'existe pas : ${path}`,
  pickerNotFile: (path: string) => `Le chemin choisi n'est pas un fichier : ${path}`,
  pickerNotDirectory: (path: string) => `Le chemin choisi n'est pas un dossier : ${path}`,
  pickerWrongType: (extensions: string[]) => `Le type de fichier doit être ${extensions.join(' / ')}`,
  pickerTitleFile: 'Choisir un fichier',
  pickerTitleDirectory: 'Choisir un dossier',
  pickerSupportedFiles: 'Fichiers pris en charge',
  pickerAllFiles: 'Tous les fichiers',
  pickerNoPowerShell: "PowerShell est introuvable sur cette machine, le sélecteur de chemin ne peut pas s'ouvrir",
  pickerNoOsascript: "osascript est introuvable sur cette machine, le sélecteur de chemin ne peut pas s'ouvrir",
  pickerNoLinuxTool: 'Aucun sélecteur de chemin disponible sur cette machine ; installez zenity ou kdialog',
  pickerFailed: (error: string) => `Impossible d'ouvrir le sélecteur de chemin de cette machine : ${error}`,
  pickerUnsupported: (platform: string) => `Cette plateforme n'a pas de sélecteur de chemin natif : ${platform}`,
};
