import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

const pluralRules = new Intl.PluralRules('ru');
const plural = (n: number, one: string, few: string, many: string) => {
  const form = pluralRules.select(n);
  return form === 'one' ? one : form === 'many' ? many : few;
};

export const serverText: Partial<typeof en> = {
  paused: 'Приостановлено: события по-прежнему сохраняются и ставятся в очередь, пробуждения не доставляются',
  resumed: 'Возобновлено: накопленные события доставляются одним пакетом',
  exitShutdown: 'Процесс сейчас завершится',
  exitSupervised: 'Процесс сейчас завершится; лаунчер запустит его снова',
  exitSupervisedPaused: 'Процесс сейчас завершится; лаунчер запустит его снова с приостановленной доставкой событий, поэтому возобновите её в управлении запуском',
  exitUnsupervised: 'Процесс сейчас завершится; цикл лаунчера не обнаружен, поэтому его нужно запустить снова вручную',
  shutdownSkipped: (n: number, labels: string[]) =>
    `Локальное выключение завершено, но ${n} ${plural(n, 'шаг не выполнен', 'шага не выполнены', 'шагов не выполнено')}: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Локальное выключение завершено (выполнены все шаги: ${n})`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status} (${detail}). Ручное действие: ${manualAction}`, '.'),
  externalVerified: '; все проверки внешнего состояния подтвердили завершение',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: 'Управление запуском недоступно',
  shutdownUnavailable: 'Управление выключением недоступно',
  restartUnavailable: 'Управление перезапуском недоступно',
  hostRejected: 'Host не принят',
  crossSiteRejected: 'Межсайтовый запрос отклонён',
  wrongPassword: 'Неверный пароль',
  loginRequired: 'Требуется вход',
  avatarUnavailable: 'Хранилище аватара недоступно',
  avatarNotPng: 'Аватар должен быть корректным изображением PNG',
  themeUnavailable: 'Запись темы недоступна',
  sessionsUnavailable: 'Наблюдение за сессиями недоступно',
  debugUnavailable: 'Отладочный канал недоступен',
  onboardingUnavailable: 'Отметка вводного знакомства недоступна',
  worldVisibilityUnavailable: 'Переключатель видимости World недоступен',
  worldActivationUnavailable: 'Переключатель активации World недоступен',
  worldRestartUnavailable: 'Перезапуск World недоступен',
  extensionsUnavailable: 'Управление расширениями недоступно',
  extensionCheckUnavailable: 'Проверка расширений недоступна',
  promptsUnavailable: 'Редактирование шаблонов промптов недоступно',
  prefixPreviewUnavailable: 'Предпросмотр префикса недоступен',
  toolSchemasUnavailable: 'Схемы инструментов недоступны',
  prefixReloadUnavailable: 'Перезагрузка префикса сессии недоступна',
  configUnavailable: 'Объявления настроек недоступны',
  missingField: (name: string) => `Не указано: ${name}`,
  missingPackage: 'Не указано имя пакета',
  missingPackageOrPath: 'Не указано имя пакета или путь',
  notBoolean: (name: string) => `${name} должен быть булевым значением`,
  notString: (name: string) => `${name} должен быть строкой`,
  badKind: (kind: string) => `kind должен быть world, provider или bot, получено: ${kind}`,
  argsNotJson: 'args не является корректным JSON',
  argsNotArray: 'args должен быть массивом JSON',
  noSession: (id: string) => `Нет такой сессии: ${id}`,
  noStoragePart: (key: string) => `Нет такой части хранилища: ${key}`,
  noStorageParts: 'На сервере не подключён список хранилища',
  statFailed: (error: string) => `Не удалось получить статистику: ${error}`,
  promptTooLarge: 'Промпт больше 1MB и не сохранён',
  npmSearchFailed: (error: string) => `Поиск в npm не удался: ${error}`,
  unknownConfigGroup: (id: string) => `Неизвестная группа настроек: ${id}`,
  streamFailed: (error: string) => `Ошибка потока: ${error}`,
  streamResolveFailed: (error: string) => `Не удалось разрешить поток: ${error}`,
  fileNotAbsolute: 'Provider вернул неабсолютный путь к файлу',
  fileInvalid: 'Provider вернул некорректное описание файла',
  fileSizeMismatch: 'Размер файла provider не совпадает с объявленным',
  fileTruncated: 'Файл provider был обрезан во время проверки',
  fileHashMismatch: 'Hash файла provider не совпадает с объявленным',
  noPage: (pageId: string) => `Нет такого provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `Provider ${pageId} не объявляет панель ${panelId}`,
  postOnly: (panelId: string, method: string) => `Метод ${method} панели ${panelId} принимает только POST`,
  noPanelSurface: (pageId: string) => `У provider ${pageId} нет поверхности данных панели`,
  noStreamSurface: (pageId: string) => `У provider ${pageId} нет поверхности потока`,
  pickerNul: (name: string) => `${name} не должен содержать символы NUL`,
  pickerBadExtension: (value: string) => `Недопустимое расширение файла: ${value}`,
  pickerBodyNotObject: 'Тело запроса должно быть объектом',
  pickerBadKind: 'kind должен быть file или directory',
  pickerBadExtensions: 'extensions должен быть массивом строк',
  pickerMissing: (path: string) => `Выбранный путь не существует: ${path}`,
  pickerNotFile: (path: string) => `Выбранный путь не является файлом: ${path}`,
  pickerNotDirectory: (path: string) => `Выбранный путь не является папкой: ${path}`,
  pickerWrongType: (extensions: string[]) => `Тип файла должен быть ${extensions.join(' / ')}`,
  pickerTitleFile: 'Выберите файл',
  pickerTitleDirectory: 'Выберите папку',
  pickerSupportedFiles: 'Поддерживаемые файлы',
  pickerAllFiles: 'Все файлы',
  pickerNoPowerShell: 'На этом компьютере не найден PowerShell, поэтому окно выбора пути не открыть',
  pickerNoOsascript: 'На этом компьютере не найден osascript, поэтому окно выбора пути не открыть',
  pickerNoLinuxTool: 'На этом компьютере нет доступного окна выбора пути; установите zenity или kdialog',
  pickerFailed: (error: string) => `Не удалось открыть окно выбора пути на этом компьютере: ${error}`,
  pickerUnsupported: (platform: string) => `На этой платформе нет системного окна выбора пути: ${platform}`,
};
