import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: 'Pausiert: Ereignisse werden weiter gespeichert und eingereiht, es wird kein Wecken zugestellt',
  resumed: 'Fortgesetzt: Der Rückstau wird in einem Batch zugestellt',
  exitShutdown: 'Der Prozess wird gleich beendet',
  exitSupervised: 'Der Prozess wird gleich beendet; der Launcher startet ihn neu',
  exitSupervisedPaused: 'Der Prozess wird gleich beendet; der Launcher startet ihn mit pausierter Ereigniszustellung neu, setze sie im Laufstatus fort',
  exitUnsupervised: 'Der Prozess wird gleich beendet; keine Launcher-Schleife erkannt, daher muss er manuell neu gestartet werden',
  shutdownSkipped: (n: number, labels: string[]) => `Lokales Herunterfahren beendet, aber ${n} ${n === 1 ? 'Schritt wurde' : 'Schritte wurden'} nicht abgeschlossen: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Lokales Herunterfahren beendet (${n === 1 ? '1 Schritt' : `alle ${n} Schritte`} abgeschlossen)`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status} (${detail}). Manuelle Aktion: ${manualAction}`, '.'),
  externalVerified: '; alle externen Zustandsprüfungen haben das Ende bestätigt',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: 'Laufsteuerung nicht verfügbar',
  shutdownUnavailable: 'Steuerung zum Herunterfahren nicht verfügbar',
  restartUnavailable: 'Neustart-Steuerung nicht verfügbar',
  hostRejected: 'Host nicht akzeptiert',
  crossSiteRejected: 'Websiteübergreifende Anfrage abgelehnt',
  wrongPassword: 'Falsches Passwort',
  loginRequired: 'Anmeldung erforderlich',
  avatarUnavailable: 'Avatar-Speicher nicht verfügbar',
  avatarNotPng: 'Der Avatar muss ein gültiges PNG-Bild sein',
  themeUnavailable: 'Theme-Datensatz nicht verfügbar',
  sessionsUnavailable: 'Session-Beobachtung nicht verfügbar',
  debugUnavailable: 'Debug-Kanal nicht verfügbar',
  onboardingUnavailable: 'Onboarding-Markierung nicht verfügbar',
  worldVisibilityUnavailable: 'Sichtbarkeitsschalter für World nicht verfügbar',
  worldActivationUnavailable: 'Aktivierungsschalter für World nicht verfügbar',
  worldRestartUnavailable: 'World-Neustart nicht verfügbar',
  extensionsUnavailable: 'Erweiterungsverwaltung nicht verfügbar',
  extensionCheckUnavailable: 'Erweiterungsprüfung nicht verfügbar',
  promptsUnavailable: 'Bearbeiten der Prompt-Vorlagen nicht verfügbar',
  prefixPreviewUnavailable: 'Präfix-Vorschau nicht verfügbar',
  toolSchemasUnavailable: 'Tool-Schemas nicht verfügbar',
  prefixReloadUnavailable: 'Neuladen des Session-Präfixes nicht verfügbar',
  configUnavailable: 'Einstellungsdeklarationen nicht verfügbar',
  missingField: (name: string) => `${name} fehlt`,
  missingPackage: 'Paketname fehlt',
  missingPackageOrPath: 'Paketname oder Pfad fehlt',
  notBoolean: (name: string) => `${name} muss ein Boolean sein`,
  notString: (name: string) => `${name} muss ein String sein`,
  badKind: (kind: string) => `kind muss world, provider oder bot sein, ist aber ${kind}`,
  argsNotJson: 'args ist kein gültiges JSON',
  argsNotArray: 'args muss ein JSON-Array sein',
  noSession: (id: string) => `Keine solche Session: ${id}`,
  noStoragePart: (key: string) => `Kein solcher Speicherteil: ${key}`,
  noStorageParts: 'Auf dem Server ist keine Speicherliste eingebunden',
  statFailed: (error: string) => `Statistik fehlgeschlagen: ${error}`,
  promptTooLarge: 'Der Prompt ist größer als 1MB und wurde nicht gespeichert',
  npmSearchFailed: (error: string) => `npm-Suche fehlgeschlagen: ${error}`,
  unknownConfigGroup: (id: string) => `Unbekannte Einstellungsgruppe: ${id}`,
  streamFailed: (error: string) => `Fehler im Stream: ${error}`,
  streamResolveFailed: (error: string) => `Stream konnte nicht aufgelöst werden: ${error}`,
  fileNotAbsolute: 'Der Provider hat einen nicht absoluten Dateipfad zurückgegeben',
  fileInvalid: 'Der Provider hat eine ungültige Dateibeschreibung zurückgegeben',
  fileSizeMismatch: 'Die Dateigröße des Providers stimmt nicht mit der Angabe überein',
  fileTruncated: 'Die Datei des Providers wurde während der Prüfung gekürzt',
  fileHashMismatch: 'Der Hash der Provider-Datei stimmt nicht mit der Angabe überein',
  noPage: (pageId: string) => `Kein solcher Provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `Provider ${pageId} deklariert kein Panel ${panelId}`,
  postOnly: (panelId: string, method: string) => `Methode ${method} von Panel ${panelId} akzeptiert nur POST`,
  noPanelSurface: (pageId: string) => `Provider ${pageId} hat keine Panel-Datenschnittstelle`,
  noStreamSurface: (pageId: string) => `Provider ${pageId} hat keine Stream-Schnittstelle`,
  pickerNul: (name: string) => `${name} darf keine NUL-Zeichen enthalten`,
  pickerBadExtension: (value: string) => `Ungültige Dateiendung: ${value}`,
  pickerBodyNotObject: 'Der Request-Body muss ein Objekt sein',
  pickerBadKind: 'kind muss file oder directory sein',
  pickerBadExtensions: 'extensions muss ein Array aus Strings sein',
  pickerMissing: (path: string) => `Der gewählte Pfad existiert nicht: ${path}`,
  pickerNotFile: (path: string) => `Der gewählte Pfad ist keine Datei: ${path}`,
  pickerNotDirectory: (path: string) => `Der gewählte Pfad ist kein Ordner: ${path}`,
  pickerWrongType: (extensions: string[]) => `Der Dateityp muss ${extensions.join(' / ')} sein`,
  pickerTitleFile: 'Datei auswählen',
  pickerTitleDirectory: 'Ordner auswählen',
  pickerSupportedFiles: 'Unterstützte Dateien',
  pickerAllFiles: 'Alle Dateien',
  pickerNoPowerShell: 'PowerShell wurde auf diesem Rechner nicht gefunden, daher kann die Pfadauswahl nicht geöffnet werden',
  pickerNoOsascript: 'osascript wurde auf diesem Rechner nicht gefunden, daher kann die Pfadauswahl nicht geöffnet werden',
  pickerNoLinuxTool: 'Auf diesem Rechner ist keine Pfadauswahl verfügbar; installiere zenity oder kdialog',
  pickerFailed: (error: string) => `Die Pfadauswahl auf diesem Rechner konnte nicht geöffnet werden: ${error}`,
  pickerUnsupported: (platform: string) => `Diese Plattform hat keine native Pfadauswahl: ${platform}`,
};
