import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: 'En pausa: los eventos se siguen guardando y encolando, no se entrega ningún despertar',
  resumed: 'Reanudado: los eventos acumulados se entregan en un solo lote',
  exitShutdown: 'El proceso está por salir',
  exitSupervised: 'El proceso está por salir; el lanzador lo volverá a iniciar',
  exitSupervisedPaused: 'El proceso está por salir; el lanzador lo volverá a iniciar con la entrega de eventos en pausa, así que reanúdala desde el control de ejecución',
  exitUnsupervised: 'El proceso está por salir; no se detectó un ciclo de lanzador, así que hay que volver a iniciarlo manualmente',
  shutdownSkipped: (n: number, labels: string[]) =>
    `El apagado local terminó, pero ${n === 1 ? '1 paso no se completó' : `${n} pasos no se completaron`}: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Apagado local terminado (se completaron los ${n} pasos)`,
  externalUnverified: (items: string[]) => `; [P0] ${items.join('; ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    `${label}=${status} (${detail}). Acción manual: ${manualAction}`,
  externalVerified: '; todas las comprobaciones de estado externo confirmaron el cierre',
  powerReceipt: (local: string, external: string, exit: string) => `${local}${external}. ${exit}`,
  runUnavailable: 'El control de ejecución no está disponible',
  shutdownUnavailable: 'El control de apagado no está disponible',
  restartUnavailable: 'El control de reinicio no está disponible',
  hostRejected: 'Host no aceptado',
  crossSiteRejected: 'Solicitud entre sitios rechazada',
  wrongPassword: 'Contraseña incorrecta',
  loginRequired: 'Se requiere iniciar sesión',
  avatarUnavailable: 'El almacenamiento del avatar no está disponible',
  avatarNotPng: 'El avatar debe ser una imagen PNG válida',
  themeUnavailable: 'El registro del tema no está disponible',
  sessionsUnavailable: 'La observación de sesiones no está disponible',
  debugUnavailable: 'El canal de depuración no está disponible',
  onboardingUnavailable: 'La marca de bienvenida no está disponible',
  worldVisibilityUnavailable: 'El interruptor de visibilidad del World no está disponible',
  worldActivationUnavailable: 'El interruptor de activación del World no está disponible',
  worldRestartUnavailable: 'El reinicio del World no está disponible',
  extensionsUnavailable: 'La administración de extensiones no está disponible',
  extensionCheckUnavailable: 'La verificación de extensiones no está disponible',
  promptsUnavailable: 'La edición de plantillas de prompt no está disponible',
  prefixPreviewUnavailable: 'La vista previa del prefijo no está disponible',
  toolSchemasUnavailable: 'Los schemas de herramientas no están disponibles',
  prefixReloadUnavailable: 'La recarga del prefijo de sesión no está disponible',
  configUnavailable: 'Las declaraciones de configuración no están disponibles',
  missingField: (name: string) => `Falta ${name}`,
  missingPackage: 'Falta el nombre del paquete',
  missingPackageOrPath: 'Falta el nombre del paquete o la ruta',
  notBoolean: (name: string) => `${name} debe ser un booleano`,
  notString: (name: string) => `${name} debe ser una cadena`,
  badKind: (kind: string) => `kind debe ser world, provider o bot; se recibió ${kind}`,
  argsNotJson: 'args no es un JSON válido',
  argsNotArray: 'args debe ser un arreglo JSON',
  noSession: (id: string) => `No existe esa sesión: ${id}`,
  noStoragePart: (key: string) => `No existe esa parte del almacenamiento: ${key}`,
  noStorageParts: 'El servidor no tiene montada una lista de almacenamiento',
  statFailed: (error: string) => `Falló la estadística: ${error}`,
  promptTooLarge: 'El prompt supera 1MB y no se guardó',
  npmSearchFailed: (error: string) => `Falló la búsqueda en npm: ${error}`,
  unknownConfigGroup: (id: string) => `Grupo de configuración desconocido: ${id}`,
  streamFailed: (error: string) => `Error en el stream: ${error}`,
  streamResolveFailed: (error: string) => `No se pudo resolver el stream: ${error}`,
  fileNotAbsolute: 'El provider devolvió una ruta de archivo que no es absoluta',
  fileInvalid: 'El provider devolvió un descriptor de archivo inválido',
  fileSizeMismatch: 'El tamaño del archivo del provider no coincide con el declarado',
  fileTruncated: 'El archivo del provider se truncó durante la verificación',
  fileHashMismatch: 'El hash del archivo del provider no coincide con el declarado',
  noPage: (pageId: string) => `No existe ese provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `El provider ${pageId} no declara el panel ${panelId}`,
  postOnly: (panelId: string, method: string) => `El método ${method} del panel ${panelId} solo acepta POST`,
  noPanelSurface: (pageId: string) => `El provider ${pageId} no tiene superficie de datos de panel`,
  noStreamSurface: (pageId: string) => `El provider ${pageId} no tiene superficie de stream`,
  pickerNul: (name: string) => `${name} no puede contener caracteres NUL`,
  pickerBadExtension: (value: string) => `Extensión de archivo inválida: ${value}`,
  pickerBodyNotObject: 'El cuerpo de la solicitud debe ser un objeto',
  pickerBadKind: 'kind debe ser file o directory',
  pickerBadExtensions: 'extensions debe ser un arreglo de cadenas',
  pickerMissing: (path: string) => `La ruta elegida no existe: ${path}`,
  pickerNotFile: (path: string) => `La ruta elegida no es un archivo: ${path}`,
  pickerNotDirectory: (path: string) => `La ruta elegida no es una carpeta: ${path}`,
  pickerWrongType: (extensions: string[]) => `El tipo de archivo debe ser ${extensions.join(' / ')}`,
  pickerTitleFile: 'Elegir un archivo',
  pickerTitleDirectory: 'Elegir una carpeta',
  pickerSupportedFiles: 'Archivos compatibles',
  pickerAllFiles: 'Todos los archivos',
  pickerNoPowerShell: 'No se encontró PowerShell en esta computadora, así que el selector de rutas no puede abrirse',
  pickerNoOsascript: 'No se encontró osascript en esta computadora, así que el selector de rutas no puede abrirse',
  pickerNoLinuxTool: 'No hay ningún selector de rutas disponible en esta computadora; instala zenity o kdialog',
  pickerFailed: (error: string) => `No se pudo abrir el selector de rutas de esta computadora: ${error}`,
  pickerUnsupported: (platform: string) => `Esta plataforma no tiene un selector de rutas nativo: ${platform}`,
};
