import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: '已暫停:事件照常寫入資料庫排隊,不投遞喚醒',
  resumed: '已繼續:積壓事件一次性投遞',
  exitShutdown: '處理程序即將結束',
  exitSupervised: '處理程序即將結束,啟動器隨即重新啟動',
  exitSupervisedPaused: '處理程序即將結束,啟動器隨即重新啟動;回來時事件投遞是暫停的,要在執行狀態裡按繼續',
  exitUnsupervised: '處理程序即將結束;沒有偵測到啟動器迴圈,需要手動重新啟動',
  shutdownSkipped: (n: number, labels: string[]) => `本機關機完成,但有 ${n} 步沒走完:${labels.join('、')}`,
  shutdownComplete: (n: number) => `本機關機完成(${n === 1 ? '1 步已走完' : `${n} 步全部走完`})`,
  externalUnverified: (items: string[]) => `。[P0] ${items.join('')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status}（${detail}）。人工處理:${manualAction}`, '。'),
  externalVerified: '；外部狀態均已確認結束',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '，')}${exit}`,
  runUnavailable: '執行控制無法使用',
  shutdownUnavailable: '關機控制無法使用',
  restartUnavailable: '重新啟動控制無法使用',
  hostRejected: '不接受這個 Host',
  crossSiteRejected: '已拒絕跨站請求',
  wrongPassword: '密碼不對',
  loginRequired: '需要登入',
  avatarUnavailable: '頭像儲存無法使用',
  avatarNotPng: '頭像必須是有效的 PNG 圖片',
  themeUnavailable: '主題記錄無法使用',
  sessionsUnavailable: 'session 觀察無法使用',
  debugUnavailable: '除錯通道無法使用',
  onboardingUnavailable: '開場引導標記無法使用',
  worldVisibilityUnavailable: 'World 可見性開關無法使用',
  worldActivationUnavailable: 'World 啟用開關無法使用',
  worldRestartUnavailable: 'World 重新啟動無法使用',
  extensionsUnavailable: '擴充功能管理無法使用',
  extensionCheckUnavailable: '擴充功能檢查無法使用',
  promptsUnavailable: '提示詞範本編輯無法使用',
  prefixPreviewUnavailable: '前綴預覽無法使用',
  toolSchemasUnavailable: '工具 schema 無法使用',
  prefixReloadUnavailable: 'session 前綴重新載入無法使用',
  configUnavailable: '設定項目宣告無法使用',
  missingField: (name: string) => `缺少 ${name}`,
  missingPackage: '缺少套件名稱',
  missingPackageOrPath: '缺少套件名稱或路徑',
  notBoolean: (name: string) => `${name} 必須是布林值`,
  notString: (name: string) => `${name} 必須是字串`,
  badKind: (kind: string) => `kind 只能是 world、provider 或 bot，目前是 ${kind}`,
  argsNotJson: 'args 不是有效的 JSON',
  argsNotArray: 'args 必須是 JSON 陣列',
  noSession: (id: string) => `沒有這個 session: ${id}`,
  noStoragePart: (key: string) => `沒有這個儲存部分: ${key}`,
  noStorageParts: '伺服器端未掛載儲存清單',
  statFailed: (error: string) => `統計失敗: ${error}`,
  promptTooLarge: '提示詞超過 1MB，拒絕儲存',
  npmSearchFailed: (error: string) => `npm 搜尋失敗: ${error}`,
  unknownConfigGroup: (id: string) => `未知的設定組: ${id}`,
  streamFailed: (error: string) => `串流面出錯: ${error}`,
  streamResolveFailed: (error: string) => `串流解析失敗: ${error}`,
  fileNotAbsolute: 'provider 回傳了非絕對檔案路徑',
  fileInvalid: 'provider 回傳了無效的檔案描述',
  fileSizeMismatch: 'provider 檔案大小與宣告不符',
  fileTruncated: 'provider 檔案在驗證期間被截斷',
  fileHashMismatch: 'provider 檔案 hash 與宣告不符',
  noPage: (pageId: string) => `沒有這個 provider: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `provider ${pageId} 沒有宣告面板: ${panelId}`,
  postOnly: (panelId: string, method: string) => `面板 ${panelId} 的方法 ${method} 只允許 POST`,
  noPanelSurface: (pageId: string) => `provider ${pageId} 沒有面板資料面`,
  noStreamSurface: (pageId: string) => `provider ${pageId} 沒有串流面`,
  pickerNul: (name: string) => `${name} 不能含 NUL 字元`,
  pickerBadExtension: (value: string) => `不合法的副檔名: ${value}`,
  pickerBodyNotObject: '請求本文必須是物件',
  pickerBadKind: 'kind 必須是 file 或 directory',
  pickerBadExtensions: 'extensions 必須是字串陣列',
  pickerMissing: (path: string) => `選擇的路徑不存在: ${path}`,
  pickerNotFile: (path: string) => `選擇的路徑不是檔案: ${path}`,
  pickerNotDirectory: (path: string) => `選擇的路徑不是資料夾: ${path}`,
  pickerWrongType: (extensions: string[]) => `檔案類型應為 ${extensions.join(' / ')}`,
  pickerTitleFile: '選擇檔案',
  pickerTitleDirectory: '選擇資料夾',
  pickerSupportedFiles: '支援的檔案',
  pickerAllFiles: '所有檔案',
  pickerNoPowerShell: '本機找不到 PowerShell，無法開啟路徑選擇器',
  pickerNoOsascript: '本機找不到 osascript，無法開啟路徑選擇器',
  pickerNoLinuxTool: '本機沒有可用的路徑選擇器；請安裝 zenity 或 kdialog',
  pickerFailed: (error: string) => `無法開啟本機路徑選擇器: ${error}`,
  pickerUnsupported: (platform: string) => `目前平台不支援本機路徑選擇器: ${platform}`,
};
