import { punctuate } from '../core/language.ts';
import type { en } from './strings.ts';

export const serverText: Partial<typeof en> = {
  paused: 'In pausa: gli eventi vengono ancora archiviati e accodati, nessun risveglio viene consegnato',
  resumed: 'Ripreso: gli eventi arretrati vengono consegnati in un unico batch',
  exitShutdown: 'Il processo sta per terminare',
  exitSupervised: 'Il processo sta per terminare; il launcher lo riavvierà',
  exitSupervisedPaused: 'Il processo sta per terminare; il launcher lo riavvierà con la consegna degli eventi in pausa, riprendila nello stato di esecuzione',
  exitUnsupervised: 'Il processo sta per terminare; nessun ciclo del launcher rilevato, quindi va riavviato a mano',
  shutdownSkipped: (n: number, labels: string[]) => `Arresto locale terminato, ma ${n} ${n === 1 ? 'passaggio non è stato completato' : 'passaggi non sono stati completati'}: ${labels.join(', ')}`,
  shutdownComplete: (n: number) => `Arresto locale terminato (${n === 1 ? '1 passaggio completato' : `tutti i ${n} passaggi completati`})`,
  externalUnverified: (items: string[]) => `. [P0] ${items.join(' ')}`,
  externalItem: (label: string, status: string, detail: string, manualAction: string) =>
    punctuate(`${label}=${status} (${detail}). Azione manuale: ${manualAction}`, '.'),
  externalVerified: '; tutti i controlli dello stato esterno hanno confermato la fine',
  powerReceipt: (local: string, external: string, exit: string) => `${punctuate(local + external, '.')} ${exit}`,
  runUnavailable: "Il controllo dell'esecuzione non è disponibile",
  shutdownUnavailable: "Il controllo dell'arresto non è disponibile",
  restartUnavailable: 'Il controllo del riavvio non è disponibile',
  hostRejected: 'Host non accettato',
  crossSiteRejected: 'Richiesta cross-site rifiutata',
  wrongPassword: 'Password errata',
  loginRequired: 'Accesso richiesto',
  avatarUnavailable: "L'archiviazione dell'avatar non è disponibile",
  avatarNotPng: "L'avatar deve essere un'immagine PNG valida",
  themeUnavailable: 'Il record del tema non è disponibile',
  sessionsUnavailable: "L'osservazione delle sessioni non è disponibile",
  debugUnavailable: 'Il canale di debug non è disponibile',
  onboardingUnavailable: "L'indicatore di benvenuto non è disponibile",
  worldVisibilityUnavailable: 'Il selettore di visibilità del World non è disponibile',
  worldActivationUnavailable: 'Il selettore di attivazione del World non è disponibile',
  worldRestartUnavailable: 'Il riavvio del World non è disponibile',
  extensionsUnavailable: 'La gestione delle estensioni non è disponibile',
  extensionCheckUnavailable: 'Il controllo delle estensioni non è disponibile',
  promptsUnavailable: 'La modifica dei template di prompt non è disponibile',
  prefixPreviewUnavailable: "L'anteprima del prefisso non è disponibile",
  toolSchemasUnavailable: 'Gli schema degli strumenti non sono disponibili',
  prefixReloadUnavailable: 'Il ricaricamento del prefisso della sessione non è disponibile',
  configUnavailable: 'Le dichiarazioni delle impostazioni non sono disponibili',
  missingField: (name: string) => `Manca ${name}`,
  missingPackage: 'Manca il nome del pacchetto',
  missingPackageOrPath: 'Manca il nome del pacchetto o il percorso',
  notBoolean: (name: string) => `${name} deve essere un booleano`,
  notString: (name: string) => `${name} deve essere una stringa`,
  badKind: (kind: string) => `kind deve essere world, provider o bot, ricevuto ${kind}`,
  argsNotJson: 'args non è un JSON valido',
  argsNotArray: 'args deve essere un array JSON',
  noSession: (id: string) => `Sessione inesistente: ${id}`,
  noStoragePart: (key: string) => `Parte di archiviazione inesistente: ${key}`,
  noStorageParts: 'Il server non ha un elenco di archiviazione montato',
  statFailed: (error: string) => `Statistiche non riuscite: ${error}`,
  promptTooLarge: 'Il prompt supera 1MB e non è stato salvato',
  npmSearchFailed: (error: string) => `Ricerca npm non riuscita: ${error}`,
  unknownConfigGroup: (id: string) => `Gruppo di impostazioni sconosciuto: ${id}`,
  streamFailed: (error: string) => `Errore nello stream: ${error}`,
  streamResolveFailed: (error: string) => `Risoluzione dello stream non riuscita: ${error}`,
  fileNotAbsolute: 'Il provider ha restituito un percorso di file non assoluto',
  fileInvalid: 'Il provider ha restituito un descrittore di file non valido',
  fileSizeMismatch: 'La dimensione del file del provider non corrisponde a quella dichiarata',
  fileTruncated: 'Il file del provider è stato troncato durante la verifica',
  fileHashMismatch: "L'hash del file del provider non corrisponde a quello dichiarato",
  noPage: (pageId: string) => `Provider inesistente: ${pageId}`,
  noPanel: (pageId: string, panelId: string) => `Il provider ${pageId} non dichiara il pannello ${panelId}`,
  postOnly: (panelId: string, method: string) => `Il metodo ${method} del pannello ${panelId} accetta solo POST`,
  noPanelSurface: (pageId: string) => `Il provider ${pageId} non ha una superficie dati del pannello`,
  noStreamSurface: (pageId: string) => `Il provider ${pageId} non ha una superficie di stream`,
  pickerNul: (name: string) => `${name} non può contenere caratteri NUL`,
  pickerBadExtension: (value: string) => `Estensione di file non valida: ${value}`,
  pickerBodyNotObject: 'Il corpo della richiesta deve essere un oggetto',
  pickerBadKind: 'kind deve essere file o directory',
  pickerBadExtensions: 'extensions deve essere un array di stringhe',
  pickerMissing: (path: string) => `Il percorso scelto non esiste: ${path}`,
  pickerNotFile: (path: string) => `Il percorso scelto non è un file: ${path}`,
  pickerNotDirectory: (path: string) => `Il percorso scelto non è una cartella: ${path}`,
  pickerWrongType: (extensions: string[]) => `Il tipo di file deve essere ${extensions.join(' / ')}`,
  pickerTitleFile: 'Scegli un file',
  pickerTitleDirectory: 'Scegli una cartella',
  pickerSupportedFiles: 'File supportati',
  pickerAllFiles: 'Tutti i file',
  pickerNoPowerShell: 'PowerShell non trovato su questo computer, quindi il selettore di percorso non può aprirsi',
  pickerNoOsascript: 'osascript non trovato su questo computer, quindi il selettore di percorso non può aprirsi',
  pickerNoLinuxTool: 'Nessun selettore di percorso disponibile su questo computer; installa zenity o kdialog',
  pickerFailed: (error: string) => `Impossibile aprire il selettore di percorso di questo computer: ${error}`,
  pickerUnsupported: (platform: string) => `Questa piattaforma non ha un selettore di percorso nativo: ${platform}`,
};
