import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  groupPersonas: 'Persona e Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'Instâncias de World',
  navAria: 'Navegação do console',
  runResume: 'Retomar',
  runPause: 'Pausar',
  runUnavailable: 'Controle de execução indisponível',
  shutdownAria: 'Desligar',
  settingsAria: 'Configurações',
  settingsTitle: 'Configurações',
  finishing: 'Desligando…',
  shutdownTitle: 'Desligar',
  shutdownBody: 'O processo será encerrado e o console será desconectado.',
  confirmShutdownTitle: '⚠ Desligar',
  confirmShutdownAgainTitle: '⚠⚠ Confirmar desligamento?',
  confirmShutdownAgainBody: 'Parar a execução e encerrar o processo?',
  finishingToast: 'Desligando…',
  stepIncomplete: 'não concluída',
  doneShutdown: 'Desligado',
  resultLocalIncomplete: 'Etapas de desligamento local incompletas',
  resultExternalUnverified: 'Desligado localmente; estado externo não verificado',
  resultUnverified: 'Etapas de desligamento executadas; estado não verificado',
  resultDefault: 'Etapas de desligamento executadas.',
  noReceipt: (msg: string) =>
    `Nenhum resultado de desligamento recebido (${msg}); o processo pode ter sido encerrado. Veja os registros de shutdown em data/runs/<run>/log.jsonl da execução atual.`,
  docTitle: (name: string) => `Console · ${name}`,
  renameTitle: 'Clique para renomear',
  renameSaved: 'Nome de exibição salvo',
  renameFailed: (msg: string) => `Nome de exibição não salvo: ${msg}`,
  releaseUpdate: (latest: string, current: string) => `Cortico ${latest} lançado (em execução: ${current})`,
  // avatar.ts
  changeAvatar: 'Trocar avatar do bot',
  uploadAvatar: 'Enviar e recortar o avatar do bot',
  unreadable: 'Não foi possível ler esta imagem',
  cropPreview: 'Prévia do recorte do avatar',
  zoomAria: 'Zoom do avatar',
  zoom: 'Zoom',
  note: 'Arraste a imagem para reposicioná-la; use a roda do mouse ou o controle deslizante para dar zoom. Salvar grava avatar.png no diretório raiz do bot.',
  cancel: 'Cancelar',
  save: 'Salvar avatar',
  cropTitle: 'Recortar avatar',
  noCanvas: 'O navegador não conseguiu criar um canvas de imagem',
  saved: 'Avatar salvo',
  // ../main.ts
  featureLoadFailed: (label: string) => `Não foi possível carregar “${label}”`,
};
