import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'Istanze dei World',
  navAria: 'Navigazione della console',
  runResume: 'Riprendi',
  runPause: 'Metti in pausa',
  runUnavailable: "Controllo dell'esecuzione non disponibile",
  shutdownAria: 'Arresta',
  settingsAria: 'Impostazioni',
  settingsTitle: 'Impostazioni',
  finishing: 'Arresto in corso…',
  shutdownTitle: 'Arresta',
  shutdownBody: 'Il processo terminerà e la console verrà disconnessa.',
  confirmShutdownTitle: '⚠ Arresta',
  confirmShutdownAgainTitle: "⚠⚠ Confermare l'arresto?",
  confirmShutdownAgainBody: "Fermare l'esecuzione e uscire dal processo?",
  finishingToast: 'Arresto in corso…',
  stepIncomplete: 'incompleto',
  doneShutdown: 'Arrestato',
  resultLocalIncomplete: 'Passaggi di arresto locale incompleti',
  resultExternalUnverified: 'Arrestato in locale; stato esterno non verificato',
  resultUnverified: 'Passaggi di arresto eseguiti; stato non verificato',
  resultDefault: 'Passaggi di arresto eseguiti.',
  noReceipt: (msg: string) =>
    `Nessun risultato di arresto ricevuto (${msg}); il processo potrebbe essere terminato. Vedi le voci shutdown in data/runs/<run>/log.jsonl dell'esecuzione corrente.`,
  docTitle: (name: string) => `Console · ${name}`,
  renameTitle: 'Clicca per rinominare',
  renameSaved: 'Nome visualizzato salvato',
  renameFailed: (msg: string) => `Nome visualizzato non salvato: ${msg}`,
  releaseUpdate: (latest: string, current: string) => `Cortico ${latest} rilasciato (in uso ${current})`,
  // avatar.ts
  changeAvatar: "Cambia l'avatar del bot",
  uploadAvatar: "Carica e ritaglia l'avatar del bot",
  unreadable: 'Impossibile leggere questa immagine',
  cropPreview: "Anteprima del ritaglio dell'avatar",
  zoomAria: "Zoom dell'avatar",
  zoom: 'Zoom',
  note: "Trascina l'immagine per riposizionarla; usa la rotella del mouse o il cursore per lo zoom. Il salvataggio scrive avatar.png nella directory principale del bot.",
  cancel: 'Annulla',
  save: 'Salva avatar',
  cropTitle: 'Ritaglia avatar',
  noCanvas: 'Il browser non è riuscito a creare un canvas per immagini',
  saved: 'Avatar salvato',
  // ../main.ts
  featureLoadFailed: (label: string) => `Caricamento di «${label}» non riuscito`,
};
