import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'Instances de World',
  navAria: 'Navigation de la console',
  runResume: 'Reprendre',
  runPause: 'Mettre en pause',
  runUnavailable: "Contrôle d'exécution indisponible",
  shutdownAria: 'Arrêter',
  settingsAria: 'Paramètres',
  settingsTitle: 'Paramètres',
  finishing: 'Arrêt en cours…',
  shutdownTitle: 'Arrêter',
  shutdownBody: 'Le processus va se terminer et la console sera déconnectée.',
  confirmShutdownTitle: '⚠ Arrêter',
  confirmShutdownAgainTitle: "⚠⚠ Confirmer l'arrêt ?",
  confirmShutdownAgainBody: "Arrêter l'exécution et quitter le processus ?",
  finishingToast: 'Arrêt en cours…',
  stepIncomplete: 'incomplet',
  doneShutdown: 'Arrêté',
  resultLocalIncomplete: "Étapes d'arrêt local incomplètes",
  resultExternalUnverified: 'Arrêté localement ; état externe non vérifié',
  resultUnverified: "Étapes d'arrêt exécutées ; état non vérifié",
  resultDefault: "Étapes d'arrêt exécutées.",
  noReceipt: (msg: string) =>
    `Aucun résultat d'arrêt reçu (${msg}) ; le processus s'est peut-être terminé. Consultez les entrées shutdown dans data/runs/<run>/log.jsonl de l'exécution en cours.`,
  docTitle: (name: string) => `Console · ${name}`,
  renameTitle: 'Cliquer pour renommer',
  renameSaved: 'Nom affiché enregistré',
  renameFailed: (msg: string) => `Nom affiché non enregistré : ${msg}`,
  releaseUpdate: (latest: string, current: string) => `Cortico ${latest} est disponible (version actuelle ${current})`,
  // avatar.ts
  changeAvatar: "Changer l'avatar du bot",
  uploadAvatar: "Importer et recadrer l'avatar du bot",
  unreadable: 'Impossible de lire cette image',
  cropPreview: "Aperçu du recadrage de l'avatar",
  zoomAria: "Zoom de l'avatar",
  zoom: 'Zoom',
  note: "Faites glisser l'image pour la repositionner ; utilisez la molette ou le curseur pour zoomer. L'enregistrement écrit avatar.png dans le répertoire racine du bot.",
  cancel: 'Annuler',
  save: "Enregistrer l'avatar",
  cropTitle: "Recadrer l'avatar",
  noCanvas: "Le navigateur n'a pas pu créer de canevas d'image",
  saved: 'Avatar enregistré',
  // ../main.ts
  featureLoadFailed: (label: string) => `Échec du chargement de « ${label} »`,
};
