import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'World 인스턴스',
  navAria: '콘솔 탐색',
  runResume: '재개',
  runPause: '일시 중지',
  runUnavailable: '실행 제어를 사용할 수 없음',
  shutdownAria: '종료',
  settingsAria: '설정',
  settingsTitle: '설정',
  finishing: '종료하는 중…',
  shutdownTitle: '종료',
  shutdownBody: '프로세스가 종료되고 콘솔 연결이 끊어집니다.',
  confirmShutdownTitle: '⚠ 종료',
  confirmShutdownAgainTitle: '⚠⚠ 종료하시겠습니까?',
  confirmShutdownAgainBody: '실행을 중지하고 프로세스를 종료하시겠습니까?',
  finishingToast: '종료하는 중…',
  stepIncomplete: '미완료',
  doneShutdown: '종료됨',
  resultLocalIncomplete: '로컬 종료 단계 중 일부가 완료되지 않음',
  resultExternalUnverified: '로컬 종료 완료, 외부 상태 미확인',
  resultUnverified: '종료 단계 실행됨, 상태 미확인',
  resultDefault: '종료 단계를 실행했습니다.',
  noReceipt: (msg: string) =>
    `종료 결과를 받지 못했습니다(${msg}). 프로세스가 이미 종료되었을 수 있습니다. 자세한 내용은 현재 실행의 data/runs/<run>/log.jsonl에 있는 shutdown 기록을 확인하세요.`,
  docTitle: (name: string) => `콘솔 · ${name}`,
  renameTitle: '클릭하여 이름 변경',
  renameSaved: '표시 이름을 저장했습니다',
  renameFailed: (msg: string) => `표시 이름을 저장하지 못했습니다: ${msg}`,
  releaseUpdate: (latest: string, current: string) => `Cortico ${latest} 출시(현재 ${current})`,
  // avatar.ts
  changeAvatar: '봇 아바타 변경',
  uploadAvatar: '봇 아바타 업로드 및 자르기',
  unreadable: '이 이미지를 읽을 수 없습니다',
  cropPreview: '아바타 자르기 미리 보기',
  zoomAria: '아바타 확대/축소',
  zoom: '확대/축소',
  note: '이미지를 드래그해 위치를 조정하고, 마우스 휠이나 슬라이더로 확대/축소하세요. 저장하면 봇 루트 디렉터리의 avatar.png에 기록됩니다.',
  cancel: '취소',
  save: '아바타 저장',
  cropTitle: '아바타 자르기',
  noCanvas: '브라우저에서 이미지 캔버스를 만들 수 없습니다',
  saved: '아바타를 저장했습니다',
  // ../main.ts
  featureLoadFailed: (label: string) => `"${label}"을(를) 불러오지 못했습니다`,
};
