import type { en } from './strings.ts';

export const S: Partial<typeof en> = {
  // index.ts
  groupPersonas: 'Persona & Memory',
  groupWorlds: 'World',
  moduleInstancesAria: 'World-Instanzen',
  navAria: 'Konsolennavigation',
  runResume: 'Fortsetzen',
  runPause: 'Pausieren',
  runUnavailable: 'Laufsteuerung nicht verfügbar',
  shutdownAria: 'Herunterfahren',
  settingsAria: 'Einstellungen',
  settingsTitle: 'Einstellungen',
  finishing: 'Wird heruntergefahren…',
  shutdownTitle: 'Herunterfahren',
  shutdownBody: 'Der Prozess wird beendet und die Konsole getrennt.',
  confirmShutdownTitle: '⚠ Herunterfahren',
  confirmShutdownAgainTitle: '⚠⚠ Herunterfahren bestätigen?',
  confirmShutdownAgainBody: 'Lauf stoppen und Prozess beenden?',
  finishingToast: 'Wird heruntergefahren…',
  stepIncomplete: 'unvollständig',
  doneShutdown: 'Heruntergefahren',
  resultLocalIncomplete: 'Lokale Schritte zum Herunterfahren unvollständig',
  resultExternalUnverified: 'Lokal heruntergefahren; externer Zustand nicht geprüft',
  resultUnverified: 'Schritte zum Herunterfahren ausgeführt; Zustand nicht geprüft',
  resultDefault: 'Schritte zum Herunterfahren ausgeführt.',
  noReceipt: (msg: string) =>
    `Kein Ergebnis des Herunterfahrens erhalten (${msg}); der Prozess ist möglicherweise beendet. Siehe die shutdown-Einträge in data/runs/<run>/log.jsonl des aktuellen Laufs.`,
  docTitle: (name: string) => `Konsole · ${name}`,
  renameTitle: 'Zum Umbenennen klicken',
  renameSaved: 'Anzeigename gespeichert',
  renameFailed: (msg: string) => `Anzeigename nicht gespeichert: ${msg}`,
  releaseUpdate: (latest: string, current: string) => `Cortico ${latest} veröffentlicht (aktuell ${current})`,
  // avatar.ts
  changeAvatar: 'Bot-Avatar ändern',
  uploadAvatar: 'Bot-Avatar hochladen und zuschneiden',
  unreadable: 'Dieses Bild konnte nicht gelesen werden',
  cropPreview: 'Vorschau des Avatar-Zuschnitts',
  zoomAria: 'Avatar-Zoom',
  zoom: 'Zoom',
  note: 'Ziehe das Bild, um es zu verschieben; zoome mit dem Mausrad oder dem Schieberegler. Speichern schreibt avatar.png ins Stammverzeichnis des Bots.',
  cancel: 'Abbrechen',
  save: 'Avatar speichern',
  cropTitle: 'Avatar zuschneiden',
  noCanvas: 'Der Browser konnte keine Bild-Canvas erstellen',
  saved: 'Avatar gespeichert',
  // ../main.ts
  featureLoadFailed: (label: string) => `„${label}“ konnte nicht geladen werden`,
};
